### ISSUE TITLE
module spider does not find modules 2nd time with user cache

### ISSUE THREAD

**Issue by bartoldeman** [TACC/Lmod#104]
The situation is as follows:
- we have a system cache
- if a user does `module use /path/to/many/modulefiles` outside the system cache it will generate
  `.lmod.d/.cache/moduleT.x86_64_Linux.lua`
  but no corresponding `dbT*` file.

The first time the user then does:
`module spider samtools`
where samtools is in the user cache he gets the correct output. The second time it can't find it.

I got it working by looking at Cache.lua, commenting out the lines as follows:

``` lua
   -- With a valid moduleT build dbT if necessary:
   -- if (next(dbT) == nil or buildModuleT) then
      spider:buildSpiderDB({"default"}, moduleT, dbT)
   -- end
```

there must be a better way though...

**Comment by rtmclay** [comment]
I believe that this bug has been fixed by Lmod 7.1+.  If it doesn't please reopen this issue.
