### ISSUE TITLE
Cent6: /usr/bin/ps vs /bin/ps, /usr/share/lmod/6.0.15/init/profile

### ISSUE THREAD

**Issue by teratano** [TACC/Lmod#118]
bug:low priority
Upon login - I get the following new error 
from  /usr/share/lmod/6.0.15/init/profile from line 40 :
my_shell=$(/usr/bin/ps -p $$ -ocomm=)

-bash: /usr/bin/ps: No such file or directory
/bin/basename: missing operand
Try `/bin/basename --help' for more information.

This only happens on centos6,rhel6 - since rhel7, fedora23,  - provide symlink for '/bin -> usr/bin'
 I work-around the problem by adding a symlink '/usr/bin/ps' -> '/bin/ps' 

![screensht](https://cloud.githubusercontent.com/assets/9915880/15249284/6a3761fe-18e4-11e6-827a-502e817c660d.png)

[profiledif.txt](https://github.com/TACC/Lmod/files/263336/profiledif.txt)

Thanks for Lmod and working with eb !
-Don

**Comment by rtmclay** [comment]
The location of ps is determined by configure.  So the only way I can see this happening is configuring on  one  OS and running it on another.  This is true for version 6.0.15 as well as 6.3.3

R.

**Comment by teratano** [comment]
I snagged the src.rpm from epel6 and rebuilt it- on cento6 - the problem was repeated. 
I looked at spec file and found he has set an option PS=/usr/bin/ps to configure? The author
of the spec file is Orion Poplawski .  Removing the PS option for configure fixes the rpmbuild. 

Is there a more up to date SRPM of Lmod - or a repo - that is kept up to date with latest stable? 
(rhel6,rhel7,cent6,cent8,ubuntu16,14)
I'll send Orion an email. 
Thanks R
-Don
diff -Naur Lmod.spec Lmod.spec.orig
--- Lmod.spec	2016-05-18 13:42:45.986815821 -0500
+++ Lmod.spec.orig	2016-05-18 13:42:36.809815823 -0500
@@ -48,7 +48,7 @@
 
 
 %build
-%configure --prefix=%{_datadir} 
+%configure --prefix=%{_datadir} PS=/usr/bin/ps
 make %{?_smp_mflags}

**Comment by boegel** [comment]
@opoplawski ping?

**Comment by fgeorgatos** [comment]
@teratano : you may be interested in this, it's an experimental (yet working) .spec:
https://github.com/plabrop/bic/blob/master/Lmod/branches/7.0/Lmod-illumina.spec

**Comment by rtmclay** [comment]
I have release Lmod 6.4.5 on github. This new version tests to see if the location for ps, expr and basename found by configure exist and are executable.  If it is not then it checks in /bin and /usr/bin to see if they can be found.
