### ISSUE TITLE
conflict should support modifiers

### ISSUE THREAD

**Issue by rtmclay** [TACC/Lmod#12]
prereq and load take modifiers, conflict should too.  So 

   conflict( lessthan("foo","1.4.7"))

would say that it is a conflict if module FOO is loaded and has a version less that 1.4.7

Possible Modifier functions:

  lessthan()
  greaterthan()
  between()

The between() function definition has a problem:

```
conflict(between("FOO", "1.2", "2.4"))
```

could be interpreted to mean that FOO/2.0 is conflict or is not.

Maybe:
   conflict(lessthan("FOO", "1.2"))
   conflict(greaterthan("FOO", "2.4"))

would be clearer and 
   prereq(between("FOO","1.2", "2.4"))

gets the case where FOO has to be loaded and between version 1.2 and 2.4.

**Comment by damianam** [comment]
Does `conflict` support versions at all? In my tests with `7.3.17` seem to indicate that it doesn't:

```
$ module --version

Modules based on Lua: Version 7.3.17  2017-02-16 12:43 -06:00
    by Robert McLay mclay@tacc.utexas.edu

$ ml Architecture/.KNL
Lmod has detected the following error:  Cannot load module "Architecture/.KNL" because these module(s) are loaded:
   Stages/2015a Stages/2015b Stages/2016a Stages/2016b Stages/Legacy

While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    Architecture/.KNL  /usr/local/software/mod_environment/Architecture/.KNL.lua

$ ml

Currently Loaded Modules:
  1) Architecture/.SandyBridge (H,S)   2) Stages/.2017a (H,S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge
   H:             Hidden Module
```

**Comment by rtmclay** [comment]
Thanks for the bug report! It turns out that this has never been supported in Lmod.  I have pushed a new version to HEAD.  It will eventually become 7.3.18.  If you get the chance, please test this new version to see if it works for you.  Thanks!

**Comment by damianam** [comment]
I tested it and I can confirm that it works for me too. Thanks for fixing it!

**Comment by zerothi** [comment]
Can this be closed? ;)

**Comment by rtmclay** [comment]
Yes, it can!
