### ISSUE TITLE
Provide full path & filename of current modulefile 

### ISSUE THREAD

**Issue by schauveau** [TACC/Lmod#124]
A welcome addition to LMOD would be to provide the full filename of the current modulefile from LUA.
The usual LUA methods (using the debug  package) do not work here because the lua execution is sandboxed. 

I already have a patched version loadModuleFile.lua and sandbox.lua (i.e. pass the filename to run() and I make it available as a global variable _MODULEFILE in the sandbox). I can send them to you but I am pretty sure that you can quickly redo that in a more cleaner way.

The reason for that request is that knowing the filename make a lot of automation possible. 

For example, one of the things I do not like in the proposed hierarchical structure is the need to make multiple levels of directories Core, Compiler, MPI each reproducing the hierarchy of the previous level.

**REMARK: What is below is just an example of what becomes possible when knowing the filename. This is not a feature request since everything can be implemented by the end-user.**

I already have a prototype implementation that implements an alternative hierarchical scheme as follow:

All module files are all of the form  .../modulefiles/SUBDIR/.mf/NAME/VERSION.lua   

SUBDIR can be any even number of directories. Ech pair of directories represents the name/version of a parent module in the hierarchy. 

The initial modulepath is the directory .../modulefiles/.mf/ so with an empty SUBDIR

The default sub-modulepath of the module
   .../modulefiles/SUBDIR/.mf/NAME/VERSION.lua 
is
   .../modulefiles/SUBDIR/NAME/VERSION/.mf/ 
 
A user-defined LUA module takes care of decomposing the filename into NAME,  VERSION and SUBDIR to the module. It also provides a few utility functions (see the example below).

So a typical modulefile for OpenMPI could look like that:

```
local mgr = require("ModuleFileMgr")
local mf = mgr:currentModuleFile() 

whatis("The OpenMPI library " .. mf.version  ) 

-- Construct a text describing the 'parent' modules using SUBDIR 
-- For instance if mf.subdir is  "gcc/4.5/cuda/7.0" then produce something like:
--     Parent modules are: gcc/4.5 cuda/7.0   
mf:whatisParents()      

-- For convenience, the tools are installed in a hierarchy that mimics the module hierarchy
local rootdir = pathJoin("/opt/", mf.subdir , mf.name , mf.version, "usr"  ) 
prepend_path("PATH", pathJoin(rootdir,"bin") )
prepend_path("MANPATH", pathJoin(rootdir,"man") )
prepend_path("LD_LIBRARY_PATH", pathJoin(rootdir,"lib") )

-- Prepend subdirectory for the dependent modules 
mf:prependSubModulepath() 

```
So if the module file is .../modulefiles/gcc/4.5/cuda/7.5/.mf/openmpi/1.2.lua then this module would add .../modulefiles/gcc/4.5/cuda/7.5/openmpi/1.2/.mf/ to MODULEPATH and would use OpenMPI installed in /opt/gcc/4.5/cuda/7.5/openmpi/1.2/usr/

If done properly, most modulefiles should be fully reusable. They can be copied or symlinked multiple times in the hierarchy. 

More advanced functionalities can of course be implemented in the user-defined lua module.

So, the only thing that is currently missing in LMOD is the ability to get the full filename

**Comment by rtmclay** [comment]
These functions already exist.  They are described in the Lmod documentation (http://lmod.readthedocs.io/en/latest/100_generic_modules.html) to provide what I call generic modulefiles and you are right they are extremely useful.   The functions that I find particularly useful are:

       myFileName()  - the complete path to the modulefile
       myModuleName() - the name of the module.  (OpenMPI)
       myModuleFullName() - the full name of the module. (OpenMPI/1.8)
       hierarchyA() - A function useful when dealing with modules in the software hierarchy.

There are more functions.  All Lua functions made available are described here (http://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html)

If the documentation isn't clear, please feel free to ask questions or clarifications.

**Comment by schauveau** [comment]
Indeed. In fact, I found them a few minutes ago.
I completely missed the documentation provided in the package itself.
I incorrectly assumed that all the documentation was in the main web page at tacc.utexas.edu.

I do not think that the the link to  lmod.readthedocs.io is given anywhere.

**Comment by rtmclay** [comment]
The link to lmod.readthedocs.org is listed at the bottom of module --help.

**Comment by schauveau** [comment]
The documentation of the hierarchyA() function is a bit obscure.

Its behaviour seems quite complex and I am not sure that I can rely on it to implement my hierarchical scheme. 

If I understand well, the 1st argument is supposed to be the "name/version" in which case the result is an array providing the previous directory pairs.

For example, let's assume that the module is  .../aa/1.0/bb/2.0/cc/3.0.lua   

 hierarchyA("cc/3.0",1) returns { "bb/2.0" }
 hierarchyA("cc/3.0",2) returns { "bb/2.0" , "aa/1.0" }
 ...

So far so good.

However, I also noticed that when I pass something different from "cc/3.0" then the behaviour is  
  hierarchyA("x/y",1) returns  { "cc/3.0" } 
  hierarchyA("x/y",2) returns  { "cc/3.0" , "bb/2.0"}
  hierarchyA("x/y",3) returns  { "cc/3.0" , "bb/2.0" , "aa/1.0" }
and
  hierarchyA("x",1) returns  { "3.0" } 
  ..
  hierarchyA("x",6) returns  { "3.0", "cc" , "2.0" , "bb" , "1.0" , "aa" } 
and
  hierarchyA("x//y/z",1) returns  { "2.0/cc/3.0" }
 
So it seems that the number of / in the first argument controls how much directories are packed in each element of the resulting array.

Is that the intended behaviour or just an unexpected side effect of not passing the expected value as argu,ent?

Anyway,  hierachyA is probably not suitable to implement my own hierarchical scheme because my ''/.md/' directory breaks the regular pattern of "name/version".

**Comment by rtmclay** [comment]
You are right.  The hierarchyA() function is complex and it is only useful when you are using the hierarchy described in the documentation.  If you use name/version or category/name/version consistently then hierarchyA can be useful.

There is nothing in Lmod that requires you use the Core, Compiler, MPI hierarchy style.  Sites can and do use a Flat layout.  Or you can use a different hierarchy layout.  Lmod doesn't care.  All Lmod really does is watch for changes in MODULEPATH and loads or unloads modulefile when necessary.

Welcome to Lmod.  I hope you find it useful.  If you come up with a different hierarchy that you think others will find useful please feel free to describe it on the Lmod mailing list.

**Comment by schauveau** [comment]
Thanks, I indeed believe that my hierarchy scheme is more elegant than the proposed one. 
I will definitely propose it on the mailing list once I clean everything. 
Thanks

**Comment by fgeorgatos** [comment]
+1 in that Lmod does not force upon you the hierarchy, and that it is a nice-to-have option. I've been using flat schemes since ever and I have rode over Lmod's ability to track MODULEPATH changes while delivering "buildsets". I just opened #125 to prove the case and ask an, unrelated to this, question ;)

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by schauveau** [comment]
ok to close
