### ISSUE TITLE
Support a drop file under ~/.lmod.d/* to invalidate the cache

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#127]
fi. this should be effective: `touch ~/.lmod.d/.cache/invalidated`

The meaning of this is that upon next lmod invocation the cache contents are forced-rebuilt.
(Hint for integrity under parallel runs: first rename the cachefile, only then remove that and the dropfile)

**Comment by wpoely86** [comment]
why would you want this? Just remove it?

**Comment by fgeorgatos** [comment]
@wpoely86: nope, that's not the same;

the advantage of a dropfile is that can have several processes doing `touch $dropfile` and there is no competition between them; `rm -fr .lmod.d/cache` won't be the same, nor would it be atomic.

Perhaps an mv might help, but that would shift responsibility for the clean up from Lmod to a user; that's undesired and yet not the most efficient.

**Comment by wpoely86** [comment]
but it's the user cache. Even just a touch doesn't make this atomic. Why lmod process will process the `$dropfile`? `rm -fr .lmod.d/cache` will actually do the trick and work nicely. The fs will take care.

**Comment by fgeorgatos** [comment]
for processes which do not rely much upon the cache file and simply drop
builds & modulefiles (such as EB does), I'd expect the drop file to be more
efficient, esp.  when multiple things are built at once - to be verified.

On 20 June 2016 at 19:41, wpoely86 <notifications@github.com> wrote:

> but it's the user cache. Even just a touch doesn't make this atomic. Why
> lmod process will process the $dropfile? rm -fr .lmod.d/cache will
> actually do the trick and work nicely. The fs will take care.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TACC/Lmod/issues/127#issuecomment-227231509>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABdgQA6AU_szy5qPU5SB42JCBTzYT7ioks5qNt7ygaJpZM4IrH-f>
> .
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by fgeorgatos** [comment]
ideally, i'd like to see the option to choose (perhaps per user/group basis), that people who do `module use/unuse` automatically imply a cache refresh. It would be expensive for (some) EB operations, but it gives so much peace of mind for the regular (EB) user

**Comment by wpoely86** [comment]
Lmod already does that on the fly?

**Comment by fgeorgatos** [comment]
i'd really like to have this feature and should be easy to implement. It would then permit, fi.:
 
`alias eb='function _eb() { eb "$*" && touch ~/.lmod.d/.cache/invalidated; unset -f _eb; }; _eb'`

This should allow to get away with ad-hoc random trainings about how Lmod cache behaves...
(ie. it would stop all those puzzling users' moments, this really slows down people)

**Comment by rtmclay** [comment]
O.K.  I have implement this feature in 6.5.16.  The rules are:

1. When ~/.lmod.d/.cache/invalidated exists the user cache file(s) are ignored
2. If Lmod ever writes out a new user cache file it delete ~/.lmod.d/.cache/invalidated

Please test this new version when you get a chance.

**Comment by fgeorgatos** [comment]
hi, 

just to mention that I'm relying on this since a recent `Lmod/6.6` upgrade and looks a described - thanks!

I'm closing the issue since this indeed prevents wasted and redundant `rm -rf`s !
