### ISSUE TITLE
Support `module available`

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#128]
weird to not have this... does anyone have a module called `available`? :p

**Comment by rtmclay** [comment]
This is now available from github in HEAD.

**Comment by boegel** [comment]
Wow, I'm surprised by this too.

cc @wpoely86

**Comment by wpoely86** [comment]
does anyone ever still type `module available`? :speak_no_evil: 

If they do, it's only because they have not yet seen the light of `ml av`. Or `ml spider`. Why use available at all if you have spider?

**Comment by boegel** [comment]
Well, not a lot of people do, otherwise this would've surfaced a long time ago. You get tired of typing `modlue avalialbe` very soon, because you mistyping it. ;-)

**Comment by rtmclay** [comment]
For a flat module layout, there is no advantage to ml av to ml spider.  However with a software hierarchy, I use ml av all the time because it tells me the modules I can now without doing any module swaps.

**Comment by fgeorgatos** [comment]
fixed - ty!
