### ISSUE TITLE
.lmod.d/.cache/moduleT.x86_64_Linux.lua:13248: function or expression needs too many registers near '{'

### ISSUE THREAD

**Issue by abadran** [TACC/Lmod#129]
I have deleted ~/.lmod.d/.cache to make sure that I start from a clean slate, then when I do `module avail` I get the following:

```
[# AB #] module avail
Rebuilding cache, please wait ...<snipped>/tools/lua-5.3.2/bin/luac: ~/.lmod.d/.cache/moduleT.x86_64_Linux.lua:13248: function or expression needs too many registers near '{'
 (written to file) done.

```

The relevant part of the `moduleT.x86_64_Linux.lua` at that line is (after I've removed a _lot_ of whitespace at the beginning of every line):

```
["/usr/share/Modules/bin/add.modules"] = {
  children = {
      },
  ["epoch"] = 1369860755,
  ["full"] = "bin/add.modules",
  ["full_lower"] = "bin/add.modules",
  ["markedDefault"] = false,
  ["name"] = "bin",
  ["name_lower"] = "bin",
  ["path"] = "/usr/share/Modules/bin/add.modules",
},
```

**Comment by rtmclay** [comment]
This is the same as issue #38.  You CAN NOT use Tmod system modules.  That is any modules in /usr/share/Modules/

R.

**Comment by rtmclay** [comment]
I should be clear that normal TCL modules work just fine but the add.module and the use.own module can't be used with Lmod.  It is best to remove those module from MODULEPATH.

**Comment by abadran** [comment]
I'm not, but the environment-modules is already installed on the system, does that somehow confuse Lmod?

**Comment by rtmclay** [comment]
You have add.module and maybe use.own in your MODULEPATH.  Try removing any paths in your MODULEPATH that have /usr/share/Modules and see if avail works.

**Comment by abadran** [comment]
I had to completely skip sourcing `/etc/profile.d/modules.sh`

**Comment by rtmclay** [comment]
Obviously that works but you could also change MODULEPATH before issuing the first module command.  

If changing MODULEPATH is hard to do before the first module command, you can do:

    $ module unuse /usr/share/Modules/...

**Comment by ikirker** [comment]
It looks like this is also triggered by modules that `use` the path that contains that module: perhaps some sort of depth limit would help? Or at least a warning or error to that effect.

(I encountered this bug on a poorly-written module and lua had stopped at 195 levels of nesting...)

**Comment by rtmclay** [comment]
Lmod 7.8.17 and later can now handle any Tmod 3.2.10 modulefiles.

**Comment by rtmclay** [comment]
Closing this issue.  If there are problems, please let me know.
