### ISSUE TITLE
Lmod not working for fish shell

### ISSUE THREAD

**Issue by albireox** [TACC/Lmod#138]
Lmod does not seem to work properly in Fish. For instance, my original PYTHONPATH is

`/Users/albireo/Documents/Repo/external/pyOPM:/Users/albireo/Documents/MaNGA/Utils:/Users/albireo/Documents/GitRepos/RO/python:/Users/albireo/Documents/Repo/eups/python`

but after loading a few modules it gets to

`/Users/albireo/Documents/Repo/sdss/sdss_python_module/python /Users/albireo/Documents/Repo/sdss/sdss_access/python /Users/albireo/Documents/Repo/sdss/sdss4tools/python /Users/albireo/Documents/Repo/manga/marvin/python\30/Users/albireo/Documents/Repo/manga/marvin_brain/python\30/Users/albireo/Documents/Repo/manga/mangadesign/python\30/Users/albireo/Documents/Repo/manga/Totoro\30/Users/albireo/Documents/Repo/operations/autoscheduler/python\30/Users/albireo/Documents/Repo/external/pyOPM\30/Users/albireo/Documents/MaNGA/Utils\30/Users/albireo/Documents/GitRepos/RO/python\30/Users/albireo/Documents/Repo/eups/python`

with the `\30` making the variable unusable.

Also, what is the best way of using Lmod in Fish. There not seem to be a script to source like for the other shells. Right now I'm doing `eval (eval $LMOD_CMD fish "$argv")` which seems to work for setting the env variables, but breaks the stdout (commands like `module list` do no write anything to stdout).

**Comment by rtmclay** [comment]
Version 7.3.25 or greater now seems to support the fish shell.  The problem that I had was how to define the module function in fish.  This is what I'm using:

```
function module 
    eval $LMOD_CMD fish $argv | source -
end
```

This seems to work well.

**Comment by albireox** [comment]
Thanks @rtmclay! This worked nicely. One additional issue, that maybe you didn't encounter because you are not using TCL modules. If I try to load a module with TCL syntax I get this error

```
can't read "g_shell": no such variable
    while executing
"error " +(0):ERROR:0: Unknown shell type \'($g_shell)\'""
    ("." arm line 2)
    invoked from within
"switch -regexp -- $g_shellName {
    ^(sh|bash|ksh|zsh)$ {
	set g_shellType sh
    }
    ^(cmd)$ {
        set g_shellType cmd
    }
    ^(csh|tcsh)$ ..."
    (file "/usr/local/lmod/lmod/libexec/tcl2lua.tcl" line 854)
Lmod has detected the following error:  Unable to load module:
sopActor/subgit
     /Users/albireo/.dotfiles/modulefiles/sopActor/subgit: Non-zero status
returned

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    sopActor/subgit  /Users/albireo/.dotfiles/modulefiles/sopActor/subgit
```

The solution, for me, was to edit `/usr/local/lmod/lmod/libexec/tcl2lua.tcl` and add

```
    ^(fish)$ {
	set g_shellType fish
    }
```

to the if-else clause that defines `g_shellType`. After that, everything seems to work fine.

**Comment by rtmclay** [comment]
Thank for testing! I have created Lmod 7.3.27 which has this  change to tcl2lua.tcl.   Please report any other bugs you find.  Thanks!

O.K. to close this issue?

**Comment by albireox** [comment]
I tried 7.3.27 and seems to work nicely. I think it's ok to close this. Thanks!
