### ISSUE TITLE
ZSH autocompletion doesn't work

### ISSUE THREAD

**Issue by dmitry-kabanov** [TACC/Lmod#144]
I noticed that ZSH autocompletion doesn't work for versions of LMOD 5.8.5 and 6.4.

I've just installed Lmod 6.4 and add line to my `~/.zshrc':
   source /opt/apps/lmod/lmod/init/profile

So, the `module` command is now available:

```
dima@dima-macbook-air ~
  % type module
type module
module is a shell function from /opt/apps/lmod/lmod/init/zsh

dima@dima-macbook-air ~
  % echo $LMOD_CMD
echo $LMOD_CMD
/opt/apps/lmod/lmod/libexec/lmod

dima@dima-macbook-air ~
  % echo $MODULEPATH
echo $MODULEPATH
/opt/apps/modulefiles/Darwin:/opt/apps/modulefiles/Core:/opt/apps/lmod/lmod/modulefiles/Core

dima@dima-macbook-air ~
  % ml av
ml av

------------------------------------ /opt/apps/modulefiles/Core ------------------------------------
   amcs394b/1.0.0              python-sphinx-rst/3.4
   python/3.5-Anaconda3-4.0    tdd-python-book-percival/3.8.3

------------------------------- /opt/apps/lmod/lmod/modulefiles/Core -------------------------------
   lmod/6.4    settarg/6.4
```

However, if I try to use autocompletion, it basically doesn't work. For example, I try

```
module lo<TAB>
```

and it autocompletes to `load`, but if I do

```
module spi<TAB>
```

then it doesn't autocomplete. The most important, I do not get autocompletion for module names:

```
ml amc<TAB>
```

does not do anything, although it should autocomplete as I have a module named `amcs394b/1.0.0`.

I'm using Mac OS X El Capitan with zsh:

```
dima@dima-macbook-air ~
  % zsh --version
zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

If I execute `bash` and source `init/profile` script there, then autocompletion works for me.

**Comment by rtmclay** [comment]
This problem has been fixed in 7.1.2
