### ISSUE TITLE
shortcut ml command not work after using screen

### ISSUE THREAD

**Issue by lidaof** [TACC/Lmod#145]
I am using Ubuntu 16.04 and the default lmod package from apt-get

after using screen command, ml command is not working, and $LD_LIBRARY_PATH become empty

does anyone know how to fix this? thanks a lot.

**Comment by rtmclay** [comment]
I'm going to answer this question on the lmod mailing as this is not a bug in Lmod but the way that Ubuntu works.

Please join the lmod mailing list at https://lists.sourceforge.net/lists/listinfo/lmod-users

Thanks,

**Comment by boegel** [comment]
See https://sourceforge.net/p/lmod/mailman/message/35182849/
