### ISSUE TITLE
Lmod trips over use of $::env(...) in Tcl modules

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#153]
example:

```
remove-path PATH    $::env(EBROOTQUANTUMESPRESSO)/espresso-5.2.1/YAMBO/bin
```

which results in

```
Lmod has detected the following error:
/tmp/eb-vPh5Hq/tmpLKWk5g/all/Yambo/4.0.2-rev.90-intel-2015b-QuantumESPRESSO-5.2.1:
(Yambo/4.0.2-rev.90-intel-2015b-QuantumESPRESSO-5.2.1): can't read
"::env(EBROOTQUANTUMESPRESSO)": no such variable
```

This is using:

```
$ ml --version

Modules based on Lua: Version 6.5  2016-08-16 14:08
    by Robert McLay mclay@tacc.utexas.edu
```

**Comment by rtmclay** [comment]
This is NOT an Lmod error.  This error message is from tclsh.  It is telling you that EBROOTQUANTUMESPRESSO is not set in the environment.

**Comment by boegel** [comment]
@rtmclay That environment variable should be set when that statement is evaluated... Maybe it is related to the fact that `$EBROOTQUANTUMESPRESSO` via a `module load` included in that module file itself?

Since this works fine with Tmod, maybe it's something related to `tcl2lua`?

**Comment by rtmclay** [comment]
If I understand you correctly, you are trying to load a module that does something like this:

   #%Module
   module load foo  # This defines EBROOTQUANTUMESPRESSO
   remove-path PATH $::env(EBROOTQUANTUMESPRESSO)

Then yes, this will not work in Lmod.  This exact scenario is discussed in http://lmod.readthedocs.io/en/latest/095_tcl2lua.html.   The ``module load foo`` is not evaluated by tcl2lua.tcl.  That is done by Lmod.  This means that the environment variable won't be defined inside of tcl2lua.tcl.

**Comment by boegel** [comment]
That's exactly the case we're talking about...

Any way around this? Can we postpone grabbing the value for `$EBROOTQUANTUMESPRESSO` until after `tcl2lua.tcl` somehow?

**Comment by rtmclay** [comment]
The only solution I know of is to generate both a *.lua and tcl modulefile in the same directory.

**Comment by boegel** [comment]
Well OK, but that renders the Tcl module file completely useless, right (well ok, unless you're still using Tmod somewhere else, but who would do that?!? :P)

**Comment by rtmclay** [comment]
The only other obvious solution is to write the contents of "foo" into the module.  You are generating the modules anyway.

**Comment by boegel** [comment]
@rtmclay that's a rather drastic change...

To me, this feels like a bug in how Lmod handles Tcl modules, but I agree it's a weird cornernase, in general the way Lmod currently uses `tcl2lua.tcl` is fine (but it's not perfect).

Long story short: use module files in Lua syntax when using Lmod... ;-)

**Comment by rtmclay** [comment]
Agreed.  This is a limitation on how Lmod handles TCL modulefiles.  

I suppose that it might be possible to get ``tcl2lua.tcl`` to actually evaluate the ``module load foo`` statements.  But then ``tcl2lua.tcl`` would  have to somehow communicate to Lmod that it had loaded ``foo`` but Lmod wouldn't actually load ``foo``.  It is a mess.

If anyone is looking for an interesting project, please  have at it.
