### ISSUE TITLE
spider cache locations not correct with multiple lmodrc files

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#156]
I'm trying to get Lmod to use both our system spider cache for our centrally installed modules alongside my personal spider cache for my (large set of) own modules, but that doesn't seem to be working...

We have a system configuration file in `/etc/lmodrc.lua`, with a system spider cache in `/apps/lmodcache`:

```
scDescriptT = {
    {
        ["dir"] = "/apps/lmodcache",
        ["timestamp"] = "/apps/lmodcache/timestamp",
    },

}
```

and I've added a `$HOME/.lmodrc.lua` which specifies the location of my own spider cache as:

```
scDescriptT = {
  {
    ["dir"]       = "/user/example/lmod/cache",
    ["timestamp"] = "/user/home/example/lmod/timestamp",
  },
}
```

However, `ml --config` tells me only my personal cache is active, despite that both the system and my own `lmodrc` files are picked up (actual paths edited for readability)

```
$ ml --config
Active RC file(s):
------------------
/usr/share/lmod/6.5.2/init/lmodrc.lua
/etc/lmodrc.lua
/user/home/example/.lmodrc.lua


Cache Directory           Time Stamp File
---------------           ---------------
/user/example/lmod/cache  /user/home/example/lmod/timestamp
```

removing my `$HOME/.lmodrc.lua` brings back the system cache locations:

```
$ rm $HOME/.lmodrc.lua
$ ml --config
Active RC file(s):
------------------
/usr/share/lmod/6.5.2/init/lmodrc.lua
/etc/lmodrc.lua


Cache Directory  Time Stamp File
---------------  ---------------
/apps/lmodcache  /apps/lmodcache/timestamp
```

Shouldn't both caches be taken into consideration with this setup, without having to list both location in `$HOME/.lmodrc.lua`?

**Comment by rtmclay** [comment]
Please test Lmod version 6.5.3 to see if this fixes your problem.

**Comment by boegel** [comment]
@rtmclay Lmod 6.5.3 indeed fixes this issue, thanks!
