### ISSUE TITLE
Lmod shouldn't be shy to say it doesn't recognize certain options, fi. --vrseion, -asdfasdf

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#163]
fi. compare with EB:

```
[fgeorgatos@demo2 ~]$ eb --version
This is EasyBuild 2.8.2 (framework: 2.8.2, easyblocks: 2.8.2) on host demo2.
[fgeorgatos@demo2 ~]$ eb --versionn
Usage: eb [options] easyconfig [...]

eb: error: no such option: --versionn
[fgeorgatos@demo2 ~]$ ml --version

Modules based on Lua: Version 6.5.11 (git-2e415be) 2016-09-07 11:16 -05:00
    by Robert McLay mclay@tacc.utexas.edu

[fgeorgatos@demo2 ~]$ ml --versionn
[fgeorgatos@demo2 ~]$ ml --vresion
[fgeorgatos@demo2 ~]$ ml -asdfasdf
[fgeorgatos@demo2 ~]$ ml --version

Modules based on Lua: Version 6.5.11 (git-2e415be) 2016-09-07 11:16 -05:00
    by Robert McLay mclay@tacc.utexas.edu
```

**Comment by rtmclay** [comment]
The module command does complain if you give the wrong option.  However 

    $ ml -vers

means unload the "vers" module.  Trying to unload a non-existent module is not an error or warning.

It might be possible to add code which detects bad --options but not -options.  So 

    $ ml -versionn

could never be an error.  But 

    $ ml --versionn

Could be an error.   Is that something you want?

**Comment by boegel** [comment]
@rtmclay would make printing a warning on running an `unload` without having a matching module present make sense? Maybe only when the `ml -<mod>` syntax is used (which you wouldn't use in module files, only interactively)?

**Comment by rtmclay** [comment]
No.  

     $ module unload foo

Is not an error even if foo is not loaded.

**Comment by boegel** [comment]
I'm aware of that, but a warning message being printed is not an error though?
Also, it should only be printed in very specific cases (use of `-` to `unload` a non-loaded module).

Anyway, just a suggestion. :)

**Comment by rtmclay** [comment]
I have pushed 6.5.13 which returns an error if --option is unknown:

     % ml --vers
     Option: "--vers" is unknown
     Try ml --help for usage
     % ml -vers
     %

Note that ml -word is not an error.  Remember that ml just generates a module command.   It doesn't know what modules are loaded or anything about the internals of Lmod.

Please test out 6.5.13 when you get a chance.

**Comment by fgeorgatos** [comment]
i've testing 6.5.13 during this period and consider the handling sufficient, closing the issue.
