### ISSUE TITLE
pushenv failing to restore stack value when pushed value is null string.

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#164]
Hi,

I believe that pushenv is failing to properly restore environmental variables when a blank string is pushed.  I have attached a shell script that generates the phenomena with a fresh checkout of the master branch.

--
Lewis
[issue.txt](https://github.com/TACC/Lmod/files/494300/issue.txt)

**Comment by rtmclay** [comment]
Thanks very much for the bug report!  Your reproducer was a great help.  I was able to reproduce the bug and fix it for me.  I have pushed Lmod 6.5.14 to github.  

When you get a chance, please test out the new version of Lmod to see if it fixes it for you. Thanks!

**Comment by lewis-john-lloyd** [comment]
Robert (Rob?),

6.5.14 resolves the issue.  Also, thanks for naming the regression test after me. :)

--
Lewis

**Comment by rtmclay** [comment]
I go by Robert.  You are welcome about the regression test.  I usually try to make the test or part of the test have the person or organization name in the test.  So far nobody has complained.
