### ISSUE TITLE
Add .modulerc

### ISSUE THREAD

**Issue by AntoineD** [TACC/Lmod#17]
Hello,

would it be possible to add support for a .modulerc file that would be automatically processed by lmod?
I miss this feature from modules.sourceforge.net

**Comment by rtmclay** [comment]
Please check out version 6.0rc1 as it now supports ~/.modulerc files

**Comment by AntoineD** [comment]
Thx @rtmclay, I'll check it out (not anytime soon though).

**Comment by abadran** [comment]
Is the .modulerc support in Lmod supposed to be 100% compatible with that of environment-modules (http://modules.sourceforge.net/)? The excerpt below suggests that, but I've come across a case where that is not true.
```
a) Full support for global RC files as well as .modulerc files.
      This means that $MODULERCFILE will be read along with
      ~/.modulerc. Also .modulerc files are read when they appear
      in the same directory and the version files (i.e. the same
      directory as 1.2 or 2.1.lua). One caveat, Setting the default
      module version in $MODULERCFILE or ~/.modulerc is not
      supported due Spider cache issues
```

**Comment by boegel** [comment]
@abadran Can you provide more details in how you saw different behaviour?

**Comment by abadran** [comment]
@boegel In a `${HOME}/.modulerc`, I have the following:
`module use /foo`
With the intention that this will add `/foo` to the list of directories that contain modulefiles. With Lmod this fails with a TCL stack trace and a 'failed to parse' error. This is perfectly valid in the original TCL or C Environment Modules package. Looking briefly at the RC2Lua.tcl script, it became obvious that this syntax cannot ever work in the current version of the code.

**Comment by boegel** [comment]
@abadran hmm, that sounds weird to me... Can you provide the full traceback?

**Comment by abadran** [comment]
@boegel The existence of the magic cookie at the beginning or not makes no difference. I had to obfuscate certain paths below.
```
$ cat ~/.modulerc
#%Module
module use /apps/etc/modules

$ module avail
invalid command name "module"
    while executing
"module use /apps/etc/modules"
    (file "~/.modulerc" line 2)
    invoked from within
"source $mRcFile"
    (procedure "main" line 6)
    invoked from within
"main ~/.modulerc"
    ("eval" body line 1)
    invoked from within
"eval main $argv"
    (file "<some-path>/Lmod-6.3/lmod/lmod/libexec/RC2lua.tcl" line 54)
Lmod has detected the following error:  Unable to parse: ~/.modulerc  Aborting!


$ cat <some-path>/Lmod-6.3/lmod/lmod/libexec/RC2lua.tcl
#!/usr/bin/env tclsh
global g_currentModuleName
proc doubleQuoteEscaped {text} {
    regsub -all "\"" $text "\\\"" text
    return $text
}

proc module-alias {name mfile} {
    puts stdout "\{kind=\"module-alias\",name=\"$name\",mfile=\"$mfile\"\},"
}

proc hide-version {mfile} {
    puts stdout "\{kind=\"hide-version\", mfile=\"$mfile\"\},"
}


proc module-version {args} {
    set module_name    [lindex $args 0]
    foreach version [lrange $args 1 end] {
        set val [doubleQuoteEscaped $version]
        lappend argL "\"$val\""
    }
    set versionA [join $argL ","]
    puts stdout "\{kind=\"module-version\",module_name=\"$module_name\", module_versionA=\{$versionA\}\},"
}

proc main {mRcFile} {
    puts stdout "modA=\{"
    set version  -1
    set found 0

    source $mRcFile

    if {[info exists ModulesVersion]} {
      set version $ModulesVersion
      set found 1
    } elseif {[info exists ModuleVersion]} {
      set version $ModuleVersion
      set found 1
    }
    #if {[info exists NewModulesVersionDate]} {
    #  set date $NewModulesVersionDate
    #}
    #if {[info exists NewModulesVersion]} {
    #  set newVersion $NewModulesVersion
    #}

    if { $found > 0 } {
        puts stdout "\{kind=\"set-default-version\", version=\"$version\"\}"
    }
    puts stdout "\}"
}

eval main $argv
```

**Comment by abadran** [comment]
@boegel I'm not a TCL expert and I haven't tried to trace it carefully, but looking briefly it would seem that the only module commands supported in a `.modulerc` file are `module-alias`, `hide-version` and `module-version`, but I could very well be missing something here.

**Comment by boegel** [comment]
@abadran That's possible, let's see what @rtmclay thinks about this.

**Comment by abadran** [comment]
@boegel  Adding the following to the RC2Lua.tcl file
```
proc module {args} {
    puts stderr $args
}
```
prevents the error from happening and causes `$ module avail` to print a `use /apps/etc/modules` before the available modules (as expected), but at least prevents the error from happening, of course it doesn't change the `MODULEPATH` (if that's the correct env. var) either to accomplish the intended consequence.

**Comment by rtmclay** [comment]
@abadran is correct.  The only functions supported in ```.modulerc``` are ```module-alias```, ```hide-version``` and ```module-version```.   I never knew that one might include  a ```module use ...```  in ```.modulerc```  

Adding support for ```module use``` from a ```~/.modulerc``` file to Lmod won't happen very soon.  The only thing I can suggest that you move the module use /foo into your startup scripts until this functionality is possible in Lmod.

**Comment by fgeorgatos** [comment]
Hello all,

@abadran:
better yet, try to rely upon Lmod's "module save", after loading a module
file with the `module use` - I've been doing this and works brilliantly.
(if your /etc/profile.d/*mod* initialization is done right, module restore
should be invoked automatically, exactly when it should).

I have always been very critical of how most people dump things under shell
startup scripts,
because essentially that ends up into "startup environment pollution", esp.
bashrc pollution - Don't do that!

You know you are there when you try to modify a variable like $PATH,
$LD_LIBRARY_PATH or $MODULEPATH
only to see it overwritten as soon as you invoke "bash". People don't
realize that unguarded tuning of such variables,
essentially deprives them from freedom to use them later on. Call it:
side-effects on steroids!

Give a shot to Lmod's feature `module save`, after having the correct mix
of module files and you won't regret it.


On 29 May 2016 at 15:18, Robert McLay <notifications@github.com> wrote:

> @abadran <https://github.com/abadran> is correct. The only functions
> supported in .modulerc are module-alias, hide-version and module-version.
> I never knew that one might include a module use ... in .modulerc
>
> Adding support for module use from a ~/.modulerc file to Lmod won't
> happen very soon. The only thing I can suggest that you move the module use
> /foo into your startup scripts until this functionality is possible in Lmod.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TACC/Lmod/issues/17#issuecomment-222362986>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABdgQFn4qV71wyU6KB6WpErLCh7A87bxks5qGaAkgaJpZM4B7iI3>
> .
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by abadran** [comment]
@fgeorgatos Well, being new to Lmod, I guess I don't see how `module save` and `module restore` can replace a `module use /some-path` in a `~/.modulerc` or a shell init script.
With `module save` and `module restore`, you've already _configured_ your environment and _known_ the correct mix of modules, and you are just recreating that environment in a new shell via a `module restore`.
The idea with `module use /some-path`, is that the modulefiles are in a non-standard path and I don't want to go and change Lmod's startup scripts to add this non-standard path. So it's basically, telling Lmod to add this `/some-path` to its modulefiles inventory and a `module avail` should show me what's available now (with the potential of finding new modules there), how is that synonymous or satisfiable with a `module save` and `module restore`?

**Comment by rtmclay** [comment]
Yes but a module save also knows about the MODULEPATH used to save the collection.

**Comment by abadran** [comment]
@rtmclay Can a `module save` be used to save an empty module collection after I've issued a `module use /path` manually just to remember the MODULEPATH? If yes, than that may be a work-around after doing a `module restore` to not have to change the shell init scripts.
Although, I would opt for the much simpler `module use /path` in a .bashrc, albeit being a tad messier than being in a separate `.modulerc` just because it becomes automatic in any new shell.

**Comment by rtmclay** [comment]
A module save will remember the current set of modules and the directories in MODULEPATH so if you do:
```
$ module purge
$ module use /some_path
$ module --force save
```

Then yes that is what you will get.   If your site provides a default list of modules then this may not be what you want.  Note that ```module restore``` does a module purge and then loads the list of modules.  In this case your module restore will have added /some_path to MODULEPATH and removed all modules.

**Comment by abadran** [comment]
>  If your site provides a default list of modules then this may not be what you want. Note that module restore does a module purge and then loads the list of modules

@rtmclay It's good to know that, so effectively it's recreating (rewriting) the environment, not just adding to it. Thank you, and a job well done with Lmod 👍

**Comment by fgeorgatos** [comment]
> If your site provides a default list of modules then this may not be what
you want.

I'd like to point out that if the site relies upon
$LMOD_SYSTEM_DEFAULT_MODULES,
things basically behave quite well. Site has central control about what the
default environment
for new users should be, meanwhile experts have a change to decide for
themselves their own choices.
Call it best of both worlds.

I've been using the technique across a dozen of clusters with several
hundreds of users
and so far it appears to do the intended function without issues, even
while providing
for multiple buildsets (ie. collections of modules) and very delicate user
needs.


On 30 May 2016 at 02:47, Ahmed Badran <notifications@github.com> wrote:

> If your site provides a default list of modules then this may not be what
> you want. Note that module restore does a module purge and then loads the
> list of modules
>
> @rtmclay <https://github.com/rtmclay> It's good to know that, so
> effectively it's recreating (rewriting) the environment, not just adding to
> it. Thank you, and a job well done with Lmod 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TACC/Lmod/issues/17#issuecomment-222396893>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABdgQKijIjOaXfSUTPoHL8anBdpvyjy3ks5qGkGzgaJpZM4B7iI3>
> .
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by abadran** [comment]
@fgeorgatos would this list of modules persist even after a `restore`, i.e. would they survive the `purge` step?

**Comment by rtmclay** [comment]
No.  Lmod does a forced purge and remove all module including the sticky modules.
