### ISSUE TITLE
LMOD_COMPILER_VERSION?

### ISSUE THREAD

**Issue by davidedelvento** [TACC/Lmod#183]
It would be **very** useful if lmod set also an environmental variable for the **version** of the compiler (and MPI, or whatever other families defined), besides the `LMOD_FAMILY_COMPILER` (etc) itself.

Nosing other folks interested in this @vanderwb @PatNichols @rck1138  @siddsghosh

**Comment by rtmclay** [comment]
I have pushed Lmod 6.5.17 to github to support this feature request.  This was an easy change as it only required 2 new lines of code.  The new environment variable is LMOD_FAMILY_<NAME>_VERSION.  So if you have family("COMPILER") in your intel/16.0.4 modulefile then

     LMOD_FAMILY_COMPILER=intel
     LMOD_FAMILY_COMPILER_VERSION=16.0.4

will be pushed into the environment.

Please test this new version when you get a chance.  This new version will likely be the new 6.6  of Lmod.

**Comment by rtmclay** [comment]
I am closing this issue.  If there are problems please feel free to reopen this.

**Comment by davidedelvento** [comment]
This seems to work as far as I am concerned. Thanks
