### ISSUE TITLE
Module swap feature?

### ISSUE THREAD

**Issue by PatNichols** [TACC/Lmod#189]
Hi,
  I am going to apologize in advance for this be so long but it is a difficult problem to explain.
  We recently created a module to load SGI MPT (mpi) toolkit with a specified compiler. Since Fortran needs a compiler dependent "module" file we need to set a path to a version that is unique for each compiler.
The  lua module code for this part of the module look like:
...
local compiler=os.getenv("LMOD_FAMILY_COMPILER")
local compiler_vers = os.getenv("LMOD_COMPILER_VERSION")
local modpath = "/picnic/u/apps/la/opt/mpt_fmods/2.15" 
local this_modpath1 = pathJoin(modpath,compiler)
local this_modpath2 = pathJoin(this_modpath1,compiler_vers)
prepend_path("CPATH",this_modpath2)
...

where the LMOD_COMPILER_VERSION is set by the compiler module and LMOD_FAMILY_COMPILER is set in the usual way. 
If we do a

pnichols@laramie2:~> module load intel mpt
pnichols@laramie2:~> echo $CPATH
/picnic/u/apps/la/opt/mpt_fmods/2.15/intel/16.0.3:/opt/sgi/mpt/mpt-2.15/include

we get the correct CPATH. However if we do the following the path is wrong.

module swap intel gnu
pnichols@laramie2:~> module swap intel gnu

Due to MODULEPATH changes the following have been reloaded:
  1) mpt/2.15

pnichols@laramie2:~> echo $CPATH
/picnic/u/apps/la/opt/mpt_fmods/2.15/gnu/6.2.0:/opt/sgi/mpt/mpt-2.15/include:/picnic/u/apps/la/opt/gnu/6.2.0/include:/picnic/u/apps/la/opt/mpt_fmods/2.15/intel/16.0.3

The old CPATH still remains in this case. Note this does not happen if you unload the mpt module, do the swap and then load mpt again.

The answer we have found so far is to create several versions of the mpt.lua and replace the parts dependent on the LMOD_\* environmental variables with real hard coded paths.

 local modpath = "/picnic/u/apps/la/opt/mpt_fmods/2.15/gnu/6.2.0" 
prepend_path("CPATH",modpath)

This works but the former approach seemed to be less error prone. Is there a better way to do what we intended to do ? Would you consider this a bug ?
Thanks,
Pat Nichols
NCAR CSG

**Comment by rtmclay** [comment]
You can't rely on environment variable to do this as you have seen.  This works on load but not on unload.   A swap is just an unload followed by a load:

      $ module swap intel gnu

is:

      $ module unload intel; module load gcc

So the LMOD_COMPILER_FAMILY is unset by intel and then set by gcc.   If there are compiler dependent modules, then they will get unloaded AFTER intel is unloaded so those compiler dependent modules won't have LMOD_COMPILER_FAMILY defined.  This can mess up unloading.

The only dependable method I know to handle this is path.  That is the boost module for intel is located in a place where the dependency is known.

     /opt/apps/modulefiles/Compiler/gcc/6.2/boost/1.60.0.lua

You can use the location of the module to figure out it dependency.   You should read http://lmod.readthedocs.io/en/latest/100_generic_modules.html for more details.  If you have questions about this please ask.

**Comment by davidedelvento** [comment]
Robert, we'll study more the documentation you pointed out, but meanwhile, at NCAR we discussed this crazy idea. Let us know if it does not make any sense (or if it's simply too much work for what it provides).

With a mechanism which I don't know the details of, some modules get reloaded (I guess it means unloaded then reloaded -- or is it something different?) after a `module swap` which causes a `MODULEPATH` change. This already works right now (e.g. the mpi module is reloaded after a compiler swap).

So, my crazy idea is to build on top of this existing functionality, in the following way: the above mentioned step get executed in "dry-run" mode, just to identify those other modules that need to be reloaded, let me call them mtbr (e.g. mtbr=mpi module when doing a swap on the compiler -- mtbr in the general case can be more than one). Once those mtbr are identified, lmod performs the actual "real" swapping, by unloading the mtbr **first**, then unloading the module under swap, and finally reloading these mtbr.

It seems to me that this change will fix our issue, without changing anything else (other than perhaps being a little more slow) in other cases. Thoughts?

Thanks as usual! :smile:

**Comment by rtmclay** [comment]
Lmod has no idea about the hierarchy.  All Lmod does is watch the environment variable MODULEPATH. If MODULEPATH changes (by either adding or removing a directory) then in either case Lmod looks at every loaded module to see if it would chose that one again.  So if you have say gcc and boost where boost depends on gcc, then if you do:

    module swap gcc intel

Then gcc gets unloaded and boost is marked as inactive.  Then intel is loaded and it changes the modulepath so Lmod looks to load any of the inactive modules.  If there is an appropriate boost it gets loaded.

If you have gcc, mvapich2 and petsc loaded and you do:

    module swap gcc intel

then gcc is unloaded which forces mvapich2 to unload which forces petsc to be unloaded.  So now mvapich2 and petsc are inactive.  Now intel gets loaded and it finds an intel based mvapich2 and then it can find a intel-mvapich2 based petsc and that gets loaded.

I think that you should try to see if there is a simple way to use path approaches to figure out what needs to be loaded.

If you or any of your colleagues want to discuss this or other issues, I'll be at SC16.

**Comment by rtmclay** [comment]
O.K to close this issue?

**Comment by PatNichols** [comment]
Yes . Thanks,
Pat
