### ISSUE TITLE
MANPATH changes break default Ubuntu config

### ISSUE THREAD

**Issue by bmcgough** [TACC/Lmod#191]
I think this is related to  #35  - at least, it is going to need to be a similar solution.

On Ubuntu, MANPATH is empty by default, and in this case /etc/manpath.config is consulted. When a value is added to MANPATH, /etc/manpath.config is skipped, so only MANPATH is consulted, removing man pages for all system software.

I believe the solution should be to include the delimiter before or after any entry  in MANPATH. I've tested this and found it to work; /etc/manpath.config is used if the delimiter in at the beginning or end of the included path.

I suspect this should be safe to do for other distributions/shells, but I have not tested outside bash on Ubuntu.

**Comment by rtmclay** [comment]
Currently init/profile.in has:

    # If MANPATH is empty, Lmod is adding a trailing ":" so that
    # the system MANPATH will be found
    if [ -z "${MANPATH:-}" ]; then
      export MANPATH=:
    fi
    export MANPATH=$(@PKG@/libexec/addto MANPATH @PKG@/share/man)

and the string "@PKG@" gets replaced with the location of Lmod.  I use this on a ubuntu system and this works well for me.   Is this not working for you?

**Comment by bmcgough** [comment]
That part is, but I am having an issue with modulefiles and MANPATH at module load time.

By default (on Ubuntu at least) MANPATH is empty, causing the `manpath` search magic to happen.

If I load a modulefile that does a `prepend-path MANPATH /blah` I end up with MANPATH=/blah which stops the `manpath` search magic. If Lmod used the delimiter in MANPATH even if MANPATH is empty, both the prepended path and the `manpath` search would happen.

Ex:

bmcgough@rhino-d:~$ module purge
bmcgough@rhino-d:~$ echo $MANPATH

bmcgough@rhino-d:~$ man -w bash
/usr/share/man/man1/bash.1.gz
bmcgough@rhino-d:~$ module load zlib
bmcgough@rhino-d:~$ echo $MANPATH
/app/zlib/1.2.8/share/man
bmcgough@rhino-d:~$ man -w zlib
/app/zlib/1.2.8/share/man/man3/zlib.3
bmcgough@rhino-d:~$ man -w bash
No manual entry for bash
See 'man 7 undocumented' for help when manual pages are not available.
bmcgough@rhino-d:~$ export MANPATH=/app/zlib/1.2.8/share/man:
bmcgough@rhino-d:~$ man -w zlib
/app/zlib/1.2.8/share/man/man3/zlib.3
bmcgough@rhino-d:~$ man -w bash
/usr/share/man/man1/bash.1.gz
bmcgough@rhino-d:~$ echo $MANPATH
/app/zlib/1.2.8/share/man:

Ben McGough
System Administrator / Center IT - Scientific Computing / 206.667.7818 / bmcgough@fredhutch.org / Fred Hutch / Cures Start Here

----- Original Message -----

**Comment by rtmclay** [comment]
I think the problem is that you haven't set up Lmod correctly.  A module purge should never leave an empty MANPATH.  I recommend in:

   http://lmod.readthedocs.io/en/latest/030_installing.html

That you either copy or symlink:

    $ ln -s /opt/apps/lmod/lmod/init/profile /etc/profile.d/z00_lmod.sh
    $ ln -s /opt/apps/lmod/lmod/init/cshrc   /etc/profile.d/z00_lmod.csh

If you do that then MANPATH already has a value and a trailing ":"

**Comment by bmcgough** [comment]
Yes, that is it. I migrated our systems from an old Environment Modules install to Lmod. We were directly sourcing init/bash with Environment Modules, so I just switched /opt/apps/lmod/lmod/init/bash in place.

I can see that MANPATH is set in init/profile, and once that happens for a user during login, everything should fall into place after that.

Thanks for the help, and sorry for the confusion!

**Comment by veselov** [comment]
Ran into this on Fedora (FC26). Though the default manpath is attached when manual pages are searched, the autocompletion script doesn't work, because doesn't use manpath at all times. Annoying, but imagine a poor Fedora guy that installed Lmod and suddenly lost their ability to autocomplete man pages. Drove me nuts.

**Comment by rtmclay** [comment]
What version of Lmod are you using?  Also like @bmcgough, have you installed Lmod correctly with the Lmod configuration files install correctly as described above?

Is there something that Lmod needs to do or not do?  Thanks.

**Comment by veselov** [comment]
@rtmclay It's whatever comes with FC26, which is currently `Lmod-7.5.3-1.fc26`, which has your empty colon fix. The installation is through FC packaging system, so I couldn't have botched that up. Anyway, `$MANPATH` functions as it's supposed to (IMHO), but the man autocomplete script gets borked. And I don't think it's Lmod problem, hence I complained to bash-completion about it. I don't see what Lmod can do differently.

**Comment by Russell-Jones-OxPhys** [comment]
One may also run into this issue (apparmor preventing man from accessing man pages on NFS mounts) https://unix.stackexchange.com/questions/633389/man-cannot-read-manpage-from-nfs-although-the-file-is-readable
