### ISSUE TITLE
providing latest modules with regards to semantic versioning

### ISSUE THREAD

**Issue by wookietreiber** [TACC/Lmod#195]
On our system, we are currently using the old environment modules and we are considering to migrate to lmod :) I am currently evaluating lmod regarding the features we would like to have.

One of these features is about *providing default modules with regards to semantic versioning* for our users, see example below for a detailed explanation of this *feature*.

## Example: python modules

Suppose the following module files:

```
python/2.7.8-1
python/2.7.9-1
python/2.7.9-2
python/2.7.9-3
python/2.7.12-1
python/3.4.3-1
python/3.5.2-1
```

What we would like for our users to have is the following:

1.  `module load python` should load the up-to-date python.

    ... for the users who really do not care about which version they load, they simply want the latest one
2.  Loading up-to-date major version

    ... for the users who depend on a specific major version.
2.1  `module load python/2` should load the up-to-date python with major version 2.
2.2  `module load python/3` should load the up-to-date python with major version 3.
3.  ... same logic can be applied to minor versions.
4.  ... same logic can be applied to patch versions.

    Note: Mind our *release* suffix `-1`, `-2` and `-3` for the `python/2.7.9` modules.

---

With the old environment modules, this was possible by creating subdirectories and, if necessary, (lots of) symlinks. To support loading a specific major version, the tree would look like:

```
python/2/7.8-1
python/2/7.9-1
python/2/7.9-2
python/2/7.9-3
python/2/7.12-1
python/3/4.3-1
python/3/5.2-1
```

The symlinks would be required if users should still be able to e.g. load `python/2.7.12-1`, i.e. with dots instead of slashes.

---

I have tried this with lmod, but, unfortunately, this does not work. This is the testing module file layout I used:

```
$ tree
.
├── a
│   ├── 4
│   │   ├── 12.0.lua
│   │   └── 2.0.lua
│   ├── 5
│   │   ├── 12.0.lua
│   │   └── 2.0.lua
│   └── 6
│       ├── 12.0.lua
│       └── 2.0.lua
├── b
│   ├── 4.12.0-1.lua
│   ├── 4.2.0-1.lua
│   ├── 5.12.0-1.lua
│   ├── 5.2.0-1.lua
│   ├── 6.12.0-1.lua
│   └── 6.2.0-1.lua
└── c
    ├── 4.12.0.lua
    ├── 4.2.0.lua
    ├── 5.12.0.lua
    ├── 5.2.0.lua
    ├── 6.12.0.lua
    └── 6.2.0.lua

6 directories, 18 files
```

Trying to use this:

```
$ module spider

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
The following is a list of the modules currently available:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  a/4: a/4/2.0, a/4/12.0
    Lmod: An Environment Module System

  a/5: a/5/2.0, a/5/12.0
    Lmod: An Environment Module System

  a/6: a/6/2.0, a/6/12.0
    Lmod: An Environment Module System

  b: b/4.2.0-1, b/4.12.0-1, b/5.2.0-1, b/5.12.0-1, b/6.2.0-1, b/6.12.0-1
    Lmod: An Environment Module System

  c: c/4.2.0, c/4.12.0, c/5.2.0, c/5.12.0, c/6.2.0, c/6.12.0
    Lmod: An Environment Module System
...

$ ml a
Lmod has detected the following error:  The following module(s) are unknown: "a"
...
$ ml a/4
$ ml a/5
$ ml a/6
$ ml b
$ ml b/4
Lmod has detected the following error:  The following module(s) are unknown: "b/4"
...
$ ml b/5
Lmod has detected the following error:  The following module(s) are unknown: "b/5"
...
$ ml b/6
Lmod has detected the following error:  The following module(s) are unknown: "b/6"
...
```

`c` has the same problem as `b`. `a` is somehow not recognized as a module on its own, but instead there are modules called `a/4`, `a/5` and `a/6`.

- Has this something to do with hierarchies?
- Do I need to configure something so that `a` gets recognized as its own module?
- Also: Feature request: You are already aware of semantic versioning regarding the sorting of modules, i.e. `ml a/4` loads `a/4/12.0`. This is **awesome** :) Extend this approach with loading prefixes of versions so the `b` module tree would work with the requirements above, i.e. `ml b`, `ml b/6`, `ml b/6.12`, `ml b/6.12.0` and `ml b/6.12.0-1` would all work - with a flat hierarchy and no symlinks! It would certainly be nice if we could get this to work :)
- Is this already possible and I just haven't figured out how to do this yet?
- If not, how can I help?

**Comment by rtmclay** [comment]
I think you are making this too complicated.  Lmod can already do what you need.   With the following caveats.   Lmod already loads the default if you say:

     $ module load python

This either loads the marked default or the highest semantic version.

Now because of the one name rule.  If a user wants to load both a python 2 and a python 3 they can't do it. You can have python/2.7.12 and python3/3.4 loaded at the same time but not python/2.7.12 and python/3.4 at the same time in the same shell.

If you want users to be able to load the latest python/2.6 or python/2.7 then you can use aliases:

        #%Module
        module-version python/2.7.12      2.7 2
        module-version python/2.6.7        2.6

These lines are part of your system modulerc file and say that "module load python/2" or "module load python/2.7" will load python 2.7.12.  Where as "module load python/2.6" will load python 2.6.7

Now really want to do  a/4/2.0, a/4/12.0, a/5/2.0 as your naming convention then use the latest version of Lmod 6.9.*-beta and put an empty .version file in the a directory:

```
% tree -a mf
mf
└── a
    ├── .version
    ├── 4
    │   ├── 12.0.lua
    │   └── 2.0.lua
    └── 5
        └── 2.0.lua
% ml spider a

------------------------------------------------------------------------
  a:
------------------------------------------------------------------------
     Versions:
        a/4/2.0
        a/4/12.0
        a/5/2.0

% module load a ; module list

Currently Loaded Modules:
  1) a/5/2.0

% ml a/4

The following have been reloaded with a version change:
  1) a/5/2.0 => a/4/12.0

% ml a/4/2.0

The following have been reloaded with a version change:
  1) a/4/12.0 => a/4/2.0

```

**Comment by wookietreiber** [comment]
@rtmclay thanks, for you answer. I haven't gotten around to testing this, but this `module-version` looks promising.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by wookietreiber** [comment]
I guess so.
