### ISSUE TITLE
Git tag 6.6.2 incorrectly identifies itself as 6.9.6-beta.

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#197]
Hi,

When building from the 6.6.2 tag, LMOD thinks that it is 6.9.6-beta.
This results with the  installation being placed into a 6.9.6-beta directory.
According to diff, they appear to be the same set of files (.git directory aside).

--
Lewis

**Comment by rtmclay** [comment]
Thanks for catching this.  I have created 6.6.3.  This is Lmod before all the changes to make the new Lmod 7+ series.    If you get a chance, please see if this works for you.   Note that I have removed the 6.6.2 label.

**Comment by lewis-john-lloyd** [comment]
Robert,

That worked.
Thanks.

Are you at SC16?

--
Lewis

**Comment by rtmclay** [comment]
Yes, I am.  I'll be giving a Lmod Talk in the TACC booth on Tuesday at 2pm.
