### ISSUE TITLE
Lmod fails on module dirs that user doesn't have read to

### ISSUE THREAD

**Issue by JackPerdue** [TACC/Lmod#199]
The following VASP directory was only readable by members of the vasp group.  It is in the default MODULEPATH.  With 6.6 we didn't have a problem.  After upgrading to 7.0 (today) our help desk saw this.

/usr/bin/lua: /software/lmod/7.0/libexec/DirTree.lua:171: cannot open /software/easybuild/modules/all/VASP: Permission denied

stack traceback:

    [C]: in function 'dir'

    /software/lmod/7.0/libexec/DirTree.lua:171: in function 'walk'

    /software/lmod/7.0/libexec/DirTree.lua:226: in function 'walk_tree'

    /software/lmod/7.0/libexec/DirTree.lua:237: in function 'walk_tree'

    /software/lmod/7.0/libexec/DirTree.lua:250: in function 'build'

    /software/lmod/7.0/libexec/DirTree.lua:263: in function 'new'

    /software/lmod/7.0/libexec/ModuleA.lua:575: in function '__new'

    /software/lmod/7.0/libexec/ModuleA.lua:632: in function 'singleton'

    /software/lmod/7.0/libexec/Var.lua:105: in function 'chkMP'

    /software/lmod/7.0/libexec/Var.lua:316: in function 'prepend'

    /software/lmod/7.0/libexec/MasterControl.lua:317: in function 'op'

    /software/lmod/7.0/libexec/cmdfuncs.lua:905: in function 'cmd'

    /software/lmod/7.0/libexec/lmod:460: in function 'main'

    /software/lmod/7.0/libexec/lmod:507: in main chunk

    [C]: ?

**Comment by rtmclay** [comment]
What are the owner and permissions on the VASP directory?

**Comment by JackPerdue** [comment]
Pretty sure ownership was j-perdue:vasp with 2750 on the directory and 640 on the modules.  Can't say anymore since its gone.  I didn't notice the problem, being in the vasp group.  But our users sure did when I made the swap from 6.6. to 7.0 (we are back to 6.6 for now... VASP wasn't the only problem).

**Comment by JackPerdue** [comment]
We also had a Rosetta module that I had set with 000 permissions.  Again, never had a problem with 6.6 but does with 7.0.   

My crew is reminding me why we don't make changes on a Friday afternoon (especially when half of them are still at or recovering from SC16). :)

**Comment by rtmclay** [comment]
I have pushed a new version (7.0.4) which now checks the permissions on the directory before walking the directory just like it did in 6.6.  Please test this out if you get the chance.

Thanks for the bug report.
