### ISSUE TITLE
[Question] Testing Requirements

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#202]
What programs are required to run the lmod test suite?

**Comment by rtmclay** [comment]
As you can see in the travis script: .travis.yml:

  - git clone https://github.com/rtmclay/Hermes.git
  - export PATH="$PATH:$PWD/lua_install/bin:$HOME/Hermes/bin"


You need to clone the rtmclay/Hermes repo.  Then put Hermes/bin in your path.  Finally cd lmod/rt
and run 

    $ tm

**Comment by lewis-john-lloyd** [comment]
This may be an odd request, but you could tag a version in the Hermes repository? Or update the TACC repo with a tagged version?

**Comment by rtmclay** [comment]
github.com/rtmclay/Hermes.git now has updated tags.
