### ISSUE TITLE
pager options are lower-cased

### ISSUE THREAD

**Issue by wookietreiber** [TACC/Lmod#218]
This is the command:

```bash
LMOD_PAGER=less LMOD_PAGER_OPTS='-XF' module list
```

This is the excerpt of the process list:

```console
$ ps aufxh
|   \_ /usr/bin/lua /software/lmod/lmod/libexec/lmod bash list
|       \_ sh -c LESS=-xf /usr/bin/less 1>&2
|           \_ /usr/bin/less
```

Somehow, my `-XF` gets lower-cased to `-xf`. Is this intentional or did I stumble across a bug?

**Comment by rtmclay** [comment]
Thanks for the bug report!  Please try out HEAD to see if it fixes this for you.

**Comment by wookietreiber** [comment]
Just checked with 7.3.6 and its fixed. Thanks.
