### ISSUE TITLE
LUA

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#220]
There is a recommended lua installation tarball that incorporates two lua libraries, posix and lfs.
Would it be possible to have a lua tarball that also incorporates a json library?

**Comment by rtmclay** [comment]
Sure, since I just uploaded today, I just overrode lua-5.1.4.9.tar.gz to have luajson.

**Comment by lewis-john-lloyd** [comment]
Thanks.
I will check the tarball and close today.

**Comment by lewis-john-lloyd** [comment]
Good to Go.
