### ISSUE TITLE
Request: Exit Status

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#222]
Would it be possible (or is it already) to have a module load command return an exit status if one or more of the modules listed on the command line failed to load?

**Comment by rtmclay** [comment]
It does it already.  At least it does it for me.  Note that if you do:

```
   $ module load A B XXX
```

and A and B exist but XXX doesn't then no modules are loaded and you should get a non-zero exit status.

**Comment by lewis-john-lloyd** [comment]
Which shell is that?
I had been in the tcsh and was not getting a return value.

**Comment by lewis-john-lloyd** [comment]
I just verified that the module alias does provide a return value in Bash.

**Comment by rtmclay** [comment]
There was a problem with the way the (t)csh alias was defined.  I have created version 7.3.12 which fixes the problem.  Please test out this version to see if it works for you.  Thanks for the bug report!

**Comment by lewis-john-lloyd** [comment]
Good to go with the abominable c-shell. Thanks as usual.
