### ISSUE TITLE
module show with optional "load" or "unload"

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#225]
Is there a way to do a module show that fakes the "load" or "unload" mode?
We have modulefiles that have if mode() == "load" and if mode() == "unload", and we would like to check via a module show if they are what we expect.
If there is not a way to do that, then would it be possible to add a flag to the show command to do that?

**Comment by rtmclay** [comment]
Why not use --raw?

    $ ml --raw show <module>

**Comment by lewis-john-lloyd** [comment]
If one were to iterate over a table, pushing environment variables and their values pulled from two separate tables that were dynamically generated, then the module --raw show <module> command is not very helpful since the there are many logical pathways that are navigated to set the values in the tables prior to the final pushenv command, which is just pushing pushing the table value.

It is difficult to see what would be pushed in this case.  I don't see any advantage of the module --raw show <module> as compared to just looking at the modulefile. The nice thing about module show is that the local variables are resolved, which is what we want to check.

**Comment by rtmclay** [comment]
Then I think that a shell script would do this quite nicely.  I can be the equivalent of:

```
$ (module load foo; module show bar)
```

**Comment by rtmclay** [comment]
I miss-understood what the question was.  As I understand the question, if a module has:
```
     if (mode() == "load") then
          setenv("FOO","BAR")
    end
```
then module show will not report the ```setenv("FOO","BAR")```.   Is there a way to have module show print more?   Yes, I'd change the modulefile to:

```
     if (mode() == "load" or mode() == "show" ) then
          setenv("FOO","BAR")
    end
```

**Comment by rtmclay** [comment]
Information about the week long class on how TACC manages systems can be found at:

https://www.tacc.utexas.edu/education/institutes/designing-and-administering-large-scale-systems
