### ISSUE TITLE
LMOD_REDIRECT breaks tab completion

### ISSUE THREAD

**Issue by kthust** [TACC/Lmod#233]
Maybe I do not use it correctly but when setting LMOD_REDIRECT=yes tab completions do not work.

```sh
    $ export LMOD_REDIRECT=yes
    $ module load <TAB> <TAB> # nothing happens
    $ export LMOD_REDIRECT=no
    $ module load <TAB> <TAB>
    [list of all modules]
```

`LMOD_REDIRECT=yes` also feels like the expected default behavior as the output of `module avail` is no error (I see a reason for the output on stderr for technical and historical reasons, but it still is less convenient).

**Comment by rtmclay** [comment]
It is helpful to report what version of Lmod you found the problem as well as what shell you are using.  In this case however, I figured out that there was a problem in bash where tab completion wasn't working correctly.

Please try Lmod 7.3.17 to see if it fixes tab completion for you as well.

**Comment by kthust** [comment]
The fix works fine for me. Thanks!
