### ISSUE TITLE
Inconsistent environment variable names for families

### ISSUE THREAD

**Issue by afif-elghraoui** [TACC/Lmod#240]
from `docs/source/010_user.rst`

> Then Lmod will not load another compiler modulefile. Another benefit of the modulefile family directive is that an environment variable "LMOD_COMPILER_FAMILY" is assigned the name (and not the version). This can be useful specifying different options for different compilers. In the High Performance Computing (HPC) world, the message passing interface (MPI) libraries are important. The mpi modulefiles can contain a family("MPI") directive which will prevent users from loading more than one MPI implementation at a time. Also the environment variable "LMOD_FAMILY_MPI" is defined to the name of the mpi library.

I was wondering why the format of the variable name is inconsistent. I think it would spare people confusion if these types of environment variables were in only one of the two formats `LMOD_*_FAMILY` or `LMOD_FAMILY_*`.

**Comment by rtmclay** [comment]
Thanks for the careful reading of the documentation.  Lmod has produced LMOD_FAMILY_* since the family function was introduced.  However you have found a bug in the documentation.  This has now been fixed.

**Comment by afif-elghraoui** [comment]
Great! Thanks for correcting to the documentation. I'm glad I could help bring it to your attention.
