### ISSUE TITLE
MT.lua attempt to index a nil value

### ISSUE THREAD

**Issue by shawnahall71** [TACC/Lmod#243]
Hi,

We've been seeing an intermittent issue on our new CentOS 7.3.1611 systems.  On occasion the system will get into a state where it will throw errors upon login to every user.  Clearing up this condition either requires a reboot or just patience until the problem goes away on its own.  We are running Lmod version 6.0.1 on all of our systems.

The errors appear to be all related to the `MT._build_locationTbl` function.  Logged errors are found below.

[lmod_errors.txt](https://gist.github.com/shawnahall71/3d7fca04e703f8ee464a08fad580dfeb)

**Comment by rtmclay** [comment]
Please test Lmod 7.4.1 to see if the problem persists.  I can only fix the latest versions.  Thanks,

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by shawnahall71** [comment]
Unfortunately I haven't had a chance to try out the new version, although I'm expecting I'll get to that sooner than later.  The presence of the issue is pretty infrequent, so even after the upgrade it will be a bit of wait and see.
