### ISSUE TITLE
isloaded status with concurrent loads

### ISSUE THREAD

**Issue by vanderwb** [TACC/Lmod#249]
I don't know if this is an oversight, or if it is the intended design of isloaded, but we've noticed that the isloaded function reports false in the case that you load the module to be checked at the same time as the containing module. That case causes some trouble for us, as we wrote a module which runs some extra commands if another module is loaded, and both modules are a part of the default module set. So when a user logs in and the default set is loaded, the extra commands aren't run due to the above behavior.

We are currently running Lmod 7.2.1. If that is the intended behavior of isloaded, another function that returns true for concurrent loads as well as previously loaded modules would be very useful!

**Comment by rtmclay** [comment]
Lmod marks the status of a module at the start of a load as "pending" then when the load completes it changes the status to "loaded".  It can't be marked as "loaded" because some modules conflict with themselves.  That is the gcc/6.3.lua modulefile might say:

```
conflict("gcc")
```

By marking the module as pending this conflict is avoided.  So if module A load B and B loads C then in module C both A and B are pending.  You can use the "isPending()" function like this:

```
   if( isloaded("A") or isPending("A")) then
      ...
  end
```

**Comment by vanderwb** [comment]
Thank you for the explanation and the suggestion. I don't think the "isPending" function suits our needs, since we aren't loading modules within other modules. However, in testing it, I found that the latest Lmod (7.4.5) has the behavior we need. Here is an example:

A.lua:
```
require("posix")
LmodMessage("Module A is loaded!")
```

B.lua
```
require("posix")
LmodMessage("Module B is loaded!")

if isloaded("A") then
    LmodMessage("B: I detect module A is loaded")
end
```

And the command result:
```
[17:04] lmod_pending$ ml A B
Module A is loaded!
Module B is loaded!
B: I detect module A is loaded
[17:08] lmod_pending$ ml B A
Module B is loaded!
Module A is loaded!
```

With version 7.2.1, neither order would trigger the isloaded check, which caused problems for us. Since the newer version behaves as we were expecting, I think you can close this issue.

**Comment by rtmclay** [comment]
Thanks for the clarification.  Closing.
