### ISSUE TITLE
complex expressions in prepend_path definitions 

### ISSUE THREAD

**Issue by michaelmayer2** [TACC/Lmod#250]
Situation is this:

I would like to define PATH in an LMOD Lua module so that PATH is constructed on-demand when loading the module, e.g. 

prepend_path("PATH","/apps/`id -g -n`/bin")

This works very nicely (Lmod 7.4, Lua 5.3) when the module is loaded. In my case (part of group users) the PATH /apps/users/bin is prepended to PATH.

When I try to unload the module however the PATH is not removed. 

Doing the same thing with explicitly replacing the `id -g -n'   with users works as expected.

I wonder if the issue now is that when unloading the module Lmod tries to remove the non-interpreted PATH and cannot find it. Is there any way to also interpret the PATH before removing it ? 

Any hints on how this could be fixed/solved ?

Many thanks,

Michael.

**Comment by rtmclay** [comment]
Lua doesn't do shell expansion so as far as Lmod is concerned the path is literally  /apps/`id -g -n`/bin and not the expanded version of say /apps/staff/bin.  The following will work better:

```
local groupName = capture("id -g -n")
prepend_path("PATH", pathJoin("/apps",groupName,"bin")
```

**Comment by michaelmayer2** [comment]
Yeah - that works a lot better. My suspicion about Lmod not interpreting the `id -g -n` seems to be correct indeed. Thanks for your quick feedback ! 

Now I just need to find a way to get this somehow in an easybuild recipe. 

Michael.

**Comment by boegel** [comment]
@michaelmayer2 You can include custom Lua code in module files via the `modluafooter` easyconfig parameter.

We can also consider adding support for a `%(groupname)s` template value, if this is of wider interest.

**Comment by michaelmayer2** [comment]
@boegel - thanks for your reply - modluafooter is a great idea. Will keept that in mind for the future.

For now I have solved the issue in a more pythonesque way: 

I replaced the `id -g -n` with os.popen("id -g -n").read().rstrip()

Thanks again ! Will keep the modluafooter in mind !

The background to this request here was to be able to offer group specific application directories for apps like Python, R, ... without having to actually hack the Lua modules once they are built by EasyBuild. Both solutions (modluafooter and python code) solve this issue. 

Not sure if a `%(groupname)s` template would be that widely used. I only would need it in 2 out of 500+ easyconfigs we maintain.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by michaelmayer2** [comment]
Sure, let's close. Thanks again ! 

For future reference - the pythonesque solution does not work as expected - obviously does EasyBuild interpret the popen call right at build time and then set the PATH once and for all to the group of the builder.

The proper dynamic solution is to use the modluafooter and use custom luad code there.

`modluafooter = 'prepend_path("PATH", pathJoin("/apps",capture("id -g -n"),"bin")'`
