### ISSUE TITLE
environment variable is not removed properly after rm or purge command

### ISSUE THREAD

**Issue by handrake0724** [TACC/Lmod#251]
My Lmod version is 7.4.7 and lua is 5.3.4.

I have a following module, test.lua

```
-- -*- lua -*-
-- test.lua
local version="4.x"
local foamRoot=os.getenv("HOME")

setenv("WM_PROJECT", "OpenFOAM")
setenv("WM_PROJECT_VERSION", version)
setenv("WM_PROJECT_INST_DIR", pathJoin(foamRoot, os.getenv("WM_PROJECT")))
setenv("WM_PROJECT_DIR", pathJoin(os.getenv("WM_PROJECT_INST_DIR"), os.getenv("WM_PROJECT").."-"..version))
setenv("WM_THIRD_PARTY_DIR", pathJoin(os.getenv("WM_PROJECT_INST_DIR"), "ThirdParty-"..version))
setenv("WM_PROJECT_USER_DIR", pathJoin(os.getenv("HOME"), os.getenv("WM_PROJECT"), os.getenv("USER").."-"..version))
setenv("WM_DIR", pathJoin(os.getenv("WM_PROJECT_DIR"), "wmake"))

```

running module load test and environment variables are set as follows:

```
env | grep WM_
WM_PROJECT_INST_DIR=/home/bb/OpenFOAM
WM_THIRD_PARTY_DIR=/home/bb/OpenFOAM/ThirdParty-4.x
WM_PROJECT_USER_DIR=/home/bb/OpenFOAM/seongmo-4.x
WM_PROJECT=OpenFOAM
WM_DIR=/home/bb/OpenFOAM/OpenFOAM-4.x/wmake
WM_PROJECT_VERSION=4.x
WM_PROJECT_DIR=/home/bb/OpenFOAM/OpenFOAM-4.x
```

and running module rm test or running module purge and environment variables are set as follows:

```
env | grep WM_
WM_THIRD_PARTY_DIR=/home/bb/OpenFOAM/ThirdParty-4.x
WM_PROJECT_USER_DIR=/home/bb/OpenFOAM/seongmo-4.x
WM_DIR=/home/bb/OpenFOAM/OpenFOAM-4.x/wmake
WM_PROJECT_DIR=/home/bb/OpenFOAM/OpenFOAM-4.x
```

So, 4 out of 7 environment variables is still alive. It is normal action in Lmod (Tcl version environment module removes the variables correctly, though) or did I set something wrong?

Regards.

**Comment by boegel** [comment]
It's probably not a coincidence that the variables that remain defined are the ones that rely on other `$WM_*` environment variables (e.g. `$WM_DIR` depends on `$WM_PROJECT_DIR`)...

**Comment by handrake0724** [comment]
@boegel then, Am I not able to define environment variables which have dependency on other environment variables in Lmod? But, this approach works in Tcl environment variables so I think weird.
If the way I define environment variables is not correct, How can I correct the behavior?

**Comment by rtmclay** [comment]
When a module is unloaded it reverse the action.  So when test.lua is unloaded it removes the env. vars. from the environment.  So unloading 
    setenv("WM_PROJECT", "OpenFOAM")

means that WM_PROJECT has no value so all the os.getenv() that depend on WM_PROJECT have no value.  You'll be better off doing:
```
local version         = "4.x"
local foamRoot        = os.getenv("HOME")
local project         = "WM_PROJECT"
local inst_dir        = pathJoin(foamRoot,project)
local proj_dir        = pathJoin(inst_dir,project.."-"..version)
local third_party_dir = pathJoin(inst_dir,"ThirdParty-"..version)
local user_dir        = pathJoin(foamRoot,project, os.getenv("USER").."-"..version)
local wm_dir          = pathJoin(proj_dir,"wmake")

setenv("WM_PROJECT", project)
setenv("WM_PROJECT_VERSION", version)
setenv("WM_PROJECT_INST_DIR", inst_dir)
setenv("WM_PROJECT_DIR", proj_dir)
setenv("WM_THIRD_PARTY_DIR", third_party_dir)
setenv("WM_PROJECT_USER_DIR",user_dir)
setenv("WM_DIR", wm_dir)
```
This will do the right thing when loading and unloading.

**Comment by handrake0724** [comment]
@rtmclay Thanks for kindly explanation. BTW, I have one more question about the Lmod's behavior with prepend_path.
let my PATH variable has following values:
PATH=/usr/local/bin:/usr/bin:$HOME/local/bin

when I use prepend_path like
prepend_path("PATH", "/usr/bin")

I expected PATH variable should have
PATH=/usr/bin:/usr/local/bin:/usr/bin:$HOME/local/bin

but, actual value is
PATH=/usr/bin:/usr/local/bin:$HOME/local/bin

So, the path /usr/bin is gone after running module rm or module purge.
Is this behavior intended or is there a way to avoid it?

**Comment by rtmclay** [comment]
By default Lmod, prevents you from having duplicate directories in a path-like variable.   You can configure Lmod to allow for duplicate path by configuring Lmod with "--with-duplicatePaths=yes"

A future version of Lmod will support reference counting for entries in a path when duplicates are not allowed.  It maybe summer before I get to that.

**Comment by handrake0724** [comment]
@rtmclay Thanks a lot.

**Comment by handrake0724** [comment]
@rtmclay Following your comment, I can make lua file load and unload environment script.
Problem is when I make a meta module.

I have three modules: compiler.lua, openmpi.lua and test.lua
and meta module (meta.lua) reads
```
load("compiler", "openmpi", "test")
```
which has dependency: test on openmpi, openmpi on intel

module load meta is working good.
But, module purge or module rm meta does not unload environment variables defined in openmpi and test.
Following you comment, the behavior of meta module's unloading is in the order of compiler and openmpi and test instead of test and openmpi and compiler.
Is it impossible to specify unloading order in meta module?

**Comment by rtmclay** [comment]
Then do this:
```
local foo=pathJoin(os.getenv("FOO_COMPILER"),"abc")
local bar=...
if (mode() == "unload") then
   foo = "foo"
   bar = "bar"
end
setenv("FOO",foo)
setenv("BAR",bar)
```
Or I suppose you could do 

```
if (mode() =="load") then
    load("compiler","openmpi","test")
else
   load("test","openmpi","compiler")
end
```

but this is a lot of work that the hierarchy solves for you.

**Comment by handrake0724** [comment]
@rtmclay The second solution works like a charm. Thank you so much. You saved my life.

**Comment by rtmclay** [comment]
O.K. to close?
