### ISSUE TITLE
progress bar when loading modules

### ISSUE THREAD

**Issue by xiaohan2012** [TACC/Lmod#252]
Hi, 

I am using `module load`, which takes a long time for certain modules. 

Is it possible to inspect the progress somehow? For example, a text-based progress bar will be cool.

Thanks!

**Comment by rtmclay** [comment]
If loading a module take a long time, then you might have a problem.  It is possible that you have a load storm.   You should make sure that you have the latest version of Lmod (or at least 7.4.5) and look at 

1) http://lmod.readthedocs.io/en/latest/220_tracing.html

2) http://lmod.readthedocs.io/en/latest/210_load_storms.html

See if the tracing or the full debug will tell you something.
