### ISSUE TITLE
update_lmod_system_cache_files used by different users

### ISSUE THREAD

**Issue by LucHermitte** [TACC/Lmod#253]
Hi,

We are in a situation where modules can be installed by different persons (belonging to a same privileged group), and where the cache file could also be updated by these same different persons.

When using `update_lmod_system_cache_files` we observe two issues:

1. We don't have suffisient rights to modify `spiderT.lua` and `system.txt` files.
2. `cp -p spiderT.lua spiderT.lua.old` fails because of the owner change

Here is a little patch that fixes 1) thanks to `chmod 664`, and 2) by using `mv` instead of `cp -p`. As the old file is discarded, and the current one is replaced, using `mv` seems to make sense. I may have missed a use case though. I'm not sure.

```patch
--- /opt/lmod/lmod/libexec/update_lmod_system_cache_files   2017-04-19 12:11:49.682689000 +0000
+++ /opt/lmod/lmod/libexec/update_lmod_system_cache_files.2 2017-04-19 12:13:49.549419000 +0000
@@ -236,6 +236,7 @@
     debug "Creating Lmod cache timestamp file @ ${LMOD_CACHE_TIMESTAMP_FILE}.new"
     debug "Creating empty timestamp file at ${LMOD_CACHE_TIMESTAMP_FILE}.new"
     touch ${LMOD_CACHE_TIMESTAMP_FILE}.new
+    chmod g+w "${LMOD_CACHE_TIMESTAMP_FILE}.new"
 }


@@ -243,7 +244,7 @@
 install_new_cache() {
     cache_ext=$1
     cache_file_path=$2
-    chmod 644 ${cache_file_path}.new.${cache_ext}
+    chmod 664 ${cache_file_path}.new.${cache_ext}

     local OLD=${cache_file_path}.old.${cache_ext}
     local NEW=${cache_file_path}.new.${cache_ext}
@@ -252,13 +253,14 @@
     # back up existing cache file
     if [ -f $RST ]; then
         debug "Backup up old Lmod cache file $RST to $OLD"
-        cp -p $RST $OLD
+        mv $RST $OLD
         debug "`ls -l $OLD`"
     fi

     # put new cache file in place
     debug "Putting new cache file $NEW place at $RST"
     mv $NEW $RST
+    chmod 664 $RST
 }

 # run spider command to generate specified cache type to specified file path
```

You may prefer to offer this feature optionally. I can't tell.

**Comment by wpoely86** [comment]
This should be optionally. It's not a good idea to change the default behaviour.

The `cp` cannot be changed to `mv`? This means that users which do something with Lmod in between those lines will not find a cache.

**Comment by LucHermitte** [comment]
OK. I understand. I tend to see `mv` as atomic, compared to `cp -p`, but you're right it isn't.

**Comment by boegel** [comment]
@LucHermitte it's not so much that `mv` isn't atomic, it's that Lmod checks both multiple filenames for the cache (both the specified and with a `.old` suffix), see https://github.com/TACC/Lmod/blob/master/src/Cache.lua#L141

**Comment by LucHermitte** [comment]
What about deleting the old file before the `cp -p` then? In that case, `$RST` continues to exist until `$OLD` is fully replaced. In the mean time, there is no old file.

This would give this patch (which provides a `-G` option`):

```patch
--- /opt/lmod/lmod/libexec/update_lmod_system_cache_files.0	2017-04-19 12:52:33.150742000 +0000
+++ /opt/lmod/lmod/libexec/update_lmod_system_cache_files	2017-04-19 12:50:44.069036000 +0000
@@ -71,6 +71,10 @@
 UPDATE_JSON_RMAPT=0
 UPDATE_XALT_JSON_RMAPT=0
 
+# Tells whether anybody in the current group can update the cache
+# Defaut: no, export to 1, in .bashrc for instance, to globally authorize
+LMOD_GROUP_CAN_UPDATE_CACHE=${LMOD_GROUP_CAN_UPDATE_CACHE:-0}
+
 #
 # Utility functions
 #
@@ -111,6 +115,8 @@
     echo "      print (this) help and exit"
     echo "  -t <timestamp.txt>"
     echo "      location of Lmod cache timestamp file (default: determine via 'ml --config')"
+    echo "  -G"
+    echo "      enable anybody in the current group to update the cache file."
     echo "  -r"
     echo "      enable updating reverseMapT cache file (default: only spiderT and dbT cache files)"
     echo "  -R <reverseMapD>"
@@ -128,7 +134,7 @@
 parse_cmdline(){
     debug "Parsing command line options..."
     local OPTIND
-    while getopts :d:DhmHt:rR:XJK opt; do
+    while getopts :d:DhmHt:rR:XJKG opt; do
         case $opt in
             d)
                 LMOD_CACHE_DIR=$OPTARG
@@ -159,6 +165,9 @@
 	    K)
                 UPDATE_XALT_JSON_RMAPT=1
                 ;;
+            G)
+                LMOD_GROUP_CAN_UPDATE_CACHE=1
+                ;;
             \?)
                 print_help
                 error "Unknown option specified: -$OPTARG"
@@ -236,6 +245,11 @@
     debug "Creating Lmod cache timestamp file @ ${LMOD_CACHE_TIMESTAMP_FILE}.new"
     debug "Creating empty timestamp file at ${LMOD_CACHE_TIMESTAMP_FILE}.new"
     touch ${LMOD_CACHE_TIMESTAMP_FILE}.new
+
+    if [ ${LMOD_GROUP_CAN_UPDATE_CACHE} -eq 1 ] ; then
+        debug "Give group write permission on ${LMOD_CACHE_TIMESTAMP_FILE}"
+        chmod g+w "${LMOD_CACHE_TIMESTAMP_FILE}.new"
+    fi
 }
 
 
@@ -252,6 +266,7 @@
     # back up existing cache file
     if [ -f $RST ]; then
         debug "Backup up old Lmod cache file $RST to $OLD"
+        [ -f "${OLD}" ] && rm $OLD
         cp -p $RST $OLD
         debug "`ls -l $OLD`"
     fi
@@ -259,6 +274,11 @@
     # put new cache file in place
     debug "Putting new cache file $NEW place at $RST"
     mv $NEW $RST
+
+    if [ ${LMOD_GROUP_CAN_UPDATE_CACHE} -eq 1 ] ; then
+        debug "Give group write permission on ${OLD} and ${RST}"
+        chmod g+w "$OLD" "$RST"
+    fi
 }
 
 # run spider command to generate specified cache type to specified file path
```

**Comment by rtmclay** [comment]
And what happens if a user is in the middle of reading the cache file that you delete.  By moving the file the inode remains the same and the read can continue.

This patch is too specific to your site's needs and not of general use. It won't be added to the main line.    Also this script is provided as a convenience, you can manage to build the system spider cache file as you like.     

This script doesn't change very often.  Once it was stable, it only changed once when the name of the system cache file changed when going to Lmod 7.  You should be safe maintaining your own copy of this script.

**Comment by LucHermitte** [comment]
> And what happens if a user is in the middle of reading the cache file that you delete. By moving the file the inode remains the same and the read can continue.

The file wasn't moved, but overwritten with `cp -p`. Anyway, IIRC, this shouldn't change anything: filesystems will keep the inode if the file was opened and not yet closed while a `rm` (or an overwriting `cp`, or a `mv`) is performed. If the file was peeked thanks to multiple calls to tools like `grep` or `sed`, it wouln't work correctly even with `cp -p`.

> This script doesn't change very often. Once it was stable, it only changed once when the name of the system cache file changed when going to Lmod 7. You should be safe maintaining your own copy of this script.

This slightly complicates future lmod updates as we'll have to override the official script with our specific instance.

> This patch is too specific to your site's needs and not of general use. It won't be added to the main line.

OK. If you don't see this as a general enough scenario, we understand.

Thank you.
