### ISSUE TITLE
Convenience Feature Request - load modules by absolute path

### ISSUE THREAD

**Issue by davidedelvento** [TACC/Lmod#254]
Often times I find myself doing something like `module use /path/to/blah` for the sole purpose of doing `module load something` (which is located in `/path/to/blah`), just to test the `something` module, or for a few other odd reasons.

Besides the double typing, often times there are name clashes which I need to pay attention to (as described in http://lmod.readthedocs.io/en/latest/060_locating.html) to make sure I'm loading the right `something` and I feel I'm spending too much time in bookkeeping as opposed to what I really need to pay attention to (which is left to the imagination of the reader).

It would be extremely useful and much more convenient to be able to load a module just by absolute path. 
Since by design it breaks the module hierarchy and other lmod features, it may not be appropriate to call it load, and it does not even need to be called so. It could be called `test`, `add`, `take` or whatever other name deemed appropriate (however it needs to "load" the module to be useful).

**Comment by rtmclay** [comment]
In an old version of Lmod, you could load an absolute path (like version 2 or 3) but it created a problem which I do not remember now.  

The whole bases of the code internal to Lmod is based on MODULEPATH.  Every time MODULEPATH changes all the modules are checked to see if they would be loaded again.  If not the module is made inactive.   There would have to be a great deal of special case code to handle the case where the following modules are not from an entry in MODULEPATH.  And even then it would still likely come up against the problem that I found before.

Another approach might be to somehow take the full path an magically break it into a MODULEPATH entry and then a module full name.    The trouble is that it is impossible to know where to perform the split.  Is the module a name without a version? Is it Name/version? Is it Name/Version/Version? ...

My suggestion would be to create a shell script or some kind of program that takes single argument:

```
$ mltest /path/to/module_name/version
```

Where internally you know that you always create N/V style modulefiles so you split the path up into parts and call the two module commands:

```
MDIR="/path/to"
NAME="module_name/version"
module use $MDIR
module load $NAME
```

It is easy to create a script that does the right thing for you but it is impossible for Lmod to read the user's  mind to know whether they would like N,NV,CNV or NVV naming scheme.

**Comment by davidedelvento** [comment]
Thanks for explaining some of the issues that adding my feature request would create. The problem with the "script" approach is still that I have to pay attention to the name clashes, which is my main gripe here (typing 2 commands instead of one is not ideal but it's not a big deal either). 

One simple use case, there is module `foo/n` somewhere and it has a problem. So I write a module `foo/n` in some other location and I want to test it to see if the problem is solved. Therefore I want to make sure I am loading the **right** `foo/n` for my purpose.

But I appreciate this being a complicated issue for the reasons you stated. Let me try a different approach, let me know if it's easier and make any sense to you.

Let's use another command instead of module (but the code base will be shared) and let me call it `cuckoo` for the lack of a better name. What `cuckoo` does is a limited subset of what `module` does, namely it supports only load-by-absolute-path, list (will list absolute path), and unload. Whatever `cuckoo` does, `module` kind-of-ignores, like if I manually set aliases or environmental variables outside of modules (and vice-versa, `cuckoo` ignores anything that module may do).

Such a `cuckoo` would satisfy my needs, hopefully without causing any problem to module. Of course, I am not sure how hard would it be to implement, since now the load, unload and list routines will need to check "am I called as module or as cuckoo" (which is easy), but then if `cuckoo`, they need to do something similar, but not quite identical which may still require too many special paths in the code to be worth implementing.

**Comment by rtmclay** [comment]
Cuckoo wouldn't be as hard to implement since all it does is evaluate the modulefile itself and push it into the environment.  

The only time where it wouldn't be the one you wanted is in the following case:  Your module tree has 
foo/1 and foo/2 and foo/2 is marked as a default.  If you then try to your own foo/2 then you will have a problem because Lmod picks the first default over the first one found.

So my solution to that is to modify the shell script to do:

```
MDIR="/path/to"
SN="module_name"
V="version"
NAME="module_name/version"
module use $MDIR
(cd $MDIR/$SN; rm -f default; ln -s $V default)
module load $NAME
```
This way you will have marked the "new" foo/2 as the default.  That way any system defaults will be overridden by the symbolic default created in the script.

**Comment by davidedelvento** [comment]
I think this works. I've shared it with other people in my team and they might comment something here. If they don't in a week or so, feel free to close this issue.
Thanks
Davide
