### ISSUE TITLE
MODULESHOME not defined in profile script

### ISSUE THREAD

**Issue by adamjstewart** [TACC/Lmod#271]
I recently installed Lmod 7.4.9 and symlinked both profile and cshrc to the list of startup scripts according to the instructions [here](http://lmod.readthedocs.io/en/latest/030_installing.html). Things seem to be working (the module function is defined and `module avail` works), but when I log in or run a Bash script I see:
```
/bin/bash: /init/bash: Not a directory
```
I tracked this down to the `profile` script, which contains this line:
```
export BASH_ENV=$MODULESHOME/init/bash
```
Unfortunately, this script doesn't define `MODULESHOME` so Bash tries to source `/init/bash` instead. Is this a bug? It seems like every other initialization script defines this variable.

**Comment by rtmclay** [comment]
Thanks for the bug report!  I have checked in version 7.4.11 to fix this problem.  The fix here is to replace $MODULESHOME with @PKG@ in init/profile.in and re-install if you to stay at 7.4.9

**Comment by adamjstewart** [comment]
For the record, this commit appears to be the culprit:
https://github.com/TACC/Lmod/commit/b863e82b77769ff83360502ea1fcf392a3a6fcd5

**Comment by rtmclay** [comment]
O.K. to close?
