### ISSUE TITLE
Is the default modulefile always the one with the highest prefix or what?

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#275]
I recall that Tmod behaves like this; I was expecting Lmod to pick the one marked with (D), no?!
(will supply more info if confirmed)

```
[fgeorgatos@node114 ~]$ ml av Eas

------------------------ /home/fgeorgatos/.local/easybuild/modules/all -------------------------
   EasyBuild/2.8.2    EasyBuild/3.1.2

-------------------------------------- /etc/site/modules --------------------------------------------
   EasyBuild/2.9.0

----------------- /bla/HPCBIOS/20170505/el7/hi/modules/all ------------------------------------
   EasyBuild/3.2.1 (D)

  Where:
   D:  Default Module

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".


[fgeorgatos@node114 ~]$ ml EasyBuild
[fgeorgatos@node114 ~]$ eb --version
This is EasyBuild 3.1.2 (framework: 3.1.2, easyblocks: 3.1.2) on host node114.
```

**Comment by rtmclay** [comment]
It depends on whether the layout is NV or NVV.  It is FIND-BEST with nv layout and FIND-FIRST with NVV module layouts.  Now if you do have an NVV module layout then Lmod picked the correct module.  However if you have an NVV layout then Lmod told you the wrong default.  Which is it?

**Comment by fgeorgatos** [comment]
You are correct, in that this is an instance of a mixed layout (hidden by the fact that I only searched for easybuild). I actually observe: `N, NV, NVV, NVVV, NVVVV` (all Bright 7.0 systems probably have it so).

In short, yes, i was expecting then the (D) letter in another location; other than that it works as it says on the tin :)

**Comment by rtmclay** [comment]
Please test HEAD to see if this fixes this for you.

**Comment by fgeorgatos** [comment]
@rtmclay : ok, I tried on the demo2 system but couldn't reproduce the (bug) effect (so that I can validate the change). That means it would take me much more to go through the hoops, at least now.

Basically, if your test case passes, I'd consider it a given that this is fixed and will verify on my next `bic` check cycle, just in case - r we ok with that?

**Comment by rtmclay** [comment]
I consider this bug fixed.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by fgeorgatos** [comment]
y! done

**Comment by fgeorgatos** [comment]
OK, this is just to confirm that as of Lmod/7.6 it does what it says on the tin; here's a record:

```
[fgeorgatos@ussd-tst-brln01 ~]$ ml av Easy

------------------------- /home/fgeorgatos/.local/easybuild/modules/all --------------------------
   EasyBuild/2.8.2    EasyBuild/3.1.2 (D)

------------------------------- /bla/HPCBIOS/20160923/modules/all --------------------------------
   EasyBuild/2.9.0

  Where:
   D:  Default Module

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

[fgeorgatos@ussd-tst-brln01 ~]$ date
Tue Jul 25 12:10:26 PDT 2017
[fgeorgatos@ussd-tst-brln01 ~]$ ml EasyBuild
[fgeorgatos@ussd-tst-brln01 ~]$ eb --version
This is EasyBuild 3.1.2 (framework: 3.1.2, easyblocks: 3.1.2) on host ussd-tst-brln01.
[fgeorgatos@ussd-tst-brln01 ~]$ ml --version

Modules based on Lua: Version 7.6  2017-07-24 14:07 -05:00
    by Robert McLay mclay@tacc.utexas.edu

[fgeorgatos@ussd-tst-brln01 ~]$
```
