### ISSUE TITLE
xmlSoftwarePage generation no longer works with v7.x.

### ISSUE THREAD

**Issue by acaprez** [TACC/Lmod#279]
Hello,

The `xmlSoftwarePage` option to `spider` throws the following error starting with Lmod 7.0:
```
/usr/bin/lua: /util/opt/lmod/lmod/libexec/spider:745: attempt to index field 'full' (a nil value)
stack traceback:
	/util/opt/lmod/lmod/libexec/spider:745: in function 'localSoftware'
	/util/opt/lmod/lmod/libexec/spider:649: in function 'xmlSoftwarePage'
	/util/opt/lmod/lmod/libexec/spider:352: in function 'func'
	/util/opt/lmod/lmod/libexec/spider:475: in function 'main'
	/util/opt/lmod/lmod/libexec/spider:771: in main chunk
	[C]: ?
```

It appears the structure of the `dbT` table changed between versions 6.6 and 7, and so some of the key names are no longer valid.

I have a local branch with fixes for the new format that works correctly for our module files collection.  I'd be happy to open a PR if that would be useful.

**Comment by rtmclay** [comment]
Sure, please submit a PR.  Thanks!
