### ISSUE TITLE
INSTALL: createSystemCache.sh file?

### ISSUE THREAD

**Issue by HenrikBengtsson** [TACC/Lmod#285]
The [`INSTALL`](https://github.com/TACC/Lmod/blob/c0b0ee9225f4af63b49f45c3ee4eef4171ba5518/INSTALL#L95-L103) file talks about a `createSystemCache.sh` script - what / where is that script?
```
      2) If you have a formal proceedure for installing packages on your system
         then I recommend you do the following.  Have the install proceedure run
         the createSystemCache.sh file.  This will create file called "system.txt"
         which marks the time that the system was last updated, so Lmod knows that
         the cache is still good.

      3) Or you can run the createSystemCache.sh script say every 30 mins.  This way
         the cache file is up-to-date.  No new module will be unknown for more
         30 mins.
```

**Comment by HenrikBengtsson** [comment]
Should that `createSystemCache.sh` be updated to `update_lmod_system_cache_files`, cf. http://lmod.readthedocs.io/en/latest/130_spider_cache.html?

**Comment by ocaisa** [comment]
I think this is what is meant...
https://github.com/TACC/Lmod/blob/master/contrib/BuildSystemCacheFile/createSystemCacheFile.sh

**Comment by boegel** [comment]
@HenrikBengtsson Definitely use `update_lmod_system_cache_files`, the `INSTALL` file should be updated.

**Comment by rtmclay** [comment]
I have updated the INSTALL file with the following:

      3) Or you can create a script (say createSystemCache.sh) that runs every 30
         mins.  This way the cache file is up-to-date.  No new module will be
         unknown for more 30 mins.  Assuming that you are going to store the cache file
         in /opt/moduleData/cacheDir and the timestamp is in /opt/moduleData/system.txt.
         Please create the following script:

         $ cd /opt/moduleData
         $ cat > createSystemCache.sh
         LMOD_CACHE_LOCATION=/opt/moduleData
         LMOD_DIR=<path_to_the_command_spider>
         MODULEPATH=<Your site's default MODULEPATH>

         $LMOD_DIR/update_lmod_system_cache_files -t $LMOD_CACHE_LOCATION/system.txt -d $LMOD_CACHE_LOCATION/cacheDir $MODULEPATH
         ^D                  

        Please modify the top three environment variables to match your site.

Hopefully this will clarify the situation.

**Comment by HenrikBengtsson** [comment]
Thanks - this certainly clarifies how it works / what the intentions are.  May I suggest to use `LMOD_CACHE_DIR` instead of `LMOD_CACHE_LOCATION` because you're already using the former in the code.  This also lowers the risk of believing `LMOD_CACHE_LOCATION` is a supported environment variable.

**Comment by rtmclay** [comment]
Thanks for your comments.  I have updated the INSTALL file to change LMOD_CACHE_LOCATION to CACHE_LOCATION.  

O.K. to close?

**Comment by HenrikBengtsson** [comment]
Thxs
