### ISSUE TITLE
Regular expressions with spider

### ISSUE THREAD

**Issue by vanzod** [TACC/Lmod#286]
I could not find a way to pass `spider` a regular expression to search for modules. 
That would be a useful feature if not yet supported.

**Comment by rtmclay** [comment]
It is there:
```
   $ module -r spider '^s' 
```
will find all modules that start with 's'  (not 'S').  To find both upper and lower case s, you can do either:

```
     $ module -r spider '^s' '^S'
     $ module -r spider '^[Ss]'
```

The documentation from module help was a little confusing so I have changed it to:

```
Searching with Lmod:
--------------------
  All searching (spider, list, avail, keyword) support regular expressions:


  -r spider           '^p'          Finds all the modules that start with `p' or `P'
  -r spider           mpi           Finds all modules that have "mpi" in their name.
  -r spider           'mpi$         Finds all modules that end with "mpi" in their name.
```

**Comment by wpoely86** [comment]
Keep in mind that these are lua patterns. They don't support everything you might expect. Something like `(foo|bar)` does not work.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by vanzod** [comment]
@rtmclay Yes. Thanks
