### ISSUE TITLE
EXAMPLES: Minimal examples illustrating different Lmod concepts?

### ISSUE THREAD

**Issue by HenrikBengtsson** [TACC/Lmod#287]
Does anyone know of a set of teeny module files that illustrate the different properties of Lmod?  Maybe in an online repos?  Something that one (e.g. first timers but also advanced users) can download / clone locally and play with, e.g.

```sh
module show lmod-examples/envvars
-----------------------------------------------------------------------------------------------------------
   /home/hb/modulefiles/lmod-examples/envvars/default.lua:
-----------------------------------------------------------------------------------------------------------
help([[Lmod Examples: Environment Variables
]])
whatis("Description: Example of how Lmod handles environment variables.")
setenv("LMOD_EXAMPLES_SETENV","Assigned using setenv()")
pushenv("LMOD_EXAMPLES_PUSHENV","Assigned using pushenv()")
```
and
```sh
$ env | grep LMOD_EXAMPLES_

$ export LMOD_EXAMPLES_SETENV=0
$ export LMOD_EXAMPLES_PUSHENV=0
$ env | grep LMOD_EXAMPLES_
LMOD_EXAMPLES_PUSHENV=0
LMOD_EXAMPLES_SETENV=0

$ module load lmod-examples/envvars
$ env | grep LMOD_EXAMPLES_
LMOD_EXAMPLES_PUSHENV=1
LMOD_EXAMPLES_SETENV=1
__LMOD_STACK_LMOD_EXAMPLES_PUSHENV=MQ==:MA==

$ module unload lmod-examples/envvars
$ env | grep LMOD_EXAMPLES_
LMOD_EXAMPLES_PUSHENV=0
__LMOD_STACK_LMOD_EXAMPLES_PUSHENV=MA==
```
Above using:
```sh
$ module --version

Modules based on Lua: Version 7.5  2017-06-16 14:32 +02:00
    by Robert McLay mclay@tacc.utexas.edu
```

**Comment by rtmclay** [comment]
There are many many example module files in the rt/* directories.  For example the modulefiles in rt/pushenv/mf/* show examples of pushenv.  The files in rt/* are the way Lmod tests itself.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by HenrikBengtsson** [comment]
Yes, it's ok to close, the existing test cases are good enough for me.  However, I was posting this issue more as a suggestion for having examples that would be available in, or easily accessible from, the document for all / future users.  I think that would help lower the bar a little.  I understand that providing that would be major work.

**Comment by rtmclay** [comment]
I did add some documentation about this:

http://lmod.readthedocs.io/en/latest/100_modulefile_examples.html

I hope this helps

**Comment by HenrikBengtsson** [comment]
beautiful - thxs
