### ISSUE TITLE
'ml spider' mentions hidden modules without --show-hidden

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#289]
While looking into updating our Lmod 6.6 installation to the latest Lmod 7.5.4, we found this issue:

```
$ module spider intel/2016a

----------------------------------------------------------------------------
  intel: intel/2016a
----------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "intel/2016a" module is available to load.

      cluster/.metapod
      cluster/delcatty
      cluster/golett
      cluster/phanpy
      cluster/raichu
      cluster/swalot
```

Why is the hidden module `cluster/.metapod` being mentioned here, while `--show-hidden` is not used? Is that an intentional change in Lmod 7 compared to Lmod 6?

**Comment by rtmclay** [comment]
The showing of dependencies that are hidden is a change between Lmod
6 and Lmod 7.  The trouble is that the Julich EB'ers wanted it, so in
some sense, you need to fight it out with them.

It is clear to me that show_hidden flag only applies to the module
being displayed and not the dependencies.  There are also some
questions that need to be answered before deciding what the right
thing to do is:

Suppose you have module A which depends on .GCCcore only.  What should be
displayed when show hidden is off?

  * Do you show A with no dependencies?
  * Not show A at all?
  * Show A with its dependency hidden or not.
  * Should there be different behavior when all are hidden?

There are other problems.  While it is easy to know about the .dot
hidden modules, marked hidden modules (i.e.) no leading dot. have just
become much harder to determine.  The isVisible function takes the
fullName, sn and the fullpath to the modulefile.   This is a problem
as the fullpath to the modulefile as been lost.

But I still think the biggest problems are what does all this mean.

**Comment by boegel** [comment]
In our case, modules that depend on a hidden module to be loaded should not be visible in the output of `ml spider`. So if there are no other modules that can provide access to them, the output should be empty.

I understand the use case of @damianam & @ocaisa & co here, but ours is a bit different.

So, maybe this can be made site configurable (keeping the default as-is)?

If not, we'll just go ahead and patch our Lmod installation, that shouldn't be too much work, @wpoely86 was already offering help there to point out the location to do this. ;-)

**Comment by wpoely86** [comment]
Yeah but I haven't had a proper look at it. In theory it's just a call to `isVisible` but if you don't know the fullpath of the module, it's very non-trivial.

**Comment by rtmclay** [comment]
It is trivial to patch Lmod to know how to deal with a dot module but for full isVisibleHook support would hard to do.  It require changing the mechanism to compute the dependency for spider so it would definitely be a PITA.

**Comment by boegel** [comment]
@rtmclay Thoughts on this patch (provided by @wpoely86) to fix this problem for our setup?

Mind, I'm not asking that this is applied in the central Lmod repository, we can just apply this patch in our local installation...

```diff
diff --git a/src/Spider.lua b/src/Spider.lua
index 587ff3c1..84d08d95 100644
--- a/src/Spider.lua
+++ b/src/Spider.lua
@@ -971,8 +971,10 @@ function M._Level2(self, sn, entryA, possibleA)
          for j = 1, #entryT.parentAA do
             local parentA = entryT.parentAA[j]
             for i = 1, #parentA do
-               b[#b+1] = parentA[i]
-               b[#b+1] = '  '
+               if show_hidden or not parentA[i]:find("cluster/%.") then
+                 b[#b+1] = parentA[i]
+                 b[#b+1] = '  '
+               end
             end
             b[#b] = "\n      "
          end
```

**Comment by rtmclay** [comment]
That is fine.  You could change the if test to be:
```
if (show_hidden or not (parentA[i]:find("^.") or parentA[i]:find("/%."))) then
```
if you wanted a general test for any old style hidden module.

**Comment by boegel** [comment]
Great, thanks for the feedback @rtmclay.

I'm closing this issue since it's clear this is a site-customisation 'problem'.
