### ISSUE TITLE
setup to pick default module based on environment variable no longer works with Lmod 7

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#290]
For one of our (hand-written) sets of modules, we want to pick the default 'version' based on a particular environment variable (and complain that no default can be picked if that environment variable is not set).

This setup works with Lmod 6.6:

* `cluster/default` symlink to hidden module file `.defaultcluster.lua`
* contents of `cluster/.defaultcluster.lua`:

```
-- -*- lua -*-

local defaultcluster = os.getenv("VSC_DEFAULT_CLUSTER_MODULE") or ""

if defaultcluster ~= "" then
    load("cluster/" .. defaultcluster)
else
    LmodError([[No default cluster can be loaded. You need to choose one: 'ml spider cluster' gives an overview]])
end
```

This works as intended with Lmod 6:

```
$ ml --version

Modules based on Lua: Version 6.6  2016-10-13 13:28 -05:00
    by Robert McLay mclay@tacc.utexas.edu

# note: default isn't marked as such, but that's not a huge problem for us
$ ml av cluster/
--------------- /etc/modulefiles/vsc ---------------
   cluster/delcatty (S)    cluster/golett (S)    cluster/phanpy (S)    cluster/raichu (S)    cluster/swalot (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge

If you need software that is not listed, request it at hpc@ugent.be

$ ml
No modules loaded
$ echo $VSC_DEFAULT_CLUSTER_MODULE
delcatty
$ ml cluster
$ ml

Currently Loaded Modules:
  1) cluster/delcatty (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge
```

With Lmod 7, the alphabetically last `cluster/swalot` is loaded instead:

```
$ ml --version

Modules based on Lua: Version 7.5.4  2017-06-22 06:08 +02:00
    by Robert McLay mclay@tacc.utexas.edu

# note: default *is* marked now, but not as we intended it to
$ ml av cluster

--------------- /etc/modulefiles/vsc ---------------
   cluster/delcatty (S)    cluster/golett (S)    cluster/phanpy (S)    cluster/raichu (S)    cluster/swalot (S,D)

  Where:
   S:  Module is Sticky, requires --force to unload or purge
   D:  Default Module

If you need software that is not listed, request it at hpc@ugent.be

$ ml
No modules loaded

$ echo $VSC_DEFAULT_CLUSTER_MODULE
phanpy
$ ml cluster
$ ml

Currently Loaded Modules:
  1) cluster/swalot (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge
```

Two questions:

* Is it expected that this doesn't work anymore with Lmod 7?
* If so, what alternatives do we have to pick a default based on an environment variable? Is that supported?

**Comment by rtmclay** [comment]
What happens if you do:

    $ module --ignore_cache load cluster

?

**Comment by rtmclay** [comment]
I am able to reproduce the problem so I don't need to know to the results of "ml --ignore_cache cluster".

The reason why Lmod 7 doesn't load the default set by the environment variable is due to the rule that Lmod enforces about defaults and hidden modules.  The new rule is that a default can't be the default.  Lmod 6 didn't enforce that rule.   That is why there is a difference.

If I change the name of .defaultcluster.lua to defaultcluster.lua (and change the file "default" to point to the new name).  Then it works just like it did in Lmod 6.

Maybe the right solution is to not enforce the rule that hidden modules can defaults.  Or maybe the right solution is to make this yet another configuration option.  I would rather not do that.  I'm beginning to think that Lmod should not enforce this rule.

Comments?

**Comment by boegel** [comment]
@rtmclay You said "The new rule is that a default can't be the default.", but I think you meant "The new rule is that a hidden module can't be the default.", did I get that right?

In this particular case, I think we have a good reason to make `defaultcluster.lua` hidden, since having a `cluster/defaultcluster` module available for people to load would be strange...

I can't think of another way to make the default be determined at runtime by an environment variable, but maybe I'm overlooking something?

**Comment by rtmclay** [comment]
Yes, of course I mean:"The new rule is that a hidden module can't be the default."

I understand why you want to do what you have been doing.  The real question is: Should Lmod enforce this rule ever?

**Comment by boegel** [comment]
I feel that if someone wants to set a hidden module as the default module explicitely, Lmod should let them and honour it. As I think the above shows, there can be valid reasons for it.

Also, it's surprising to me that Lmod blatently and silently ignores something I've specified explicitely, just because it feels (I'm sure we're close to it becoming sentient) it's not right to do so.

What you definitely do *not* want is that Lmod picks a hidden module as the default if no module was marked to be default, even if it is the most recent available version...

**Comment by rtmclay** [comment]
You are correct.  Marked defaults will be honored even if they point to a hidden module.  What remains true is that hidden module will not be the default if highest version (and not a marked default).

I have updated the github repo to be 7.5.5.  If you get a chance, please test Lmod 7.5.5  and let me know if it fixes this issue for you.  Thanks for letting me know about this issue.

**Comment by boegel** [comment]
@rtmclay I've just checked with Lmod 7.5.5, fix confirmed, thanks!
