### ISSUE TITLE
module restore warning message for users with no default modules

### ISSUE THREAD

**Issue by adamjstewart** [TACC/Lmod#293]
Every time I log in to our cluster, I see the following warning message:
```
Lmod Warning:  You have no modules loaded because the collection "default" is
empty!
```
The problem is that `z00_StdEnv.sh` runs `module restore` and I don't have any default modules. This is on purpose, as I don't want anything to pollute my `LD_LIBRARY_PATH`. I ran:
```
$ module purge
$ module save
```
to get what I want. Is there any way to prevent this warning message?

**Comment by rtmclay** [comment]
You can change the z00_StdEnv.sh file from:

     module --initial_load --no_redirect restore

to:

     module --initial_load ---quiet -no_redirect restore

This will turn off the output of warnings when doing the restore.

**Comment by adamjstewart** [comment]
@rtmclay I'm worried about blanket ignoring all warning messages with `--quiet`. I assume there are other warning messages that can occur that are much more important, like if a saved module no longer exists. Let me try out 7.5.8.

**Comment by rtmclay** [comment]
O.K. to close?
