### ISSUE TITLE
Spider reporting unloadable modules to get to a given package

### ISSUE THREAD

**Issue by damianam** [TACC/Lmod#294]
This issue is similar to https://github.com/TACC/Lmod/issues/234, but not exactly the same.

We have a default `MODULEPATH` with our latest software, and a set of modules that allow the users to change that default `MODULEPATH` to older versions of the stack. We call those "Stages". These modules are not in the default `MODULEPATH` to limit spider to our latest stack.

The script that updates the cache obviously has access to the default and the extended `MODULEPATH`. The problem is that when spidering for a software package that is perfectly reachable when loading the appropriate compiler, lmod reports also the "Stages" modules. That happens just when using the cache:

```
~]$ ./with_cache.sh

-------------------------------------------------------------
  software1: software1/1.0
-------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.

      Stages/2017a  compiler1/1.0

Modules available:

--------------------- Compilers ---------------------
   compiler1/1.0

...

~]$ ./without_cache.sh

-------------------------------------------------------------
  software1: software1/1.0
-------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.

      compiler1/1.0

Modules available:

--------------------- Compilers ---------------------
   compiler1/1.0
...
```

The first case is wrong, since `Stages/2017a` is not loadable. Attached is a minimal example with a couple of scripts to easily reproduce the issue. Note that the scripts should be run from the directory where they reside, as they rely on `$PWD` and the modules rely on `lfs.currentdir()`

[test_cache_lmod.tar.gz](https://github.com/TACC/Lmod/files/1112631/test_cache_lmod.tar.gz)

cc: @ocaisa

**Comment by rtmclay** [comment]
Thanks very much for the minimal example.  I don't think I would have been able to find the problem without it.  This one was tricky.  It took me sometime to track this bug down.  I have included a modified version of your example in Lmod's test suite.  Please test version 7.5.16 to see if it works for you.  Thanks again for the bug report.

**Comment by damianam** [comment]
Thanks for looking into this @rtmclay! Unfortunately, the issue isn't completely solved. With 7.5.16, I don't get any module to be loaded when using a cache, which is wrong, since to access software1 I need to load first compiler1. Without cache still works as expected:

```
~]$ ./with_cache.sh

-----------------------------------------------------------------------------------
  software1: software1/1.0
-----------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.





Modules available:

-------------------------------- Compilers --------------------------------
   compiler1/1.0

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of
the "keys".


~]$ ./without_cache.sh

-----------------------------------------------------------------------------------
  software1: software1/1.0
-----------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.

      compiler1/1.0




Modules available:

-------------------------------- Compilers --------------------------------
   compiler1/1.0

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of
the "keys".


```

**Comment by rtmclay** [comment]
I did mess up here.  Thanks for letting me know.   I have updated the code and now my test results now work just like your example:

```
step 9
lua ProjectDIR/src/lmod.in.lua bash --regression_testing spider software1
===========================
  software1: software1/1.0
    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.
      compiler1/1.0
```

Please test 7.5.17 to see if it works for you.

**Comment by damianam** [comment]
Thanks! I can confirm it works now. There is a minor thing though: It still lists Stages/2017a as a requirement, if that module is in the MODULEPATH:

```
~]$ ./with_cache.sh

-----------------------------------------------------
  software1: software1/1.0
-----------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.

      compiler1/1.0

~]$ module use $PWD/module_tree/OtherStages/
~]$ ./with_cache.sh

-----------------------------------------------------
  software1: software1/1.0
-----------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "software1/1.0" module is available to load.

      Stages/2017a  compiler1/1.0

```

It is a minor thing though.

**Comment by rtmclay** [comment]
You are going to have to live with that.  As far as the hierarchy is concerned "Stages/2017a" is the bottom of the hierarchy and compiler1/1.0 is the next level.  The fact that you use the path to compiler1/1.0 as the base of MODULEPATH is something that Lmod can not deal with.

**Comment by damianam** [comment]
That's good enough for us. Thanks!
