### ISSUE TITLE
Hidden module files

### ISSUE THREAD

**Issue by adamjstewart** [TACC/Lmod#296]
I couldn't find anything in the documentation, but please point me to it if I missed it. I want to create "hidden" module files that aren't visible in `module avail` but can be loaded like normal. How do I do this?

**Comment by adamjstewart** [comment]
So far I've figured out that if you name the module file to start with a period, it will be marked as "hidden", and `module --show_hidden avail` will display it as such. But `module load <name>` doesn't work, nor does `module load .<name>`. I have to explicitly request the exact version with `module load .<name>/<version>`. It would be nice if I could still set a default version and load like normal without adding the period. I'm using this for administrator tools like Spack that I don't want to be user-facing.

**Comment by rtmclay** [comment]
This is more a question for the Lmod mailing list than here at Github.  More people read this kind of information there than here.

I'll answer this here but please next time, ask this kind of question there.

You are correct, a module named foo/.1.2 will have to be loaded with "ml foo/.1.2".

You can mark a module as hidden with the MODULERC file. ml --config will tell you where this file is on your site.

In that file you could have 

```
#%Module
hide-version spack/1.2
```

then it is hidden.  What you can do is mark a hidden module as the default.  If all the modulefiles are hidden (by dot version or marked hidden)  then they won't show up in "ml av" but you can load "ml spack" and get the default.  For example:
```
% tree -a spack
spack
├── .1.2.lua
├── .1.3.lua
└── default -> .1.2.lua
```

and ``ml spack`` works and "ml av" doesn't show spack. However "ml --ignore_cache av" does. You should thank @boegel for this to work as his site uses this trick magically pick his cluster module.

**Comment by boegel** [comment]
It seems this is indeed not well covered in the documentation yet, but as far as I know, you have two options:

* use one or more 'hide-version' lines in a .modulerc file see, this is sort of covered in https://github.com/TACC/Lmod/blob/master/Transition_to_Lmod7.txt

* implement the isVisible hook, see the example implementation contributed by @wpoely86 at https://github.com/TACC/Lmod/tree/master/contrib/more_hooks

**Comment by adamjstewart** [comment]
Thanks, setting the hidden modules in `MODULERC` sounds like it will give me what I want. I'll ask on the mailing list next time.
