### ISSUE TITLE
spider -o jsonSoftwarePage and `default` file

### ISSUE THREAD

**Issue by HenrikBengtsson** [TACC/Lmod#298]
# Issue

Contrary to `module load / avail`, `spider -o jsonSoftwarePage <path>` does not acknowledge a `default` soft link.

If this is the intended behavior*, is there another way to infer the default version?  (I'm attempting to highlight the default version in a dynamically generated HTML page - Issues #284)

(\*) Was that what you meant in Issue #297?

# Reproducible example

```sh
mkdir -p /tmp/lmod-foo
cd /tmp/lmod-foo

mkdir -p foo
echo 'help([[foo v1.0]])' > foo/1.0.lua
echo 'help([[foo v1.1]])' > foo/1.1.lua
ln -s foo/1.0.lua foo/default
```
which creates
```sh
$ ls -l foo/
total 8
-rw-rw-r-- 1 hb hb 19 Jul  3 20:15 1.0.lua
-rw-rw-r-- 1 hb hb 19 Jul  3 20:15 1.1.lua
lrwxrwxrwx 1 hb hb 11 Jul  3 20:15 default -> foo/1.0.lua
```

With these modules, I get
```sh
$ $LMOD_DIR/spider -o jsonSoftwarePage . | python -m json.tool
[
    {
        "defaultVersionName": "1.1",
        "package": "foo",
        "versions": [
            {
                "canonicalVersionString": "000000001.*zfinal",
                "full": "foo/1.0",
                "help": "foo v1.0",
                "path": "foo/1.0.lua",
                "versionName": "1.0"
            },
            {
                "canonicalVersionString": "000000001.000000001.*zfinal",
                "full": "foo/1.1",
                "help": "foo v1.1",
                "path": "foo/1.1.lua",
                "versionName": "1.1"
            }
        ]
    }
]
```

# Session details
```sh
module --version

Modules based on Lua: Version 7.5.9  2017-07-01 21:09 -05:00
    by Robert McLay mclay@tacc.utexas.edu
```

**Comment by rtmclay** [comment]
Yes, this is exactly what I meant in #297.   The command module spider doesn't have MODULEPATH associated with it.  So there is no way that it can have defaults.   How Lmod picks defaults is somewhat complex and is described at http://lmod.readthedocs.io/en/latest/060_locating.html.  It depends on the user's ~/.modulerc, the system MODULERC and the .modulerc and/or the .version or the default symlink files that are located with the modulefiles.

There is no way that "module spider" output can know what the default would be.  The jsonSoftwarePage is pre-calculated and couldn't change when a user's ~/.modulerc file changes the default.

The field "defaultVersionName" has a bad name.  I chose it a long time ago and don't feel that I can change it.  What "defaultVersionName" reports is which modulefile Lmod has chosen to report the 
"Description" from.  This issue has been discussed recently on the Lmod Mailing list that has the subject title of  "Spider output - whatis vs help".

The point is that Lmod looks for a whatis() call that looks like whatis ("Description: blah blah ...") and takes the "blah blah ..." string and used that string to be the description.  For example:
```
% cat foo/1.1.lua 
whatis("Description: 1.1 blah blah ...")
% cat foo/1.0.lua
whatis("Description: 1.0 blah blah ...")
% spider -o jsonSoftwarePage . | python -mjson.tool
[
    {
        "defaultVersionName": "1.1",
        "description": "1.1 blah blah ...",
        "package": "foo",
        "versions": [
            {
                "canonicalVersionString": "000000001.*zfinal",
                "full": "foo/1.0",
                "path": "foo/1.0.lua",
                "versionName": "1.0"
            },
            {
                "canonicalVersionString": "000000001.000000001.*zfinal",
                "full": "foo/1.1",
                "path": "foo/1.1.lua",
                "versionName": "1.1"
            }
        ]
    }
]

```

In this particular case the whatis Description fields are different between the two modulefiles, but normally they are the same.   What I'd like to do remove the "defaultVersionString" field but I don't feel like breaking sites use of it.

I'll add documentation to describe this issue later.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by HenrikBengtsson** [comment]
> There is no way that "module spider" output can know what the default would be. The jsonSoftwarePage is pre-calculated and couldn't change when a user's ~/.modulerc file changes the default.
> ...
> The field "defaultVersionName" has a bad name. I chose it a long time ago and don't feel that I can change it. What "defaultVersionName" reports is which modulefile Lmod has chosen to report the
"Description" from. This issue has been discussed recently on the Lmod Mailing list that has the subject title of ["Spider output - whatis vs help"](https://sourceforge.net/p/lmod/mailman/lmod-users/thread/83272520-4E34-495E-9DFC-C0B6ED98B132%40fz-juelich.de/#msg35916762).
> ...
> In this particular case the whatis Description fields are different between the two modulefiles, but normally they are the same. What I'd like to do remove the "defaultVersionString" field but I don't feel like breaking sites use of it.

Thanks; this clarifies it very well.

The remaining / follow-up question is: is there a way to programatically infer the default version used?  My only idea now is to parse the output of `module avail` or `module --default avail`.

**Comment by rtmclay** [comment]
The best way to do that would be
```
    $ module --terse --default avail
```

**However** I don't think you want to do that.  At least I don't think you want to do that if you are using the software hierarchy.  Suppose you are using the hierarchy and you are using gcc and mvapich2 the the default of petsc might be one version and changing to intel and impi, the default for petsc might be another.  Also if you are using the hierarchy, ``module --terse --default avail`` won't show modules that are in a different part of the hierarchy

Also users can set their own default by setting things in ~/.modulerc.  Also the default might be different depending on the module order.   A software webpage, won't know about a user's ~/.modulerc, won't know the user's $MODULEPATH.

**However** (yet again) I can see where a site might like to be able to report to users which modulefiles are  marked as defaults.  So I have changed the sorting on the version to use what I call wV and not pV.  The pV is the internal name of the canonical version string.  There is a weight version (of wV) which knows about marked defaults.  So the output of Lmod 7.5.10 will be where foo/1.0 is a marked default.
```
% spider -o jsonSoftwarePage . | python -mjson.tool
[
    {
        "defaultVersionName": "1.0",
        "description": "1.0 blah blah ...",
        "package": "foo",
        "versions": [
            {
                "canonicalVersionString": "000000001.000000001.*zfinal",
                "full": "foo/1.1",
                "markedDefault": false,
                "path": "foo/1.1.lua",
                "versionName": "1.1",
                "wV": "000000001.000000001.*zfinal"
            },
            {
                "canonicalVersionString": "000000001.*zfinal",
                "full": "foo/1.0",
                "markedDefault": true,
                "path": "foo/1.0.lua",
                "versionName": "1.0",
                "wV": "^00000001.*zfinal"
            }
        ]
    }
]
```

Your sites software page can explain that foo/1.0 is a marked default by the site but could be overridden by the site's MODULERC file or a user's ~/.modulerc.   Also you can see that I've added a field called "markedDefault" which will be true when it is marked by a .version, default or .modulerc in the same directory as the version files.

I think you'd be better off telling your users to use "module avail" or "module --default avail" to determine which modulefiles will be defaults then trying to encode this in your software page and explain all the reasons why a marked default isn't the default Lmod picked for them.

**Comment by HenrikBengtsson** [comment]
Beautiful!  Confirming that it works.

Thanks for clarifying the bigger picture - it's really helpful especially since I'm still learning about how Lmod works and is intended to be used.
