### ISSUE TITLE
path operators for different separators

### ISSUE THREAD

**Issue by davidedelvento** [TACC/Lmod#299]
I've run into some software (Ferret, FWIW) that use environmental variable with different separators (e.g. space), and creating a module file for them in lmod seems to be unnecessarily cumbersome. It would be nice if I could do

```
prepend_path("MY_VAR", "some_stuff", " ")
```

instead of having to do in the (annoying) shell like mode. If not specified, the last argument would default to the usual ":"

**Comment by rtmclay** [comment]
Lmod already supports this.  I'm moving this discussion to the mailing list.

**Comment by davidedelvento** [comment]
Thanks much! I've seen the message on the mailing list and the updated documentation. Since it wasn't mentioned in the docs, I did not think of looking at the code or try it anyway...
