### ISSUE TITLE
"attempt to concatenate a nil value" when putting a prereq on non-existent module

### ISSUE THREAD

**Issue by morrisonlevi** [TACC/Lmod#301]
Let's say I have a `prereq` like so:

    prereq(atleast("foobar", "1.4"))

I get this error when `foobar` doesn't have any modules at all:

> /apps/lmod/lmod/libexec/MN_Between.lua:61: attempt to concatenate a nil value

Happens on both 7.4 and 7.5. If there are any modules with that name then it will give a proper error message, regardless of whether the version of the `foobar` module that is present would satisfy the dependency:

    Lmod has detected the following error:  Cannot load module "test" without these module(s) loaded:
       atleast("foobar","1.4")

**Comment by rtmclay** [comment]
Thanks for the bug report!  I was able to reproduce your bug and fix it. I have released 7.5.13 that fixes this problem for me.  Please test 7.5.13 to see if it fixes the problem for you. Thanks!

**Comment by morrisonlevi** [comment]
I confirmed that it works for us. Thank you for the quick turn-around!
