### ISSUE TITLE
CC = cc is gone in make' predefined setup

### ISSUE THREAD

**Issue by handrake0724** [TACC/Lmod#305]
my gcc module is as follows:

pushenv("CC", "gcc")
pushenv("CXX", "g++")
pushenv("FC", "gfortran")

before loading the gcc module, make -p says
  # default
  CC = cc

after loading the gcc module, CC = cc is gone in the make -p result.
Some program uses cc instead of CC, i.e., OpenFOAM.
Since CC = cc is gone, CC and cc are now pointing to different compilers and make problem.

Can this behavior be resolved?
of course, adding pushenv("cc", "gcc") can solve the problem.

**Comment by rtmclay** [comment]
This is not a problem that Lmod can help with.  In addition, it is not clear to me that adding 

    pushenv("cc","gcc")

to your gcc module would help.  It would depend on whether the build system for OpenFOAM is using $(cc) or cc.  If it uses cc and not ${cc} then setting the environment variable $cc won't affect command lines like:

      cc -c foo.c
