### ISSUE TITLE
pushenv() using variables

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#308]
Hi Robert!

I have a Lua module file which sets an environment variable using `pushenv()` to a value build from Lua variables. Or, in short:

```lua
my_var = "foo"
pushenv("MY_VAR", my_var)        
```

I can load the module fine, without any issue, but `spider` kind of complains about it with the following warning:
```
$ $LMOD_DIR/spider $MODULEPATH_ROOT

Lmod Warning: Syntax error in file: <path_to_module>/my_module.lua
 with command: pushenv, one or more arguments are not strings.

<path_to_module>/my_module.lua
```

It's not that I really mind about it, and it's absolutely true that one or more arguments are not strings, but I'm curious about the rationale: is it a "bad thing"(TM) to use `pushenv()` with variables as arguments?

**Comment by rtmclay** [comment]
There is something else going on.  There is nothing wrong with what you have.  In this case:

     local my_var = "foo"
     pushenv("MY_VAR",my_var)

You are sending two strings to pushenv().   Below is an example of where you are NOT sending two strings:

     local my_var = 1
     pushenv("MY_VAR",my_var)

It is perfectly safe to use variable to send to pushenv().  I don't know what you are really doing but if you are depending on one module to set a variable that is used by another, you could run into trouble.

**Comment by kcgthb** [comment]
Aah, that's helpful, thanks!
`my_var` was actually defined as the output of a function, which can, under certain circumstances, return `nil`. So `pushenv()` second argument was in fact undefined, hence the warning.

Thanks for the tips, it's all good now.
