### ISSUE TITLE
Is there an option to make settarg case-insensitive? or, make it tunable via a variable

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#309]
I have managed to get it fully working playing with release 7.6.1,
however, it's unrealistic to have to recompile past buildsets for just gcc & openmpi.

I think it would be great to have an option for case-insesitivity, because that would make it play with default EasyBuild namespaces out of the box! any better ways to do this?!

**Comment by rtmclay** [comment]
Anyone who is using settarg is going have to tailor the settarg_rc.lua file to match the names of modules at their site.  I don't see a way around it.  Please try copying the system settarg_rc.lua file to your home account and rename to ~/.settarg.lua and modify that until you are happy.

**Comment by fgeorgatos** [comment]
OK, @rtmclay, I've opened PR #310 since supporting EB does not harm existing configuration
but got stuck in that short symbols won't work for me as expected (this is a PR on my PR!):
https://github.com/fgeorgatos/Lmod/pull/1/files
Could you propose how to fix it?!

**Comment by fgeorgatos** [comment]
OK, could we point to settarg_rc.lua via a variable? (or via the config file?)

**Comment by rtmclay** [comment]
Lmod 7.6.2 now supports an env. var. called SETTARG_RC which will override the standard settarg_rc.lua file.  So SETTARG_RC should point to a file that provides the tables that settarg needs.

**Comment by fgeorgatos** [comment]
ok, after merging #310 & #311 , I'd consider this case closed until proven wrong.

**Comment by fgeorgatos** [comment]
btw. i think `LMOD_SETTARG_RC` would be more fitting naming (keep the style) but whatever

**Comment by rtmclay** [comment]
You are right.  I am changing it to LMOD_SETTARG_RC

R.
