### ISSUE TITLE
How to support dynamic default module version

### ISSUE THREAD

**Issue by chuckatkins** [TACC/Lmod#312]
I'm trying to setup modules for two different packages each with multiple versions, such that the default version of one is dependent on the other.  The problem is a general one, but I'm specificaly trying to implement it for OpenHPC and managing the version dependencies between the Intel compiler and IntelMPI.  The idea being that while any impi version can be used with any icc version, the default impi version should be based on the currently loaded icc version.  I've tried to implement this by adding a variable in the compiler module:

```tcl
# intel/17.0.4.196 compiler module
setenv	LMOD_FAMILY_MPI_IMPI_DEFAULT_VERSION 2017.3.196
```
or
```tcl
# intel/16.0.4.258 compiler module
setenv	LMOD_FAMILY_MPI_IMPI_DEFAULT_VERSION 5.1.3.258
```
etc., and then reference that variable in the impi/.version file:
```tcl
#%Module1.0#####################################################################
if { [info exists ::env(LMOD_FAMILY_MPI_IMPI_DEFAULT_VERSION)] } {
    set	ModulesVersion	$::env(LMOD_FAMILY_MPI_IMPI_DEFAULT_VERSION)
}
```
The problem seems to be that the spider cache holds on the the first default version it finds so if I swap the compiler module for a different version, the impi default version doesn't change until I update the cache.  Is there either a) some way to invalidate the cache only for a certain module so that the impi versions are re-cached whenever the intel compiler module is loaded, unloaded, or swapped, or b) some other way entirely to achieve this dynamic default version behavior?

**Comment by rtmclay** [comment]
No this is not supported.  The spider cache does not work with dynamic quantities of any kind.  The way this is typically handled is through the software hierarchy.  This way intel/16 sees impi version 5.1.3.258 has its highest version and therefore its default.  Similarly intel/17 sees the latest impi as its default.

The only way to get this to work is to not have any cache at all.  No system cache and prevent user's caches being built.

**Comment by chuckatkins** [comment]
What about excluding a particular directory from the cache but keeping it in the module search path?  That way I could just exclude the directory for a given package from the cache while letting all the other static modules remain cached.

**Comment by rtmclay** [comment]
Yes, but the point is for the compiler and mpi stack to match.  If you exclude those you lose the compiler dependent modules and the compiler - mpi dependent modules as well.  This will limit the usefulness of the cache.

**Comment by chuckatkins** [comment]
I don't necessarily want them to match, but just have the defaults match.  Using other versions should still be valid.  So, for example, the desired behavior would be:
```bash
$ module load intel/17.0.4.196 impi
$ module list
Currently Loaded Modules:
  1) intel/17.0.4.196   4) impi/2017.3.196
```
or
```bash
$ module load intel/16.0.4.258 impi
$ module list
Currently Loaded Modules:
  1) intel/16.0.4.258   4) impi/5.1.3.258
```
But using other version combinations explicitly should still be valid, i.e. this should still be valid:
```bash
$ module load intel/16.0.4.258 impi/2018.0.082
$ module list
Currently Loaded Modules:
  1) intel/16.0.4.258   4) impi/2018.0.082
```

I think I just figured out a way to do this too through the directory structure with symlinks.  Create the modules via:
```
# Compiler modules
modules/intel/1 # add moduledeps/versioned/intel/1 to the MODULEPATH
modules/intel/2 # add moduledeps/versioned/intel/2 to the MODULEPATH
modules/intel/3 # add moduledeps/versioned/intel/3 to the MODULEPATH

# Actual impi modules, but hidden in a . folder
moduledeps/intel/.impi/10
moduledeps/intel/.impi/20
moduledeps/intel/.impi/30

# Compiler-version specific modules, really just symlinks to the actual modules
# plus a .version file to set the impi default specific to the compiler version

moduledeps/versioned/intel/1/impi/.version #set default to "10"
moduledeps/versioned/intel/1/impi/10 -> moduledeps/intel/.impi/10
moduledeps/versioned/intel/1/impi/20 -> moduledeps/intel/.impi/20
moduledeps/versioned/intel/1/impi/30 -> moduledeps/intel/.impi/30

moduledeps/versioned/intel/2/impi/.version #set default to "20"
moduledeps/versioned/intel/2/impi/10 -> moduledeps/intel/.impi/10
moduledeps/versioned/intel/2/impi/20 -> moduledeps/intel/.impi/20
moduledeps/versioned/intel/2/impi/30 -> moduledeps/intel/.impi/30

moduledeps/versioned/intel/3/impi/.version #set default to "30"
moduledeps/versioned/intel/3/impi/10 -> moduledeps/intel/.impi/10
moduledeps/versioned/intel/3/impi/20 -> moduledeps/intel/.impi/20
moduledeps/versioned/intel/3/impi/30 -> moduledeps/intel/.impi/30
```
