### ISSUE TITLE
Download of some archived releases does not work

### ISSUE THREAD

**Issue by maikenp** [TACC/Lmod#315]
E.g. 

7.6.10 and 7.0

clicking on the tar.gz for download at https://github.com/TACC/Lmod/releases gives "Internal Server Error". 

![screen shot 2017-08-23 at 15 15 17](https://user-images.githubusercontent.com/22190352/29617674-e7ade9ae-8815-11e7-967e-f7a3fc3242ac.png)

**Comment by boegel** [comment]
This is most likely a (temporary) problem with GitHub itself, it has nothing to do with Lmod...

You should report this via https://github.com/contact.

**Comment by maikenp** [comment]
Very good, thanks for that.
