### ISSUE TITLE
Module names with a leading underscore

### ISSUE THREAD

**Issue by vlopezh** [TACC/Lmod#316]
Does Lmod not support leading underscores in the module name or is it not intended?

I've found at least two issues about this:
- The spider cache does not store information about these modules, `module avail` will not show my modules unless I either run with `--ignore_cache` or explicitly remove the cache before every query.
- `module load _mymodule` will load _mymodule and successfully modify the appropriate environment variables but neither `module list` nor `module unload` will recognise it, making impossible to revert the modified environment variable back.

**Comment by rtmclay** [comment]
Previously, Lmod did not support module names with a leading underscore.  The new version of Lmod (7.6.12) now supports module names with a _single_ leading underscore.   Lmod does **NOT** support module names with two or more leading underscores.

The reason for this is that Lmod uses the table data structure to pass information between module command invocations.  In particular, Lmod stores the _ModuleTable_ data structure to know what modules are loaded or inactive.  There are key-value pairs that are needed internally that are not passed between invocations.   There are also special variables (like self.__index) which Lua used to implement the Class functions.  These key-value pairs used to have a single leading underscore, they now have two leading underscores.

Lmod serializes the _ModuleTable_ structure and removes any keys that now start with a double underscore. 

To test this, you'll have to install Lmod 7.6.12 and rebuild the cache files with 7.6.12 to make sure that the cache files will have support for any modulefile that starts with a single underscore.

Thanks very much for the bug report!

**Comment by vlopezh** [comment]
Working perfectly on 7.6.12, thank you.
