### ISSUE TITLE
[RFE] display module properties in the output of "spider -o jsonSoftwarePage"

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#317]
Hi Robert,

I'd like to ask if it would be possible to enhance the output of `spider -o jsonSoftwarePage` to include details about [module properties](https://lmod.readthedocs.io/en/latest/145_properties.html)? I see the properties are already listed when using different spider output formats, like `spider-json`, but also getting them in the aggregated output of `jsonSoftwarePage` would prove very useful.

Thanks!

**Comment by rtmclay** [comment]
Please try Lmod 7.6.14.  I have modified the generation of the software page to include properties.

**Comment by kcgthb** [comment]
This looks awesome, thanks a ton for implementing it so rapidly!

**Comment by rtmclay** [comment]
OK to close?

**Comment by kcgthb** [comment]
Yup, thanks again!
