### ISSUE TITLE
TARG_TITLE_BAR_PAREN spurious message under tcsh

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#318]
i'm no *csh fan by any means, but thought of reporting nevertheless; this is not 6.9 or 7.7-specific,
although I did the version upgrade on this system (access available), just to confirm (see near end):

```
[root@demo2 profile.d]# grep -R TARG_TITLE_BAR_PAREN /etc/
/etc/profile.d/z00_lmod.csh:  setenv TARG_TITLE_BAR_PAREN " "
/etc/sysconfig/modules/lmod/z00-lmod.csh:      setenv TARG_TITLE_BAR_PAREN " "
grep: /etc/grub2-efi.cfg: No such file or directory
/etc/site/modules/settarg/7.7.lua:                ${SET_TITLE_BAR:-:} "${TARG_TITLE_BAR_PAREN}${USER}@${SHOST}:${PWD/#$HOME/~}";
/etc/site/modules/settarg/7.7.lua:      set_alias("precmd",'echo -n "\\033]2;${TARG_TITLE_BAR_PAREN}${USER}@${HOST} : $cwd\\007"')

[root@demo2 profile.d]# su - fgeorgatos
Last login: Thu Sep 21 21:34:03 CEST 2017 on pts/0
TARG_TITLE_BAR_PAREN: Undefined variable.
Faulty alias 'precmd' removed.
[fgeorgatos@demo2 ~]$ ml --version

Modules based on Lua: Version 7.7  2017-09-19 11:05 -05:00
    by Robert McLay mclay@tacc.utexas.edu
[fgeorgatos@demo2 ~]$
```

Truth be told, this could easily be a packaging issue, not an Lmod issue; tbd/tbc (if so => ./bic repo)

**Comment by rtmclay** [comment]
Your /etc/profile.d/z00_lmod.csh is out of date.  All the TARG_* variable are set in init/csh
However, I have trouble seeing out TARG_TITLE_BAR_PAREN is not defined.  If I have read your situation correctly, it is defined in /etc/profile.d/z00-lmod.csh and init/csh.  So I don't see what is wrong.

**Comment by rtmclay** [comment]
I have created version 7.7.1 which fixes the problem seen with tcsh and TARG_TITLE_BAR_PAREN.  

There were problems with the previous design of settarg.  It wouldn't work with sub-shells.  This new version will.  There is now a new variable: when  LMOD_SETTARG_TITLE_BAR=yes then and only then will Lmod/settarg place information in the title bar.

**Comment by fgeorgatos** [comment]
confirming that that warning issue went away as of `7.7.1`:

```
[root@demo2 ~]# su - fgeorgatos
Last login: Fri Sep 22 03:05:09 CEST 2017 on pts/0
[fgeorgatos@demo2 ~]$ echo $SHELL
/bin/tcsh
[fgeorgatos@demo2 ~]$ ml --version

Modules based on Lua: Version 7.7.1  2017-09-24 02:11 -05:00
    by Robert McLay mclay@tacc.utexas.edu

[fgeorgatos@demo2 ~]$ date
Sun Sep 24 10:20:35 CEST 2017
```

closing issue; 
I take a note that we need reengineering of our `.spec` in relation to `z00-lmod.csh`. Thanks!
