### ISSUE TITLE
Is the modulefile not read at unload? Lua execute with modeA not working.

### ISSUE THREAD

**Issue by bmcgough** [TACC/Lmod#319]
I am trying to add shell tab completion on a module load, and remove it on a module unload as it will fail with ugly path messages if I do not.

So I am using the 'execute' command in my modulefile like this:
```
execute {cmd="complete -C <cmd> <name>", modeA={"load"}}
execute {cmd="complete -r <name>", modeA={"unload"}}
```

This works for load, but not unload.

I tested by adding this to my modulefile:

```
local m = mode()
io.stderr:write("mode: ",m,"\n")
```

If I run `$LMOD_CMD bash load <module> >/dev/null` I see `mode: load`.
If I run `$LMOD_CMD bash unload <module> >/dev/null` I see nothing.

What am I doing wrong? Is this a bug?

I tried this is Lmod 6.4.5, which is out production Lmod, and in 7.7 and got the same results.

Thanks!

**Comment by rtmclay** [comment]
A module has to be loaded before you can unload it.  so try:

```
% module load A
mode: load
% $LMOD_CMD bash unload A > /dev/null
mode: unload
% $LMOD_CMD bash unload A > /dev/null
mode: unload
```
Once a module is loaded you can test `$LMOD_CMD bash unload A` as many time as you like

**Comment by bmcgough** [comment]
Oh, of course.

I think it is working correctly now.

Now I just have to find a good reproducible way to get this into the easyconfig for our module... .

Thanks!
