### ISSUE TITLE
Proposal for minor variables alias

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#321]
ref. https://github.com/Bright-Computing/bic/issues/51#issuecomment-331696893

while looking at this, a couple ideas came to mind:
* `TARGPATHLOC                 -> SETTARG_PATH_LOCATION`
* `FULL_SETTARG_SUPPORT -> SETTARG_FULL_SUPPORT`

that would group logically variables and allow configuration files to look very neat, as an example:

```
LMOD:
  SETTARG:
    FULL_SUPPORT                 yes  ## yeah, ok, that's really handled at build time
    PATH_LOCATION:               last
    TITLE_BAR:                   yes
```

your view?!

(more generally, it would be nice to cluster together and have similar aliases for other options)

**Comment by rtmclay** [comment]
I am O.K with changing LMOD_FULL_SETTARG_SUPPORT to LMOD_SETTARG_FULL_SUPPORT.
I have changed LMOD_TARGPATHLOC to LMOD_SETTARG_TARG_PATH_LOCATION.

See Lmod 7.7.7 for these changes.  Note that LMOD_SETTARG_FULL_SUPPORT just has to be set before loading the settarg module.   You can configure Lmod to full support if you want but you don't have to.

**Comment by fgeorgatos** [comment]
I have finally a fully working 7.7.7 RPM with these features included in.
There is still an issue on my end with the TITLE_BAR, but that's a separate bug so I'm closing this!
