### ISSUE TITLE
Relative paths translated into full paths

### ISSUE THREAD

**Issue by DirkdeDraak** [TACC/Lmod#324]
Our users came across an issue where they modify the PATH, they add a path with a relative section in it, like `/my/test/../path`.

```
$ export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
$ export PATH="$PATH:/my/test/../path"
$ module load git
$ echo $PATH
/tools/git/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/my/path
```

Notice that the PATH ends with `/my/path` and not `/my/test/../path`.
Effectively that is correct, though many of the developers scripts depend/rely on the value they had put in the PATH.
Can it be made in such a way it will not "resolve" relative paths, but just leaves them be.

**Comment by rtmclay** [comment]
Lmod 7.7.10 will keep ".." in the path.  Lmod will still convert /a/./b to /a/b and it will convert /a//b to /a/b etc.

Please test 7.7.10 to see if it works for you.

**Comment by DirkdeDraak** [comment]
Robert, the change seems to do what I had hoped for. I'll pass it by my users for further verification.
Thanks for the quick resolution!

**Comment by DirkdeDraak** [comment]
Users confirmed this fix is working for them. Thank you.
