### ISSUE TITLE
Feature request: support multiple targets in a rule of the LMOD_ADMIN_FILE:

### ISSUE THREAD

**Issue by fgeorgatos** [TACC/Lmod#326]
fi. either comma delimited, or regex or whatever, so that there is not much text repetition going on:

```
cuda75/toolkit/7.5.18,CUDA/7.5.18:
        Please, do NOT use *these* versions of CUDA, there is also...
```

**Comment by rtmclay** [comment]
I don't see how to support multiple targets safely.   How can you know if someone has spaces, comma's, colon's in their module paths.   You'd have to change the syntax of the LMOD_ADMIN_FILE to safely support it to something that one can safely parse.  Say something like this:

     {"cuda75/toolkit/7.5.18", "CUDA/7.5.18"} : 
          Please, do NOT use ...

That would break too many sites.   Instead I can support lua regex patterns:

      [Cc][Uu][Dd][Aa]/.*7.5.18:
           Please, do NOT use ...

This is available in 7.7.11.  Please try it out.  Thanks for the feature request.

**Comment by rtmclay** [comment]
Please test 7.7.12 as it now supports multiple targets for the same message.

**Comment by moskalenko** [comment]
I just tried a pre-install of 7.7.12 and saw the following error I don't see with 7.7.6:

couldn't read file "/apps/lmod/dev/libexec/../../etc/rc": no such file or directory
    while executing
"source $mRcFile"
    (procedure "main" line 7)
    invoked from within
"main /apps/lmod/dev/libexec/../../etc/rc"
    ("eval" body line 1)
    invoked from within
"eval main $argv"
    (file "/apps/lmod/dev/libexec/RC2lua.tcl" line 90)
Lmod has detected the following error:  Unable to parse: "/apps/lmod/dev/libexec/../../etc/rc". Aborting!

Here's the path: MODULERCFILE                     /apps/lmod/etc/rc

The etc/rc file is fine. It can be found at that path.

**Comment by rtmclay** [comment]
Please try:

    $ /apps/lmod/dev/libexec/RC2lua.tcl /apps/lmod/dev/libexec/../../etc/rc

Please let me know if that works or produces the error.

Also please generate a debug output with -D and send it to me.

**Comment by moskalenko** [comment]
Robert, the gist of the problem is that Lmod turns the /apps/lmod/etc/rc path set in MODULERCFILE into /apps/lmod/dev/libexec/../../etc/rc, which RC2lua.tcl can't use.

**Comment by rtmclay** [comment]
I tested doing something similar on my computer and it worked fine.   So does this work or not:

     $ /apps/lmod/dev/libexec/RC2lua.tcl /apps/lmod/dev/libexec/../../etc/rc

?

**Comment by moskalenko** [comment]
Not with tclsh from tcl-8.5.7-6.el6.x86_64. It works with the /apps/lmod/etc/rc path, but not with /apps/lmod/dev/libexec/../../etc/rc

**Comment by moskalenko** [comment]
I narrowed the introduction of the bug to the 7.7.8->7.7.10 change.

Debug logs for a test: 'module load python'
7.7.8:

 222   Load_Usr(python){              
   223     Setting mcp to MC_Load
   224     MasterControl:load_usr(mA={python}){
   225       registerUserLoads(mA){     
   226         userName: python         
   227       } registerUserLoads        
   228       MasterControl:load(mA={python}){
   229         Master:singleton(safe: nil){
   230           s_master: table: 0x1014a50, safe: true
   231         } Master:singleton       
   232         Master:load(mA={python}){
   233           Master:load i: 1, userName: python
   234           Mname:sn(){
   235             lazyEval(python){    
   236               ModuleA:singleton(t){
   237                 ModuleA:__new(){
   238                   calling DirTree:new()
   239                   MRC:singleton(){
   240                     MRC l_build(self,fnA){
   241                       capture(/usr/bin/tclsh /apps/lmod/dev/libexec/RC2lua.tcl  /apps/lmod/etc/rc){
   242                       } capture


7.7.10:

 223   Load_Usr(python){
 224     Setting mcp to MC_Load
 225     MasterControl:load_usr(mA={python}){
 226       registerUserLoads(mA){
 227         userName: python
 228       } registerUserLoads
 229       MasterControl:load(mA={python}){
 230         Master:singleton(safe: nil){
 231           s_master: table: 0x1026140, safe: true
 232         } Master:singleton
 233         Master:load(mA={python}){
 234           Master:load i: 1, userName: python
 235           Mname:sn(){
 236             lazyEval(python){
 237               ModuleA:singleton(t){
 238                 ModuleA:__new(){
 239                   calling DirTree:new()
 240                   MRC:singleton(){
 241                     MRC l_build(self,fnA){
 242                       capture(/usr/bin/tclsh /apps/lmod/dev/libexec/RC2lua.tcl  /apps/lmod/dev/libexec/../../etc/rc){
 243 couldn't read file "/apps/lmod/dev/libexec/../../etc/rc": no such file or directory
 244     while executing
 245 "source $mRcFile"

**Comment by rtmclay** [comment]
For a very long time Lmod converted all paths from /a/b/../d/e to /a/d/e.  Issue #324 requested that Lmod stop doing that.  That was part of the Lmod 7.7.10 release.  Apparently your version of tclsh has a problem with paths that look like /a/b/../d/e.  While it seems very unlikely, I am wondering if there is a permission problem with trying to load /apps/lmod/dev/libexec/../../etc/rc vs. /apps/lmod/etc/rc.  An easy way to test would be to see if you got different results for the long path between using root and a regular user.

I have not been able to reproduce the problem with the two centos releases we have (namely Centos 6.9 or Centos 7.3.1611).   Our Centos 6.9 is using:

      tcl-8.5.7-6.el6.x86_64

Still it is any easy fix to clean up the path for calls to tclsh.  So I have released Lmod 7.7.13.  Please test this version out to see if works for you.

**Comment by moskalenko** [comment]
This is just whatever tclsh EL6.8 has. We've no control over that.

It's not a permission issue. Running as root produces the same error with 7.7.10+

7.7.13 fixes the issue as expected.

Thank you,

Alex

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by moskalenko** [comment]
Okay with me. I've not found any other bugs, yet. Cheers.

**Comment by rtmclay** [comment]
Fotis?  O.K. to close?
