### ISSUE TITLE
Reference Count for MODULEPATH

### ISSUE THREAD

**Issue by rjdave** [TACC/Lmod#327]
Would it be possible to allow reference counts on MODULEPATH and have a special case for 'module unuse &lt;path&gt;' that would short circuit the ref count and remove <path> from MODULEPATH regardless of ref count?

Here's my situation. My university has a condominium model super computing cluster using Lmod. My "condo" has a shared space for the department to install software, write modules, store common earth system model initialization and forcing data, etc. The different models require different collections of custom packages. Both the cluster base system and I have followed the recommended organization of modulefiles/{Core,Compiler,MPI} with different roots (/path/to/sys for the system /path/to/department for my custom modules).

My lua module file for model A loads the system modules for the compiler and mpi implementation with **always_load** then prepends the path for custom compiler dependent modules to MODULEPATH then prepends the path for custom MPI dependent modules. Finally it uses **depends_on** to load the custom modules required.

The module files for model B and C do the same with different custom modules so every model uses the same system compiler and mpi (that doesn't automatically unload because of **always_load**) but some common and some different custom modules.

These models can potentially be coupled together so they don't all conflict (some do). Say I want to test model A coupled with B and C then with just C. If I do the following:

module load A B C
     :
&lt;run the coupled system&gt;
     :
module unload B

all of the custom packages in /path/to/department/modulefiles/{Compiler,MPI} are deactivated because I unloaded B even though modules in A and C still depend on those MODULEPATHs. This doesn't happen if everything is in the system locations because /path/to/sys/modulefiles/{Compiler,MPI} are set by the compiler and mpi modules respectively and those modules are not unloaded due to the **always_load** function leaving that part of MODULEPATH in tact.

I know there are a couple ways around this but in my situation it would be simplest to create and maintain modules if reference counting were enabled on MODULEPATH.

**Comment by rtmclay** [comment]
This is really a question for the Lmod mailing list.  Please post it there.  Also please create a tar ball with a module tree that shows exactly what you are trying to do.  Thanks!

**Comment by rtmclay** [comment]
O.K I have added support for reference counting for MODULEPATH.  It is always on now.  Please test out 7.7.15 to see if it fixes the problem you are seeing.

**Comment by rtmclay** [comment]
I am closing this ticket.  If you feel that there is still an issue here please reopen the ticket.
