### ISSUE TITLE
old compiler modulepath not fully removed when reloading when using a meta-module

### ISSUE THREAD

**Issue by moskalenko** [TACC/Lmod#328]
Background:
intel/2016.0.109 is the default 'intel' module.
Latest intel module is 2017, which is a meta-module for intel/2017.4.056

Reproduce:
$ ml
No modules loaded
$ echo $MODULEPATH
/apps/lmod/modulefiles/core

ml intel/2017
$ echo $MODULEPATH
/apps/lmod/modulefiles/compiler/intel/2017.4.056:/apps/lmod/modulefiles/compiler/intel/2017:/apps/lmod/modulefiles/core

$ ml intel

The following have been reloaded with a version change:
  1) intel/2017.4.056 => intel/2016.0.109

$ echo $MODULEPATH
/apps/lmod/modulefiles/compiler/intel/2016.0.109:/apps/lmod/modulefiles/compiler/intel/2017:/apps/lmod/modulefiles/core

**Comment by rtmclay** [comment]
Please do the following:

    $ ml purge
    $ ml -T intel/2017
    $ ml -T intel

And look at what happens.  It might be clear from those message.  If it isn't then I'm am going to need a reproducer that shows the problem.

**Comment by moskalenko** [comment]
It's just what I described. The meta-module component of the MODULEPATH is not removed as only a single top component of the path is removed. We're setting two path components - one for the meta-module, which covers all compatible builds, and one for the specific module loaded by the meta-module, which covers incompatible builds. I realize that we may have an unusual approach that is not handled by Lmod. This is less of a bug and more of a 'do we have a bug, a possible feature request, or an impossible feature request' situation.

$ ml -T intel/2017
running: module -T load intel/2017
  Loading: intel/2017 (fn: /apps/lmod/modulefiles/core/intel/2017.lua)
    Prepending: /apps/lmod/modulefiles/compiler/intel/2017 to MODULEPATH
    Loading: intel/2017.4.056 (fn: /apps/lmod/modulefiles/core/intel/2017.4.056.lua)
      Prepending: /apps/lmod/modulefiles/compiler/intel/2017.4.056 to MODULEPATH

$ ml -T intel

The following have been reloaded with a version change:
  1) intel/2017.4.056 => intel/2016.0.109

running: module -T load intel
  Loading: intel (fn: /apps/lmod/modulefiles/core/intel/2016.0.109.lua)
  Unloading: intel (fn: /apps/lmod/modulefiles/core/intel/2017.4.056.lua)
    Removing: /apps/lmod/modulefiles/compiler/intel/2017.4.056 from MODULEPATH
  Loading: intel (fn: /apps/lmod/modulefiles/core/intel/2016.0.109.lua)
    Prepending: /apps/lmod/modulefiles/compiler/intel/2016.0.109 to MODULEPATH

**Comment by rtmclay** [comment]
You seem to have two modulefiles with a short name of "intel".  You only get one module with a short name of "intel".    I think the problem is that you need to have two different names.  I would suggest "intel" for the meta-module and some other name for the implementation (say "core_intel" or "intel_impl" or even "random_intel_bits").  As you can see the intel/2017 is not unloaded in the second command because it is just part of the list of modules loaded after the first command.  So there is no way that any information that intel/2017 has can be unloaded like the removal of /apps/lmod/modulefiles/compiler/intel/2017 from $MODULEPATH.

**Comment by moskalenko** [comment]
We've historically used 'intel' and 'gcc' for compiler module names. The idea with intel/2017 and so on was to have a meta-module that would load the latest release for applications built with a previous point release, but retain the ability to specify an older release if the application was incompatible like intel/2017.1.132 when migrating to 2017.4.056 as intel/2017. I understand the point you made above.  However, because of the historical naming schema changing the point release module name to something like intel_core would not be desirable. I think what might work is to change the intel/2017 module to be a copy of the latest point release module intel/2017.4.056 instead of loading it. That way Lmod will handle swaps normally and we can still do major/minor release migrations.

**Comment by rtmclay** [comment]
I'm sure you'll figure out something that works for you.  O.K. to close?

**Comment by moskalenko** [comment]
Sure. Thank you.
