### ISSUE TITLE
Allow pushenv("MY_VAR",false) to clear $MY_VAR

### ISSUE THREAD

**Issue by rtmclay** [TACC/Lmod#331]
This is a request from Lewis to extend the capabilities of pushenv to clear values but maintain a stack.

**Comment by lewis-john-lloyd** [comment]
Robert,

This feature works correctly in 7.7.14.
Fantastic. Thank you as usual.

--
Lewis

**Comment by rtmclay** [comment]
You are welcome.  I'm glad that it works for you.
