### ISSUE TITLE
lmod crashes reading cache as it is being regenerated

### ISSUE THREAD

**Issue by gatagat** [TACC/Lmod#333]
Hi, i think i came across a bug which is triggered by a process attempting to read the cache that is being regenerated by some other process at the same time. For me this happens when multiple jobs issue `ml use path` while starting at the same time. The stack trace is as below.  Current workaround is to set `LMOD_CACHED_LOADS=no`. A solution that might solve this would be to have the cache divided into multiple files indexed by the `MODULEPATH` entries.

lmod compiled from source: 7.7.8  2017-10-17 12:37 -05:00

    $ rpm -qa | grep lua
    cm-lua-5.3.4-19_cm8.0.x86_64
    lua-bit32-0.2-12_cm8.0.x86_64
    lua-term-0.07-16_cm8.0.x86_64
    lua-json-1.3.4-18_cm8.0.noarch
    lua-lpeg-1.0.1-14_cm8.0.x86_64
    lua-5.1.4-15.el7.x86_64
    lua-filesystem-1.6.3-13_cm8.0.x86_64
    lua-posix-33.4.0-24_cm8.0.x86_64

 Stack trace:

    running: module load scikit-image/0.13.1-foss-2017a-python-2.7.13
    /usr/bin/lua: /usr/share/lmod/lmod/libexec/Cache.lua:304: /home/user/.lmod.d/__cache__/spiderT.x86_64_Linux.lua:28530: unfinished string near '<eof>'
    stack traceback:
        [C]: in function 'assert'
        /usr/share/lmod/lmod/libexec/Cache.lua:304: in function 'l_readCacheFile'
        /usr/share/lmod/lmod/libexec/Cache.lua:409: in function 'build'
        /usr/share/lmod/lmod/libexec/ModuleA.lua:673: in function 'singleton'
        /usr/share/lmod/lmod/libexec/MName.lua:166: in function 'lazyEval'
        /usr/share/lmod/lmod/libexec/MName.lua:241: in function 'sn'
        /usr/share/lmod/lmod/libexec/Master.lua:277: in function 'load'
        /usr/share/lmod/lmod/libexec/MasterControl.lua:970: in function 'load'
        /usr/share/lmod/lmod/libexec/MasterControl.lua:946: in function 'load_usr'
        /usr/share/lmod/lmod/libexec/cmdfuncs.lua:430: in function 'cmd'
        /usr/share/lmod/lmod/libexec/lmod:480: in function 'main'
        /usr/share/lmod/lmod/libexec/lmod:537: in main chunk
        [C]: ?

**Comment by wpoely86** [comment]
are you talking about a system cache or your user cache?

The system cache should always be consistent: the new one is generated and the swapped with the old one.

**Comment by gatagat** [comment]
User cache, as in the stacktrace: /home/user/.lmod.d/__cache__/spiderT.x86_64_Linux.lua

**Comment by rtmclay** [comment]
I have modified Lmod and pushed to HEAD a fix for this problem.  It is not a great fix.  To do it right would require using file locking and I just don't trust file locking parallel file systems.  

My current solution is to create a temporary file, write the cache and then rename the temp file to be the cache file. There are probably race conditions here but the chances of hitting them are smaller.

Please test out HEAD to see if it works for you.

**Comment by gatagat** [comment]
I share your dislike of locking files on a distributed filesystem. Generating the cache to a temp file will hopefully solve it most of the time.

**Comment by gatagat** [comment]
When using HEAD, I don't see the issue.
