### ISSUE TITLE
Fish shell support docs and bugs

### ISSUE THREAD

**Issue by henryiii** [TACC/Lmod#334]
The fish shell support seems to be poorly documented, and possibly a little buggy. I'm on macOS using `fish` and `lmod` from `brew`, FYI.

## Enable

Add
```
source (brew --prefix lmod)/lmod/init/fish
```
to `~/.config/fish/config.fish`. If fish was installed another way, replace the brew portion with the actual path.

## Problems

If I run:
```
ml
```
I get the error:

```
fish: Unknown command '/usr/local/Cellar/lmod/7.6.11/lmod/libexec/ml'
- (line 1):
begin; /usr/local/Cellar/lmod/7.6.11/lmod/libexec/ml
       ^
from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.7.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 17 of file /usr/local/opt/lmod/lmod/init/fish

in function 'ml'
	called on standard input
```

If I run:
```
module avail
```
I get
```
Lmod has detected the following error:  module avail is not possible. MODULEPATH is not set or not set with valid paths.
```

I haven't been able to get it to be happy with a MODULEPATH, where I'm copying that from the Bash version.

## The init file

Looking at the init file, it seems to be missing several things in the bash version:

* `LMOD_DIR` is set twice in the Fish version, to the same path. Only set once in Bash.
* `MODULESHOME` is only set in bash

**Comment by rtmclay** [comment]
Can this issue be closed?

**Comment by henryiii** [comment]
The other thing that needs to be addressed would be adding a mention to the documentation. I'll take a look at doing that.
