### ISSUE TITLE
Alternative prerequisites

### ISSUE THREAD

**Issue by robertsawko** [TACC/Lmod#343]
This is just a question and potentially an enhancement request. It it possible to specify alternative `prereq`? Note, I don't necessarily think this is an important enhancement. Please feel free to advise a better solution.

**Rationale**
A site I am working operates a multi-cluster environemnt. To deal with some of the complexities the admin team created meta-modules `use.<cluster_name>` and corresponding paths on some shared file systems e.g. `<cluster_name>/apps/gcc/etc/etc/`. Also, clusters have separate home directories which are visible on corresponding compute nodes and the login nodes. Meanwhile, as a user I am trying to create unified modules e.g.

```lua
-- can I use prereq('use.cluster1' OR 'use.cluster2') somehow?
-- use.clustername sets CLUSTER env variable

local cluster = os.getenv("CLUSTER")
local home = os.getenv("HOME")
local name = myModuleName()
local version = myModuleVersion()
local cluster_home = string.gsub(home, "login_node", cluster)
local install_path = pathJoin(cluster_home, 'apps', name, version)

-- set some paths
```

**Comment by rtmclay** [comment]
See the documentation.  You can use 

    prereq_any("cluster1","cluster2")

to request that either cluster1 or cluster2 are loaded.

**Comment by robertsawko** [comment]
This is just great. Thanks.
