### ISSUE TITLE
`ls --color` alias screws up .modulespath

### ISSUE THREAD

**Issue by nolta** [TACC/Lmod#346]
One of our users has `ls` aliased to `ls --color=always`, and this interacts badly with `.modulespath`:
```
$ cat /path/to/lmod/lmod/init/.modulespath 
/path/to/modules/base
$ alias ls='ls --color=always'
$ . /path/to/lmod/lmod/init/profile
$ module avail
Lmod has detected the following error:  module avail is not possible.
MODULEPATH is not set or not set with valid paths.
```

The problem is that `MODULEPATH` contains ANSI escape characters:
```
$ echo $MODULEPATH | sed -n l
\033[0m\033[38;5;27m/path/to/modules/base\033[0m$
```

I think the problem is here: https://github.com/TACC/Lmod/blob/8497b254d9781c8371d56a81d2727cdf5b1e8bce/init/profile.in#L19

Why is `ls` called?

**Comment by rtmclay** [comment]
Thanks for point out this bug.  You are right, there is no reason why ls needs to be called there.  I have changed this to use shell commands instead for both bash and tcsh.  

Please test Lmod 7.7.16 to see if this version fixes this bug.

**Comment by nolta** [comment]
It does, thanks!
