### ISSUE TITLE
Cannot find shared object file: libimf.so for openmpi

### ISSUE THREAD

**Issue by handrake0724** [TACC/Lmod#351]
I am testing openmpi (2.1.1 and 3.0.0) compiled with intel compiler 2018.
So, the modules are like this:
```
intel/2018
openmpi/2.1.1
openmpi/3.0.0
test
```

where test module contains the following statement
```
pinc=capture("mpicc -showme:compile")
setenv("PINC", pinc)
```

In the gnome terminal, I typed following command and got an error
```
module load intel/2018 openmpi/2.1.1 test
mpicc: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
```

I searched what the libimf.so is and found that is related to intel fortran compiler.

Weird thing is if I just load intel and openmpi and type the command directly in the terminal, there is no problem like
```
module load intel/2018 openmpi/2.1.1
mpicc -showme:compile
```
Also, I double-checked if libimf.so is in the environment path.
I found that a issue about openmpi and libimf.so is related to interactive and non-interactive logins in OpenMPI FAQ (https://www.open-mpi.org/faq/?category=running#intel-compilers-static).

How can I solve this issue?

**Comment by rtmclay** [comment]
As it says in the documentation: 

     lmod.readthedocs.io/en/latest/050_lua_modulefiles.html?highlight=subprocess

You need to use the subprocess() function instead of the capture() function.

**Comment by handrake0724** [comment]
It works. Thanks.
