### ISSUE TITLE
mod help shows up unexpectedly in fish

### ISSUE THREAD

**Issue by albireox** [TACC/Lmod#356]
I'm using lmod 7.7.22 installed on a Mac with hombrew, and using fish shell. Overall, it works fine but the `module` command help shows up at unexpected times. For instance, every time I ssh to a machine I get the module command output and then my ssh command finishes correctly. No error, just the module command output. Another instance for this is to run `ls` from inside an ipython console. Again, the `ls` command works fine, but before it there is a dump from the `module` help.

**Comment by albireox** [comment]
So, I did some digging and the problem seems to be that at the end of my `config.fish` I source a file with a bunch of `module load`

```
source $HOME/.modules
```

If I wrap that line in a `status --is-login`

```
if status --is-login
   source $HOME/.modules
end
```

the problem seems to go away. Not sure if this is a bug/feature with fish or Lmod, but maybe it should be documented.

**Comment by rtmclay** [comment]
There are many times that a subshell is created when running a command.  The command "less" does this and I am sure that there are others.  This is not a problem with Lmod.  It is just the way that shell work.  Thanks for sorting this issue yourself.
