### ISSUE TITLE
Confusing error

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#358]
We accidentally had a module file contains something like:

```lua
help([==[

Description
]==])

append_path("VAR", os.getenv("ANOTHERVAR") .. "/somepath/")
```

This fails with `ml show` as `$ANOTHERVAR` was not set (thus returning `nil`).

The error we got was:
```
Lmod has detected the following error:  Unable to load module:
     /path/to/module.lua: [string "help([==[..."]:46: attempt to concatenate a nil value
```

I found this very confusing. The error is correct but it seemed to suggest that the line with help was the origin.  The reference to line 46 was correct. Maybe it shouldn't show the first couple of character of the module file?

**Comment by rtmclay** [comment]
That string "help([==[..."]:46" is coming directly from the lua interpreter and not directly under Lmod's control.  I am loath to change or edit what the interpreter returns.  I agree that the message is not helpful so if you have suggestions on how to modify the "Unable to load module:" text, I am willing to listen. 

One thought might be:

```
Lmod has detected the following error:  Unable to load module because of error when evaluating  modulefile:
    /path/to/module.lua: ...
```

**Comment by wpoely86** [comment]
OK, I agree on not touching what comes directly from the lua parser. Your suggestions for the message is good.

I will have a look if we can also test a `ml show` in EasyBuild (we already test the load). That should avoid this from happening in the first place.

**Comment by rtmclay** [comment]
I have created and uploaded 7.7.28 which has the following this type of failure:

```
Lmod has detected the following error: Unable to load module because of error error when evaluating modulefile:
     /Users/mclay/w/lmod/rt/errHandler/mf/bad_syntax/1.0.lua: [string "setenv("BAD_SYNTAX","1.0")..."]:2: unexpected symbol near '#'
     Please check the modulefile and especially if there is a the line number specified in the above message 
```

I hope this new message is clearer.

**Comment by wpoely86** [comment]
I think it is. Thanks Robert!
