### ISSUE TITLE
7.7.25 parallelized "make install" failure

### ISSUE THREAD

**Issue by ilovezfs** [TACC/Lmod#361]
```
/usr/local/opt/lua/bin/lua ./src/lmod.in.lua bash --help >/dev/null 2> /usr/local/Cellar/lmod/7.7.25/share/man/cat1/module.1
/Applications/Xcode.app/Contents/Developer/usr/bin/make FILELIST="messageDir/de.lua messageDir/en.lua messageDir/es.lua messageDir/fr.lua messageDir/template.lua messageDir/zh.lua" DIRLOC=/usr/local/Cellar/lmod/7.7.25/messageDir __installMe
/Applications/Xcode.app/Contents/Developer/usr/bin/make FILELIST="tools/i18n/init.lua tools/i18n/interpolate.lua tools/i18n/plural.lua tools/i18n/variants.lua tools/i18n/version.lua" DIRLOC=/usr/local/Cellar/lmod/7.7.25/tools/i18n __installMe
/usr/local/opt/lua/bin/lua /usr/local/Cellar/lmod/7.7.25/libexec/spiderCacheSupport --cacheDirs ""          \
	                         --updateFn  ""           \
                                 --descriptFn ""  \
                                 >> /usr/local/Cellar/lmod/7.7.25/init/lmodrc.lua;
/usr/local/opt/lua/bin/lua: cannot open /usr/local/Cellar/lmod/7.7.25/libexec/spiderCacheSupport: No such file or directory
make: *** [spiderCacheSupport] Error 1
make: *** Waiting for unfinished jobs....
cp -a *.so* /usr/local/Cellar/lmod/7.7.25/lib/term
cp term/*.lua /usr/local/Cellar/lmod/7.7.25/libexec/term
```

full log
https://gist.github.com/ilovezfs/0986c1dff711f93aa4246bb192944e65

**Comment by rtmclay** [comment]
I just ran 

    $ brew install -dvs lmod 

and it worked fine on my mac system. Please retry it again and see if it works for you this time.

**Comment by rtmclay** [comment]
Right.  The step before installs spiderCacheSupport in the libexec directory.  Then the next step uses  libexec/spiderCacheSupport.  Could you fix line 48?  Lmod is spelled Lmod and not LMod.

**Comment by ilovezfs** [comment]
@rtmclay to be clear, we consider the inability to build in parallel (`make -j`) to be a bug and `ENV.deparallelize` in a formula should be a temporary workaround until the parallelization bug is fixed upstream, which is why I have reported this.

I fixed the spelling of Lmod.

**Comment by ilovezfs** [comment]
Fix looks good to me. Let's see if CI agrees: https://github.com/Homebrew/homebrew-core/pull/26136

**Comment by ilovezfs** [comment]
7.7.26 shipped. Thanks for the quick fix @rtmclay
