### ISSUE TITLE
"make install" fork bomb under rpmbuild

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#362]
Building Lmod using our custom `.spec` file (see https://github.com/hpcugent/Lmod-UGent) has started failing since Lmod 7.7.21 because `make install` results in a fork bomb where the `/usr/share/lmod/<version>/lib` directory is being created over and over again in the  `BUILDROOT`:

```
grep "^mkdir.*x86_64\/home" rpmbuild.out | head -5
mkdir -p /home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/usr/share/lmod/7.7.26/lib
mkdir -p /home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/usr/share/lmod/7.7.26/lib
mkdir -p /home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/usr/share/lmod/7.7.26/lib
mkdir -p /home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/usr/share/lmod/7.7.26/lib
mkdir -p /home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/home/kehoste/Lmod-UGent/rpmbuild/BUILDROOT/Lmod-7.7.26-1.ug.el7.centos.x86_64/usr/share/lmod/7.7.26/lib
...
```

It seems like this was introduced somehow via the changes made to `Makefile.in` for #352 (the problem is not there with Lmod 7.7.20).
I'm guessing this is because the definition of `LIB` has moved up, before `DIRLIST` is defined (it used to be defined *after*, resulting in the `$(DESTDIR)$(LIB)` entry in `DIRLIST` being equivalent with `$(DESTDIR)`.

The culprit seems to be:
i) the hardcoded `lfs` requirement for `spiderCacheSupport` in `Makefile.in`
ii) the lack of error handling in the commands in the `lfs` target, i.e.:
  * `cd $(srcdir)/pkgs/luafilesystem` fails:
     ```
    /bin/sh: line 0: cd: ./pkgs/luafilesystem: No such file or directory
     ```
  * the subsequent `make` command is executed anyway, but in the wrong directory, causing `make install` to called recursively...

The missing `pkgs/luafilesystem` is caused by our `.spec` file: we remove the `pkgs` directory prior to building the RPM to ensure that the provided `lfs` is used rather than the one shipped with Lmod. 
This worked fine before, but now suddenly results in a fork bomb...

So, I guess this boils down to:

* running `make` in a subdirectory should be done via either `make -C <subdir> ...` or `cd <subdir> && make ...` to prevent that `make install` is called recursively in the same directory
* why is `lfs` hardcoded as a requirement for `spiderCacheSupport`, shouldn't a provided `lfs` be used instead if it's there?

**Comment by rtmclay** [comment]
I don't understand why 

     cd $(srcdir)/pkgs/luafilesystem 

Fails.  That seems to be the key issue here. 

In any event, I have changed Makefile.in so that it a) Only builds luafilesystem when it is needed. b) that it only tries to build luafilesystem when the $(srcdir)/pkgs/luafilesystem exists.

The reason why lfs and other targets are requirements for spiderCacheSupport is that is necessary when  supporting "make -j" builds of Lmod.  To run the spiderCacheSupport program lfs and other lua libraries must be already installed for the program can run.

Please try Lmod 7.7.27 to see if it works better for you.

**Comment by boegel** [comment]
I'm indeed not seeing this issue anymore with Lmod 7.7.27, thanks for the quick fix!
I looked into the change you made, and it makes sense to me, although you maybe also want to use `make -C` in the `pkgs` target?

To clarify: our `.spec` file removes the entire `pkgs` directory, in an attempt to ensure that `lua-term`, `lfs` and `lua-json` are picked up from the OS (we list those in `(Build)Requires`), which explains why we were seeing the issue.

**Comment by wpoely86** [comment]
This is pretty weird. We have build 7.7.23 without issue using the same spec file. Maybe something system specific is triggering this?

**Comment by boegel** [comment]
@wpoely86 Did you use our `.spec` without any changes? I don't see how the issue can be system-specific, but it was specific to the `.spec` file since the `pkgs` dir was being removed.

**Comment by wpoely86** [comment]
The changes are minimal:
https://github.com/hpcugent/Lmod-UGent/compare/master...wpoely86:vub
