### ISSUE TITLE
"Lmod Warning:  Syntax error" when using prepend_path with a function

### ISSUE THREAD

**Issue by adorsey-NOAA** [TACC/Lmod#363]
We have a LUA module called ```craype-theia``` that loads several other modules to save our users some time and effort.  One of the modules that ```craype-theia``` loads sets an environment variable ```$CRAY_LD_LIBRARY_PATH``` that is intended to be prepended to the ```$LD_LIBRARY_PATH``` variable.

I tried doing the following in our module to accomplish this:
```
-- set up Cray libraries
prepend_path("LD_LIBRARY_PATH", os.getenv("CRAY_LD_LIBRARY_PATH"))
```
This works perfectly, but when running certain other commands, we get errors, even when ```craype-theia``` isn't loaded:
```
[Adam.Dorsey@tfe01 ~]$ module load pgi/18.3
[Adam.Dorsey@tfe01 ~]$ module av openmpi
Lmod Warning:  Syntax error in file: /apps/modules/modulefiles/craype-theia/8.6.4.lua
 with command: prepend_path, one or more arguments are not strings.

-------------------------------------------------------------------------- /apps/modules/modulefamilies/pgi ---------------------------------------------------------------------------
   openmpi/1.10.2    openmpi/2.1.2 (D)

  Where:
   D:  Default Module

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".
```

I tried using a variable in ```prepend_path``` instead as follows, but I get the same errors.
```
-- set up Cray libraries
cray_ld_library_path = os.getenv("CRAY_LD_LIBRARY_PATH")
prepend_path("LD_LIBRARY_PATH", cray_ld_library_path)
```

**Comment by rtmclay** [comment]
Lmod is working as designed.  The function os.getenv("FOO") returns nil if $FOO is not in the environment.  So Lmod is telling you that you are trying to prepend a nil, which is an error.  if you want to prevent Lmod from generating an error you will have to test for the nil:

```
local cray_ld_lib_path = os.getenv("CRAY_LD_LIBRARY_PATH")
if (cray_ld_lib_path) then
    prepend_path("LD_LIBRARY_PATH", cray_ld_lib_path)
end
```

**Comment by adorsey-NOAA** [comment]
Thank you, I can confirm that the code in your response fixes the problem.  I appreciate the help.
