### ISSUE TITLE
Software module hierarchy in the docs

### ISSUE THREAD

**Issue by robertsawko** [TACC/Lmod#368]
Sorry, this is going to be nitpicking on the documentation.

I am looking at [How to use a Software Module hierarchy](http://lmod.readthedocs.io/en/latest/080_hierarchy.html) and I am seeing a minor, I think, discrepancy between examples and the text:

 * The examples mention explicitly the `MPI` directory e.g. `/opt/apps/modulefiles/MPI/gcc/4.9/openmpi/1.8`
 * The text omits this e.g. 
```
1. Core packages: /opt/apps/pkgName/version
2. Compiler dependent packages: /opt/apps/compilerName-version/pkgName/version
3. MPI-Compiler dependent packages: /opt/apps/compilerName-version/mpiName-version/pkgName/version
```
I am not sure, but I think the `MPI` directory is actually crucial as otherwise I would see the structure before loading specific MPI for a specifc compiler with all the prefixes related to compiler, MPIs, versions etc.

Please advise.

**Comment by rtmclay** [comment]
I am changing the following text from:
```
We store packages as follows:
```
to 
```
The above description is a suggested way to handle the modulefile
software hierarchy.  The software packages themselves can be stored in
many ways.  For software packages, but not the modulefiles, we store
them as follows:
```

This web page is trying to explain two kinds of software hierarchies: one for the the modulefiles and another for the software packages themselves.  Does this change in the documentation help explain the two hierarchies?  

By the way, I appreciate questions about the documentation.  Thanks for the question.

**Comment by robertsawko** [comment]
Oh I see, thanks. That makes a lot of sense.
