### ISSUE TITLE
[Discussion] Compiler-MPI hierarchy on top of science discpline division

### ISSUE THREAD

**Issue by robertsawko** [TACC/Lmod#369]
Hi,

This is not an issue. I would just like to ask about ideas for handling multiple layers of modules hierarchy. On one of our clusters the packages managed in Lmod are divided up into disciplines: `engineering`, `data-science`, `life-sciences`, `chemistry` etc.

On the other hand, I would like to have the Compiler-MPI hierarchy working e.g. load gcc/7.2.0 and see only MPIs compiled with that compiler, load MPI to be presented only with applications specific for this MPI. Is there a sensible way of combining this with the disciplines?

My plan A was this:
 * `/path/to/modulefiles/compilers`
 * `/path/to/modulefiles/compilers/gcc/7.2./openmpi/3.0.0`
 * `/path/to/modulefiles/compilers/gcc/7.2./openmpi/3.0.0/engineering/openfoam`
 * `/path/to/modulefiles/compilers/gcc/7.2./openmpi/3.0.0/visualisation/paraview`

This way I take advantage of swapping, active and inactive module functionality, but I think I will lose the simplicity as no modules will be visible if no gcc or MPI is loaded.

I am afraid, I am pursuing two contradictory goals here as I would like to have a view of say engineering applications without loading an MPI and a compiler, but at the same time I would like to retain compiler-MPI hierarchy. Is there like a middle-ground solution e.g. as I load compiler and MPI it populates the discipline section with applications compatible with a given pair?

**Comment by rtmclay** [comment]
This is discussion belongs on the Lmod mailing list.  See my comments there.

**Comment by robertsawko** [comment]
Ok. Thanks, will have a look.
