### ISSUE TITLE
can't add nag message to module with dash in name

### ISSUE THREAD

**Issue by nolta** [TACC/Lmod#370]
With lmod 7.7.16, we can't seem to add deprecation messages to modules with '-' in their name.

I think the problem may have been introduced by ec7b9af88c233c57ee779b36b2a48052561daee1:

```
$ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> x = "boost"
> x:find("boost")
1	5
> y = "boost-mpi"
> y:find("boost-mpi")
nil
```

**Comment by rtmclay** [comment]
This is not a bug but a feature.   The "name" is now a regular expression and not an exact match:

You'll need to quote the "-" with a percent:  
     boost%-mpi: This module is about ....

**Comment by nolta** [comment]
It would be nice to have both exact & pattern matching, and probably not too difficult:

```lua
if (fullName == pattern    or fn == pattern or
    fullName:find(pattern) or fn:find(pattern)) then
```

**Comment by nolta** [comment]
Thanks! Is this a typo: `fn = pattern`?

**Comment by rtmclay** [comment]
You have to grab 7.7.30 and not https://github.com/TACC/Lmod/commit/4cc7578f7dbaf07e9c46e29edafd6d650ad81c1e

**Comment by nolta** [comment]
7.7.30 works -- thanks again.
