### ISSUE TITLE
tag last release with latest release

### ISSUE THREAD

**Issue by dirtyharrycallahan** [TACC/Lmod#371]
Is there a reason there have been eight releases after 7.7.22 that did not get the latest release tag?

**Comment by rtmclay** [comment]
It is because I don't yet understand how to automate the creation of the latest release tag. The documentation is opaque to me.  If anyone is could give me an explanation on what exact I need to automate, I'll be happy to add it.

**Comment by boegel** [comment]
I already sent this to @rtmclay via mail, but I might as well mention it here too...

You can create a release using `curl` to talk to the GitHub API.

For example:

```
$ curl --user boegel -X POST --data '{"tag_name": "test2","target_commitish": "master", "name": "test2", "body": "this is just another test"}' https://api.github.com/repos/boegel/eb-scripts/releases

See the result at https://github.com/boegel/eb-scripts/releases .

Documentation on this is at https://developer.github.com/v3/repos/releases/#create-a-release, I also used https://gist.github.com/caspyin/2288960 for inspiration.

This will prompt you for your GitHub password, but you can probably avoid that by using a personal access GitHub token; see https://developer.github.com/v3/auth/.
Of course you'll need to be careful about not leaking the token, storing it in cleartext in a script is obviously not recommended... 

I hope this helps!

**Comment by rtmclay** [comment]
This now works.  I am closing this issue
