### ISSUE TITLE
Running out of RAM on a 32Gb machine when installing Lmod 7.7.22

### ISSUE THREAD

**Issue by aaronk** [TACC/Lmod#372]
This seems a bit crazy to me, but "make install" takes several hours and is running out of RAM.  Could there be some funky loop happening?

**Comment by rtmclay** [comment]
Yes there is a problem with 7.7.22 in certain cases.  Please use the latest, currently 7.7.32

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by aaronk** [comment]
Yes.  All set.

ajk
