### ISSUE TITLE
Lmod 7.7.33 fails to prepend paths in fish

### ISSUE THREAD

**Issue by albireox** [TACC/Lmod#373]
Since the latest release when one of my modules tries to prepend a path to `$PATH` I get and error such as

> set: Warning: $PATH entry "/Users/albireo/Documents/SDSSV/SurveySimulations/observesim/bin /usr/local/opt/findutils/libexec/gnubin /usr/local/opt/gnu-tar/libexec/gnubin /usr/local/opt/gnu-sed/libexec/gnubin /usr/local/opt/gnu-getopt/bin /usr/local/opt/coreutils/libexec/gnubin /Users/albireo/Documents/MaNGA/Utils /usr/local/subgit/bin /usr/local/texlive/2016/bin/x86_64-darwin /opt/X11/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/opt/qt@4/bin /Users/albireo/.pyenv/bin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin" is not valid (No such file or directory)

My prepend_path is `prepend_path{"PATH","/Users/albireo/Documents/SDSSV/SurveySimulations/observesim/bin",delim=":",priority="0"}`. This works fine with 7.7.32.

**Comment by rtmclay** [comment]
Thanks for the bug report! Please test 7.7.34 to see if it fixes the problem for you.

**Comment by albireox** [comment]
Everything seems to be working fine now. Thanks!

**Comment by rtmclay** [comment]
You are welcome.  I'm closing this issue.
