### ISSUE TITLE
Doc page for Tracking Module Usage uses scripts that are not linked to

### ISSUE THREAD

**Issue by eamonn-murray** [TACC/Lmod#378]
The process outlined from step 5, where a mysql database is created for tracking usage, mentions the following scripts that I don't see linked anywhere:

- conf_create and createDB.py in step 5
- store_module_data in step 6
- analyseLmodDB in step 7

**Comment by rtmclay** [comment]
Thanks for the question.  I have updated the documentation to say that all the scripts can be found in the contrib/tracking_module_usage directory.

**Comment by eamonn-murray** [comment]
Thanks for the quick response & fix. Much appreciated.
