### ISSUE TITLE
configure --prefix not working as expected

### ISSUE THREAD

**Issue by ysagon** [TACC/Lmod#383]
Hello,

I'm trying to install lmod-7.8.4 in a custom location. I want it to be installed here:

    /opt/lmod/7.8.4

I have already other lmod versions here:

    /opt/lmod/6.1
    /opt/lmod/6.4

I do the configure like this:

    ./configure  --prefix=/opt/

according to the output, it seems ok.

When doing a `make install`, everything is installed in `/opt/lmod/` (at the root) and the symlink is created where I type `make install`

**Comment by rtmclay** [comment]
It is not clear to me what you want.  If you do:

    $ ./configure --prefix=/opt/
    $ make install

Then I would expect that there would be in /opt and lmod directory
then in /opt/lmod/  I would expect:

      $ cd /opt; tree -L 1 lmod
           lmod
           ├── 6.1
           ├── 6.4
           ├── 7.8.4
          └── lmod -> 7.8.4

This is expected behavior for Lmod installation.  Are you seeing something different?  If you are saying that prefix works differently than it does in  many other programs; yes it does.  This is discussed here:

https://lmod.readthedocs.io/en/latest/030_installing.html#why-does-lmod-install-differently

**Comment by ysagon** [comment]
Yes I'm seeing something different. I didn't had this issue with older lmod.

In the output of `configure`:
    
    [...]
    Actual Install dir.......................................... : /opt/lmod/7.8.4
    [...]

But after doing `make install`, this is what I get in `/opt/lmod`:
```
tree -L 1 /opt/lmod/
/opt/lmod/
├── 6.1
├── 6.4
├── cleanupmodule.patch
├── init
├── lib
├── libexec
├── messageDir
├── modulefiles
├── settarg
├── share
├── shells
└── tools
```

**Comment by rtmclay** [comment]
There is something bizarre going on.  I'll need the output of ./configure and the output of "make install" and

       $ /opt/lmod/libexec/lmod bash --config > ~/config.log 2>&1

and the ~/config.log generated by the above command.  You can email this to me.

**Comment by rtmclay** [comment]
O.K.  I know what happen.  Namely that the lua code which determines the Lmod version failed to work.  What I don't understand is why.  Could you run the following:

   $ /opt/lua/lua-5.3.5/bin/lua -e 'print(package.path)'

Thanks
R.

**Comment by ysagon** [comment]
Ok, I see. After running:

/opt/lua/lua-5.3.5/bin/lua -e 'print(package.path)'

I see I forgot to add ";;" in the LUA_PATH and LUA_CPATH env variable. I
had only path to luarocks set.

After adding this, the installation works fine. Let me know if you want
more information anyway.

Thanks for the help.

Le jeu. 27 sept. 2018 à 01:16, Robert McLay <notifications@github.com> a
écrit :

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by ysagon** [comment]
Sure! Thanks.
