### ISSUE TITLE
unbound variable __lmod_vx

### ISSUE THREAD

**Issue by opoplawski** [TACC/Lmod#384]
See https://bugzilla.redhat.com/show_bug.cgi?id=1594964

Description of problem:
Building a package in mock for Rawhide today, saw this:
```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
/usr/share/lmod/lmod/init/bash: line 15: __lmod_vx: unbound variable
```
Indeed, if none of the cases in the if statement above line 15 match, or the if
condition is false, then __lmod_vx is unbound.  It should be set to the empty
string prior to the if statement to avoid this.

**Comment by rtmclay** [comment]
Thanks for reporting this unbound variable.  I have fixed it and uploaded 7.8.6.  Please test this new version to see if it works for you.

**Comment by opoplawski** [comment]
Thanks, but I'm not seeing 7.8.6

**Comment by rtmclay** [comment]
It is there now.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by opoplawski** [comment]
I think so.
