### ISSUE TITLE
Unloading of sticky modules

### ISSUE THREAD

**Issue by bmario** [TACC/Lmod#385]
I'm not sure if this is ~the~ unintended behavior or if the documentation needs clarification, but I found it surprising that `module reset` and `module restore` actually unload sticky modules.

The documentation for sticky modules reads like this:

> This means that if the module is loaded then it won’t be removed with a normal unload or **purge**.

And the documentation for `module reset` reads like this:

> [`module reset`] will **purge** all currently loaded modules then load the list of modules specified by LMOD_SYSTEM_DEFAULT_MODULES. 

So I read it as `module reset` is a `module purge` plus some `module load ...` and assumed that it, therefore, shouldn't unload sticky modules.

**Comment by rtmclay** [comment]
The current actions of Lmod are the design.  The documentation needs fixing.  I will change the documentation for reset to say:

     [module reset] will unload ALL modules, including the sticky ones, then load the list of modules specified by LMOD_SYSTEM_DEFAULT_MODULES.

The intent of "module reset" and "module restore" is to get to a known state.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by bmario** [comment]
It's fine for me.

**Comment by runiq** [comment]
Just for clarification---the difference between `reset` and `purge` is that:

- `reset` unloads everything, then reloads the modules in `LMOD_SYSTEM_DEFAULT_MODULES`,
- `purge` unloads everything _except_ the modules in `LMOD_SYSTEM_DEFAULT_MODULES`.

Is this correct?

**Comment by rtmclay** [comment]
The command `module reset` purges all modules including the sticky modules then load the modules listed in `LMOD_SYSTEM_DEFAULT_MODULES`

The command `module purge` unloads **ALL** modules then tries to reload any sticky modules.  So your second bullet is wrong.     Please feel free to test this.
