### ISSUE TITLE
Forcibly load a collection

### ISSUE THREAD

**Issue by damianam** [TACC/Lmod#388]
A user complained because his collection broke and his jobs failed. The collection broke because we changed one module to have

```
if not isloaded("one_module/.version") then
    load("one_module/.version")
end
```
instead of
```
if not isloaded("one_module/version") then
    load("one_module/version")
end
```
Naïvely, I would say it makes sense to allow `--force restore`, to forcibly load a collection even if it "appears" broken. Of course it is a dangerous option depending on the changes. But I guess just going through the list of modules in the collection and try to load them should be allowed. If the load fails and the environment is broken, then so be it, those are the risks of `--force`. Any comments?

**Comment by kayleanelson** [comment]
I was wondering if there were any thoughts on this issue? We also face in job failures with collections "breaking" when changes have been made to a module and it would be great to be able to forcibly load the collection.

**Comment by kayleanelson** [comment]
Hello. This just tripped our users up again. Is there any consideration for adding a "--force" flag?

**Comment by rtmclay** [comment]
This is not happening.  There is no way to make this work reliably.  You get a failure from loading a collection when loading the modules in a collection by hand is different from loading module collections.  Not only that, there is no feedback to the user that it failed and the collection has to be rebuilt.
