### ISSUE TITLE
Have message formatting preserved in admin.list.

### ISSUE THREAD

**Issue by aaichsmn** [TACC/Lmod#389]
If admin.list contains, for instance ...

foo/3.3.0:
This module is being replaced by an update and will be removed on yyyy/mm/dd.  To use the updated version, use ...
        module purge
        module load foo/4.3.2
The purge is optional but a suggested practice when loading foo modules.

When the user loads foo/3.3.0, the message text is displayed without preserving the line spacing and indents.  Effectively as a single wrapped line.

I'm aware of no means to preserve the formatting after working my way through documentation.  I tried embedding newlines in the message without success.  

Can the display function be modified to preserve formatting?

**Comment by rtmclay** [comment]
Here is an example of what the new output looks like:

```
There are messages associated with the following module(s):
format/1.1:
   This module is best used when you do:
      $ module purge
      $ module load format
```

**Comment by aaichsmn** [comment]
Thanks for your trouble.  Will pester staff here to get the fresh files into our system.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by aaichsmn** [comment]
Sure.  Thanks for the fix and happy belated T-day.

                                                                Best regards,
                                                                Phil

                                                                P. A. Cheeseman
                                                                aai@purdue.edu
                                                                765.496.8224
