### ISSUE TITLE
Show family info when using spider tool

### ISSUE THREAD

**Issue by gassyfeve** [TACC/Lmod#392]
I am trying to make a visiable lmod tool to help hpc user to select available modules.
 Now I use spider tool to resolve the module info.
spider -o spider-json $MODULEPATH`
I think field "parentAA" is very useful but not enough.

Could spider tool show the family info. So that I could know if modules I have selected are conflict or not.

**Comment by rtmclay** [comment]
I have finally gotten around to your request.  Please test out Lmod 8.1.1 to see if it solves this problem for you.

**Comment by rtmclay** [comment]
I am closing this issue.  If there are problems, please let me know.
