### ISSUE TITLE
"module is-loaded" is not giving an ouput

### ISSUE THREAD

**Issue by clsgithubusr** [TACC/Lmod#393]
Hi

I recently upgraded Lmod to the latest version, but when I try to execute "module is-loaded prod_clean", it is not giving me  true or neither false

```shell
$ module is-loaded prod_clean #existing module
$ module is-loaded prod_clean55 #non-existing module
```

**Comment by rtmclay** [comment]
All the "module is-loaded" does is set the status bit.  This means that one can do:
```
if [ $(module is-loaded prod_clean) ]; then
    echo prod_clean is loaded
fi
```

Does that work for you?

**Comment by rtmclay** [comment]
Sorry that wasn't the correct usage.  It should be:
```
if module is-loaded prod_clean ; then
   echo "prod_clean is loaded";
fi

**Comment by rtmclay** [comment]
O.K. to close this issue?
