### ISSUE TITLE
env_modules_python.py doesn't generate output in a Jupyter Notebook

### ISSUE THREAD

**Issue by jonathaneichelberger** [TACC/Lmod#399]
The following works in a python or ipython interpreter, but not in a Jupyter Notebook - no output is observed:
```python
import os
import sys

sys.path.append(os.environ['LMOD_PKG'] + '/init')
from env_modules_python import module

module('avail')
```

The following implementation for `env_modules_python.py.in` fixes the issue (works for Python 2 & 3):
```python
# -*- python -*-
import os, sys 
from subprocess import PIPE, Popen

def module(command, *arguments):
    proc = Popen(['@PKG@/libexec/lmod', 'python', command] + list(arguments), stdout=PIPE, stderr=PIPE)
    stdout, stderr = proc.communicate()
    print(stderr.decode())
    exec(stdout.decode())

```

**Comment by rtmclay** [comment]
Thanks for the fix.  The standard that Lmod uses is to write the output of stderr is written to stderr.  I had to change your implementation to do that.  However, I have change env_module_python.py.in to support LMOD_REDIRECT.  So if you want the output from module('avail') to go to sys.stdout, you can either configure Lmod to turn on redirect or set the env. var.  LMOD_REDIRECT to 'yes'

Here is what the new version of env_modules_python.py.in looks like:

```
# -*- python -*-
from __future__ import print_function
from subprocess import PIPE, Popen
import os, sys 


def module(command, *arguments):
    proc = Popen(['@PKG@/libexec/lmod', 'python', command] + list(arguments), stdout=PIPE, stderr=PIPE)
    stdout, stderr = proc.communicate()
    err_out=sys.stderr
    if (os.environ.get('LMOD_REDIRECT','@redirect@') != 'no'):
        err_out=sys.stdout

    print(stderr.decode(),file=err_out)
    exec(stdout.decode())
```

**Comment by rtmclay** [comment]
This fix has been push to HEAD.  It will become part of the Lmod 7.8.22 release.

**Comment by rtmclay** [comment]
OK to close?

**Comment by jonathaneichelberger** [comment]
Yes, thank you.
