### ISSUE TITLE
switching modules does not work in tcl modulefiles with R shell

### ISSUE THREAD

**Issue by bmcgough** [TACC/Lmod#402]
https://github.com/TACC/Lmod/blob/e2a334bef4f4fd217d20bf2ea0a0df6d93ee3bf0/src/tcl2lua.tcl#L930

This line is the beginning of a code block that does not include R as a recognized shell. Is there a reason for this? It looks like more shells were added at some point (7.3-ish?), but not R.

I have users who would like Lmod to behave the same way in R and bash. Right now you get a warning, but the new module(s) load in bash, but the module(s) are not loaded in R, and an unhelpful error is displayed:

```
> module("load", "BCFtools")
 +(0):ERROR:0: Unknown shell type '(r)'
    while executing
"error " +(0):ERROR:0: Unknown shell type \'($g_shellName)\'""
    ("." arm line 2)
    invoked from within
"switch -regexp -- $g_shellName {
    ^(sh|bash|ksh|zsh)$ {
      set g_shellType sh
    }
    ^(cmd)$ {
        set g_shellType cmd
    }
    ^(csh|tcsh)$ ..."
    (file "/app/Lmod/lmod/lmod/libexec/tcl2lua.tcl" line 863)
Lmod has detected the following error: Unable to load module: zlib
     /app/easybuild/modules/all/zlib/1.2.8-GCCcore-5.4.0: Non-zero status
returned
 
While processing the following module(s):
    Module fullname           Module Filename
    ---------------           ---------------
    zlib/1.2.8-GCCcore-5.4.0  /app/easybuild/modules/all/zlib/1.2.8-GCCcore-5.4.0
    BCFtools/1.9-foss-2016b   /app/easybuild/modules/all/BCFtools/1.9-foss-2016b.lua
 
Error in eval(expr = parse(file = hndl)) : object 'false' not found

```

**Comment by rtmclay** [comment]
Thanks for the bug report!  All I can say is that your users are the first to notice that modulefiles written TCL didn't work when trying to load them into R.

Please test 8.0.6 to see if it fixes your users' problem.

There is an unresolved issue with R that I don't know how to handle as I don't know the R scripting language.   Lmod produces a "false" to signify that the loading of the module has failed.  This works fine in normal shells (e.g. bash, csh) but doesn't work in R.  Is there something that Lmod can produce that will let R know that there was a problem in loading the module.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by bmcgough** [comment]
Yes, we can close, but I would like for this to work. I will try to test the newest Lmod. We do have legacy tcl modulefiles as some of our initial EasyBuild toolchains were built long ago, before we moved Lmod to lua (we have an archive of older tcl modulefiles we must continue to support).

So what I think you are saying is that Lmod produces a 'false' when a module load fails (which happens when there is a conflict/switch) but in normal shells execution continues, and in the case of a switch the old module is unloaded and then the new loaded again? But in R that 'false' return halts execution? If that is correct, I can start to query our R experts.

**Comment by rtmclay** [comment]
Right.  Now Lmod correctly handles the R shell with TCL modulefiles.  And if there is no errors in the modulefile itself then all will be fine.  However, if there is an error in the modulefile then Lmod produces a "false" which upsets R.  It would be nice if Lmod produced something that R handled gracefully.

**Comment by rtmclay** [comment]
I talked with a local R script expert and found a way to safely handle bad modulefiles in R.

Please test 8.1.3 to see if works for you.

**Comment by rtmclay** [comment]
Closing this issue.  If there is a problem please open this issue again.
