### ISSUE TITLE
Unload order bug

### ISSUE THREAD

**Issue by vanderwb** [TACC/Lmod#403]
We have a hierarchical module tree which goes compiler -> MPI -> software. This works well for the most part but have found that module unload ordering matters. In this example, I load pnetcdf, which was built with Open MPI which was built with GCC. That's fine, but if I unload the compiler and MPI I get results that differ based on order. See the following:

```
$ cat works.sh
#!/bin/bash -l

module purge
module load gnu/8.1.0 openmpi pnetcdf

module -T rm openmpi gnu

$ ./works.sh
Using settings for cheyenne1
Lmod version: 8.0.8  2019-04-26 11:29 -05:00
running: module -T rm openmpi gnu
  (1)(0)Unloading: openmpi (status: active) (fn: /glade/u/apps/ch/modulefiles/default/gnu/8.1.0/openmpi/3.1.0.lua)
    Removing: /glade/u/apps/ch/modulefiles/default/openmpi/3.1.0/gnu/8.1.0 from MODULEPATH
  (2)(0)Unloading: gnu (status: active) (fn: /glade/u/apps/ch/modulefiles/default/compilers/gnu/8.1.0.lua)
    Removing: /glade/u/apps/ch/modulefiles/default/gnu/8.1.0 from MODULEPATH
  reloadAll(1)(pnetcdf)
  (3)(1)Unloading: pnetcdf (status: active) (fn: /glade/u/apps/ch/modulefiles/default/openmpi/3.1.0/gnu/8.1.0/pnetcdf/1.11.0.lua)

Inactive Modules:
  1) pnetcdf
```

```
$ cat fails.sh
#!/bin/bash -l

module purge
module load gnu/8.1.0 openmpi pnetcdf

module -T rm gnu openmpi

$ ./fails.sh
Using settings for cheyenne1
Lmod version: 8.0.8  2019-04-26 11:29 -05:00
running: module -T rm gnu openmpi
  (1)(0)Unloading: gnu (status: active) (fn: /glade/u/apps/ch/modulefiles/default/compilers/gnu/8.1.0.lua)
    Removing: /glade/u/apps/ch/modulefiles/default/gnu/8.1.0 from MODULEPATH
  (2)(0)Unloading: openmpi (status: active) (fn: /glade/u/apps/ch/modulefiles/default/gnu/8.1.0/openmpi/3.1.0.lua)
    Removing: /glade/u/apps/ch/modulefiles/default/openmpi/3.1.0 from MODULEPATH
  reloadAll(1)(pnetcdf)
```

The issue seems to be that "gnu/8.1.0" gets chopped from the Open MPI module path before it gets removed from MODULEPATH. I can see two solutions:

1. Make the MODULEPATH modification less greedy. This seems trickier to me at first glance.

2. Reorder the user-specified unload operation to make sure the order is consistent with the order of LOADEDMODULES. Specifically, the unload list needs to be the inverse of the LOADEDMODULES order. Doing so would ensure that an unload operation won't be run that is the inverse of an invalid load operation.

In any case, this bug is rare but does hit our users and leads to confusing errors at compile time.

**Comment by rtmclay** [comment]
I have run a similar test where gcc -> impi -> petsc hierarchy exists.  Here is what I see:
```
running: module --regression_testing -T rm gcc impi
  (1)(0)Unloading: gcc (status: active) (fn: ProjectDIR/rt/hierarchy/mf/Core/gcc/6.1.lua)
    Removing: ProjectDIR/rt/hierarchy/mf/Compiler/gcc/6.1 from MODULEPATH
  (2)(0)Unloading: impi (status: active) (fn: ProjectDIR/rt/hierarchy/mf/Compiler/gcc/6.1/impi/17.0.3.lua)
    Removing: ProjectDIR/rt/hierarchy/mf/MPI/gcc/6.1/impi/17.0 from MODULEPATH
  reloadAll(1)(petsc)
  (3)(1)Unloading: petsc (status: active) (fn: ProjectDIR/rt/hierarchy/mf/MPI/gcc/6.1/impi/17.0/petsc/3.7.lua)
Inactive Modules:
  1) petsc
```

As you can see, I do not reproduce your issue. I suspect that the problem you are seeing has to do with how you form the directory that modifies the MODULEPATH. I would recommend that you look at your openmpi modulefile to see if it depends on having environment variables that depend on having the gnu module loaded.

**Comment by vanderwb** [comment]
Robert, thank you for taking the time to run that test and provide the helpful suggestion. You are absolutely right. It appears I was trying to get too clever a couple of years back. It's our issue, so please consider this closed.

I'll post the offending code here, just in case anyone else does something similar and stumbles on this issue.

```
local mroot     = os.getenv("MODULEPATH_ROOT")
local compname  = os.getenv("LMOD_FAMILY_COMPILER")
local compver   = os.getenv("LMOD_FAMILY_COMPILER_VERSION")
local mdir      = pathJoin(mroot, "openmpi", "3.1.0", compname, compver)
append_path("MODULEPATH",mdir)
```

**Comment by rtmclay** [comment]
Yes, you can not depend on the value of any environment variables that depend on another modulefile. I like to make some of my modulefiles be generic, so I use the path that the modulefile exist to know how to build things like directories to be added to $MODULEPATH.  Since, I place the modulefiles in a hierarchy, I can use the location of current modulefile to help build the entry for $MODULEPATH.

The details are discussed here:
https://lmod.readthedocs.io/en/latest/100_modulefile_examples.html?highlight=hierarchyA#generic-modules-with-the-hierarchy
