### ISSUE TITLE
modulerc support regression

### ISSUE THREAD

**Issue by ocaisa** [TACC/Lmod#405]
I was introducing Lmod8 to our travis setup for EasyBuild (https://github.com/easybuilders/easybuild-framework/pull/2849) and I noticed that our modulerc tests are broken once we hit `8.0.7`. 

The relevant tests can be found at https://github.com/easybuilders/easybuild-framework/blob/master/test/framework/module_generator.py#L345 and the specific broken test is at https://github.com/easybuilders/easybuild-framework/blob/master/test/framework/module_generator.py#L390

**Comment by wpoely86** [comment]
Did you install Lmod with `--with-extendedDefault=no`?

**Comment by ocaisa** [comment]
Confirmed, that resolved it. It's an issue to consider in the tests then.

**Comment by boegel** [comment]
@ocaisa No, we should configure Lmod to disable the extended defaults feature when it's running under EasyBuild, much like we disable the use of the Lmod spider cache as well (since we want EasyBuild to pick up on installed stuff even when they're not included in the cache yet).
