### ISSUE TITLE
Runtime switch for extended defaults

### ISSUE THREAD

**Issue by ocaisa** [TACC/Lmod#406]
Feature request, would it be possible to have a runtime environment switch to disable extended defaults? Related to #405 I fixed the EB test suite by disabling this (https://github.com/easybuilders/easybuild-framework/pull/2849), but users will probably have just gone with the Lmod defaults so the test suite will fail for them unless we can switch this off with an environment var.

Thanks!

**Comment by rtmclay** [comment]
It already exists:
```
   export    LMOD_EXTENDED_DEFAULT=no
```

**Comment by ocaisa** [comment]
Great, thanks, I'll fix that tomorrow.
