### ISSUE TITLE
Unable to Load 'R' Module

### ISSUE THREAD

**Issue by yanaung29** [TACC/Lmod#408]
Hi, 

We are facing the problems that unable to load 'R' module. 
The error showing like
'Unable to load module because  of error when evaluating module files:'
/usr/share/lmod/lmod/modulefiles/Core/gnu8/R/3.5.0: /usr/share/lmod/lmod/libexec/MasterControl.lua:887: attempt to compare number with nil

What could it be the issue since the rest of the module we are able to load.

**Comment by boegel** [comment]
Please provide some more details about the Lmod version you are using, and your Lmod configuration (output of “ml --config”)

**Comment by rtmclay** [comment]
As @boegel says, it is always important to report which version of Lmod you are using.  It is also clear, based on the error message you are reporting that you are not using the most recent version of Lmod.  

Please try 8.1.3 to see if it shows a similar problem.

**Comment by rtmclay** [comment]
Any news on this issue?  If not I will close it.

**Comment by yanaung29** [comment]
Hi,
Sorry for the late reply. Yes, I was able to solve the issue and can close
it.

Thank You

**Comment by DirectorSloan** [comment]
Hi @yanaung29.

can you please share your solution? I'm facing the same problem with lmod 7.7.14 and Easybuild 4.5.5. when Loading e.g. foss2020b.

Thanks

**Comment by DirectorSloan** [comment]
Nevermind, Using the latest (for now 8.7.4) Lmod Version fixed it for me.

**Comment by ocaisa** [comment]
@DirectorSloan I think the solution was just to user a more recent version of Lmod
