### ISSUE TITLE
Add custom load/unload functions

### ISSUE THREAD

**Issue by ianliu** [TACC/Lmod#411]
I have installed a program in my Cluster that has its own load/unload scripts. It would be nice if Lmod provided a custom load/unload function, something like:

```lua
help("Help string")
whatis("Version: 1.0")
load_script("/opt/software/load.sh")
unload_script("/opt/software/unload.sh")
```

Sorry if this is already possible, but I've searched the web and even peeked at the source code to see if this was possible but didn't find anything.

**Comment by rtmclay** [comment]
This is not something that Lmod is going to directly support.  It goes against the whole reason why modules  was created in the first place.   You are free to write your own ```load_script``` and ```unload_script``` function and place those functions in your own SitePackage.lua file.  You can read about how to set this up in lmod.readthedocs.io.  

As it said on here:

```
How do I use the initializing shell script that comes with this application with Lmod?

The short answer is you don’t. Among the many problems is that there is no way to unload that shell script. If the script is simple you can read it through and create a modulefile. To simplify this task, Lmod provides the sh_to_modulefile script to convert shell scripts to modulefiles. See Converting shell scripts to modulefiles for more details.
```
found : https://lmod.readthedocs.io/en/latest/040_FAQ.html

That being said you can do what you want right now.  The load_script function could be written as:

```
if (mode() == "load" and myShellType() == "sh") then
  local str = subprocess("cat /opt/software/load.sh")
  execute{cmd=str, modeA={"load"}}
end
```
The unload_script operation is similar except that the "load" strings are replaced by "unload"

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by ianliu** [comment]
Yes, and I've managed to achieve what I wanted with the execute command, like so:

```
execute { cmd = "source load.sh", modeA = { "load" }}
execute { cmd = "source unload.sh", modeA = { "unload" }}
```

Thanks!
