### ISSUE TITLE
Unable to restore PS1

### ISSUE THREAD

**Issue by doctaweeks** [TACC/Lmod#413]
It appears that changes introduced in v7.7.33 may have broken the ability to pushenv PS1 and correctly restore it when it contains escape sequences (almost always):

test.lua:
`
pushenv("PS1","hello> ")
`

`PS1="test \u@\h> "`
`test user@vm> module load test`
`hello> module unload test`
`test u@h> `

**Comment by rtmclay** [comment]
Thanks for the bug report! The change in 7.7.33 forgot about escape sequences like \u.  This has been fixed in Lmod Version 8.1.7.  When you get the chance, please test 8.1.7 to see if it works for you.  Thanks!

**Comment by doctaweeks** [comment]
Looks good. Thanks for the quick fix!
