### ISSUE TITLE
Tracking module Usage -  store_module_data issue

### ISSUE THREAD

**Issue by clsgithubusr** [TACC/Lmod#422]
Hello

I have implemented the Tracking module usage in our environment.
I have done all steps described in [the readthedocks page](https://lmod.readthedocs.io/en/latest/300_tracking_module_usage.html)
The crontab(from [step 6](https://lmod.readthedocs.io/en/latest/300_tracking_module_usage.html#step-6)) is working fine for a few weeks, but suddenly I'm getting the following error when the crontab has been executed:

```
data_to_db():  (1526, 'Table has no partition for value 737724')
data_to_db():  (1526, 'Table has no partition for value 737725')
data_to_db():  (1526, 'Table has no partition for value 737726')
data_to_db():  (1526, 'Table has no partition for value 737727')
```
A temporary fix is to purge the database, and create a new one, but after a few weeks, I am getting the same error.

**Comment by rtmclay** [comment]
Please try 8.2.1 and use the createDB.py program that comes with it.  You'll have to purge the database and recreate it but this version should work fine.  

The version of createDB.py was my attempted to try to make it easier to deal with the ever increasing size of the Lmod DB.  I'll have to find another way to do it.

**Comment by clsgithubusr** [comment]
I have tried to run the latest version of createDB.py with python2, but I am trying the following error:
```sh
 ./createDB.py 
start
(1) create userT table
(2) create moduleT table
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delimiter $$
       create procedure CreateDataPartition (newPartValue DATETIME)' at line 1
```

Then I tried to run the script with python3, but then I received the following error:
```
./createDB.py 
  File "./createDB.py", line 129
    except  MySQLdb.Error, e:
                         ^
SyntaxError: invalid syntax

```

with which python version should I run this script?

**Comment by rtmclay** [comment]
I picked a version of the createDB.py script that I thought would work but didn't test.  I have tested it now. please try Lmod 8.2.3.  Thanks. Robert.

**Comment by clsgithubusr** [comment]
Ok thanks, it is working now.

I will let you know if I am having the same issue again or not in a few weeks.

Ticket can be closed now.

**Comment by rtmclay** [comment]
Thanks for the bug report! Closing now.
