### ISSUE TITLE
clearLmod on zsh

### ISSUE THREAD

**Issue by rubendibattista** [TACC/Lmod#423]
Hello, is there any reason why for `init/zsh` `clearLmod` alias is not defined?

**Comment by rtmclay** [comment]
What version of Lmod are you running?  The ```clearLmod``` command was defined in version 8.1.14 and newer.  If you are running 8.1.14 or newer then the clearLmod command should be defined in both init/bash and init/zsh.  There are old minor differences between those two files.

**Comment by rubendibattista** [comment]
I'm on `8.1.5` on my machine and I got confused. Sorry @rtmclay for bothering, I'll update lmod then! :)
