### ISSUE TITLE
Lmod chokes on large module file with long 'extensions' statement

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#428]
Lmod chokes as follows:

```
$ module load Perl/5.30.0-GCCcore-8.3.0
Lmod has detected the following error: Unable to load module because of error when evaluating modulefile:
     /tmp/eb-idlfoc6k/tmp2s1c6_jv/all/Perl/5.30.0-GCCcore-8.3.0.lua: [string "help([==[..."]:118: function or expression needs too many registers near '"Test::Simple/1.302168"'
     Please check the modulefile and especially if there is a the line number specified in the above message
While processing the following module(s):
    Module fullname            Module Filename
    ---------------            ---------------
    Perl/5.30.0-GCCcore-8.3.0  /tmp/eb-idlfoc6k/tmp2s1c6_jv/all/Perl/5.30.0-GCCcore-8.3.0.lua
```

when trying to load the module file shown in https://gist.github.com/boegel/f21fd2ffb0a33b18ba67647f1f77d0d0

The culprit seems to be the long `extensions` statement (perhaps in combination with the long `whatis` line listing the extensions as well).

If I trim `extensions` statement a bit by removing `Test::Requires/0.10` and all entries after, loading the module works fine.

In addition, if I trim down the module file by removing everything before the `if convertToCanonical...` line, then the load works fine as well.

I observed this problem with both Lmod versions 7.8.21 and 8.2.5.

I've included the output of `LMOD_IGNORE_CACHE=1 module -DD load Perl/5.30.0-GCCcore-8.3.0` in https://gist.github.com/boegel/f21fd2ffb0a33b18ba67647f1f77d0d0 as well (using Lmod 8.2.5)

**Comment by boegel** [comment]
It seems like this boils down to a fundamental limitation in Lua 5.1.

I can easily reproduce the underlying issue using `loadstring` that Lmod uses when running on top of Lua 5.1:

```
$ cat test.lua
f= io.open("/Users/kehoste/work/WIP/5.30.0-GCCcore-8.3.0.lua")
mod = f:read("*all")

foo, msg = loadstring(mod)
print(msg)

$ lua5.1 test.lua
[string "help([==[..."]:118: function or expression too complex near '"Test::Most/0.35"'
```

**Comment by boegel** [comment]
This seems to explain it:

```
Local variables and temporary values are always allocated into registers. Each func-tion may allocate up to 250 registers; this limit is imposed by the format of the virtualmachine instructions which use eight bits to denote a register.  If the function needsmore registers (e.g., because it has too many local variables or intermediate values) thecompiler simply emits an error of “function or expression too complex”. In the very fewcases where a programmer hits this limit, it is easy to refactor the code to avoid theproblem (e.g., by creating limited scopes via explicit blocks or functions).
```

So, perhaps the `extensions` statement should be changed to accept a single string argument, which is then split into a list of values by Lmod for further processing?

**Comment by rtmclay** [comment]
I have created Lmod 8.2.7.  Please test it when you get the chance. You will have to change ```extensions()``` to take a single string of module extensions.

**Comment by boegel** [comment]
cc @wpoely86 ^

**Comment by boegel** [comment]
@rtmclay I can confirm that the crash is fixed with Lmod 8.2.7, after I changed the module file to supply a single string in the `extensions` statement.

I replaced:

```lua
extensions("Algorithm::Dependency/1.111", "Algorithm::Diff/1.1903", ..., "YAML::Tiny/1.73")
```

with

```lua
extensions("Algorithm::Dependency/1.111,Algorithm::Diff/1.1903,...,YAML::Tiny/1.73")
```

That resolves the `function or expression needs too many registers` issue, but there's another one...

In the output of `module avail`, there's only extension entries like `Algorithm` and `YAML`, rather than the expected full extension name `Algorithm::Dependency`, `Algorithm::Diff`, and `YAML::Tiny`:

```

----------------------- This is a list of module extensions ------------------------
                       (E)     Graph            (E)     Readonly           (E)
    API2               (E)     Grep             (E)     RecDescent         (E)
    Abstract           (E)     Grove            (E)     Recursive          (E)
    Accessor           (E)     Guard            (E)     Reduced            (E)
    Admin              (E)     HMAC             (E)     RegExp             (E)
    Algorithm          (E)     HTML             (E)     Regexp             (E)
...
```

Is `::` somehow special, and not allowed as part of a extension name?

Note that there's also an empty entry (see the first entry), even though the `extensions` statement doesn't include a leading or trailing comma...

**Comment by rtmclay** [comment]
I was going to allow comma and colon separated list.  Obviously that doesn't work.  Please test Lmod 8.2.8 when you get a chance.

**Comment by boegel** [comment]
Looks a lot better now, thanks for the quick fix!

```
$ ml --version

Modules based on Lua: Version 8.2.8  2019-12-02 08:19 -06:00
    by Robert McLay mclay@tacc.utexas.edu

$ ml av Data::

----------------------- This is a list of module extensions ------------------------
    Class::Data::Inheritable (E)     Data::OptList         (E)     Data::Types (E)
    Data::Dump               (E)     Data::Section         (E)     Data::UUID  (E)
    Data::Dumper::Concise    (E)     Data::Section::Simple (E)
    Data::Grove              (E)     Data::Stag            (E)
```
