### ISSUE TITLE
ReadTheDocs with older versions

### ISSUE THREAD

**Issue by gdevenyi** [TACC/Lmod#432]
The newest version of lmod packaged in Ubuntu is 6.6: https://packages.ubuntu.com/search?keywords=lmod&searchon=names&suite=all&section=all

Is there a way to access documentation corresponding to that version?

**Comment by rtmclay** [comment]
Thanks for the question.  I have updated my readthedocs setup so that the documentation for Lmod 6.6 is now available. The 6.6 documentation is available at lmod.readthedocs.io and use the pull down menu to switch to version 6.6.

**Comment by gdevenyi** [comment]
Thanks very much!
