### ISSUE TITLE
Lmod activation is failing on Ubuntu 18 LTS, Zsh, domain user

### ISSUE THREAD

**Issue by mjsteinbaugh** [TACC/Lmod#434]
Hi, I seem to have hit a weird shell configuration issue where Lmod isn't loading up correctly at login. I'm currently seeing this only on an AWS VM running Ubuntu 18 LTS, for a domain user account running Zsh. If I switch back over to Bash, Lmod loads up as expected. I'm not seeing this issue on a different VM running RHEL 7, Zsh, with a domain user.

Here's my current Lmod config:

```
LMOD_CMD=/n/app/lmod/apps/lmod/lmod/libexec/lmod
LMOD_DIR=/n/app/lmod/apps/lmod/lmod/libexec
LMOD_PKG=/n/app/lmod/apps/lmod/lmod
LMOD_ROOT=/n/app/lmod/apps/lmod
LMOD_SETTARG_FULL_SUPPORT=no
LMOD_VERSION=8.2
LMOD_sys=Linux
```

If helpful, here's the script I ran to install:
https://github.com/acidgenomics/koopa/blob/master/os/linux/sbin/install-lmod

And `/etc/profile.d` looks good as far as I can tell, with z00_lmod.csh, z00_lmod.sh.

**Comment by mjsteinbaugh** [comment]
For reference, if I run `source /etc/profile.d/z00_lmod.sh` inside an interactive shell on the Zsh config in question, then Lmod activates as expected. So there's something going on with `/etc/profile.d` not behaving the same way on Debian/Ubuntu as it is on Fedora/RHEL.

**Comment by mjsteinbaugh** [comment]
This inelegant hot fix works, but I'm wondering how I can avoid something like this:

```sh
if [ -z "${LMOD_ROOT:-}" ] && [ -f "/etc/profile.d/z00_lmod.sh" ]
then
    # shellcheck disable=SC1091
    . "/etc/profile.d/z00_lmod.sh"
fi
```

**Comment by rtmclay** [comment]
Looking at a linux computer running Ubuntu 18.04 LTS for the zsh startup files, I see that the zsh startup files DO NOT source files in /etc/profile.d/*.sh.  So you'll have to modify either your personal ~/.zshenv or ~/.zshrc files to source /etc/profile.d/z00_lmod.sh or modify /etc/zsh/zshenv on the Ubuntu box to force it to source files in /etc/profile.d.  I suspect that the Fedora/RHEL zsh startup files  are sourcing files from /etc/profile.d. 

You can look at /etc/zsh/zshenv or /etc/zshenv  to see what they do in Fedora/RHEL.  

If I where you, I would have my ~/.zshenv file contain the following:

```
      whence -vf module > /dev/null 2>&1
      if [ "$?" -ne 0 ]; then
         . /etc/profile.d/z00_lmod.sh
     fi
```
That way you will only source the lmod initialization file when necessary.

**Comment by mjsteinbaugh** [comment]
@rtmclay Comparing with the RHEL machine, I think you're correct. Thanks for the tip!

**Comment by mjsteinbaugh** [comment]
Following up, here are some relevant files:

RHEL 7 `/etc/zprofile`

```
_src_etc_profile()
{
    #  Make /etc/profile happier, and have possible ~/.zshenv options like
    # NOMATCH ignored.
    #
    emulate -L ksh

    # source profile
    if [ -f /etc/profile ]; then
            source /etc/profile
    fi
}
_src_etc_profile

unset -f _src_etc_profile
```
