### ISSUE TITLE
version alias not found if default file exists

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#436]
In short:

- `LMOD_IGNORE_CACHE=1 LMOD_EXTENDED_DEFAULT=no` is set
- There is a /sw/modules/ml/lang/Java/.modulerc.lua with `module_version("Java/1.8_191-b26-OpenJDK", "1.8")`
- There is a `/sw/modules/ml/lang/Java/1.8_191-b26-OpenJDK.lua`
- `/sw/modules/ml/lang` is in MODULEPATH
- `module show Java/1.8_191-b26-OpenJDK` shows the module
- `module show Java/1.8` does not

After some painful investigation I found that the `Java` folder contains a symlink `default` to `1.8_191-b26-OpenJDK.lua`. If I remove that, the module is found. However this obviously changes the default loaded (in this case to `Java/11.0.6-ppc64le`)

**Comment by rtmclay** [comment]
Lmod only support one way to support of setting version and defining default.  If you have both a default symlink and a .modulerc.lua file, the default symlink is used.  If you want to set a version alias and set default you need to do it both in the .modulerc.lua file and remove the default symlink.

```
module_version("Java/1.8_191-b26-OpenJDK", "1.8")
module_version("Java/1.8_191-b26-OpenJDK", "default")
```

**Comment by rtmclay** [comment]
O.K. to close this ticket?

**Comment by Flamefire** [comment]
It would be great if it would merge the configs instead as this has caused us quite a bit of trouble finding the cause. For background: We had the default file but after some updates EasyBuild installed the modulerc additionally, for the version alias not the default. So merging this would have been possible.

Maybe at least detect this case (symlink and modulerc) and show a warning?

Otherwise ok to close

**Comment by rtmclay** [comment]
How?  To whom? How often?

Lmod is not going to merge them.  What happens when there is a conflict. Who wins.  Lmod could report that are multiple files (default, .modulerc, .modulerc.lua, .version) But if it did so it would report it every time there is a "module avail" or "module load".  So all users would get the message.  Also some sites might be moving from .modulerc or .version to .modulerc.lua.  Should Lmod report those as errors?

**Comment by Flamefire** [comment]
Good question.

I'd probably make it a hard error when there is either a conflicting setting or even there are multiple possible files to choose from. E.g. in our case a hard error "found default file and modulerc.lua" would have been better. An admin can delete or merge those once any users runs into this. But so there was a silent bug

**Comment by rtmclay** [comment]
Please test the tool "check_module_tree_syntax" found in Lmod 8.4.3 to find these kind of errors where there are more than one marked default like you had for Java.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by Flamefire** [comment]
It's an extra tool to run but ok I guess.
