### ISSUE TITLE
sh_to_modulefile: nesting of [[...]] is deprecated

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#438]
Hi!

I'm bot sure where it's coming from, but I'm getting an error when trying to use the `sh_to_modulefile` script, on any kind of script.

For instance, with that really basic `test.sh` test script:
```
$ cat ./test.sh
#!/bin/bash
export FOO=bar
```
here's the output of `sh_to_modulefile`:
```
$ /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile ./test.sh
/bin/lua: /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile:512: [string "envT = {..."]:8: nesting of [[...]] is deprecated near '['
stack traceback:
        [C]: in function 'assert'
        /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile:512: in function 'main'
        /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile:602: in main chunk
        [C]: ?
```
This is with Lua 5.1.4:
```
$ lua -v
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
```
For everything else, Lmod works perfectly fine.

Any idea where that problem could be coming from?
Thanks!

**Comment by rtmclay** [comment]
I ran your test case and it worked just fine for me.  The way that ```sh_to_modulefile``` works is that it compares the state of your environment before and after the shell script is run.  So I think that there is some string in your environment that has '[['  or something else in it which Lua is tripping over. 

Can you send me via email a copy of "env > env.log"?

**Comment by kcgthb** [comment]
Hi Robert, 

Thanks for the pointer, and that's spot on, indeed! I do have bash functions defined that use tests in the form of `if [[ condition ]]; then action`. And the double-bracket likely causes the parsing problem.

If I `unset` those functions, `sh_to_modulefile` works without any problem.

### Reproducer
* without any exported function using `[[` in the environment:
```
$ /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile test.sh
setenv("FOO","bar")
```
* when defining and exporting such a function:
```
$  test_func() {
> if [[ -z "$1" ]]; then
>   echo "$1"
> else
>   echo "n/a"
> fi
> }
$ export -f test_func
$ /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile test.sh
/bin/lua: /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile:512: [string "envT = {..."]:56: nesting of [[...]] is deprecated near '['
stack traceback:
        [C]: in function 'assert'
        /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile:512: in function 'main'
        /share/software/user/open/lmod/8.3.1/libexec/sh_to_modulefile:602: in main chunk
        [C]: ?
```

**Comment by rtmclay** [comment]
Thanks very much for the bug report!. I was able to reproduce the problem and show the problem with the '[['.  I have uploaded Lmod 8.3.4 which fixes the problem for me.  Please test this version when you get the chance.

**Comment by kcgthb** [comment]
Version 8.3.4 fixes the problem in my case too, thank you!
