### ISSUE TITLE
module update is has not desired effect

### ISSUE THREAD

**Issue by mand35** [TACC/Lmod#439]
I have a metamodule, which depends on the present node architecture. When using slurm my environment gets inherited to the new node. I tried to update the modules, thus the paths get adapted, without success. `module update` and `module refresh` have no effect. If I call a `module load MyModule` the paths get updates. 
The test case: 
#### the module file:
cat test.lua
local test = subprocess("date +%H%M%S")
setenv('LMOD_TEST', test)
#### the test and output:
module load test
$ echo $LMOD_TEST
134925
$ module load test
$ echo $LMOD_TEST
134941                                                         # module load reloads module as expected
$ module update
$ echo $LMOD_TEST
134941                                                         # no change using module update
$ module refresh
$ echo $LMOD_TEST
134941                                                         # no change using module refresh
$ lmod --version

Modules based on Lua: Version 7.7.14  2017-11-16 16:23 -07:00
    by Robert McLay mclay@tacc.utexas.edu

**Comment by rtmclay** [comment]
Thanks for the bug report!.  I have updated Lmod so that a "module update" will reload all the currently loaded modules.  Please test Lmod 8.3.4 when you get a chance to see if it works for you.

**Comment by rtmclay** [comment]
O.K. to close this ticket?
