### ISSUE TITLE
Cannot unuse module path with symbolic link

### ISSUE THREAD

**Issue by ocaisa** [TACC/Lmod#44]
Hi Robert,

I wish to use a symbolic link to redirect to an installation space for my modules. Lmod resolves the link for the ```module use``` statement but this is not directly reversible by the ```module unuse``` statement
```
-bash-4.1$ module --version

Modules based on Lua: Version 5.8  2014-11-04 12:46
    by Robert McLay mclay@tacc.utexas.edu

-bash-4.1$ ls -l /usr/local/software/juropatest/modules
lrwxrwxrwx 1 ocaisa software 14 29. Okt 13:39 /usr/local/software/juropatest/modules -> Stage1/modules
-bash-4.1$ echo $MODULEPATH

-bash-4.1$ module use /usr/local/software/juropatest/modules/all/Compiler
-bash-4.1$ echo $MODULEPATH
/usr/local/software/juropatest/Stage1/modules/all/Compiler
-bash-4.1$ module unuse /usr/local/software/juropatest/modules/all/Compiler
-bash-4.1$ echo $MODULEPATH
/usr/local/software/juropatest/Stage1/modules/all/Compiler
-bash-4.1$ 
```

Is this by design? Should I just use hard links?

Thanks,

Alan

**Comment by rtmclay** [comment]
Thanks for this bug report! I have been able to reproduce the problem and I have fixed this in HEAD.  Lmod will still convert the symlinks to absolute paths.  But you will be able to do 

     $ module use symlink_dir
     $ module unuse symlink_dir

Thanks again,

R.
