### ISSUE TITLE
load_any?

### ISSUE THREAD

**Issue by samcmill** [TACC/Lmod#444]
Is there a `prereq_any()` equivalent that loads modules, e.g., `load_any()`?  I looked through the documentation and didn't find anything that matched.  

I'd like to write a module file that works on multiple systems, where a dependency is `Foo` in some cases and `foo` in other cases.  I'd like to do something like `load_any("Foo", "foo")` to load the first successful match.  The proposed semantic would be to try to load a module going left to right, stopping if successful, and erroring if none of the modules could be loaded.

`try_load("Foo", "foo")` is close, but its semantics would load both if both are present, and not fail if neither are found.  

I can create my own using `isloaded()` + `try_load`, but it's not very elegant.

**Comment by rtmclay** [comment]
I have add the function load_any() to Lmod 8.3.7.  Before this version you will have to use try_load() and isloaded() to emulate the same functionality.  

I have also added new functions isDefined() and isNotDefined() to be able to tell if a function is defined or not.  Unfortunately, I have added these functions for this version and not a long time ago, so you won't be able to use  the function isDefined("load_any") to decide if you need to provide your own load_any() function.

Please test Lmod 8.3.7 to see if it works for you.

**Comment by samcmill** [comment]
Looks good to me!

One note that might be appropriate for the documentation, on unload all the modules listed in `load_any()` will be unloaded, not just the first one.
