### ISSUE TITLE
version-alias in subfolder behaves differently to EnvironmentModules

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#446]
Assume a line `module-version Java/1.8.0_181 1.8` in `Core/Java/.modulerc` and a module file `1.8.0_181` in the same folder.

With EnvironmentModules `module show Core/Java/1.8.0_181` returns the module and `module show Core/Java/1.8` does too.

With LMod (and partial matches disabled) only the former shows the module while the latter would need `module-version Core/Java/1.8.0_181 1.8`

Is this intended behavior?

**Comment by Flamefire** [comment]
FWIW: The (very old) EnvironmentModulesTcl does the same as Lmod (does not find the short module-version)

**Comment by rtmclay** [comment]
From Lmod point of view the full name of the module is Core/Java/1.8.  Lmod doesn't complain if the alias is not used.  You could have put ```module-version Cafe/1.8.0_181 1.8```

If you want something that will work with Lmod or Tmod or Tmod4 you can use 

```
#%Module
module-version /1.8.0_181 1.8
```

**Comment by Flamefire** [comment]
Ok, so that is intended behavior. Just wanted to make sure, thanks!
