### ISSUE TITLE
module avail shows broken aliases

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#447]
When having something like `module-alias Java/NonExist non_existant/1` in a modulerc then `module avail Java/NonExist` will list that even though it cannot be loaded

This is at least inconsistent with `module show` which shows nothing in that case.

**Comment by rtmclay** [comment]
Please see that Lmod version 8.4.5 now reports that a global alias will not resolve:

```
Global Aliases
   a13 -> (N/A)    z23 -> (N/A)
ProjectDIR/rt/modulerc/mf4
   a/1.0        a/3.0              mpich/3.1.2      mpich/3.2 (D)
   a/2.0 (D)    mpich/3.1.2-dbg    mpich/3.2-dbg
  Where:
   D:    Default Module
   N/A:  Alias cannot be loaded with current $MODULEPATH
```

**Comment by rtmclay** [comment]
O.K. to close this issue?
