### ISSUE TITLE
findExec in init/profile broken for ksh

### ISSUE THREAD

**Issue by xavierabellan** [TACC/Lmod#448]
The newly introduced findExec function in the init/profile works well for bash shells, but doesn't behave properly for ksh and shows errors such as shown below when sourced:

`/etc/profile[119]: .[368]: .[402]: .[460]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[461]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[462]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[463]: eval[1]: =: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[460]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[461]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[462]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[463]: eval[1]: =: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[460]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[461]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[462]: local: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[463]: eval[1]: =: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[479]: -p: not found [No such file or directory]
/etc/profile[119]: .[368]: .[402]: .[480]: : cannot execute [Is a directory]`

**Comment by rtmclay** [comment]
I have removed the "local" keyword from the findExec() shell function. This fixes the problem in my tests. Please try version 8.3.9 to see if it works for you.

As a side note. I have limited knowledge of ksh.  How do you use it?  Is it setup just for your personal use or is there some system way of doing it?

**Comment by xavierabellan** [comment]
Hi Robert, Many thanks for the quick fix! Indeed I can confirm it seems to work well on our system. 
Just to give you a bit more context, ksh is not a personal choice of my own setup. For historical reasons, at ECMWF many of our users have ksh as their login shell. Although many have moved to bash, we still have a considerable number of users and workflows on ksh. That is why for us it is very important that both bash and ksh are well supported by the modules implementation.

**Comment by rtmclay** [comment]
Looking at the way that ksh does its startup, it is clear that it uses /etc/profile to start a login shell. Which means it can use the same setup as bash.  However, in my tests, if a ksh user starts a ksh sub-shell, the module command is undefined. For example here is a login ksh where the module command works but the module command doesn't in a sub-shell:

```
~ [9]$ module -v
Modules based on Lua: Version 8.3.9  2020-05-05 12:39 -05:00
    by Robert McLay mclay@tacc.utexas.edu
~ [10]$ ksh
~ [11]$ module -v
ksh: module: not found [No such file or directory]
```
Do you do something special in this case to handle sub-shells or other interactive shells?

**Comment by xavierabellan** [comment]
Hi Robert,

What we are doing now get this to work is to follow the same approach as Tmod for Korn shell: the FPATH environment variable. It would probably be a good idea to integrate this strategy into the distribution itself, so others may benefit.

Here is what we do in case you want to take it on board:
- We have a directory called /path/to/ksh_functions containing 3 files:
`$ ls -1 ksh_functions/`
`clearMT`
`ml`
`module`
- Each of those is named like the corresponding function, and contains the function definition itself. For example:
`$ cat ksh_functions/module`
`module()`
`{`
`  eval $LMOD_CMD sh "$@"`
`}`
- Then, in the init scripts for ALL shells we export the variable FPATH adding the /path/to/ksh_functions. For example, for bash or ksh itself, it would be:
`export FPATH=/path/to/ksh_functions:$FPATH`

This way, it doesn't matter what shell you are in, if you run a ksh script or start an non-login interactive ksh everything works as you would expect. I guess you could ship that directory within Lmod itself, and add that FPATH definition to the Lmod startup.

I believe that is the only "hack" we had to implement on our side to make ksh behave, but I'm happy to give more feedback on ksh support (or any other issue) if we find any in the future. 

Xavi

**Comment by rtmclay** [comment]
Thanks very much for explaining how sub-shells in ksh work. Based on your explanation, I have created version 8.3.10 which has ksh support including sub-shells.  I have tested it with a test ksh user account.  If you get the chance, please test Lmod 8.3.10 to see if it works for your ksh users. 

Lmod now sets FPATH for sh, bash, tcsh/csh but not fish or zsh.  I suspect that the fish shell users do not need to run ksh scripts that depend on modules and I do not understand fish well enough.

Zsh also uses FPATH to look for tab completions functions so I have not changed FPATH to include the ksh functions.  AFAIK, this will only affect zsh users running ksh scripts that need module commands.

Thanks again for the clear explanation.

**Comment by xavierabellan** [comment]
I just removed our hack and tried with 8.3.10, and it all looks good! At least for our use cases (bash/ksh) I could not find any issue. Bash users can run bash/ksh subshells and commands ok, and same applies for ksh users now. 
Thanks for the quick fixes!

**Comment by rtmclay** [comment]
You are welcome.  I'm closing this ticket.

**Comment by rtmclay** [comment]
I ran into a problem with ksh and FPATH and zsh. FPATH is used differently in zsh from ksh. It is a local variable that is defined by zsh on every shell as long as it is not an exported variable.  It is also a problem for local installs since bash reads the startup scripts then zsh reads the startup scripts after which defines and exports FPATH before zsh starts. 

My solution for Lmod 8.3.11 is only prepend to FPATH for bash and ksh users if $SSH_CLIENT is defined. I think that this will work in your case as well.  I have also defined the module command in a place where ksh will look.  However I am not exporting FPATH for zsh.  Zsh users who wish to run ksh scripts that use module commands will have to export FPATH first. Lmod isn't going to do that because I don't want to mess with zsh users who most likely don't need to run ksh scripts.

I have updated the documentation for Ksh and Zsh users.  If you get a chance please test Lmod 8.3.11.  Thanks

**Comment by xavierabellan** [comment]
I just tried and it all mostly works except on one edge case. When submitting a SLURM batch job, which is ksh, from a bash shell and with no export of the original environment, it does not work. In that case, when the job starts, the environment for the job is pre-populated from a fresh source of the profile of the user's login shell. FPATH is not defined because it's bash and SSH_CLIENT variable is of course not set.
I am aware this is a very specific corner case, so I'd be happy to live with the current implementation.  We can have something on our system setup to work around this defining the FPATH when it is not defined by lmod, as we don't use zsh.

**Comment by rtmclay** [comment]
Obviously, failing to work with SLURM is bad for most HPC sites.  I was trying to avoid having a configure option but it looks like I need one.  Lmod 8.3.12 has a "--with-supportKsh=yes" configure option which will turn on the setting of FPATH for bash, sh, t/csh and ksh but not zsh. 

Please test Lmod 8.3.12.  I think that this will be it.  Thanks!

**Comment by xavierabellan** [comment]
I can confirm this solution works for us with no workarounds needed on our side. By the way, if we ever find any other issue in the future, I'd be happy to install from a git branch/tag so you don't need to do a full release to test something out.

Thanks for all the work!
