### ISSUE TITLE
module use 100K files behavior

### ISSUE THREAD

**Issue by ahkumar** [TACC/Lmod#449]
Dear Lmod,

We have some users using "module use /path/dir" to point to directory to find the module files. And apparently this folder has over 100K files which are not module file. I understand this is not a great way to initialize but any thought on how to selectively point to module use /path/to/module.lua file, and then load modules. User is on fly creating a job submit directory and generating custom modules files for use. Any thoughts here will be a great help. 

Regards,
Amit

**Comment by rtmclay** [comment]
The user will have to create /path/to/dir/modulefiles/module.lua.  And then do "module use /path/to/dir/modulefiles instead.

**Comment by rtmclay** [comment]
It has been a week.  I'm closing this ticket.
