### ISSUE TITLE
Allow module load foo/default to load the default version

### ISSUE THREAD

**Issue by xavierabellan** [TACC/Lmod#450]
It would be very nice to be able to load the default version of a module with the "default" label ,just like any other label you may have in the corresponding modulerc files. This works in Tmod, and actually makes it very convenient to parametrise the version to load of a given module in scripts.

With the current implementation in Lmod, the user needs to have a not very elegant `if` statement along these lines for a script to be compatible with both Tmod and Lmod implementations:

```
if [[ "$my_version" == "default" ]]; then
    module load foo
else
    module load foo/$my_version
fi
```

**Comment by rtmclay** [comment]
Well, Tmod 4.5.0 does not support ```module load foo/default```.  But I have made Lmod 8.3.13 support this.  Essential Lmod removes "/default" from any module name and then loads "foo".  It is as if it was never there at all. 

Please test Lmod 8.3.13 to see if it works for you.

**Comment by xavierabellan** [comment]
Wow that was quick! Indeed it seems to work well. Thanks!

P.S. Just as a quick note, when I said Tmod I was referring to the ancient 3.2.10 version we still have on our Cray. I should have been more specific there. I haven't had the opportunity tor try on the newer 4.X as we don't have that version installed anywhere...

**Comment by rtmclay** [comment]
I'm glad that it works for you.  I am closing this ticket.
