### ISSUE TITLE
Software Module Hierarchy and Personal Modulefiles

### ISSUE THREAD

**Issue by omor1** [TACC/Lmod#451]
I'm trying to set up some personal modulefiles so that they can be swapped out via the hierarchy mechanism. That is, in addition to:
```
/opt/apps/modulefiles
/opt/apps/intel18/modulefiles
/opt/apps/intel18/impi18_0/modulefiles
```
I can have:
```
~/modules/modulefiles
~/modules/intel18/modulefiles
```
And similarly for other compilers:
```
/opt/apps/gcc7_1/modulefiles
/opt/apps/gcc7_1/impi18_0/modulefiles
~/modules/gcc7_1/modulefiles
```

Now, the software module hierarchy mechanism works by having the module that others are dependent on add directories to the `MODULEPATH`. I can't very well modify the system compiler modules, but my thought was that I could perhaps shadow them, have the new replacement load the original, and then add my _own_ directories to the `MODULEPATH`. I can't seem to get this to work, however: Lmod either always chooses the system module or loads mine, but doesn't subsequently load the system module. This is probably due to issues with identically named and versioned modules.

Is there some other mechanism by which I can get this to work? Or is what I want currently not possible in Lmod? In particular, I'd like `module swap intel gcc` to unload the personal modules compiled with the Intel compiler and load in the corresponding versions compiled with GCC.

**Comment by rtmclay** [comment]
Lmod uses a function called ```inherit()``` to help with this issue. Please read some new documentation that I wrote to explain how to do what you want to do.  See https://lmod.readthedocs.io/en/latest/340_inherit.html for details.

**Comment by omor1** [comment]
This is promising, but I'm still having trouble getting Lmod to actually load my inherited module rather than the system one (`~` representing my home directory rather than a literal tilde):

```
$ module purge
$ echo $MODULEPATH
~/modules/modulefiles:/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
$ module --trace load intel/18.0.2
Lmod version: 8.3.6  2020-03-15 20:41 -05:00
running: module -T load intel/18.0.2
  (1)(0)Loading: intel/18.0.2 (fn: /opt/apps/modulefiles/intel/18.0.2.lua, using Find-Best)
    Prepending: /opt/apps/intel18/modulefiles to MODULEPATH
  reloadAll(1)(intel/18.0.2)
$ echo $MODULEPATH
/opt/apps/intel18/modulefiles:~/modules/modulefiles:/opt/apps/xsede/modulefiles:/opt/apps/modulefiles:/opt/modulefiles
$ cat ~/modules/modulefiles/intel/18.0.2.lua
inherit()
local home = os.getenv("HOME")
local path = pathJoin(home, "modules", "intel18", "modulefiles")
prepend_path("MODULEPATH", path);
```

**Comment by omor1** [comment]
Could this be down to some subtle difference in C/N/V versus N/V handling? Most of the examples seem to use C/N/V, but I'm matching the style on the system, which is N/V.

**Comment by omor1** [comment]
Regarding documentation, I'd only add that `inherit` should probably be added to the "Lua Modulefile Functions" section.

**Comment by rtmclay** [comment]
I'm not following your question.  My Examples are N/V.  You should do;
```
module use ~/my_modules/Core
```

**Comment by omor1** [comment]
I think you've misunderstood.
I _do_ have `module use "${HOME}/modules/modulefiles"` in my `~/.bashrc`, hence why the directory is in the `MODULEPATH` variable. However, when I go to load the inherited modulefile by `module load intel/18.0.2`, it _ignores_ the one in `~/modules/modulefiles/intel/18.0.2.lua` and instead uses the system one in `/opt/apps/modulefiles/intel/18.0.2.lua`. This is shown by using the `-T` (`--trace`) option and by the simple fact that `~/modules/intel18/modulefiles` is not prepended to `MODULEPATH`.

**Comment by rtmclay** [comment]
Right.  There is one subtle issue.  That is the issue of defaults.  Marked defaults win over order.  You need to mark the intel/18.0.2.lua module as a default:
```
$ cd ~modules/modulefiles/intel/; ln -s 18.0.2.lua default
```
You can see this with "module avail". Without the above command you'll see which modulefile is the default.

I have updated the documentation and updated a fully worked example in the source code.  This issue about defaults is discussed in the updated documentation.

**Comment by omor1** [comment]
Hmm, so Lmod prefers a module marked as default over an identically named and versioned module earlier in the path, unless it too is marked as default (which overrides the latter default).

**Comment by omor1** [comment]
Thanks for the help and for adding documentation!
