### ISSUE TITLE
last module name in stack does not show

### ISSUE THREAD

**Issue by fizwit** [TACC/Lmod#452]
module --version
Modules based on Lua: Version 8.3.10  2020-05-07 13:25 -05:00
    by Robert McLay mclay@tacc.utexas.edu

EasyBuild version 4.1.2

Using EasyBuild to create all LMOD modules. I build a custom local version of Python with a version suffix which as additional modules request by users at our site.  Python-3.7.4-GCCcore-8.3.eb is the base module and Python-3.7.4-foss-2019b-fh1.eb is a bundle that uses the base Python as a dependency.

```
module load Python/3.7.4-foss-2019b-fh1
module
Currently Loaded Modules:
  1) GCCcore/8.3.0
  2) zlib/1.2.11-GCCcore-8.3.0
  3) binutils/2.32-GCCcore-8.3.0
  4) GCC/8.3.0
...
 95) pkg-config/0.29.2-GCCcore-8.3.0
 96) MUMmer/4.0.0beta2-foss-2019b
 97) Python/3.7.4-GCCcore-8.3.0
```

The module name "-fh1" does not display.  Since the module name is not listed after it is loaded it does no unload with a purge.

**Comment by rtmclay** [comment]
You are loading a Python module and you have one loaded at the end.  Lmod enforces the one-name rule.  That means that you can only have one Python module loaded.

**Comment by fizwit** [comment]
thanks, will create a new naming scheme for custom Python and R modules.
