### ISSUE TITLE
Add magic number at end of spider cache file.

### ISSUE THREAD

**Issue by ghuls** [TACC/Lmod#454]
Could a magic number be added at the end of the spider cache file which would be read before trying to read the rest of the spider cache file, so there is some kind of confidence that the spider cache file is completely written to disk?

On our HPC system the user HOME dir has a quota of only 3GB, and when home gets full, incomplete spider cache files can be generated, which will result in crashes like this (the tracebacks can be quite different, depending on how much of the cache file could be written):
```
/usr/bin/lua: /usr/share/lmod/lmod/libexec/Cache.lua:327: /home/user/.lmod.d/.cache/spiderT.x86_64_Linux.lua:1627: unexpected symbol near '<eof>'
stack traceback:
    [C]: in function 'assert'
    /usr/share/lmod/lmod/libexec/Cache.lua:327: in function 'l_readCacheFile'
    /usr/share/lmod/lmod/libexec/Cache.lua:436: in function 'build'
    /usr/share/lmod/lmod/libexec/ModuleA.lua:673: in function 'singleton'
    /usr/share/lmod/lmod/libexec/MName.lua:166: in function 'lazyEval'
    /usr/share/lmod/lmod/libexec/MName.lua:241: in function 'sn'
    /usr/share/lmod/lmod/libexec/Master.lua:296: in function 'load'
    /usr/share/lmod/lmod/libexec/MasterControl.lua:979: in function 'load'
    /usr/share/lmod/lmod/libexec/MasterControl.lua:955: in function 'load_usr'
    /usr/share/lmod/lmod/libexec/cmdfuncs.lua:454: in function 'cmd'
    /usr/share/lmod/lmod/libexec/lmod:497: in function 'main'
    /usr/share/lmod/lmod/libexec/lmod:554: in main chunk
    [C]: ?
```

**Comment by rtmclay** [comment]
Thanks for the bug report!  There is a better approach.  I have updated Lmod to ignore broken cache file. Please test Lmod 8.3.16 to see if solves this problem for you.
