### ISSUE TITLE
"source" in init/profile fails on some flavors of /bin/sh

### ISSUE THREAD

**Issue by atombaby** [TACC/Lmod#457]
We are running into a problem with Lmod 8.3.10 on Ubuntu 18.  When run in `/bin/sh` (as in `at` or `cron`), sourcing Lmod's profile throws an error:

```
$ . /app/lmod/lmod/init/profile
/bin/sh: 73: /app/lmod/lmod/init/profile: source: not found
```

I believe this is because Ubuntu uses dash for `/bin/sh` and is thus lacking the bash-specific `source` command used in `init/profile.in`:

```
 65   if [ -f @PKGV@/init/$my_shell ]; then
 66      source    @PKGV@/init/$my_shell >/dev/null # Module Support
 67   else
 68      source    @PKGV@/init/sh        >/dev/null # Module Support
 69   fi
```

A change to `.` for the `source` commands above should do the trick and should be supported in most (all?) shells.  I'll provide a pull request as well.

Thanks- let me know if I can be of any assistance.

**Comment by rtmclay** [comment]
This is handled by #458.  So I'm closing this issue
