### ISSUE TITLE
Lua 5.4 support

### ISSUE THREAD

**Issue by junghans** [TACC/Lmod#459]
Can you add lua-5.4 support?

Fedora has a patch for it: https://src.fedoraproject.org/rpms/Lmod/blob/master/f/Lmod-8.3.17-lua5.4.patch

**Comment by rtmclay** [comment]
I will add support for Lua 5.4.  But there is a reason for the test for Lua versions.  Does Lua 5.4 work with luaposix?

**Comment by junghans** [comment]
Fedora has a patch for that as well: https://src.fedoraproject.org/rpms/lua-posix/blob/master/f/lua-posix-helpers-5.4.patch, seems pretty trivial.

**Comment by rtmclay** [comment]
But I don't control lua-posix.  Lmod will have to wait until the developers of lua-posix upgrade to support it. In the past, he has done it pretty quickly.

**Comment by junghans** [comment]
I asked here: https://github.com/luaposix/luaposix/issues/330

**Comment by rtmclay** [comment]
Lmod  8.4 now supports Lua 5.4. Please test this new version to see if it works for you.

**Comment by opoplawski** [comment]
It appears to work in Fedora.  Thanks.
