### ISSUE TITLE
'make pre-install' recognizes cache directory option, but 'make install' does not

### ISSUE THREAD

**Issue by kmanalo** [TACC/Lmod#46]
@rtmclay I tried this on SLES11sp3 and also on a clean CentOS 7 VM; I see via 'ml --config' that number of cache dirs is zero, unless I use the 'make pre-install' option, in which case it changes to 1. 

`./configure --with-spiderCacheDir=/opt/asn/etc/modulefiles/.cache/cache --with-updateSystemFn=/opt/asn/etc/modulefiles/.cache/system.txt --prefix=/apps`

It's clear in the Makefile that the `pre-install` is listed as a dependency to `install`, but something is tracking improperly.

**Comment by rtmclay** [comment]
It is not clear to me what is going on here.  Are you doing:

  $  ./configure --with-spiderCacheDir=/opt/asn/etc/modulefiles/.cache/cache --with-updateSystemFn=/opt/asn/etc/modulefiles/.cache/system.txt --prefix=/apps
  $ make install

And it fails?

**Comment by kmanalo** [comment]
No failures, everything installs, but the cache directory is not identified:

with `make install` and subsequent `ml --config`
`number of cache dirs           0`

with `make pre-install` and subsequent `ml --config`
`number of cache dirs           0`
```
Cache Directory                        Time Stamp File
---------------                        ---------------
/opt/asn/etc/modulefiles/.cache/cache  /opt/asn/etc/modulefiles/.cache/system.txt
```

Is it supposed to work like this? Maybe I just misread something in the install document.

**Comment by rtmclay** [comment]
What version of gnu make are you using?

**Comment by kmanalo** [comment]
3.82

**Comment by rtmclay** [comment]
Thanks for the bug report! This has been repaired now in HEAD.   This is a case where I solved someones problem and caused the system cache file to be ignored.  Your version of make is not the problem.

I have updated the version for HEAD to be 5.8.2

**Comment by rtmclay** [comment]
This has been fixed.
