### ISSUE TITLE
lmod fails to find hierarchical modules if a TCL modulefile with no version appended exists

### ISSUE THREAD

**Issue by rsoome** [TACC/Lmod#460]
Hi. The bug appears in version 8.2.7 of lmod, however, I'm fairly certain that it's still present in later releases.

We have multiple modulefiles in multiple locations, some written in TCL and some in lmod:

```
[root@server ~]# module av app

---------------------------------------------------------- /software/modulefiles ----------------------------------------------------------
   app (D)    app-0.10.0    app-0115

----------------------------------------------------------/location2/software/modules/linux-centos7-x86_64/Core ----------------------------------------------------------
   app/0.11.7-eowy    app/0.11.8-ngkr    app/0.11.9-lsgn
```

When I try to load anything from `/location2/software/modules/linux-centos7-x86_64/Core` I get the following error:

```
[root@server ~]# module load app/0.11.7-eowy
/usr/bin/lua: /usr/share/lmod/lmod/libexec/LocationT.lua:216: attempt to index field 'dirT' (a nil value)
stack traceback:
        /usr/share/lmod/lmod/libexec/LocationT.lua:216: in function </usr/share/lmod/lmod/libexec/LocationT.lua:127>
        (tail call): ?
        /usr/share/lmod/lmod/libexec/MName.lua:190: in function 'lazyEval'
        /usr/share/lmod/lmod/libexec/MName.lua:241: in function 'sn'
        /usr/share/lmod/lmod/libexec/Master.lua:298: in function 'load'
        /usr/share/lmod/lmod/libexec/MasterControl.lua:1008: in function 'load'
        /usr/share/lmod/lmod/libexec/MasterControl.lua:984: in function 'load_usr'
        /usr/share/lmod/lmod/libexec/cmdfuncs.lua:459: in function 'cmd'
        /usr/share/lmod/lmod/libexec/lmod:512: in function 'main'
        /usr/share/lmod/lmod/libexec/lmod:570: in main chunk
        [C]: ?
```

However, when i rename 'app' in `/software/modulefiles` to 'app-someversion', everything works fine.

The problem appears to be in **ModuleA.lua**, when grouping into modules - if the hierarchical modulefiles are found first, they are added to table T as such: 

`T["app"] = addPV("app",v,"","")`. 

Then later on the TCL modulefiles are processed and `T["app"]` gets overwritten: 

`T["app"] = {file = v.fn, metaModuleT = metaModuleT, fileT = {}, dirT = {}, defaultT = defaultT, mpath = mpath}`. 

Wouldn't it make sense to differentiate between directories and files in table T? The following "fix" seemed to work for this particular case, however it might break something else:

In **ModuleA.lua:**

```
local function GroupIntoModules(self, level, maxdepth, mpath, dirT, T)
   if (next(dirT.fileT) ~= nil) then
      for fullName, v in pairs(dirT.fileT) do
         local defaultT = {}
         if (next(dirT.defaultT) ~= nil and (dirT.defaultT.value == fullName)) then
            defaultT = dirT.defaultT
         end
         local metaModuleT = v
         metaModuleT.pV = "~"
         metaModuleT.wV = "~"
         T[fullName] = {file = v.fn, metaModuleT = metaModuleT, fileT = {}, dirT = {}, defaultT = defaultT, mpath = mpath}
      end
   end
   for path, v in pairs(dirT.dirT) do
      local prefix = extractFullName(mpath, path)
      if (next(v.defaultT) ~= nil or next(v.dirT) == nil or level == maxdepth) then
         if (next(v.dirT) ~= nil) then
            self.__isNVV = true
------------------------- ADDED PART -------------------------
         else
            prefix = prefix.."/"   --It's a directory, add '/' to the key
----------------------------------------------------------------
         end
         T[prefix] = addPV(prefix,v,"","")
      else
         GroupIntoModules(self, level+1, maxdepth, mpath, v, T)
      end
   end
end
```

In **LocationT.lua:**

```
function M.search(self, name)
   --dbg.start{"LocationT:search(",name,")"}
   local locationT = self.__locationT

   if (next(locationT) == nil) then
      --dbg.print{"next(locationT) == nil\n"}
      --dbg.fini("LocationT:search")
      return nil, nil, nil
   end

   dbg.printT("locationT",locationT)


   -- Find sn from name by looking in locationT and if it is not there
   -- Then remove "/version" from name

   local versionStr = nil
   local sn         = name
   local v          = nil
   local idx        = nil
   while true do
------------------------- ADDED PART -------------------------
      v   = locationT[sn..'/']   --First try to find if there's a directory with the name 'sn'
      if (not v) then v   = locationT[sn] end   --If a directory with the name 'sn' is not found, try to find a file with this name.
----------------------------------------------------------------
      if (v) then break end
      idx = sn:match("^.*()/")
      if (idx == nil) then break end
      sn  = sn:sub(1,idx-1)
   end

   -- if v is nil then the name was not found so quit
   if (v == nil) then
      --dbg.fini("LocationT:search")
      return nil
   end

   if (v.dirT == nil and v.file == nil) then
      --dbg.print{"sn: ",sn,"\n"}
      --dbg.printT("locationT", locationT)
      --dbg.fini("LocationT:search")
      LmodError{msg="e_LocationT_Srch"}
      return nil
   end

   if (idx) then
      versionStr = name:sub(idx+1,-1)
------------------------- ADDED PART -------------------------
   else   --Not sure if necessary - if there is no versionStr, v can't be a directory tree.
      v = locationT[sn]
----------------------------------------------------------------
   end

   ------------------------------------------------------------
   -- collect the list of possible matches:
   ------------------------------------------------------------

   ------------------------------------------------------------
   -- Find right "v"

   idx           = 1
   local vStr    = versionStr
   local done    = (vStr == nil)
   local jdx     = idx
   local fullStr = versionStr

   while (not done) do
      idx = versionStr:find("/",jdx)
      if (idx == nil) then
         done = true
         vStr = versionStr
      else
         vStr = versionStr:sub(1,idx-1)
         jdx  = idx + 1
      end
      local key   = pathJoin(sn, vStr)
      local value = v.dirT[key]

      if (value) then
         v       = value
         if (vStr == versionStr) then
            fullStr = nil
         end
      else
         done  = true
      end
   end

   --dbg.print{"sn:",sn,", versionStr: ",versionStr,", fullStr: ",fullStr,"\n"}
   --dbg.printT("v",v)

   local fileA = {}
   fileA[1]    = {}
   local extended_default = cosmic:value("LMOD_EXTENDED_DEFAULT")
   collectFileA(sn, fullStr, extended_default, v, fileA[1])
   --dbg.fini("LocationT:search")
   return sn, versionStr, fileA
end
```

**Comment by rtmclay** [comment]
You are the first group that has asked for a meta module and regular module be combined.  The app module file has no version.  Then you have app/version in a different location in the module tree.  I don't know what that means.  That has to be decided first.  What are the rules?

What does it mean if the app meta module is first before app/version.  What does it mean if app/version is before app meta module?

Suppose app and app/1.0 exist in that order?  What does "module load app" mean?  

What if they are reversed? Say app/1.0 followed by app?  What does "module load app" mean?

Why have an "app" meta module and an app/version on the same system?  What are you trying to say?  You only get one "app" module.

To me a meta module app is probably the same as "app/99999999" that is the app meta module is the highest version possible.

**Comment by rsoome** [comment]
Hello. My initial report may have been too vague, sorry for that.

In our case the 'app' modulefile was not a meta module - it was just the first built version of 'app' without the version number in the name of the modulefile - probably bad practice but it was already implemented like this when I landed on the problem.

I am not necessarily asking for such combination to work - it's just that debugging this problem was fairly time consuming. So explicitly disallowing such practice  or giving a little more meaningful error message than `attempt to index field 'dirT' (a nil value)` would suffice.

**Comment by rtmclay** [comment]
While your setup of having a module (app) with and without versions is unusual, I can see that it can happen just as you said.  An old app that has no version now has versions at a later date.  This is a case that I had not considered so Lmod produced an unhelpful error message.

I have reworked how Lmod handles this case.  The rule is that a module without a version is the "highest" version.  So if app, app/1.0 and app/2.0 exist then:

```
$ module load app  -> loads app
$ module load app/1.0 -> loads app/1.0
```

The important thing is that the format of module spider cache has changed slightly to support this change.  You or anybody else has a module like app and app/1.0 need to remake the spider caches.  Nobody else has to update their spiderT.lua files.

Please test Lmod 8.4.1 to see if it fixes the problem for you.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by rsoome** [comment]
Hi. I haven't gotten around to test the new version yet. I'll let you know ASAP.

**Comment by rtmclay** [comment]
I am closing this issue.  If there is still an issue, feel free to re-open.
