### ISSUE TITLE
Installing Lmod 8.4 on Ubuntu 18.04 and 20.04

### ISSUE THREAD

**Issue by justbennet** [TACC/Lmod#461]
I was having trouble getting Lmod 8.4 installed on Ubuntu 18.04.  The list on lmod.readthedocs.io seems outdated for 18.04 and 20.04.  The commands I used to install the Lua and TCL prerequisites were

```
$ sudo apt-get install lua5.3 liblua5.3-0 liblua5.3-dev \
    lua-filesystem-dev lua-posix-dev
$ sudo apt-get install tcl tcl8.6-dev libtcl8.6
```

After including dependencies for the packages listed, this was what got installed according to `dpkg -l`.

```
lua5.3
lua-bit32:amd64
lua-filesystem:amd64
lua-filesystem-dev:amd64
lua-posix:amd64
lua-posix-dev
liblua5.3-0:amd64
liblua5.3-dev:amd64

tcl
tcl8.6
tcl8.6-dev:amd64
libtcl8.6:amd64
```

For Ubuntu 18.04, the Lua 5.3 installation is incomplete, as there was no `/usr/bin/lua`, so I chose to use `update-alternatives` to finish the Lua 5.3 installation.  There was also no `posix.so` for Lua (this is a problem with other versions, as well), so I had to create a symlink for it.

```
sudo update-alternatives --install /usr/bin/lua \
    lua-interpreter /usr/bin/lua5.3 130 \
    --slave /usr/share/man/man1/lua.1.gz lua-manual \
    /usr/share/man/man1/lua5.3.1.gz
sudo update-alternatives --install /usr/bin/luac \
    lua-compiler /usr/bin/luac5.3 130 \
    --slave /usr/share/man/man1/luac.1.gz lua-compiler-manual \
    /usr/share/man/man1/luac5.3.1.gz
sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.3-posix.so \
    /usr/lib/x86_64-linux-gnu/lua/5.3/posix.so
```

The TCL installation puts `tcl.h` into `/usr/include/tcl8.6`, and the Lmod configure script does not find it there.  I created a symlink for generic `/usr/include/tcl` with

```
$ sudo ln -s /usr/include/tcl8.6 /usr/include/tcl
```

Once those steps were complete, running

```
$ ./configure --prefix=/opt/bionic
$ sudo make install
$ source /opt/bionic/lmod/lmod/init/profile
$ module --version

Modules based on Lua: Version 8.4  2020-07-31 12:25 -05:00
    by Robert McLay mclay@tacc.utexas.edu
```

Since Ubuntu 20.04 is visible on my horizon, I thought I should try that, too.  The problems with Lua were absent, but

```
$ sudo ln -s /usr/include/tcl8.6 /usr/include/tcl
```
was still necessary.

I don't know whether this would be fully appropriate in a PR to the documentation.  Perhaps if the Ubuntu installation were put on a separate page?  It seems a long digression for someone installing on CentOS to slog through, but useful enough from someone trying to get things to work on recent Ubuntus.

In any event, I put it here as it seems to be an issue, and perhaps someone will find this useful.

**Comment by steverweber** [comment]
Not sure it's any help but I use the following for ubuntu 18.04 and 20.04 this morning.

```
VER=8.4.2
ITERATION=0
INSTALL_PATH=/opt/lmod/stable
MODULEFILES_PATH=/opt/uw/modulefiles

apt update
apt install -y git wget sed tclsh tcl-dev libreadline-dev

#** ensure packages
test -f lua-5.4.0.tar.gz || wget http://www.lua.org/ftp/lua-5.4.0.tar.gz
tar zxf lua-5.4.0.tar.gz -C ~
test -f luarocks-3.3.1.tar.gz || wget https://luarocks.org/releases/luarocks-3.3.1.tar.gz
tar zxpf luarocks-3.3.1.tar.gz -C ~

#** build lua
cd ~/lua-5.4.0
sed -i "s|/usr/local|$INSTALL_PATH/lua|" ./Makefile
sed -i "s|/usr/local/|$INSTALL_PATH/lua/|" ./src/luaconf.h
make linux
make install

#** build luarocks
cd ~/luarocks-3.3.1
./configure --prefix=$INSTALL_PATH/lua/  --with-lua=$INSTALL_PATH/lua
make install

#** build lmod lua requirements
$INSTALL_PATH/lua/bin/luarocks install luaposix
$INSTALL_PATH/lua/bin/luarocks install luajson
$INSTALL_PATH/lua/bin/luarocks install luafilesystem

#** build lmod
cd ~
git clone https://github.com/TACC/Lmod.git
cd ~/Lmod
git checkout $VER
export PATH=$INSTALL_PATH/lua/bin:$PATH

./configure --prefix=$INSTALL_PATH --with-siteControlPrefix=yes --with-useBuiltinPkgs=yes
make install

mkdir -p "$MODULEFILES_PATH"
cat > $INSTALL_PATH/init/.modulespath <<EOF
$MODULEFILES_PATH
EOF
ln -s $INSTALL_PATH/init/profile /etc/profile.d/lmod.sh
ln -s $INSTALL_PATH/init/cshrc   /etc/profile.d/lmod.csh
```

**Comment by rtmclay** [comment]
I have updated the documentation to describe how to install Lua and lua-posix on Ubuntu 18.04 and 20.04. It turns out that the symlink between /usr/include/tcl -> /usr/include/tcl8.6 is provided by the tcl-dev package.  This simplifies the discussion.
Please look over the updated documentation if you get the chance.

**Comment by justbennet** [comment]
That looks good, Robert.  Thank you for taking the time to update the docs!
