### ISSUE TITLE
module load resolver when there's a postfix.

### ISSUE THREAD

**Issue by steverweber** [TACC/Lmod#462]
Modules based on Lua: Version 8.4.1  2020-08-12 15:27 -05:00

Would a patch to `parseVersion.lua` that basically treats a `-` dash as if it were a `.` dot be accepted? I don't mind hiding the option under an ENV var.

The Issue I'm trying to solve is that many of our modules have a postfix.
They are done this way because our packages are named like that.

When writing scripts It would be ideal if `module load r/4.0.2` would find 4.0.2-ivybridge vs an error.

```
module av
   r/4.0.2-ivybridge

root@jupyter:~/Lmod# module load r/4.0.2
Lmod has detected the following error:  The following module(s) are unknown: "r/4.0.2"
```

One workaround is rename modules with a dot `4.0.2.ivybridge` This works but too disruptive. In my case it's more simple to patch `parseVersion.lua` and package up lmod and send to all the servers.

```
root@jupyter-t02:/home/s8weber# module av
------------------------------------------------------------------------------------------------------------
   anaconda/3.2020.02    julia/1.4.2    r/4.0.2.hacksaw    r/4.0.2.ivybridge (D)    sagemath/9.1
```

**Comment by steverweber** [comment]
oops seems that `parseVersion.lua` is not the place to start.

**Comment by rtmclay** [comment]
The place that I had to change was src/collectFileA.lua.  This change will allow you to match r/4.0.2 to match r/4.0.2-something.  Note that if you have more than one of these then the "highest" will match.  So:
```
    r/4.0.2-aa   r/4.0.2-ivy   r/4.0.2-zz
```

Then Lmod will pick r/4.0.2-zz  unless one of these is a marked default.  Note that with Lmod 8.4.2 you can now do "module load r/4.0.2-a" and it will find "r/4.0.2-aa"

Please test Lmod 8.4.2 to see if it fixes your issue.

**Comment by steverweber** [comment]
Confirmed worked as expected!

Thanks for the quick and excellent work.
