### ISSUE TITLE
Hidden modules not found with version 8.4.5

### ISSUE THREAD

**Issue by stierhofj** [TACC/Lmod#467]
We encountered a problem where hidden modules are no longer found with the recent version. We used version 8.3.8 before without changing any of the setup. After the upgrade to 8.4.5 hidden modules where reported as not existent although nothing has changed here.

Version 8.4 works as expected, version 8.4.1 (and possible all from here) reports them as non-existent. The modules are hidden due to leading period in their definition files.

The modules are found, however, when listing the available modules:
```
$ module --show-hidden avail

----------------------------------------- /software/Core ------------------------------------------
   .system (H,S)    lmod
```
But loading does not work
```
$ module load .system
Lmod has detected the following error:  The following module(s) are unknown: ".system"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load ".system"

Also make sure that all modulefiles written in TCL start with the string #%Module
```

**Comment by rtmclay** [comment]
Please report your configuration with "module --config"

**Comment by stierhofj** [comment]
Here is the configuration for v8.4.5.
The file for v8.4 is exactly the same (besides versions)
[v8.4.5.txt](https://github.com/TACC/Lmod/files/5285409/v8.4.5.txt)

**Comment by rtmclay** [comment]
Thanks for the bug report!  A hidden meta module is a case I didn't have in my test suite.  I do now. Please test Lmod version 8.4.6 to see if it fixes the problem for you. Thanks!

**Comment by stierhofj** [comment]
Yes, the new version works. Thank you!

**Comment by rtmclay** [comment]
You are welcome.
