### ISSUE TITLE
Hidden modules not found with version 8.4.10

### ISSUE THREAD

**Issue by akesandgren** [TACC/Lmod#477]
As a followup to #467 our hidden modules can not be loaded with 8.4.10.
They are hidden with the
hide_modulefile("/hpc2n/eb/modules/all/Core/eb_builder/default.lua")
directive.

ml --show_hidden spider eb_builder
works, but
ml eb_builder/default
does not. This worked in 7.8.20. No other changes, just a simple upgrade to 8.4.10.

**Comment by rtmclay** [comment]
Please test Lmod version 8.4.11 to fix this problem.  I was able to reproduce the problem and fix it on my end.  When you get the chance please test the latest version of Lmod. Thanks for the bug report!

**Comment by akesandgren** [comment]
Yep, that works. Thanks.
