### ISSUE TITLE
Hierarchic modulerc files

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#479]
When loading a module that is present twice in $MODULEPATH the one in the folder appearing earlier gets loaded.

However we also have a `<global prefix>/Java/.modulerc.lua` with an entry `module_version("Java/1.8.0_161-OpenJDK", "1.8")`. I encountered trouble using that Java version (via another module loading "Java/1.8") and wanted to test if replacing it by another 1.8 version resolves that. Being unable to modify the global modulerc I installed another one to `<local prefix>/Java/.modulerc.lua` and added `<local prefix>` to the front of MODULEPATH.

However LMod doesn't seem to use that and still resolves Java/1.8 to the alias specified in the global prefix.

My request would hence be that modulerc files are handled similar to module files and ones occurring later in the MODULEPATH are overwritten by earlier ones.

**Comment by rtmclay** [comment]
What version of Lmod are you running?

**Comment by Flamefire** [comment]
That is LMod 8.3.1

**Comment by rtmclay** [comment]
Please test Lmod 8.4.12.

**Comment by rtmclay** [comment]
If you have a spider cache built with 8.3.1 you'll need to rebuild the cache file with 8.4.12.

**Comment by Flamefire** [comment]
Just tested with 8.4.12 with disabled spider cache (via `export LMOD_IGNORE_CACHE=1`) and the behavior is the same.
I guess the `.modulerc` files are loaded in order which causes the latter to override the former (contrary to how modules override each other)

Putting the path with the "system" .modulerc first makes it pick up my custom .modulerc entry which confirms my guess above.

So I'd suggest to load .modulerc files in reverse order so behavior is consistent

**Comment by Flamefire** [comment]
Yes with 8.4.13 it works here. Closing as fixed, thanks a lot! :+1:
