### ISSUE TITLE
Seting explicit Lua version

### ISSUE THREAD

**Issue by epsilon-0** [TACC/Lmod#481]
Currently I am seeing that the Lua in the hash bang `#!/usr/bin/lua` doesn't explicitly specify a version.

A way to explicitly give the version for the Lua to be used while runtime gives better reproducibility during runtime.

This is especially a problem where we have multiple versions of Lua present in the system.

Thanks,
Aisha

**Comment by rtmclay** [comment]
Lmod searches $PATH to find the first lua it finds.  It then puts the absolute path to the lua it finds.  In fact Lmod did find an explicit  lua.  The one in /usr/bin.  

If you want a different lua to be used then put a different lua in your path when you install.

**Comment by epsilon-0** [comment]
What if I have `lua5.1` and `lua5.2` installed and I have `lua -> lua5.2` symlinked but I want `lua5.1` to be used with Lmod?

**Comment by rtmclay** [comment]
The best way to do that is to have lua -> lua5.1 then configure and build lmod with that.  Then change all the #! lines to /usr/bin/lua5.1.

**Comment by epsilon-0** [comment]
I went around and tried to gauge it if it was possible to allow this during configure time.
It seems to be doable, like taking a variable - `versioned-lua`, which defaults to just `lua` but can be given during configure time, something like `--with-versioned-lua=lua5.1`, which can be used by autotools.

I'm willing to make the patch and PR and put in the work for this if it is an acceptable change.
As I've put it, it should not affect anyone and is backwards compatible as it defaults to `lua`.

**Comment by rtmclay** [comment]
Yes, it is possible to configure Lmod to use a particular lua that is not called lua but say lua5.1 or something else.  If you look at configure.ac you'll see that the variable luaprog is used in several places.  A possible problem is that the program luac has to be found as well.  The configure process will have to have matching versions of lua and luac.  

Maybe it might be better to have ```--with-versioned-lua-suffix=5.1``` instead.  That way configure could add the suffix to lua and luac, since it is likely that both will have the same suffix.  Obviously the suffix would have a default of nothing (i.e. "")

**Comment by epsilon-0** [comment]
Am checking with gentoo's lua person, but I am hopeful about the suffix method. Sounds neat :smile_cat: 

This problem is arising as our operating system (ahead of some others) is moving to having multiple lua versions present at the same time. Leading to things like having some packages (like lua filesystem and lua term) to be only installed for one version of lua.

This means that we need to be sure that any lua program is using the proper lua version which has its dependent packages installed. So far it is working fine as all the people only had one lua version, but soon it's gonna create problems.

This would help us (and I'm sure others) to keep things working fine. :heart:

**Comment by rtmclay** [comment]
I will look over a PR when it is completed.  I made a quick look at the Lmod source.  I think that you should leave PATH_TO_LUA to be the directory that contains lua.  Note as well that there is a conversion between upper and lower case. So Makefile.in has @PATH_TO_LUA@ which is converted to what the configure script does.  But the configure script doesn't modify everything.  For example in src/lmod.in.lua has at the top has:
```
#!@path_to_lua@/lua
```

This lowercase version of @path_to_lua@ is converted  by the __installMe target in Makefile.in.  I was thinking that you would convert lines like the one shown above to:

```
#!@path_to_lua@/lua@lua_suffix@
```

And do the same conversion with @LUA_SUFFIX@ in Makefile.in to @lua_suffix@ in the __installMe target.

**Comment by epsilon-0** [comment]
Indeed, this is exactly what I was thinking about.
This should (hopefully) ensure no breakage.
So far, our Lmod package is passing all the tests, so we are in good shape so far :heart: 

I am currently waiting because our resident lua expert (the one who is spearheading the work for multiple lua versions) has yet to answer about how luac is suffixed.

**Comment by epsilon-0** [comment]
Hmm, it seems the way it is currently structured, that there is no way to do a cross compilation yes?
The paths to lua and luac will be the ones for the compiling machine and not the target machine.

This is slightly problematic. Am I missing something?

**Comment by rtmclay** [comment]
Well, luac is not used in the build process so it can named for the target machine.  I suppose that lua could be called different things on the build machine from the target machine.  **But the version of lua has to be the same on both.**.  I don't know how you would guarantee that without them being the same name.

**Comment by epsilon-0** [comment]
Yes, the name can be the same, but the installation paths can be different.
So where the `configure.ac` script is calling `$(luaprog -e "print(package.cpath)")` the paths might be different for the build machine and the target machine.

**Comment by rtmclay** [comment]
Well then you'll have to have a build and target versions  of @PATH_TO_LUA@ and @LUA_SUFFIX@ of these.  Then you'll have to be careful in configure.ac and Makefile.in to use the correct one.  

Thinking about it almost all of the operations by Makefile.in and configure.ac will be build.  The only place in the Makefile.in file would be the copying.  For example the @path_to_lua@ and @lua_suffix@ sed replacement will for the target machine.

**Comment by epsilon-0** [comment]
OK, so I made the PR for the lua versioning usage - https://github.com/TACC/Lmod/pull/488
Its a big one but it is backwards compatible, so it should be enough to check if tests pass on other platforms (they do on mine).

**Comment by rtmclay** [comment]
I am closing this as this has been answered by #488
