### ISSUE TITLE
Using system wide packages - tcl2lua

### ISSUE THREAD

**Issue by epsilon-0** [TACC/Lmod#482]
My system has lua filesystem, lua json and lua term but I'm unable to find the tcl2lua package anywhere.
Even setting the option which asks for using system wide packages falls back to using the bundled tcl2lua.

Is tcl2lua a different custom package?
Is there any upstream for it which can be used to install it to a system wide location?

Aisha

**Comment by rtmclay** [comment]
tcl2lua.tcl is a TCL script that is part of Lmod.  It is automatically installed as part of the Lmod install.  Is tcl2lua.tcl being found?

**Comment by epsilon-0** [comment]
Ah, I was thinking that all the packages from the `/pkgs/` directory were also available as external modules.
It is working perfectly with the internal module for tcl2lua and the externals for others. :heart:
