### ISSUE TITLE
Error: invalid command name "module-version"

### ISSUE THREAD

**Issue by orbsmiv** [TACC/Lmod#484]
**OS: Centos 7 & Centos 8**
**Lmod version: 8.2.7 (installed via yum)**

I'm getting the error `invalid command name "module-info"` when attempting to parse a tcl file with the following content:

``` tcl
#%Module
if {"Java/11" eq [module-info version Java/11]} {
    module-version Java/11.0.2 11
}
if {"Java/1.8" eq [module-info version Java/1.8]} {
    module-version Java/1.8.0_221 1.8
```

The output of `tcl2lua.tcl` (on both OSes) is as follows:

``` bash
$ $LMOD_DIR/tcl2lua.tcl /rds/bear-apps/2019b/EL7-haswell/modules/all/Java/.modulerc
LmodError([===[/rds/bear-apps/2019b/EL7-haswell/modules/all/Java/.modulerc: (???): invalid command name "module-version"]===])
```

What's interesting, and is the main issue for me, is that running a `module load x` command that parses this file on the Centos 8 machine doesn't cause an error, whereas running on the Centos 7 version (which is incidentally inside a Singularity container) results in this:
```
Singularity> module load bluebear
invalid command name "module-info"
    while executing
"module-info version Java/1.8"
    invoked from within
"if {"Java/1.8" eq [module-info version Java/1.8]} {
    module-version Java/1.8.0_181 1.8
}"
    (file "/rds/bear-apps/2018b-1/EL7-haswell/modules/all/Java/.modulerc" line 2)
    invoked from within
"source $mRcFile"
    (procedure "main" line 9)
    invoked from within
"main $fn"
    (file "/usr/share/lmod/lmod/libexec/RC2lua.tcl" line 131)
Lmod has detected the following error:  Unable to parse:
"/rds/bear-apps/2018b-1/EL7-haswell/modules/all/Java/.modulerc". Aborting!

While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    bear-apps/2018b/5  /rds/bear-apps/system/modules/bear-apps/2018b/5
    bluebear/25        /rds/bear-apps/system/modules/bluebear/25
```

I've run `module --config` to inspect the two instances but can't see any significant differences. I've also been running the `module load` commands with the following options: `--ignore_cache --trace --debug=3`

**Comment by rtmclay** [comment]
It is unclear to me what you are trying to do here. The module-info command is only defined for modulefiles and the module-version command is only defined for .modulerc files.

**Comment by orbsmiv** [comment]
I now have a solution to the problem I was experiencing so will close this issue.

To summarise (in case anyone else has a similar issue), we're in the process of migrating from _environment modules_ to _Lmod_ and the `.modulerc` files had been generated by EasyBuild for the former modules system. I was hoping that all of the existing tcl modules would be parsed by Lmod but these `.modulerc` files seem to be an edge-case. Fortunately we'd also recently rebuilt all of the modules as part of a concurrent HPC upgrade to Centos 8 and noticed that EasyBuild was generating the `.modulerc` files differently for Lmod, i.e, this:

``` tcl
#%Module
if {"Java/1.8" eq [module-info version Java/1.8]} {
    module-version Java/1.8.0_202 1.8
}
if {"Java/11" eq [module-info version Java/11]} {
    module-version Java/11.0.2 11
}
```
... was replaced by this:

``` tcl
#%Module
module-version Java/1.8.0_202 1.8
module-version Java/11.0.2 11
```

(The reason for this is explained here: https://github.com/easybuilders/easybuild-framework/blob/604e22fdecf1a4b40bacfaccca4daac2b34039f7/easybuild/tools/module_generator.py#L289)

Not wanting to modify the existing Centos 7 module files my solution was therefore to create an additional `.modulerc.lua` file/symlink in each directory where the existing `.modulerc` was resulting in an error, given that the Lua version takes precedence.
