### ISSUE TITLE
Testing if path exists in Lmod?

### ISSUE THREAD

**Issue by mathomp4** [TACC/Lmod#485]
All,

This might be a FAQ, but my Google-Fu failed me. To wit, every so often, I make a nice subtle typo in my modulefile such that when I do (essentially):

```lua
local pkgdir = pathJoin(installdir,pathdir)
prepend_path("PATH",pathJoin(pkgdir,"bin"))
```

I get a nice silent failure. Lmod is happy to `prepend_path`, and the shell doesn't mind it either. They don't care if you added the wrong path. But, of course, the nice new package I installed doesn't exist there.

So, I was wondering, is there a way to test if a path/directory exists in Lua/Lmod? Obviously this doesn't fix every problem (e.g., if I copy a lua module to a new one and don't change anything inside, say, so Open MPI 4.0.5 still might point to 4.0.4)

I did of course search around and see how to do this in Lua and found...a lot. But as my Lua programming skills at the moment are essentially "Did @rtmclay do something like this one of his Lmod examples?"... 😄 

Or, perhaps, is this a Bad Thing™ in that it is really expensive in Lua?

**Comment by rtmclay** [comment]
You can use isDir().  It is probaby not expense on local disk (especially for SSD's) but it can be for parallel file systems like Lustre.

Here is an example of how it might be used:
```
local pkgdir = pathJoin(installdir,pathdir)
local bindir  = pathJoin(pkgdir,"bin")
if (not isDir(bindir)) then
   LmodError("The directory: \"",bindir,"\" does not exists\n")
end
```

**Comment by mathomp4** [comment]
@rtmclay Thanks! I'll try it out. And yeah, this is mainly local on my laptop. (And isn't *everything* slow on Lustre? 😄 )
