### ISSUE TITLE
using lua functions in tcl2lua.so without linking

### ISSUE THREAD

**Issue by epsilon-0** [TACC/Lmod#486]
I've been wondering how the `tcl2lua.so` library is using lua functions without linking to the lua libraries?

So far it seems to only include the headers...

**Comment by rtmclay** [comment]
Those function are pointers and are filled in by dlopen()/dlsysm()

**Comment by epsilon-0** [comment]
Is this done in some other part of the code?
I don't see it in `/pkgs/tcl2lua/tcl2lua.c`.

**Comment by rtmclay** [comment]
I don't know exactly were it is but it has to be in the lua source code somewhere.  It is done for all packages.

**Comment by rtmclay** [comment]
Can I close this issue?

**Comment by epsilon-0** [comment]
Yes, I should've done it a while ago :)
