### ISSUE TITLE
lmod 8.4.18 build issue

### ISSUE THREAD

**Issue by chenrui333** [TACC/Lmod#490]
👋  it looks like the configure got changed a lot recently, especially about how to check posix module. I wonder if I can get some help on the build fialure.

failure log:
```
2) PATH_TO_LUA:
checking for luac... /usr/local/opt/lua/bin/luac
readlink: illegal option -- f
usage: readlink [-n] [file ...]
checking for valid Lua version./configure: line 5088: -e: command not found
./configure: line 5089: -e: command not found
./configure: line 5093: -e: command not found
./configure: line 5096: -e: command not found
./configure: line 5098: test: too many arguments
...
./configure: line 5114: -e: command not found
./configure: line 5115: -e: command not found
checking for lua modules: posix

Error: The follow lua module(s) are missing:  posix

You can not run Lmod without:  posix
```

You can see the complete build log in here, https://github.com/Homebrew/homebrew-core/runs/1531820034 
relates to https://github.com/Homebrew/homebrew-core/pull/66657

**Comment by rtmclay** [comment]
What system are you on?

**Comment by rtmclay** [comment]
Never mind! The command readlink -f is not universally available.  Please test Lmod 8.4.19 to see if it fixes it for you.

**Comment by chenrui333** [comment]
sure, let me try out lmod 8.4.19

**Comment by chenrui333** [comment]
yeah, it fixed the build issue. Thanks for the quick turnaround.
