### ISSUE TITLE
module: command not found

### ISSUE THREAD

**Issue by tschoonj** [TACC/Lmod#492]
Hi all,

I have installed Lmod 8.4.19 on an Ubuntu 18.04 VM using the [ansible role](https://github.com/idiv-biodiversity/ansible-role-lmod#shell-configuration), and everything works fine when I login via ssh.

However, when I open an RDP XFCE session and open a terminal I get `module: command not found` when I invoke the `module` command. Interestingly the `MODULEPATH` and other env variables have been defined, it's just that the `module` function is not available.

I can get the `module` command if I source `/etc/profile.d/z00-lmod.sh` explicitly, but I would like to avoid having to do this.

My shell is set to /bin/bash

Any thoughts? Thanks in advance!

**Comment by rtmclay** [comment]
My best guess is that RDP is not creating a login shell.  You can test this by adding echo statement to /etc/profile and /etc/bash.bashrc to see what gets started when you open a shell in RDP mode.

**Comment by tschoonj** [comment]
I fixed it eventually by adding the following to my users' .bashrc files:

```bash
if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
```

This problem I ran into appears to be a Ubuntu _feature_, where interactive, non-login shells do not source the files in `/etc/profile.d`.

**Comment by rtmclay** [comment]
You might consider adding the following around your block so that it doesn't get sourced twice:
 
```
if ! shopt -q login_shell; then
if [ -d /etc/profile.d ]; then
 ...
fi
fi
```

**Comment by tschoonj** [comment]
Thanks for the advice!

**Comment by nblei** [comment]
I'm having a similar issue, except I do not have an `lmod.sh` or `z00_lmod.sh` in `/etc/profile.d`.  What portion of the install process creates this file?

**Comment by rtmclay** [comment]
As it says here:

https://lmod.readthedocs.io/en/latest/030_installing.html#installing-lmod:


The profile file is the Lmod initialization script for the bash and zsh shells, the cshrc file is for tcsh and csh shells, and the profile.fish file is for the fish shell. Please copy or link the profile and cshrc files to /etc/profile.d, and optionally the fish file to /etc/fish/conf.d:

$ ln -s /opt/apps/lmod/lmod/init/profile        /etc/profile.d/z00_lmod.sh
$ ln -s /opt/apps/lmod/lmod/init/cshrc          /etc/profile.d/z00_lmod.csh
$ ln -s /opt/apps/lmod/lmod/init/profile.fish   /etc/fish/conf.d/z00_lmod.fish

----------------------
You can either use a symlink like above or copy the files over.

**Comment by nblei** [comment]
Oh I see, I simply can't read properly.

Thanks.
