### ISSUE TITLE
Lmod error running Tcl environment module

### ISSUE THREAD

**Issue by fuyun-fuyun** [TACC/Lmod#494]
I got this error during testing Intel MPI 2021.1.1 Version.The lmod version I used is  Version 8.2.10 . 

Lmod has detected the following error: /opt/intel/oneapi/compiler/2021.1.1/modulefiles/compiler: (compiler): invalid command name "is-avail"

The offending line in the modulefile is:

if { [ is-avail $cmplr_root/linux/lib/oclfpga/modulefiles/oclfpga ] } {
    module load $cmplr_root/linux/lib/oclfpga/modulefiles/oclfpga
}

Does the lmod support the command 'is-avail' ?

Any thoughts? Thanks in advance!

**Comment by rtmclay** [comment]
Lmod does not support is-avail from TCL modulefiles.  It is supported for Lua modulefiles.  If this comes from OHPC you should update.
