### ISSUE TITLE
Trailing slashes stripped when setting paths

### ISSUE THREAD

**Issue by weaverba137** [TACC/Lmod#501]
Lmod version: 8.4.24

LaTeX uses trailing slashes (`//`) to denote "and subdirectories" in a path-like variable.  For example:
```lua
append_path("TEXINPUTS", PRODUCT_DIR.."//")
```
However, Lmod strips these trailing slashes:
```
TEXINPUTS=:/Code/svn/latex_repo/trunk
```
Note: the leading `:` was added separately.  Other module packages, such as the TCL version of modules, do not do this.

I also tried
```lua
append_path("TEXINPUTS", pathJoin(PRODUCT_DIR, "", ""))
```
but the result was the same.

**Comment by weaverba137** [comment]
One more data point.
```lua
setenv("TEXINPUTS", ":" .. PRODUCT_DIR .. "//")
```
*does* give the desired environment variable:
```
TEXINPUTS=:/Code/svn/latex_repo/trunk//
```

**Comment by rtmclay** [comment]
I have created Lmod 8.4.26.  This version support paths to have trailing double slashes in my tests when using append_path() or prepend_path().  Please test 8.4.26 to see if it works for you.  Thanks for reporting this issue!

**Comment by weaverba137** [comment]
It is working for me, thank you!

**Comment by rtmclay** [comment]
Great! Thanks again for reporting this issue. I'm going to close this issue.
