### ISSUE TITLE
`is-avail` is not supported, despite documentation and commit history

### ISSUE THREAD

**Issue by xmnboy** [TACC/Lmod#505]
Despite the fact that the release notes and commits indicate that the `is-avail` command has been part of the `lmod` implementation, since lmod 7.7.35 in June of 2018 (see https://github.com/TACC/Lmod/commit/e348e6f93c7c449e7fa4c4cecdfed054b34200db), the `is-avail` command is flagged as an "invalid command name":
```sh
$ module load compiler
Loading compiler version 2021.1.2
Loading tbb version 2021.1.1
Loading compiler-rt version 2021.1.2
Loading dpl version 2021.1.2
Lmod has detected the following error:  /opt/intel/oneapi/modulefiles/compiler/2021.1.2:
(compiler/2021.1.2): invalid command name "is-avail"
While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    compiler/2021.1.2  /opt/intel/oneapi/modulefiles/compiler/2021.1.2
```

In the above test both `is-avail` and `is-loaded` were referenced. The `is-loaded` reference worked, but the `is-avail` did not. I performed this test on `lmod 8.2.7` (our customer's current version) and `lmod 8.4.6` (latest version). I did not try `lmod 7.7.35` so I cannot say if this is a regression.

Here's a fragment of the modulefile code that caused the error shown above:
```sh
# Load required dependencies
if { ![ is-loaded tbb ] }         { module load tbb }
if { ![ is-loaded compiler-rt ] } { module load compiler-rt }
if { ![ is-loaded dpl ] }         { module load dpl }

# Load optional dependencies
if { ![ is-loaded debugger ] && [ is-avail debugger ] } { module load debugger }
if { ![ is-loaded oclfpga ]  && [ is-avail oclfpga ]  } { module load oclfpga }
```

**Comment by rtmclay** [comment]
The check-in you mentioned is to support the shell command "module is-avail foo" not a TCL module command.  It is not possible to support is-avail inside a TCL module file but it is possible with Lua modulefiles.  If you are going to stick with TCL modulefiles, you should use the following instead:
```
    if { ![ is-loaded debugger ]  } { module try-add debugger }
```

**Comment by xmnboy** [comment]
@rtmclay -- thank you very much for that clarification. Ideally, we want our modulefiles to work with both TCL modulefiles and Lua modulefiles, since we are providing them with our product. I'll give your suggestion a try and, fingers crossed 🤞 , it will work equally well in both places!

**Comment by xmnboy** [comment]
@rtmclay -- Unfortunately, `try-add` is not recognized by TCL modulefiles, see the error below:
```sh
Module ERROR: module: Invalid command 'try-add'
  In '/opt/intel/oneapi/modulefiles/compiler/latest'
  Please contact <root@localhost>
```
This logic appears to work:
```sh
# Load optional dependencies (if lmod else tcl)
if { [ info exists ::env(LMOD_VERSION) ] } {
    if { ![ is-loaded debugger ] } { module try-add debugger }
    if { ![ is-loaded oclfpga ]  } { module try-add oclfpga }
} else {
    if { ![ is-loaded debugger ] && [ is-avail debugger ] } { module load debugger }
    if { ![ is-loaded oclfpga ]  && [ is-avail oclfpga ]  } { module load oclfpga }
}
```
Test results below for TCL modules (blank lines added for readability):
```sh
$ module list
No Modulefiles Currently Loaded.

$ module --version
Modules Release 4.1.1 (2018-02-17)

$ module load compiler
Loading compiler version 2021.1.2
Loading tbb version 2021.1.1
Loading compiler-rt version 2021.1.2
Loading dpl version 2021.1.2
Loading debugger version 10.0.0
Loading oclfpga version 2021.1.2
Loading init_opencl version 2021.1.2

$ module list
Currently Loaded Modulefiles:
 1) tbb/latest           5) /opt/intel/oneapi/compiler/2021.1.2/linux/lib/oclfpga/modulefiles/init_opencl
 2) compiler-rt/latest   6) oclfpga/latest
 3) dpl/latest           7) compiler/latest
 4) debugger/latest
```
Test results below for Lua modules (some blank lines added/removed for readability):
```sh
$ module list
No modules loaded

$ module --version
Modules based on Lua: Version 8.4.6  2020-09-26 13:31 -05:00
    by Robert McLay mclay@tacc.utexas.edu

$ module load compiler
Loading compiler version 2021.1.2
Loading tbb version 2021.1.1
Loading compiler-rt version 2021.1.2
Loading dpl version 2021.1.2
Loading debugger version 10.0.0
Loading oclfpga version 2021.1.2

$ module list
Currently Loaded Modules:
  1) tbb/2021.1.1           3) dpl/2021.1.2      5) oclfpga/2021.1.2
  2) compiler-rt/2021.1.2   4) debugger/10.0.0   6) compiler/2021.1.2
```
One question, how far back does the existence of your `$LMOD_VERSION` variable go?

**Comment by rtmclay** [comment]
You should use LMOD_VERSION_MAJOR instead of LMOD_VERSION.  LMOD_VERSION_MAJOR is defined only inside Lmod modulefiles.  LMOD_VERSION_MAJOR was defined in Lmod 5.1.5.

**Comment by xmnboy** [comment]
Hi Robert. Thanks for the advice. I'm updating to detect the LMOD_VERSION_MAJOR variable for distinguishing between lmod-specific and tmod-specific code snippets.

**Comment by rtmclay** [comment]
I have emailed the developer of Tmod4.  He agreed to add support for "module try-load ..." in modulefiles to version 4.8.  He said that it will be soon.  Maybe by June.

O.K. to close?

**Comment by xmnboy** [comment]
Yes, okay to close this issue. I think we are in good shape with the workaround. 

One question regarding behavioral differences between lmod and tmod regarding the "module use" command. When I perform a "module use <relative-directory-name>" with the tmod version of modulefiles the specified directory name is expanded to its fully qualified pathname before insertion into $MODULEPATH. When I perform that same command with the lmod version the relative pathname is inserted into $MODULEPATH. This means that as long as I do not "cd" to another directory, everything is fine, but if I "cd" away from the current path, when using lmod, I can no longer reference the modulefiles in the folder that I just did a "module use" on. Whereas, with tmod I can reference the modulefiles in the the folder that I did a "module use" on, regardless of my current working directory.

Is the above the expected behavior? When I ran into this it took me a while to figure out what was going on. But inspecting the $MODULEPATH environment variable I can see that a relative pathname was inserted into the $MODULEPATH, not a full pathname.

**Comment by rtmclay** [comment]
Thanks for the bug report on "module use".  It is surprising to me that no one has reported this issue before.  Please test Lmod 8.4.28 to see if it works for you.

**Comment by xmnboy** [comment]
Thanks, Robert. Lmod 8.4.28 fixes the relative `module use` problem. It converted the relative path that I used into a full pathname and now works properly regardless of my cwd. I did not try a scenario that included symlinks in the modulefile folder name, but I suspect that will not be an issue.

Also, I noticed that you do not interpret the `modulename/latest` notation to mean the "default" version. In our case, it shouldn't matter, because we create both: a link to the versioned modulefile and a link for the presumed "latest" modulefile. Here's an example of what I mean:

```
------------------------------------------------ /home/ubuntu/mod-test -------------------------------------------------
   advisor/latest                dnnl-cpu-tbb/latest               intel_ipp_ia32/latest
   advisor/2021.1.1       (D)    dnnl-cpu-tbb/2021.1.1      (D)    intel_ipp_ia32/2021.1.1      (D)
   ccl/latest                    dnnl/latest                       intel_ipp_intel64/latest
   ccl/2021.1.1           (D)    dnnl/2021.1.1              (D)    intel_ipp_intel64/2021.1.1   (D)
   clck/latest                   dpct/latest                       intel_ippcp_ia32/latest
   clck/2021.1.1          (D)    dpct/2021.1.1              (D)    intel_ippcp_ia32/2021.1.1    (D)
   compiler-rt/latest            dpl/latest                        intel_ippcp_intel64/latest
   compiler-rt/2021.1.1   (D)    dpl/2021.1.1               (D)    intel_ippcp_intel64/2021.1.1 (D)
   compiler-rt32/latest          inspector/latest                  itac/latest
   compiler-rt32/2021.1.1 (D)    inspector/2021.1.1         (D)    itac/2021.1.1                (D)
   compiler/latest               intel-embree/latest               mkl/latest
   compiler/2021.1.1      (D)    intel-embree/3.12.0        (D)    mkl/2021.1.1                 (D)
   compiler32/latest             intel-oidn/latest                 mkl32/latest
   compiler32/2021.1.1    (D)    intel-oidn/1.2.4           (D)    mkl32/2021.1.1               (D)
   dal/latest                    intel-openvkl/latest              mpi/latest
   dal/2021.1.1           (D)    intel-openvkl/0.11.0       (D)    mpi/2021.1.1                 (D)
   debugger/latest               intel-ospray/latest               tbb/latest
   debugger/10.0.0        (D)    intel-ospray/2.4.0         (D)    tbb/2021.1.1                 (D)
   dev-utilities/latest          intel-ospray_studio/latest        tbb32/latest
   dev-utilities/2021.1.1 (D)    intel-ospray_studio/0.5.0  (D)    tbb32/2021.1.1               (D)
   dnnl-cpu-gomp/latest          intel-rkcommon/latest             vpl/latest
   dnnl-cpu-gomp/2021.1.1 (D)    intel-rkcommon/1.5.0       (D)    vpl/2021.1.1                 (D)
   dnnl-cpu-iomp/latest          intel-rkutil/latest               vtune/latest
   dnnl-cpu-iomp/2021.1.1 (D)    intel-rkutil/1.0.0         (D)    vtune/2021.1.1               (D)

-------------------------------------------- /usr/share/modules/modulefiles --------------------------------------------
   dot    module-git    module-info    modules    null    use.own

----------------------------------------- /opt/apps/lmod/lmod/modulefiles/Core -----------------------------------------
   lmod    settarg

  Where:
   D:  Default Module

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".
```

**Comment by rtmclay** [comment]
Lmod uses several ways to mark the default.  In particular, it uses a symlink "default" to mark the default.  You can read about how Lmod does this here: https://lmod.readthedocs.io/en/latest/060_locating.html.

If you are going to stay using Lmod, you might want to consider changing the latest symlink to "default" as you move forward.

**Comment by xmnboy** [comment]
While the "latest" designation works in Tmod in some ways that are similar to the "default" designation, it happens to show up in our list of modulefiles because of a "latest" link that sits along-side one or more versioned folders in the product installation. This "latest" symlink was not intentional for Tmod, but a nice coincidence that Tmod supports that designation.

Because of the way our product is laid out, we provide a "modulefiles-setup.sh" script that creates an organized set of modulefiles that Tmod and Lmod can make sense of. I've already added an `--ignore-latest` option to that script for those who do not want the "latest" symlink in the resulting organized modulefiles folder. I could do something similar to rename that "latest" symlink to "default" -- as an option to that same script.

Thanks again for the feedback, Robert.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by xmnboy** [comment]
👍
