### ISSUE TITLE
Recursive unloading breaks after `module use`

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#508]
I noticed that sometimes the recursive unloading doesn't work anymore and finally tracked that down: After a `ml use` it stops working.

Starting from a "clean" environment (system module path set up):
```
$ ml TensorFlow && ml unload TensorFlow
Module TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4 and 47 dependencies loaded.
Module TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4 and 47 dependencies unloaded.
$ ml use /scratch/ws/1/s3248973-EasyBuild/easybuild-haswell/modules/all/
$ ml TensorFlow && ml unload TensorFlow
Module TensorFlow/2.4.1-fosscuda-2019b-Python-3.7.4 and 48 dependencies loaded.
Module TensorFlow/2.4.1-fosscuda-2019b-Python-3.7.4 unloaded.
```

This is fully reproducible. Using LMod 8.4.16

Using `-T` I see the recursive unloading for the first (ok) variant, but for the failing one I see instead of the other unloads:
```
    Building Spider cache for the following dir(s): /scratch/ws/1/s3248973-EasyBuild/easybuild-haswell/modules/all
Spider Loading: pkgconfig/1.5.1-GCCcore-9.3.0-Python-3.8.2 (fn: /scratch/ws/1/s3248973-EasyBuild/easybuild-haswell/modules/all/pkgconfig/1.5.1-GCCcore-9.3.0-Python-3.8.2.lua)
[some more of the similar Spider Loading:]
    completed building cache. Saving cache: false
```

**Comment by rtmclay** [comment]
I'll need a module tree to test this outside of EB.

**Comment by Flamefire** [comment]
It seems to be related to adding a path which is not in the spider cache.   
Our spider cache is read-only for users, so that might add up too.

I created a minimal module tree: 
[TempModuleTree.zip](https://github.com/TACC/Lmod/files/6270560/TempModuleTree.zip)

When using our systems module tree, all works, when `ml use` this then it does not work anymore, so same as above.

I can run some more checks on our system, if you need more input, but I hope the above already helps pinpointing the issue.

**Comment by rtmclay** [comment]
I have some questions:

- What is $MODULEPATH before you start?
- Is there a Tensorflow in /scratch/ws/1/s3248973-EasyBuild/easybuild-haswell/modules/all/?
- What exactly is the problem?  I see no error message or something bad happening.  Is the problem that there is 47 dependences in the first time and 48 the second?

**Comment by Flamefire** [comment]
Ok, I'll try to be more explicit:
- We have a default $MODULEPATH which looks like this: "/sw/modules/scs5/classic:/sw/modules/scs5/vis:/sw/modules/scs5/tools:...." (sorry, that is kinda large)
- There is a module (in this example "TensorFlow") in that $MODULEPATH
- System spider cache is set up, up to date, but not user writable
- Then I add another module tree (in the original report `/scratch/ws/1/s3248973-EasyBuild/easybuild-haswell/modules/all`, or same with `TempModuleTree` from my previous answer) via `module use` which contains another (newer) version of the TF module

Now the problem is as follows:
- Loading TensorFlow loads that and its dependencies -> All Good, both with the system module tree and with the "custom" module tree
- Before adding the other module tree unloading TensorFlow without the custom tree added unloads TensorFlow AND all dependencies --> Good
- After adding the other module tree and loading and unloading TensorFlow the dependencies are not unloaded --> Bad

See the output:
```
$ ml TensorFlow && ml unload TensorFlow
Module TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4 and 47 dependencies loaded.
Module TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4 **and 47 dependencies unloaded.**
$ ml use /scratch/ws/1/s3248973-EasyBuild/easybuild-haswell/modules/all/ (or: ml use $HOME/TempModuleTree)
$ ml TensorFlow && ml unload TensorFlow
Module TensorFlow/2.4.1-fosscuda-2019b-Python-3.7.4 and 48 dependencies loaded.
Module TensorFlow/2.4.1-fosscuda-2019b-Python-3.7.4 **unloaded.**
```
I.e. the last line is missing "and 48 dependencies unloaded." and they stay loaded.

Does this make it clear, what I meant?

**Comment by rtmclay** [comment]
I can understand that this is a problem and it can be frustrating.  But I can't reproduce it. If I cannot reproduce it, I cannot fix it.  So what I need is a module tree or trees that shows the problem with the exact steps that shows the issue.

**Comment by Flamefire** [comment]
>  The tree you gave me before has no dependencies and doesn't show the problem.

Ouch, Layer 8 problem: I missed that the (kinda) new `depends_on` must be used and that this must be explicitly enabled in EasyBuild.

Thanks for the hint and sorry for the noise!
