### ISSUE TITLE
Check for priorities in use

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#509]
In EasyBuild we'd like to avoid running the `module` command as that is costly (forking the process in order to run the command takes quite some time)
One of the more frequent calls is `module use`.

I noticed, that you can directly modify the `$MODULEPATH` variable and any changes are picked up by LMod. Is there a guarantee (e.g. by the docs) of that behavior?

I also noticed that after using `module use --priority` and then manually changing `$MODULEPATH` LMod will reorder that according to the priorities on any command, even just `module list`. Same question here: Is that guaranteed?

And finally we need to prepend a path to `$MODULEPATH` to force that taking preference. https://lmod.readthedocs.io/en/latest/190_Integration_of_EasyBuild_and_Lmod.html?highlight=MODULEPATH#example-use-own-eb-prepend shows `module use --prepend` which doesn't seem to exist and actually adds "--prepend" to $MODULEPATH.
Question here would be, what the best way of prepending a path would be, even when priorities are in effect.
I was thinking about checking for `__LMOD_Priority_MODULEPATH` as e.g. in https://github.com/easybuilders/easybuild-framework/pull/3557/files#diff-6689eca3b0dacbaf4864e30f0322f22a870c572ad87e2841da4392dd1b5cae74R1433, but there are concerns, that this is an LMod internal variable which we can't rely on.

To be concrete:

- Is there a way to reliably check if priorities for `$MODULEPATH` are in effect? (so if not we can simply prepend to it)
- Is there a way to reliably prepend a path to it? (e.g. by getting the current highest priority from `$__LMOD_Priority_MODULEPATH` and using that as `--priority`)
- Can this be done without actually invoking LMod? (i.e. by just reading/writing env variables)

**Comment by rtmclay** [comment]
If you prepend to MODULEPATH outside of Lmod, then you could have a problem.   You could have a different environment when run "module use <path>" or you do it outside of Lmod.  If you run the command "module use <path>", Lmod checks to see if the "right" module are loaded.  That might be different than changing $MODULEPATH outside of Lmod.

Yes, Lmod does check for the current value of $MODULEPATH and uses it.  That is guaranteed.  The same is with priorities

BUT you have the same problem if Lmod would load different modules.  To answer your questions:

- Priorities are always checked by __LMOD_Priority_MODULEPATH
- Yes you can do it that way (with the problem stated above)
- Yes you can do it that way (with the problem stated above)

**Comment by rtmclay** [comment]
O.K. to close this issue?
