### ISSUE TITLE
Bash completion of ml restore

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#51]
The bash completion of `ml restore` does not work as expected. The tries to auto-completion with a module name instead of the output of `ml savelist`.

Since `ml restore` is my new best friend, I would love it if auto-completion would also works there and try to auto complete a name from the savelist.

**Comment by rtmclay** [comment]
Thanks for the bug report!  This has been fixed in HEAD.

**Comment by boegel** [comment]
:+1

**Comment by wpoely86** [comment]
I've tested it, and it works great! Thanks :clap:
