### ISSUE TITLE
Command executed on `ml use` which fails

### ISSUE THREAD

**Issue by Flamefire** [TACC/Lmod#511]
We recently encountered a strange issue which was discovered by running our install script with `set -e`: On a `module use` command a command is executed which fails and makes our script fail

Is it expected that `module use` runs commands from module files?

In particular we have a module "ddt" which extends the $MODULEPATH where there is another Module with a line: `if { [ system which make-profiler-libraries > /dev/null 2> /dev/null ] != 0 }`

This is seemingly only supposed to be run when loading the module.

In the install script we basically only run `module --force purge; module use <new-temporary-install-tree>` and the latter seemingly runs the `which make-profiler-libraries` command in the current shell which to me is unexpected.

Full output of those 2 commands with `set -ex`:
```
module --force purge
++ /usr/share/lmod/lmod/libexec/lmod sh --force purge
eval unset '__LMOD_REF_COUNT_LOADEDMODULES;' unset 'LOADEDMODULES;' > '__LMOD_REF_COUNT_MODULEPATH=/sw/modules/taurus/environment:1;' export '__LMOD_REF_COUNT_MODULEPATH;' > 'MODULEPATH=/sw/modules/taurus/environment;' export 'MODULEPATH;' unset '_LMOD_REF_COUNT__LMFILES;' unset 'LMFILES;' 'ModuleTable001=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTg2NDAwMDAsWyJjX3Nob3J0VGltZSJdPWZhbHNlLGRlcHRoVD17fSxmYW1pbHk9e30sbVQ9e30sbXBhdGhBPXsiL3N3L21vZHVsZXMvdGF1cnVzL2Vudmlyb25tZW50Iix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ii9zdy9tb2R1bGVzL3RhdXJ1cy9lbnZpcm9ubWVudCIsfQ==;' export 'ModuleTable001;' 'ModuleTable_Sz=1;' export 'ModuleTable_Sz;' unset 'ModuleTable003;'
++ unset __LMOD_REF_COUNT_LOADEDMODULES
++ unset LOADEDMODULES
++ __LMOD_REF_COUNT_MODULEPATH=/sw/modules/taurus/environment:1
++ export __LMOD_REF_COUNT_MODULEPATH
++ MODULEPATH=/sw/modules/taurus/environment
++ export MODULEPATH
++ unset _LMOD_REF_COUNT__LMFILES
++ unset LMFILES
++ ModuleTable001=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTg2NDAwMDAsWyJjX3Nob3J0VGltZSJdPWZhbHNlLGRlcHRoVD17fSxmYW1pbHk9e30sbVQ9e30sbXBhdGhBPXsiL3N3L21vZHVsZXMvdGF1cnVzL2Vudmlyb25tZW50Iix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ii9zdy9tb2R1bGVzL3RhdXJ1cy9lbnZpcm9ubWVudCIsfQ==
++ export ModuleTable001
++ ModuleTable_Sz=1
++ export ModuleTable_Sz
++ unset ModuleTable003
module use /sw/modules/scs5/ARCH/haswell/all
++ /usr/share/lmod/lmod/libexec/lmod sh use /sw/modules/scs5/ARCH/haswell/all
eval '__LMOD_REF_COUNT_MODULEPATH=/sw/modules/scs5/ARCH/haswell/all:1;/sw/modules/taurus/environment:1;' export > '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/sw/modules/scs5/ARCH/haswell/all:/sw/modules/taurus/environment;' export > 'MODULEPATH;' > 'ModuleTable001=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTI2MTkuMDQyOTc4Mjg2NyxbImNfc2hvcnRUaW1lIl09MjEuODI1MzU4MTUyMzksZGVwdGhUPXt9LGZhbWlseT17fSxtVD17fSxtcGF0aEE9eyIvc3cvbW9kdWxlcy9zY3M1L0FSQ0gvaGFzd2VsbC9hbGwiLCIvc3cvbW9kdWxlcy90YXVydXMvZW52aXJvbm1lbnQiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL3N3L21vZHVsZXMvdGF1cnVzL2Vudmlyb25tZW50Iix9;' export 'ModuleTable001;' 'ModuleTable_Sz=1;' export 'ModuleTable_Sz;' which make-profiler-libraries '>' /dev/null '2>' '/dev/null;' which make-profiler-libraries '>' /dev/null '2>' '/dev/null;'
++ __LMOD_REF_COUNT_MODULEPATH='/sw/modules/scs5/ARCH/haswell/all:1;/sw/modules/taurus/environment:1'
++ export __LMOD_REF_COUNT_MODULEPATH
++ MODULEPATH=/sw/modules/scs5/ARCH/haswell/all:/sw/modules/taurus/environment
++ export MODULEPATH
++ ModuleTable001=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTI2MTkuMDQyOTc4Mjg2NyxbImNfc2hvcnRUaW1lIl09MjEuODI1MzU4MTUyMzksZGVwdGhUPXt9LGZhbWlseT17fSxtVD17fSxtcGF0aEE9eyIvc3cvbW9kdWxlcy9zY3M1L0FSQ0gvaGFzd2VsbC9hbGwiLCIvc3cvbW9kdWxlcy90YXVydXMvZW52aXJvbm1lbnQiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL3N3L21vZHVsZXMvdGF1cnVzL2Vudmlyb25tZW50Iix9
++ export ModuleTable001
++ ModuleTable_Sz=1
++ export ModuleTable_Sz
++ which make-profiler-libraries
```
You can have a look at the module files here:
[failingModules.zip](https://github.com/TACC/Lmod/files/6277026/failingModules.zip)

There are 3 ddt modules which extend the $MODULEPATH, but only 2 of the referred locations actually exist, hence the 2 `which make-profiler-libraries` calls add up.

I also noticed a dependency on the spider cache:
- When manually reproducing the commands the failure does not always occur.
- After rebuilding the spider cache (without the temporary module path `/sw/modules/scs5/ARCH/haswell/all`), the issue most often ocurred, although after a couple of retries it did not anymore (maybe some timing?)
- When the `ml use` command failed the `/usr/share/lmod/lmod/libexec/ml_cmd use /sw/modules/scs5/ARCH/haswell/all` call took a couple of seconds longer than when it succeeded.

Sorry, I know this is kind of vaque as it is hard to reliably reproduce, although it occurs often enough to bother us.

The major question to me is, how a system call from a module file could end up being executed in the shell where `ml use` is run even though no modules are loaded at all?

Using Lmod 8.4.16

**Comment by Flamefire** [comment]
> to see where the module use is coming from.

The `module use` is issued by us, see `module --force purge; module use <new-temporary-install-tree>`

The purge is to make sure no modules are actually loaded which might get reloaded and trigger the system command.

The problem appears on the `module use`, which calls lmod and that returns `which make-profiler-libraries '>' /dev/null '2>' '/dev/null;' which make-profiler-libraries '>' /dev/null '2>' '/dev/null;'` which the `module` then evals in the shell (I've just seen that you have to scroll right  quite a bit, as Github put that all on 1 line)

So Lmod is clearly returns those calls to be executed, which IMO is wrong for a `module use` with no modules loaded.

**Comment by rtmclay** [comment]
I have tested it on my system and I'm not seeing what you are seeing.  Could you turn off set -xe and try:
```
module --force purge; module -T use <new-temp-install-tree> 2> use.log
```

Thanks

**Comment by Flamefire** [comment]
I recorded 2 versions: use.log is with `set -ex` to show the `which` command, use2.log is without and after running that I see a `$?=1`: [moduleUseLog.zip](https://github.com/TACC/Lmod/files/6295519/moduleUseLog.zip)

To trigger this, I have to delete my user cache first so Lmod rebuilds it: `rm ~/.lmod.d/.cache/*`

**Comment by rtmclay** [comment]
I have modified Lmod to only rebuild the spider caches when there are loaded or pending modules.  Please test Lmod 8.4.29 to see if it works for you.

Note that you might want to change the cray modules to only call the which command when they are in load mode.

**Comment by Flamefire** [comment]
Does this fix the issue or just workaround it? From what I understood the issue is caused by that module when Lmod recreates the spider cache. It then, for some reason, executes the `which` command from the module in the users shell.
The change you describe sounds like the spider cache will not be rebuild after `ml --force purge && ml use`. But it would be rebuild with the next `module load xxx`, wouldn't it? I think this might then run into the exact same issue again, just a bit later and hence harder to reproduce. Or am I missing anything? Have you found, why this happens?

> Note that you might want to change the cray modules to only call the which command when they are in load mode.

How would I do that? IIUC those modules are from cray directly though, so we'd need to patch them Hence my question here if that is something LMod could fix/handle.

**Comment by rtmclay** [comment]
You are correct.  Lmod will not rebuild the spider cache with "ml purge; ml use" but would the next time there is a "ml avail" or in your case "module load xxx" because you have LMOD_CACHED_LOAD set.   This is the way that Lmod works.  It builds a spider cache to know about properties and other things like knowing when the env. var MODULEPATH changes.  The way it does that is by evaluating modulefiles in a special way.  So yes, anytime Lmod builds a spider cache it is going to evaluate those cray modules. Evaluating those modules will cause the ```which``` command to run in the user shell.   

Adding a check to see if the cray modules are only in load mode to run the ```which``` command is the only way I know to avoid the spider cache from evaluating the shell line.

**Comment by Flamefire** [comment]
Ok thanks! What I don't understand:
The module has this problematic line: `if { [ system which make-profiler-libraries > /dev/null 2> /dev/null ] != 0 } {`

I'm not really familiar with the exact semantics of module files but my interpretation is, that this tries to run the command and checks the return value to influence the module loading process (generically speaking)

So I would expect that either of this:
- The command is fully run within the modules tool, i.e. the modules tool execs the command in a spawned shell or similar especially as it needs to pass the return code back to the module file. This seems to happen when running `ml map-link-dynamic`, i.e. `lmod bash load map-link-dynamic` simply returns "Please load the forge or perf-reports module first"
- The full `if` and everything is "translated" to bash, i.e. `if [ which make-profiler-libraries > /dev/null 2> /dev/null ]; then  ...` and returned to be evaled.

But instead what happens is the lmod returns the `system` directly to be evaled by the shell, i.e. `lmod bash use /tmp/share/modules/cray` returns `... export MODULEPATH; ... which make-profiler-libraries > /dev/null 2> /dev/null;`

So I don't understand how the `system` call (the args of it) ends up in the output of lmod. This looks incomplete at least.

I mean: If running this is required by how building the spider cache works, why isn't it run internally similar to when the module is (tried) to load?   
I'd guess there is some code responsible for returning those calls to the user shell after all the MODULEPATH/ModuleTable env var changes. Why is it doing that? Is there a legitimate reason why this might be wanted/required? I feel like that could be removed/suppressed.

For completeness the command run and output (the /sw/modules/* paths are our default paths):

```
$ /usr/share/lmod/lmod/libexec/lmod bash use /sw/installed/ddt/20.2.1-Redhat-7.0/share/modules/cray/
__LMOD_REF_COUNT_MODULEPATH=/sw/installed/ddt/20.2.1-Redhat-7.0/share/modules/cray:1\;/sw/modules/scs5/classic:1\;/sw/modules/scs5/vis:1\;/sw/modules/scs5/tools:1\;/sw/modules/scs5/toolchain:1\;/sw/modules/scs5/system:1\;/sw/modules/scs5/phys:1\;/sw/modules/scs5/perf:1\;/sw/modules/scs5/numlib:1\;/sw/modules/scs5/mpi:1\;/sw/modules/scs5/math:1\;/sw/modules/scs5/lib:1\;/sw/modules/scs5/lang:1\;/sw/modules/scs5/geo:1\;/sw/modules/scs5/devel:1\;/sw/modules/scs5/debugger:1\;/sw/modules/scs5/data:1\;/sw/modules/scs5/compiler:1\;/sw/modules/scs5/chem:1\;/sw/modules/scs5/cae:1\;/sw/modules/scs5/bio:1\;/sw/modules/scs5/base:1\;/sw/modules/taurus/environment:1;
export __LMOD_REF_COUNT_MODULEPATH;
MODULEPATH=/sw/installed/ddt/20.2.1-Redhat-7.0/share/modules/cray:/sw/modules/scs5/classic:/sw/modules/scs5/vis:/sw/modules/scs5/tools:/sw/modules/scs5/toolchain:/sw/modules/scs5/system:/sw/modules/scs5/phys:/sw/modules/scs5/perf:/sw/modules/scs5/numlib:/sw/modules/scs5/mpi:/sw/modules/scs5/math:/sw/modules/scs5/lib:/sw/modules/scs5/lang:/sw/modules/scs5/geo:/sw/modules/scs5/devel:/sw/modules/scs5/debugger:/sw/modules/scs5/data:/sw/modules/scs5/compiler:/sw/modules/scs5/chem:/sw/modules/scs5/cae:/sw/modules/scs5/bio:/sw/modules/scs5/base:/sw/modules/taurus/environment;
export MODULEPATH;
_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTcyMDAwMCxbImNfc2hvcnRUaW1lIl09MC4wNzA5MjM4MDUyMzY4MTYsZGVwdGhUPXt9LGZhbWlseT17fSxtVD17bW9kZW52PXtbImZuIl09Ii9zdy9tb2R1bGVzL3RhdXJ1cy9lbnZpcm9ubWVudC9tb2RlbnYvc2NzNS5sdWEiLFsiZnVsbE5hbWUiXT0ibW9kZW52L3NjczUiLFsibG9hZE9yZGVyIl09MSxwcm9wVD17bG1vZD17WyJzdGlja3kiXT0xLH0sfSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJtb2RlbnYvc2NzNSIsfSx9LG1wYXRoQT17Ii9zdy9pbnN0YWxsZWQvZGR0LzIwLjIuMS1SZWRoYXQtNy4wL3NoYXJlL21vZHVsZXMvY3JheSIs;
export _ModuleTable001_;
_ModuleTable002_=Ii9zdy9tb2R1bGVzL3NjczUvY2xhc3NpYyIsIi9zdy9tb2R1bGVzL3NjczUvdmlzIiwiL3N3L21vZHVsZXMvc2NzNS90b29scyIsIi9zdy9tb2R1bGVzL3NjczUvdG9vbGNoYWluIiwiL3N3L21vZHVsZXMvc2NzNS9zeXN0ZW0iLCIvc3cvbW9kdWxlcy9zY3M1L3BoeXMiLCIvc3cvbW9kdWxlcy9zY3M1L3BlcmYiLCIvc3cvbW9kdWxlcy9zY3M1L251bWxpYiIsIi9zdy9tb2R1bGVzL3NjczUvbXBpIiwiL3N3L21vZHVsZXMvc2NzNS9tYXRoIiwiL3N3L21vZHVsZXMvc2NzNS9saWIiLCIvc3cvbW9kdWxlcy9zY3M1L2xhbmciLCIvc3cvbW9kdWxlcy9zY3M1L2dlbyIsIi9zdy9tb2R1bGVzL3NjczUvZGV2ZWwiLCIvc3cvbW9kdWxlcy9zY3M1L2RlYnVnZ2VyIiwiL3N3L21vZHVs;
export _ModuleTable002_;
_ModuleTable003_=ZXMvc2NzNS9kYXRhIiwiL3N3L21vZHVsZXMvc2NzNS9jb21waWxlciIsIi9zdy9tb2R1bGVzL3NjczUvY2hlbSIsIi9zdy9tb2R1bGVzL3NjczUvY2FlIiwiL3N3L21vZHVsZXMvc2NzNS9iaW8iLCIvc3cvbW9kdWxlcy9zY3M1L2Jhc2UiLCIvc3cvbW9kdWxlcy90YXVydXMvZW52aXJvbm1lbnQiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL3N3L21vZHVsZXMvdGF1cnVzL2Vudmlyb25tZW50Iix9;
export _ModuleTable003_;
_ModuleTable_Sz_=3;
export _ModuleTable_Sz_;
which make-profiler-libraries > /dev/null 2> /dev/null;
which make-profiler-libraries > /dev/null 2> /dev/null;
```

**Comment by rtmclay** [comment]
You have found a bug. The way that Lmod handled the system command inside a TCL modulefile was incorrect.  I have updated Lmod to internally evaluate the system call inside of TCL interpreter directly.  This now works correctly for me for the tests I am able to do. But I do not have access to a Cray with these particular modules so I can not test it completely.  

Lmod now only evaluates system calls in load (or unload) mode so there is no need to add that test.

Please try Lmod 8.4.30 to see if it works for you.

**Comment by Flamefire** [comment]
Yes looks like that resolves the issue, thanks a lot!
