### ISSUE TITLE
Possible to 'append' hierarchy in module avail output?

### ISSUE THREAD

**Issue by mathomp4** [TACC/Lmod#512]
Query for the lmod gurus: I'm trying to (once again) learn to use `spack` and I have it so that it seems to set up a nice hierarchy of lmod files within itself. Now, I'm on a system where I have system modulefiles, my personal ones, etc. so when I do `ml av` I get a lot modulepaths displayed. So, then I did:
```
module use -a /path/to/spack/Core
```
and then when I do `ml av` I see a nice new section at the *bottom* of the output as expected:
```
...
   debugger/10.0.0               itac/latest                       vtune/2021.2.0   (D)
   debugger/10.1.1        (D)    itac/2021.1.1

------------- /discover/nobackup/mathomp4/spack/share/spack/lmod/linux-sles12-x86_64/Core -------------
   gcc/10.1.0

  Where:
   L:  Module is loaded
   D:  Default Module
```

What I'm wondering is, when I do `ml gcc/10.1.0`, is there a way to get the next level of its hierarchy *below* it. Because, when I do `ml gcc/10.1.0` I then get:
```
------------- /gpfsm/dnb44/mathomp4/spack/share/spack/lmod/linux-sles12-x86_64/gcc/10.1.0 -------------
   libszip/2.1.1    numactl/2.0.14    openmpi/4.0.4    zlib/1.2.11

-------------------------------- /usr/share/lmod/lmod/modulefiles/Core --------------------------------
   lmod/7.6.1    settarg/7.6.1

---------------------------------- /usr/local/share/modulefiles/Core ----------------------------------
   arm-forge/19.0.3             comp/intel/19.1.1.217        comp/pgi/20.4  (D)
   arm-forge/20.0.3             comp/intel/19.1.2.254        idl/8.1
...
   debugger/10.0.0               itac/latest                       vtune/2021.2.0   (D)
   debugger/10.1.1        (D)    itac/2021.1.1

------------- /discover/nobackup/mathomp4/spack/share/spack/lmod/linux-sles12-x86_64/Core -------------
   gcc/10.1.0 (L)

  Where:
   L:  Module is loaded
   D:  Default Module
```
The new level is now *above* all the other paths. Obviously, I could just not  `module use -a` my Spack Core, but, well, I kind of like my "personal" modulefiles to be at the end of `ml av`!

**Comment by rtmclay** [comment]
You should ask these kind of questions on the Lmod mailing list.  This is not a bug.

Trying reading: https://lmod.readthedocs.io/en/latest/200_avail_custom.html to see if this answers your question.

**Comment by mathomp4** [comment]
Apologies.
