### ISSUE TITLE
Lmod fish autocomptetion with aliases

### ISSUE THREAD

**Issue by planetmija** [TACC/Lmod#513]
When using aliases like e.g:
`module-alias compiler/intel/2019.5 compiler/intel/19.0`

you get some errors when using autocompletion and fish.

`fish: Unknown command '@compiler/intel/19.0'
fish: @compiler/intel/19.0
      ^
in command substitution
	called on standard input`

Problem is in function `__fish_lmod_av`:
`module -t av 2>&1 | sed '/^\//d'`

creates the following output:
`compiler/intel/2019.5(@compiler/intel/19.0)`

This should be repaired. If you care for aliases, this could be solved differently, if not you can just use attached patch ([module.fish.patch.gz](https://github.com/TACC/Lmod/files/6459044/module.fish.patch.gz)).

I didn't create a pull request, since this is probably not the solution you want to use. If you don't want to autocomplete aliases you're welcome to use my solution.

Thanks to Manuel who debugged this with me.

**Comment by planetmija** [comment]
It depends if you want aliases to be shown when using tab complete. There are differences in load and avail, as well:
`module avail compiler/intel/2019.5`

creates:
`No module(s) or extension(s) found!`

where loading this module works:
`module load compiler/intel/2019.5`

**Comment by rtmclay** [comment]
I was able to fix these issues much quicker that I originally thought.  It turns out that the tab completion for bash and zsh worked correctly w.r.t. aliases.  But you are right that they didn't for fish.  I believe that that is fixed now.  Please test Lmod 8.5.2 to see if it works for you.  Thanks very much for the bug report! Not  only did this issue fix problems for fish users but now ```module avail <alias>``` works correctly for all shell users.

**Comment by planetmija** [comment]
Hi, we had a holiday last week so I took a long weekend :)
I could test it today (v8.5.2) and everything works as expected with bash and fish (autocompletion and load and avail for aliases show results). Thanks a lot!

Only difference I see is, that bash only autocompletes 'ml av' (short command) while fish only 'module av' (long command). But the problem could be on my side.

**Comment by rtmclay** [comment]
That is correct.  The file init/fish/module.fish shows only statements like:

```
# avail | av
complete -f -c module -n '__fish_lmod_needs_command' -a 'av avail' -d 'List available modules'
complete -f -c module -n '__fish_lmod_using_command av avail' -r -a (__fish_lmod_av)
```

There are no lines that have ml.  I am not an expert in fish and I didn't write the tab completion for fish.  I did write the ones for bash and zsh and I know that the tab completion logic is more complicated for ml than module.  If anyone wants to write the completion for fish for ml, I'll be happy to look it over.

**Comment by planetmija** [comment]
I'm just a fish user myself and just starting to understand the concept a bit deeper. But it seems not to be that hard when you take the file module.fish and copy it to ml.fish and replace module by ml. Some entries have to be deleted, like 'H' and '?' (maybe some more).

But my problem currently is, that you can use ml module and ml -module. This would work for adding modules:
complete -f -c ml -r -a (__fish_lmod_av)

But then all modules are shown, even if you want to unload modules. But I will try to look into it the next weeks. Maybe s.o. else can figure this out. You'll need to verify that no command was given first.

**Comment by rtmclay** [comment]
Right.  You also have to be able to handle when command name and module names overlap.  So if you enter:

```
$ ml sp<TAB>
```
it might complete to the command spider but you might have modules called spaghetti, spyder or spice.  It may be helpful to look at how bash or zsh handle these complications.

**Comment by rtmclay** [comment]
Ok to close this issue?

**Comment by planetmija** [comment]
Yes of course. Problem solved and completion is an extra feature not related to issue.
