### ISSUE TITLE
Tracking explicit module usage

### ISSUE THREAD

**Issue by tstrempel** [TACC/Lmod#516]
In the documentation https://lmod.readthedocs.io/en/latest/300_tracking_module_usage.html a method to track module usage is stated. As this uses a hook on the `module load` command, all loaded modules are reported, e. g. if `cairo/1.16.0` is loaded it's implicitly loaded dependencies are logged too.

Is it possible to only log the explicitly loaded commands, e. g. only the `module load cairo/1.16.0` command is logged, but not the loaded dependencies?

**Comment by wpoely86** [comment]
Have a look at https://github.com/TACC/Lmod/blob/master/contrib/more_hooks/SitePackage.lua#L34
The parameter `userload` is set to yes if it's the module the user requested to load (and not a dependency).

**Comment by rtmclay** [comment]
I have updated the documentation to point to the contrib/more_hooks directory to track user loads.

**Comment by tstrempel** [comment]
Thanks for the help! I'll try it asap

**Comment by tstrempel** [comment]
Tried it, it works. Thanks for the help!
