### ISSUE TITLE
LMOD_AVAIL_STYLE not documented in Configuring Page

### ISSUE THREAD

**Issue by shahzebsiddiqui** [TACC/Lmod#519]
@rtmclay 
I dont see `LMOD_AVAIL_STYLE` documented in https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html page however it is documented in https://lmod.readthedocs.io/en/latest/200_avail_custom.html. I think this should be documented in the configuring lmod page if this is an environment variable that can be overridden by users.

**Comment by rtmclay** [comment]
I have updated the documentation to add ```LMOD_AVAIL_STYLE`` on the configuring_lmod page. If you get a chance please check out the updated documentation.

**Comment by shahzebsiddiqui** [comment]
i checked the docs it looks good. I have a question about this format according i understand you can use colon separated list and angle brackets to define the default ` A:B:<C> ==> C ` though i am wondering if these avail style `system` and `grouped` are reserved words or can they be anything. 

I am curious to know since i am configuring Lmod for Perlmutter and documenting this in our user guide that was recently published see https://docs.nersc.gov/environment/lmod/#format-titles-for-module-trees. What we have is an Lmod hook to do custom titles for module trees. I was under the impression that `system` is the default title but the documentation states these values can be anything.
