### ISSUE TITLE
Unexpected mounting of paths

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#521]
Hi Robert,

I've discovered something of which I don't know if it's me not understanding something or a bug. I'm using the module file that you can see at https://github.com/EESSI/software-layer/issues/68#issuecomment-854542060
It basically sets a bunch of paths that are related to a CVMFS mount which is part of an automount. If I load the module, the automount correctly triggers and all is well.
What surprised me is that if I run a `ml spider EESSI` (the name of the module), it also triggers a mount. Is that intended?

**Comment by rtmclay** [comment]
Assuming that there is no cache file related to that part of $MODULEPATH, then those modules are evaluated.  It is also true that a module file is evaluate when you do: ```module help EESSI```.  You probably want to have something like:
```
If (mode() == "load" or mode() == "unload") then
    ....
end
```

The statements inside the if block will not be evaluated the mode() is "spider".  However changes to $MODULEPATH should be seen when in spider mode().

It is not clear to me what causes the automounts but whatever it is probably ought to be in an if block similar to the one above.

This is the way that all module systems work. They have to evaluate a module when it is loaded, unloaded, "spidered", helped, shown, etc.  The difference is how each module function works when evaluated.

**Comment by wpoely86** [comment]
OK, that makes sense. I touch `$MODULEPATH` so it triggers a mount. Thanks!
