### ISSUE TITLE
Possible to exclude a folder in modulepath for recursive searching?

### ISSUE THREAD

**Issue by ruixingw** [TACC/Lmod#523]
Say if I have the following paths:
```
/modulefiles/some_lib/0.3.lua
/modulefiles/softwares/aaa/1.0.lua
```
and ```MODULEPATH=/modulefiles:/modulefiles/softwares```.

Now if I do ```module ava```, ```/modulefiles/softwares``` is listed as a separate category as I wish. 
```
----------------------  /modulefiles/softwares -------------------------
aaa/1.0
```

However, entries in subfolder ```softwares``` is also shown under ```/modulefiles```:
```
----------------------  /modulefiles ----------------------------------
some_libs/0.3      softwares/aaa/1.0
```

 Is it possible to exclude the folder ```softwares``` from the ```/modulefiles```'s category?

**Comment by rtmclay** [comment]
No it is not possible.  Lmod supports names like compiler/intel/18.1 as well as git/2.8

You could place some_lib/0.3.lua in /modulefiles/libs/some_libs/0.3.lua and change the module path to be:

MODULEPATH=/modulefiles/libs:/modulefiles/software

**Comment by ruixingw** [comment]
> No it is not possible. Lmod supports names like compiler/intel/18.1 as well as git/2.8
> 
> You could place some_lib/0.3.lua in /modulefiles/libs/some_libs/0.3.lua and change the module path to be:
> 
> MODULEPATH=/modulefiles/libs:/modulefiles/software

Thanks!
