### ISSUE TITLE
LMOD on shared filesystem with RHEL7 and RHEL8 not working

### ISSUE THREAD

**Issue by nortex** [TACC/Lmod#525]
Hi,

We are currently testing LMOD. We installed LMOD with non-root users under shared GPFS filesystem. While everything is working smoothly on our main nodes which has CentOS7, we have a problem with using LMOD on RHEL8.3. Actually the lmod installed on a shared filesystem is not working due to different O.S library versions, such an ncurses/ tcl / lua and others. 

What is the best way to maintain global lmod package installation under shared filesystem so that LMOD will be completely undependent on system o.s libraries? or atleast not hardcoded for specific library version?

Thanks!

**Comment by wpoely86** [comment]
Lmod is available as rpm in epel for both RHEL7 and RHEL8. That's the easiest way to use it.

**Comment by nortex** [comment]
> Lmod is available as rpm in epel for both RHEL7 and RHEL8. That's the easiest way to use it.

But how do we then maintain LMOD version upgrades?  and how do we keep our specific configurations of lmod? such as modulespath, admin file, lmodrc and etc... In addition those configurations may change from time to time so holding only one installation of LMOD sounds best. But how can we implement it to atleast refer to dynamic libraries instead of hardcoding to some ncurses.5.so specific library?

**Comment by wpoely86** [comment]
> 
> But how do we then maintain LMOD version upgrades? and how do we keep our specific configurations of lmod? such as modulespath, admin file, lmodrc and etc... In addition those configurations may change from time to time so holding only one installation of LMOD sounds best. But how can we implement it to atleast refer to dynamic libraries instead of hardcoding to some ncurses.5.so specific library?

Try to get a single Lmod install work for both RHEL7 and 8 is just hard and not worth the hassle IMHO. I think it's possible if you let the system provide all lua stuff and maybe disable the binary tcl2lua. 

You maintain Lmod in the same way as any other software coming from the repositories? You can put a version lock on it if you like. The configuration (SitePackage etc) can all be set by your configuration management system (for example by setting the needed variables in `/etc/profile.d`).
