### ISSUE TITLE
depends_on doesn't warn when swapping versions

### ISSUE THREAD

**Issue by Micket** [TACC/Lmod#531]
I was hoping that `depends_on`  would warn when users tries to use incompatible modules, but it seems it only warns when unloading a dependency.

Example `zlib/1.2.11-GCCcore-10.3.0`  has a `depends_on("GCCcore/10.3.0")`, and nicely prints a big warning like i hoped:
```
$ ml zlib/1.2.11-GCCcore-10.3.0 
$ ml unload GCCcore/10.3.0
---------------------------------------------------------------------------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: GCCcore/10.3.0 (required by: zlib/1.2.11-GCCcore-10.3.0)
---------------------------------------------------------------------------------------------------------------------------------------------------
```
but if I swap the version, there is no warning:
```
$ ml zlib/1.2.11-GCCcore-10.3.0 
$ ml GCCcore/11.2.0

The following have been reloaded with a version change:
  1) GCCcore/10.3.0 => GCCcore/11.2.0
```

A more realistic scenario is users doing something seemingly harmless, like:
```
ml TensorFlow/2.5.0-fosscuda-2020b lz4/1.9.2-GCCcore-9.3.0
```
where it will not even show a warning about swapping (despite the fact that it does in this case), but the resulting environment is in fact actually broken. 

I know of `LMOD_DISABLE_NAME_AUTOSWAP/LMOD_DISABLE_SAME_NAME_AUTOSWAP`, which at least prevents these bad cases. 
But, shouldn't `depends_on` be picky about the version used when it is explicitly stated?
If it's not possible, consider this a feature request for a `LMOD_PICKY_VERSION_RESOLUTION=yes` or some such.

**Comment by rtmclay** [comment]
What does your depends_on()? say.  Does it say:
```
depends_on("zlib") 
```
or
```
depends_on("zlib/1.2.11-GCCcore-10.3.0")
```
?

**Comment by Micket** [comment]
Well in the example, zlib is the one depending on GCCcore; but regardless, it's the always the full version string everywhere. (things  on top of this zlib uses `depends_on("zlib/1.2.11-GCCcore-10.3.0")`)
```
$ ml show zlib/1.2.11-GCCcore-10.3.0 
...
depends_on("GCCcore/10.3.0")
...

$ ml zlib/1.2.11-GCCcore-10.3.0 
$ ml GCCcore/11.2.0

The following have been reloaded with a version change:
  1) GCCcore/10.3.0 => GCCcore/11.2.0

$ ml

Currently Loaded Modules:
  1) zlib/1.2.11-GCCcore-10.3.0   2) GCCcore/11.2.0

$ ml purge
$ ml zlib/1.2.11-GCCcore-10.3.0 GCCcore/11.2.0  # Not even a warning
```

**Comment by Micket** [comment]
Tiny reproducible example;
```bash
mkdir modules
mkdir modules/Dependency
mkdir modules/SomeSoftware
mkdir modules/OtherSoftware
echo 'depends_on("Dependency/3.4")' > modules/SomeSoftware/1.2.lua
echo 'depends_on("Dependency/5.6")' > modules/OtherSoftware/3.4.lua
echo 'LmodMessage("Processing Dependency/3.4")' > modules/Dependency/3.4.lua
echo 'LmodMessage("Processing Dependency/5.6")' > modules/Dependency/5.6.lua

ml use modules
```

Testing it out;
```
$ ml purge
$ ml SomeSoftware
Processing Dependency/3.4
$ ml OtherSoftware
Processing Dependency/3.4
Processing Dependency/5.6

The following have been reloaded with a version change:
  1) Dependency/3.4 => Dependency/5.6
```
So despite the explicit version used in `depends_on`, the swap is permitted.  but ok, at least there is a warning (though I suspect my users wouldn't realize how much they could break things)

Scenario 2;
```
$ ml purge
$ ml SomeSoftware OtherSoftware
Processing Dependency/3.4
Processing Dependency/3.4
Processing Dependency/5.6
```
then we can see there is a incompatible swap going on still, but there is not even a warning.

**Comment by rtmclay** [comment]
Closing this issue.  If there any updates, please feel free to re-open this issue.
