### ISSUE TITLE
`--with-availExtensions=no` doesn't work

### ISSUE THREAD

**Issue by dylex** [TACC/Lmod#532]
8.5.6 configured with `--with-availExtensions=no`:
```
Display Extensions w/ module avail.......................... : no
```
results in module with config
```
Display Extension w/ avail         yes
```
I think this is because it's using `@AVAIL_EXTENSION@` (without the S):
```
sed ... -e 's|@avail_extensions@|@AVAIL_EXTENSION@|g'
```

**Comment by rtmclay** [comment]
Thanks for the bug report!.  I have changed it to be AVAIL_EXTENSIONS in the Makefile.in. and test the change and it works for me.  If you wish to test it yourself, you can do so by checking out the latest version on the master branch from the Lmod repo.

**Comment by dylex** [comment]
Thanks!  Also noticed that docs/source/090_configuring_lmod.rst also references `--with-availExtension`. I changed it in PR #533 if that helps.
