### ISSUE TITLE
Behavior of `execute` command

### ISSUE THREAD

**Issue by wyphan** [TACC/Lmod#534]
Can the documentation for the `execute` command be improved to explain the behavior of the command?
https://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html?highlight=execute#extra-functions
The current documentation gives an example of executing a command at module load.
I use this functionality in a module file for the Intel Python distribution that came with oneAPI, for executing `conda activate`, which works perfectly:
```
execute{ cmd="conda activate 2021.3.0", modeA={"load"} }
```
However, the matching command on module unload doesn't work.
```
execute{ cmd="conda deactivate", modeA={"unload"} }
```
The following is the error message that I receive. (This is on my laptop, running Ubuntu 20.04 LTS x86_64)
```
Command '' not found, but can be installed with:

sudo apt install mailutils-mh  # version 1:3.7-2.1, or
sudo apt install meshio-tools  # version 4.0.4-1
sudo apt install mmh           # version 0.4-2
sudo apt install nmh           # version 1.7.1-6
sudo apt install termtris      # version 1.3-1
```
I think this might be due to the command getting executed after the environment variable changes have been undone, particularly this one:
```
local ipy = "/opt/intel/oneapi/intelpython/latest"
setenv( "CONDA_EXE", pathJoin( ipy, "bin/conda" ))
prepend_path( "PATH", pathJoin( ipy, "bin" ))
```
I think it would be helpful to document this behavior of the `unload` mode, or even better, document all the available options for `modeA`. Additionally, an extra `modeA` option called `before_unload` would be appreciated for this specific use case of calling `conda deactivate`.

**Comment by wyphan** [comment]
@rtmclay I don't think the newest changes to the docs are live yet... I mean, when I search "print" on the page, here are the two matches:

> Method 2: Take the output directly from Lmod. You can put **print**() statements in your modulefile and do:

> Why are messages **print**ed to standard error and not standard out?

**Comment by rtmclay** [comment]
What version of Lmod are you using?

**Comment by rtmclay** [comment]
O.K.   Now this is no longer an Lmod problem but a problem with conda.    Your best bet to debug this is to do:
```
% $LMOD_CMD bash load intelpython > loading_intel_python.sh
```
and look at loading_intel_python.sh in detail to see what the problem is.


If it is any help here is the text of a module that we use on one of our systems that (unfortunately) uses conda shown below. 



```
whatis("Name: python3")
whatis("Version: powerai_1.7.0")
whatis("Category: python conda powerai ")
whatis("Keywords: python conda powerai ")
whatis("Description: powerai_1.7.0 anaconda python environment")
whatis("URL: https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html")
pushenv("IBM_POWERAI_LICENSE_ACCEPT","yes")
pushenv("CONDA_ENVS_PATH","/scratch/00515/mclay/conda_local/envs:/scratch/apps/conda/4.8.3/envs")
pushenv("CONDA_PKGS_DIRS","/scratch/00515/mclay/conda_local/pkgs,/scratch/apps/conda/4.8.3/pkgs")
execute{cmd="source /scratch/apps/conda/4.8.3/etc/profile.d/conda.sh; conda activate py3_powerai_1.7.0; export -f conda __conda_activate __conda_hashr __conda_reactivate __add_sys_prefix_to_path", modeA={"load"}}
execute{cmd="for i in $(seq ${CONDA_SHLVL:=0}); do conda deactivate; done; pre=/scratch/apps/conda/4.8.3; 
        export LD_LIBRARY_PATH=$(echo ${LD_LIBRARY_PATH} | tr ':' '\n' | grep . | grep -v $pre | tr '\n' ':' | sed 's/:$//'); 
        export PATH=$(echo ${PATH} | tr ':' '\n' | grep . | grep -v $pre | tr '\n' ':' | sed 's/:$//'); 
        unset -f conda __conda_activate __conda_hashr __conda_reactivate __add_sys_prefix_to_path; 
        unset $(env | grep -o "[^=]*CONDA[^=]*" | grep -v 'CONDA_ENVS_PATH\|CONDA_PKGS_DIRS');", modeA={"unload"}}
family("python")
```

```

**Comment by wyphan** [comment]
@rtmclay In addition to dumping `loading_intel_python.sh` as you suggested above, I also dumped `unloading_intel_python.sh` using
```bash
$ module load intelpython
$ $LMOD_CMD bash unload intelpython > unloading_intel_python.sh
```
I've updated the gist in the [previous comment](https://github.com/TACC/Lmod/issues/534#issuecomment-944626561) with both `loading_intel_python.sh` and `unloading_intel_python.sh`.

One step forward: The string inside the `print` command needs a semicolon at the end.
> `print("conda deactivate;")`

After adding the semicolon, `conda deactivate` seems to succeed. However, my `PS1` still doesn't look normal. After `module load intelpython` it shows
```bash
(2021.4.0) (base) $
```
and after `module unload intelpython` it becomes
```
(base) (base) $
```
Notice line 16 in `unloading_intel_python.sh`. There are three residual Intel Python directories in `PATH`.
Also, after executing `module unload intelpython`, on inspection (from running `env` and searching for `intel`), there are several "abnormal" environment variables:
```bash
I_MPI_ROOT=/opt/intel/oneapi/intelpython/latest
FI_PROVIDER_PATH=/opt/intel/oneapi/intelpython/latest/lib/libfabric/prov:/usr/lib64/libfabric
CONDA_PREFIX=/opt/intel/oneapi/intelpython/latest
PATH=/opt/intel/oneapi/intelpython/latest/envs/2021.4.0/bin/libfabric:/opt/intel/oneapi/intelpython/latest/envs/2021.4.0/bin:/opt/intel/oneapi/intelpython/python3.7/bin:/usr/local/texlive/2020/bin/x86_64-linux:/opt/gcc9libs/bin:/home/wyp/bin:/home/wyp/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wyp/compile/exciting-plus-gpu-dbg/bin:/home/wyp/compile/pdtoolkit-3.25.1/x86_64/bin:/home/wyp/compile/tau-2.29/x86_64/bin:/opt/papi/bin:/opt/aflow/bin:/home/wyp/go/bin
MANPATH=/opt/intel/oneapi/intelpython/latest/share/man:/usr/local/texlive/2020/texmf-dist/doc/man::/opt/papi/share/man:/opt/gcc9libs/share/man:/usr/local/texlive/2020/textmf-dist/doc/man
LIBRARY_PATH=/opt/intel/oneapi/intelpython/latest/lib/libfabric
LD_LIBRARY_PATH=/opt/intel/oneapi/intelpython/latest/lib/libfabric:/usr/lib/x86_64-linux-gnu/openmpi/lib:/opt/gcc9libs/lib::/opt/papi/lib
CLASSPATH=/opt/intel/oneapi/intelpython/latest/lib/mpi.jar
OCL_ICD_FILENAMES=libintelocl.so
__LMOD_REF_COUNT_PATH=/opt/intel/oneapi/intelpython/latest/envs/2021.4.0/bin/libfabric:1;/opt/intel/oneapi/intelpython/latest/envs/2021.4.0/bin:1;/opt/intel/oneapi/intelpython/python3.7/bin:1;/usr/local/texlive/2020/bin/x86_64-linux:2;/opt/gcc9libs/bin:1;/home/wyp/bin:1;/home/wyp/.local/bin:1;/usr/local/sbin:1;/usr/local/bin:1;/usr/sbin:1;/usr/bin:1;/sbin:1;/bin:1;/usr/games:1;/usr/local/games:1;/snap/bin:1;/home/wyp/compile/exciting-plus-gpu-dbg/bin:1;/home/wyp/compile/pdtoolkit-3.25.1/x86_64/bin:1;/home/wyp/compile/tau-2.29/x86_64/bin:1;/opt/papi/bin:1;/opt/aflow/bin:1;/home/wyp/go/bin:1
```
How do I remove these extra stuff on module unload?

I'll also try the `CONDA_SHLVL` trick you posted above and report back.

**Comment by rtmclay** [comment]
You might consider try out what happens when you comment out the sourcing of the ipy.sh script.
