### ISSUE TITLE
Loading R module with ml vs. module load

### ISSUE THREAD

**Issue by drkrynstrng** [TACC/Lmod#536]
This is very much an edge case, but I thought I'd share in case others encounter this. With Lmod 8.2 or 8.5.6 using Lua module files, there is a small discrepancy in using `ml` vs. `module load` to load an `r` module. I assume the issue is the result of a module named with one letter. In this case, I also have a module hierarchy for `openblas`.

Using the standard `module load gcc openblas r` works fine. No need to specify versions as the defaults are used.

However, with `ml` I get the following:

```
$ ml gcc openblas r
Lmod has detected the following error:  User module collection: "gcc" does not exist.
  Try "module savelist" for possible choices.


$ ml gcc openblas
$ ml r
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules
```

One solution is using `ml gcc openblas r/` or specifying a version like `ml gcc openblas r/4.1.1`. I guess because there are other modules that begin with the letter `r`. Another solution is to convert the name to an uppercase `R`, assuming there are no other modules that begin with the letter `R`.

**Comment by drkrynstrng** [comment]
I see. Thanks for the clarification!

**Comment by rtmclay** [comment]
I updated the ml help message to hopefully make this clearer:
```
% ml --help
   ml: A handy front end for the module command:

   Simple usage:
   -------------
     $ ml
                              means: module list
     $ ml foo bar
                              means: module load foo bar
     $ ml -foo -bar baz goo
                              means: module unload foo bar;
                                     module load baz goo;

   Command usage:
   --------------

   Any module command can be given after ml:

   if name is a subcommand like avail, save, load, restore, show, swap,...
       $ ml name  arg1 arg2 ...

   All options must go before the subcommand:
       $ ml --terse avail

   Then this is the same :
       $ module name arg1 arg2 ...

   Shorthand:
   ----------
       ml r  -> ml restore
       ml s  -> ml save
       ml sl -> ml savelist
       ml sw -> ml swap
   
   Loading Modules named "r" or "spider" or other module commands
   --------------------------------------------------------------

   Any modules named "r" or any other module commands must be loaded like this:

      ml load r
      ml load spider

```

I have only made this change on my copy.  It will become live at the next release of Lmod.
