### ISSUE TITLE
a test that will tell me if a package is being loaded as a result of a depends-on from another package?

### ISSUE THREAD

**Issue by douglasgscofield** [TACC/Lmod#540]
Is there a test that will tell me if a package is being loaded as a result of a depends-on from another package?

We have two modules, R/x.y.z and R_packages/x.y.z. The second is an omnibus module containing many R packages and has a `depends-on R/x.y.z`. When R/x.y.z is loaded, we issue a message alerting our (often new to HPC) users that the R_packages/x.y.z module exists to make their lives easier.

I would like to not issue this message if R/x.y.z is being loaded as a result of the depends-on from R_packages/x.y.z.  Unsurprisingly, `is-loaded R_packages/x.y.z` is always false at this point and I assume it won't be true until the R_packages/x.y.z module file exits successfully.

**Comment by rtmclay** [comment]
You can't do it from a TCL module file but you can do it from a Lua Modulefile and use the ```isPending("R_package/x.y.z")``` function.

**Comment by douglasgscofield** [comment]
tested and works perfectly, thanks!
