### ISSUE TITLE
Issue with z00_lmod.sh when wirting a bash script called R

### ISSUE THREAD

**Issue by pelacables** [TACC/Lmod#544]
Hi,

Lmod-8.2.7-1.el7.x86_64 on SL 7.9.

We need to use a bash wrapper that calls R from environment modules. The restriction is that it has to be called R. 

The script is something like:

```
#!/bin/bash
# ##############################################################################
# this file is managed by puppet
# ##############################################################################

. /etc/profile
echo "Loading Bioconductor 3.13-foss-2021a-R-4.1.0 from /usr/bin/R"| /bin/logger -t custom-r-version
module purge
module load Bioconductor/3.13-foss-2021a-R-4.1.0
export R_HOME="${EBROOTR}/lib64/R"
echo "Done loading Bioconductor 3.13-foss-2021a-R-4.1.0 from /usr/bin/R"| /bin/logger -t custom-r-version

exec R "${@}"

```
(Biocondcutor is our meta module that loads R + other local customizations)

the problem arises when running ". /etc/profile". When it goes though all the files in /etc/profile.d and reaches /etc/profile.d/z00_lmod.sh, and because our bash script is called R, it believes that the shell is a R shell and not bash and it gives this error:

```
/usr/share/lmod/lmod/init/R: line 2: syntax error near unexpected token `('
/usr/share/lmod/lmod/init/R: line 2: `module <- function(...){'
```

this happens because it believes this is a R shell and not a bash shell:

from /etc/profile.d/z00_lmod.sh

```
[...]
  my_shell=$($PS_CMD -p $$ -ocomm=)
  my_shell=$($EXPR_CMD    "$my_shell" : '-*\(.*\)')
  my_shell=$($BASENAME_CMD $my_shell)
[...]
```

if you rename the script to bash it works as expected.

I belive the script needs a better way to figure its own shell, something that does not restrict the filename.

**Comment by rtmclay** [comment]
Thanks for the bug report!  I have modified Lmod to use readlink /proc/$$/exe on linux and restricted the possible shell choices to bash, zsh and sh.  If it is not one of those it defaults to sh.

Please test Lmod 8.5.28 to see if it works for you.

**Comment by pelacables** [comment]
Thanks for the quick fix.  Is the RPM for 8.5.28 available somewhere?

**Comment by rtmclay** [comment]
Also the change is mainly in z00_lmod.sh.  You could look at the new init/profile.in to see what the changes are then map those change in the z00_lmod.sh file. You could install the latest Lmod in your account and look at the installed "profile" file and map those changes into your z00_lmod.sh

**Comment by pelacables** [comment]
Yes, sure, already did in puppet. 
It was more like a generic question. We use Lmod that comes from EPEL and I now just realized how old our version is (8.2.7) and I was wondering if there was some specific RPM repo for Lmod.
From my side you can close this issue.

**Comment by rtmclay** [comment]
I do not maintain RPM or DEB packages repo some place.  There is just not time enough in the day to do that as well as maintaining Lmod.  I'm glad that you were able to fix this issue at your site.
