### ISSUE TITLE
Last time a module loaded

### ISSUE THREAD

**Issue by MagdyA** [TACC/Lmod#546]
Does Lmod support such a function that I can check when is the last time a module is loaded ? if not is there any other way to do so?

**Comment by rtmclay** [comment]
There is no function that does that inside of Lmod.  A site can implement module tracking (see: https://lmod.readthedocs.io/en/latest/300_tracking_module_usage.html) for details.  A site can know what modules are loaded and when by storing the name, path of the module and what user loaded the module and when.  A script is provided that can report module counts for certain date ranges.

Will that do what you are looking for?

**Comment by MagdyA** [comment]
Yes pretty much, Thank you.
