### ISSUE TITLE
[8.6] Build time configuration of new LMOD_CONFIG_DIR option not working correctly

### ISSUE THREAD

**Issue by robert914** [TACC/Lmod#547]
According to the latest 8.6 documentation regarding the new Lmod config file: https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html?highlight=with-configDir#configuring-lmod-with-etc-lmod-lmod-config-lua

> Lmod looks for a file named lmod_config.lua in the LMOD_CONFIG_DIR, which is by default /etc/lmod/. So normally the file is found here: /etc/lmod/lmod_config.lua. It can be configured to any value with the configure option (–with-configDir=) or setting the environment variable LMOD_CONFIG_DIR. This file is used optionally. It is not required.

The new option `--with-configDir` appears to be documented incorrectly. Looking at the `configure --help` output, it indicates the following:
```
  --with-lmodConfigDir=ans
                          Location of Lmod Config Dir [[/etc/lmod]]
```

However, neither the documented option, nor the one shown in the help output correctly sets the configured value for the installed `<prefix>/lmod/lmod/libexec/myGlobals.lua` file, it always looks like this after installation:
```
------------------------------------------------------------------------
-- LMOD_CONFIG_DIR: The location of the Lmod config dir
------------------------------------------------------------------------
cosmic:init{name    = "LMOD_CONFIG_DIR",
            sedV    = "@LMOD_CONFIG_DIR@",
            default = "/etc/lmod"}
```
Notice that It leaves the non-replaced key `@LMOD_CONFIG_DIR@` still in the installed file instead of replacing it with what is specified by `configure --with-lmodConfigDir=/some/path`.

After digging into the `configure` and `configure.ac` files, it appears that option will replace `LMOD_CFG_DIR` and not `LMOD_CONFIG_DIR`:
```
AC_SUBST(LMOD_CFG_DIR)
AC_ARG_WITH(lmodConfigDir,
    AC_HELP_STRING([--with-lmodConfigDir=ans],[Location of Lmod Config Dir [[/etc/lmod]]]),
    LMOD_CFG_DIR="$withval"
    AC_MSG_RESULT([LMOD_CFG_DIR=$with_lmodConfigDir])
    AC_DEFINE_UNQUOTED(LMOD_CFG_DIR, "$with_lmodConfigDir")dnl
    ,
    withval="/etc/lmod"
    AC_MSG_RESULT([LMOD_CFG_DIR=$withval])
    LMOD_CFG_DIR="$withval"
    AC_DEFINE_UNQUOTED(LMOD_CFG_DIR, "$withval"))dnl
```

So I think the `src/myGlobals.lua`, `configure`, `configure.ac` and associated documentation needs a little fixing so they are all in sync so that it will work correctly.

I can certainly patch / work-around this for now, but can we get this corrected to work properly in the next release?
Please let me know if you need further information or clarification. Thanks!

**Comment by rtmclay** [comment]
I have updated my copy and pushed this to the master branch on github.com.  If you have time you can check it there.  Thanks very much for the careful reading and tracking down all the places!

I am grateful for the bug fix, but I would be interested to know why you want to change the default location (/etc/lmod) to something else.

**Comment by robert914** [comment]
Thanks @rtmclay, I'll test out your `master` changes tomorrow and let you know.

As for why I'm changing it, I'm trying to change it from `/etc/lmod` to `/usr/local/etc/lmod` to match the default prefix of `/usr/local` that is defined in `configure` so that all the files get installed under `/usr/local` for testing purposes. Currently, I'm still on the fence as to whether I will install Lmod under `/usr/local` or `/usr` for final roll-out.

**Comment by robert914** [comment]
@rtmclay Ok, your changes you pushed to `master` work fine. Thanks!

**Comment by robert914** [comment]
Oh, I noticed another error in the documentation regarding the new `lmod_config.lua` file. The example code shows:
```
-- Note that this directory could be anything including /etc/lmod
cosmic:assign("LMOD_PACKAGE_DIR", "/path/to/SitePackage_Dir/")
```
That should read `LMOD_PACKAGE_PATH`, so you might want to correct that at some point.

**Comment by rtmclay** [comment]
I am glad this is working, closing this issue
