### ISSUE TITLE
[8.6] Missing dependency message when loading a module without specifying a version

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#548]
The behavior we're seeing is a little hard to summarize in just a few words, so apologies for the vague issue title :grin: 
But it's definitely something new in 8.6, we verified that it doesn't happen with 8.5.20.

Here's an example: let's say you have a module `A/1.0` that depends on `B/2.0`, and that `B/2.0` depends on `A/1.0` as well (this kind of circular dependency has never been a problem before):

`A/1.0.lua`:
```lua
depends_on("B/2.0")
```

`B/2.0.lua`:
```lua
depends_on("A/1.0")
```

With Lmod 8.5.x, you can load `A` without specifying the version, and all looks fine:
```
$ ml --version

Modules based on Lua: Version 8.5.20  2021-10-20 10:04 -05:00
    by Robert McLay mclay@tacc.utexas.edu

$ ml A
$ ml

Currently Loaded Modules:
  1) B/2.0   2) A/1.0
```

But with Lmod 8.6, loading `A` leads to the following message:
```
The following dependent module(s) are not currently loaded: A/1.0 (required by: B/2.0)
```
Loading `A/1.0`, explicitly specifying the version number listed in `B`'s dependencies, works:

```
$ ml --force purge
$ ml
No modules loaded
$ ml --version

Modules based on Lua: Version 8.6  2021-12-06 17:19 -06:00
    by Robert McLay mclay@tacc.utexas.edu

$ ml A
---------------------------------------------------------------------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: A/1.0 (required by: B/2.0)
---------------------------------------------------------------------------------------------------------------------------------------------
$ ml purge
$ ml A/1.0
$ ml

Currently Loaded Modules:
  1) B/2.0   2) A/1.0
```

Is this expected? 

Thanks!

**Comment by rtmclay** [comment]
I was able to reproduce your issue and fix it for me.  Please test Lmod 8.6.1 to see if it works for you. Thanks very much for the bug report!

**Comment by kcgthb** [comment]
Hi Robert!
I can confirm that 8.6.1 fixes the issue for us.
Thanks a lot for the quick fix!
