### ISSUE TITLE
[8.6] can we add /etc/lmod/lmodrc.lua to the search list for the lmodrc.lua file?

### ISSUE THREAD

**Issue by robert914** [TACC/Lmod#550]
According to the documentation: https://lmod.readthedocs.io/en/latest/145_properties.html
The search order for the various `lmodrc.lua` files is:

1. /apps/lmod/X.Y.Z/init/lmodrc.lua
2. /apps/lmod/etc/lmodrc.lua
3. /etc/lmodrc.lua
4. $HOME/.lmodrc.lua
5. $LMOD_RC

It currently searches `/etc/lmodrc.lua`, but I'd like the file to be within `/etc/lmod` where I'm placing all the other files. I can't override `$LMOD_RC` from `/etc/lmod/lmod_config.lua` apparently either since it's not handled in `myGlobals.lua`, and I kinda think that wouldn't be the best thing to do anyway.

So, would it be possible to add `/etc/lmod/lmodrc.lua` to the search list, maybe added between 2-3 like this:

1. /apps/lmod/X.Y.Z/init/lmodrc.lua
2. /apps/lmod/etc/lmodrc.lua
3. /etc/lmod/lmodrc.lua
4. /etc/lmodrc.lua
5. $HOME/.lmodrc.lua
6. $LMOD_RC

This would make it easier to have all the Lmod configuration files in a single location under `/etc/lmod`. Thanks!

**Comment by rtmclay** [comment]
I have added /etc/lmod/lmodrc.lua to the list of paths searched for this file.  I have also fixed it so that LMOD_RC can be overridden in the lmod_config.lua file.

Please test Lmod 8.6.1 to see if works for you.

**Comment by robert914** [comment]
Excellent! Thank you very much! I'll test as soon as `8.6.1` releases, unless you want me to test `master`?

**Comment by rtmclay** [comment]
8.6.1 is released.

**Comment by robert914** [comment]
Excellent, I just tested out `8.6.1` and both methods work fine! It finds `/etc/lmod/lmodrc.lua` if present, and I can also set `LMOD_RC` to another file in `lmod_config.lua` and it uses that as well.

Thanks for the quick fix!

**Comment by rtmclay** [comment]
Great!  Closing this issue.
