### ISSUE TITLE
Odd behaviour of ml spider (Lmod v. 8.4.11)

### ISSUE THREAD

**Issue by akesandgren** [TACC/Lmod#551]
When doing ml spider GROMACS/2019 the output is somewhat strange.
We have both a pure CPU module and a CUDA enabled module in the HMNS:
/hpc2n/eb/modules/all/MPI/GCC/8.3.0/OpenMPI/3.1.4/GROMACS/2019.lua
and
/hpc2n/eb/modules/all/MPI/GCC-CUDA/8.3.0-10.1.243/OpenMPI/3.1.4/GROMACS/2019.lua

The description of these two differ slightly.
CPU-only build:
```
less /hpc2n/eb/modules/all/MPI/GCC/8.3.0/OpenMPI/3.1.4/GROMACS/2019.lua 
help([==[

Description
===========
GROMACS is a versatile package to perform molecular dynamics,
 i.e. simulate the Newtonian equations of motion for systems with hundreds to millions of particles.

This is a CPU only build, containing both MPI and threadMPI builds.


More information
================
 - Homepage: http://www.gromacs.org
]==])

whatis([==[Description: 
GROMACS is a versatile package to perform molecular dynamics,
 i.e. simulate the Newtonian equations of motion for systems with hundreds to millions of particles.

This is a CPU only build, containing both MPI and threadMPI builds.
]==])
```

and the GPU build:
```
less /hpc2n/eb/modules/all/MPI/GCC-CUDA/8.3.0-10.1.243/OpenMPI/3.1.4/GROMACS/2019.lua 
help([==[

Description
===========
GROMACS is a versatile package to perform molecular dynamics,
 i.e. simulate the Newtonian equations of motion for systems with hundreds to millions of particles.

This is a GPU enabled build, containing both MPI and threadMPI binaries.


More information
================
 - Homepage: http://www.gromacs.org
]==])

whatis([==[Description: 
GROMACS is a versatile package to perform molecular dynamics,
 i.e. simulate the Newtonian equations of motion for systems with hundreds to millions of particles.

This is a GPU enabled build, containing both MPI and threadMPI binaries.
]==])
```

When doing ml spider GROMACS/2019 we get this rather odd result.
```
ml spider GROMACS/2019

----------------------------------------------------------------------------------------------------------------------------------------------
  GROMACS: GROMACS/2019
----------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      GROMACS is a versatile package to perform molecular dynamics, i.e. simulate the Newtonian equations of motion for systems with hundreds
      to millions of particles. This is a CPU only build, containing both MPI and threadMPI builds. 


    You will need to load all module(s) on any one of the lines below before the "GROMACS/2019" module is available to load.

      GCC/8.3.0  CUDA/10.1.243  OpenMPI/3.1.4
      GCC/8.3.0  OpenMPI/3.1.4
 
    Help:
      Description
      ===========
      GROMACS is a versatile package to perform molecular dynamics,
       i.e. simulate the Newtonian equations of motion for systems with hundreds to millions of particles.
      
      This is a GPU enabled build, containing both MPI and threadMPI binaries.
      
      
      More information
      ================
       - Homepage: http://www.gromacs.org
```
Note how it mixes the description from both of them, first the CPU build then the GPU build.

Is this something that is fixed in later versions of Lmod?

I'd actually prefer if it would detect that the description and help differs and either prints them both under the respective toolchain, or not print it at all but writes a pointer to how to get the ml show output instead for the specific builds

**Comment by rtmclay** [comment]
I was able to reproduce the error you reported and have fix this in my version. Please test Lmod 8.6.2 to see that the description and help sections are from the same modulefile.

The output from spider level 2 (which is what you are seeing here) needs to be from just one modulefile.  However, I will be interested in adding some text that says something like:

```
    General Description: (module help <module> for specific help)
```

Thoughts?

**Comment by akesandgren** [comment]
8.6.2 makes the output consistent, thanks.

With the "General Description" stuff, do you suggest that we'd put the build details only in the help message?

This is EasyBuild generated and would require a bit of change to EB to be able to do that since it currently generates both the
help(...) and whatis() lines from a single "description=..." string.
It probably won't be to hard to change that though.

If so, ml spider should probably not output the "Help:" part when there are multiple toolchains to choose from in a HMNS setup but just the "General Description" part.

I hope I didn't misunderstand you too much...
