### ISSUE TITLE
Use properties in isVisible hook

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#552]
I'm looking if we can use properties of a module in the `isVisible` hook. The specific use case would be to 'hide' modules with the gpu property on non-gpu nodes.

As far as I figure out, it's not possible today as the hook only gets a table with:
- fullName
- sn (short name)
- fn (file path)

The properties are part of the module itself. It's not clear to me if we could get access to this kind of information in the hook?

**Comment by rtmclay** [comment]
I have modified Lmod 8.6.2 to add mname and mt objects to the table that is passed to the isVisible Hook routine.

You can use function ```mt:haveProperty(sn, propName, propValue)``` to check for arch gpu. For example:
```
   local haveGpu = mt:haveProperty(sn,"arch","gpu")
```

**Comment by wpoely86** [comment]
Thanks Robert. I will give it a spin!

It could be a nice topic for a future Lmod monthly talk on how exactly you got this done cause I'm not sure I fully understand it ;)

**Comment by rtmclay** [comment]
O.K. to close this issue?
