### ISSUE TITLE
env_modules_python.py with a few more additions

### ISSUE THREAD

**Issue by paulmelis** [TACC/Lmod#553]
Didn't want to go through the pull request workflow as I we don't have LMOD installed for development (I'm merely an end-user), hence the full script below. It took me a bit of time to figure out how to use this little snippet of Python from the docs only, so here's some suggestions for improvements. This adds a docstring, raises an exception in case the `lmod python` command returned with a non-zero exit code and adds a debug flag. 

```
# -*- python -*-
from __future__ import print_function
from subprocess import PIPE, Popen
import os, sys 


def module(command, *arguments, **kwargs):
    """
    Execute a regular LMOD command and apply environment changes to
    the current Python environment (i.e. os.environ).
    
    In case len(arguments) == 1 the string will be split on whitespace into 
    separate arguments. Pass a list of strings to avoid this.
    
    Raises an exception in case LMOD execution returned a non-zero
    exit code.
    
    Use with keyword argument show_environ_updates=True to show the actual
    changes made to os.environ (mostly for debugging).
    
    Examples:
    module('list')
    module('load', 'gcc')
    module('load', 'gcc cmake')
    module('load', 'gcc cmake', show_environ_updates=True)
    """
    numArgs = len(arguments)
    A = ['/usr/share/lmod/lmod/libexec/lmod', 'python', command]
    if (numArgs == 1):
        A += arguments[0].split()
    else:
        A += list(arguments)
        
    proc           = Popen(A, stdout=PIPE, stderr=PIPE)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        raise ValueError('LMOD returned non-zero exit code %d:\n%s' % \
            (proc.returncode, stderr.decode()))
    err_out=sys.stderr
    if (os.environ.get('LMOD_REDIRECT','no') != 'no'):
        err_out=sys.stdout
        
    print(stderr.decode(),file=err_out)
    
    if 'show_environ_updates' in kwargs:
        print(stdout.decode())
    exec(stdout.decode())
```

**Comment by rtmclay** [comment]
Thanks for the update to env_modules_python.py.  I was able to use almost everything from the above.  However, I don't want the raise ValueError() in the default version. I want Lmod errors to be printed out to stderr and not generate a Python error string.  You are free to keep it in your copy of course.  I have updated the master branch with this change.

Please spell Lmod this way: Lmod

Thanks!

**Comment by paulmelis** [comment]
The reason for raising an error in case of an Lmod returncode != 0 was to be able to catch errors when `module()` is used in scripts, as `module()` doesn't return any status information that can be used without human inspection. An alternative could be to return the returncode value from `module()`.

**Comment by rtmclay** [comment]
I have used your second suggestion and returned the returncode and stderr.decode() from module().  Please test this update from the master branch when you get a chance.  Thanks!

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by paulmelis** [comment]
Yes!
