### ISSUE TITLE
Modue swap/switch broken when called with one argument

### ISSUE THREAD

**Issue by xavierabellan** [TACC/Lmod#558]
We have observed a change of behaviour with module switch swap on the latest versions. While previously, a swap with just one argument would work (provided you had a different version of the same module loaded), it is no longer the case on 8.6.6: To illustrate the problem, here is the original behaviour:

```
$ module --version

Modules based on Lua: Version 8.5.6  2021-06-22 08:18 -05:00
    by Robert McLay mclay@tacc.utexas.edu
$ module list
No modules loaded
$ module load git
$ module list

Currently Loaded Modules:
  1) git/2.30.1


$ module swap git/old

The following have been reloaded with a version change:
  1) git/2.30.1 => git/2.26.0

$ module list

Currently Loaded Modules:
  1) git/2.26.0

```
And here is the new behaviour:
```
$ module --version

Modules based on Lua: Version 8.6.6  2022-01-21 15:09 -06:00
    by Robert McLay mclay@tacc.utexas.edu

$ module list
No modules loaded
$ module load git
$ module list

Currently Loaded Modules:
  1) git/2.30.1


$ module swap git/old
Lmod has detected the following error:  Swap failed: "git/old" is not loaded.

```
I find the original behaviour more consistent with what module (both Lmod and the classic TCL version) has traditionally allowed.

I tried to find where that change came from so I could propose a fix, but I am not too familiar with the Lmod internals so probably best for someone else to have a look.

**Comment by rtmclay** [comment]
Thanks for the bug report!  I had forgotten about this use case.  Now it is part of the tests so I won't forget it again.

I want to clarify that there is no support for "old" you have to specify the actual version.  I have created version 8.6.8 which corrects this issue.  Here is now what is supported:
```
$ module load git
$ module list

Currently Loaded Modules:
  1) git/2.30.1


$ module swap git/2.26.0
The following have been reloaded with a version change:
  1) git/2.30.1 => git/2.26.0
```

In other words ```module swap git/old``` has **NEVER** been supported.  With Lmod 8.6.8 you can now do ```module swap git/2.26.0``` assuming that git/2.26.0 exists.

The change that caused the difference between 8.5.6 and 8.6.6 was: Issue #518 that was introduced in Lmod 8.5.7

Please test 8.6.8 to see if works for you.

**Comment by rtmclay** [comment]
Great! Closing this issue.  I glad that it is working for you.
