### ISSUE TITLE
"module avail" recursively search for module files in modulefiles/?

### ISSUE THREAD

**Issue by simon-Leary42** [TACC/Lmod#561]
Currently I have module files in .../modulefiles/name/version.lua
What I want to do is make a new one in .../modulefiles/name/category/version.lua.
When I did this, I am able to do "module load name/category" just fine.
But when I do "module avail name", I was hoping to see category/version as one of the entries, but I do not.
"module spider" also doesn't find this file.

How can I make "module avail" look through this new category folder for modulefiles?

**Comment by rtmclay** [comment]
Lmod supports C/N/V.  That is Category/Name/Version.  This is typically Bio/bowtie/3.0  where Category is bio, Name is bowtie and the version is 3.0.  To load this module you have to do either "module load bio/bowtie" or module load bio/bowtie/3.0"

Also Lmod supports N/V/V.  That is Name/Version/Version.  So a typical name could be bowtie/64/3.0.  Where the name is bowtie and the version is 64/3.0.

Now Lmod supports both but it assumes that every name is either N/V or C/N/V.  To tell Lmod that you want a particular module to be N/V/V you have to put an empty .version or .modulerc or .modulerc.lua file in the directory that is the beginning of the version section.  In other words in the bowtie directory there would be a .modulerc file and a 64 directory.

Note that having a single N/V/V modulefile in your module tree changes the rules for searching from find best to find first searching.   Be sure you want to use N/V/V modulefiles and know the consequences of that choice.

See https://lmod.readthedocs.io/en/latest/055_module_names.html for details.  In fact, you should read every section that mentions N/V/V

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by simon-Leary42** [comment]
you can close the issue.
