### ISSUE TITLE
Latest 8.6.10 has new "echo" output?

### ISSUE THREAD

**Issue by robert914** [TACC/Lmod#563]
With the latest 8.6.10 release, I'm seeing this message every time I login now:
```
Last login: Thu Feb  3 15:41:05 2022 from 10.0.2.2
unsetting noglob
❯
```
It also appears after commands too:
```
❯ module avail
...
unsetting noglob
❯
```

It appears to be coming from `init/bash` here:
```
     eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
     if [ -n "${_mlshopt:-}" ]; then
       set +$_mlshopt;
       echo "unsetting noglob";
     fi;
```
Is this a leftover debugging line? I don't think we want that message being output normally, do we?

**Comment by rtmclay** [comment]
Thanks for pointing that out.  I have updated Lmod to 8.6.11.  You might consider configuring Lmod with --with-silentShellDebug=yes.  That is what I use to avoid seeing the output from lmod when I'm debugging shell scripts with set -xv

**Comment by robert914** [comment]
Ah, thanks for pointing that out! I didn't realize `set -x` would cause `module` to output it's commands. I will disable that.

**Comment by robert914** [comment]
Ok, the 8.6.11 got rid of that echo output. Thanks again for that shell tip!
