### ISSUE TITLE
source_sh not taking care of 'complete' command in bash

### ISSUE THREAD

**Issue by cniethammer** [TACC/Lmod#567]
Lmods `source_sh` does not take care of bash completions.

Example: If an environment setup script containing
```shell
function _complete_mycmd() { ... }
complete -F _complete_mycmd mycmd
```
is sourced by a module via `source_sh("bash", <ENV_SCRIPT>)` the function `_complete_mycmd` will end up in the environment after this module is loaded but the complete will not be registered.

This affects, e.g., integrating the environment setup of [spack](https://spack.io/) via lmod modules.

Affected/tested Lmod version: 8.6.12 (8.6.12-3-g941f09c6) 2022-02-09 16:10 -06:00

References:
- https://lmod.readthedocs.io/en/latest/260_sh_to_modulefile.html#converting-shell-scripts-to-modulefiles
- https://spack.readthedocs.io/en/latest/getting_started.html (Section shell support)

**Comment by rtmclay** [comment]
Well no module system has supported the complete function in bash.  It is not clear that Lmod will support it or not.  This is a  harder thing to support that one might think.   If this is going to be supported then it will take some time.   There are many questions like how many shells support a complete function or similar.  I know that bash does. Zsh has something similar but it not the same.  Does spack support tab completion for zsh?

If you are interested in having a spack module with bash tab completion support any time soon, then I recommend that you use sh_to_modulefile to convert the script to a module and then use the execute{} function to handle the complete function.

You will have to add execute{} code by hand to the generated modulefile.

**Comment by xdelaruelle** [comment]
Hi @rtmclay. I have just finished such support last week. This is doable for bash, tcsh and fish. I did not find equivalent commands for other shells.

If you are interested, I have made design notes for the addition of complete/uncomplete modulefile commands: https://modules.readthedocs.io/en/latest/design/shell-completion.html

I have also updated notes of `source-sh` to take into account completion setup by scripts evaluated through sh-to-mod sub-command and source-sh modulefile command: https://modules.readthedocs.io/en/latest/design/source-shell-script-in-modulefile.html

**Comment by cniethammer** [comment]
Thanks for the info.
Great to here, that there is already work done to support this in the future. I'd happy to test it if ready.

**Comment by xdelaruelle** [comment]
> Thanks for the info. Great to here, that there is already work done to support this in the future. I'd happy to test it if ready.

I need to clarify that this work was done on another project, not Lmod. But the notes made for this development could help the Lmod team to implement such capabilities.

**Comment by rtmclay** [comment]
I have created a branch called testing which has support for "complete" and support for complete in sh_to_modulefile and source_sh().

@xdelaruelle: Thanks for letting me know about your changes to your source code.  It was a great help!

@cniethammer: If you get the chance, please test the branch called testing to see if it fixes the issue for you.

**Comment by rtmclay** [comment]
I have merged the testing branch into the master branch.  If you get a chance, please test Lmod 8.6.15 to see if it works for you.

**Comment by cniethammer** [comment]
Thanks a lot for the effort.

I finally found some time to test this. I tried with 0b329ae7b2393c6210244afa59fad4518b256fb0
My simple test failed unfortunately with some bash error message. I enabled debug mode and output in the sourced bash script and got the following:
```
module load bashcomp 
+ echo %__________blk_divider__________%
+ /usr/bin/lua /home/christoph/bin/lmod/lmod/libexec/printEnvT.lua envT
+ echo %__________blk_divider__________%
+ alias
+ echo %__________blk_divider__________%
+ declare -f
+ echo %__________blk_divider__________%
+ complete
+ echo %__________blk_divider__________%
bash: syntax error near unexpected token `;'
```
```
cat modulefiles/bashcomp.lua
source_sh("bash", "~/codes/hpc-workspace/contribs/completion/ws_tools.sh")
```
The sourced bash completion script can be found here: https://github.com/cniethammer/hpc-workspace/blob/master/contribs/completion/ws_tools.sh
Sourcing this script directly in the shell works just fine.

**Comment by rtmclay** [comment]
Thanks for testing this out and reporting your issues.  I was able to reproduce your issue and fix it for me.  Please access the testing branch at github to see if it works for you.  Thanks!

**Comment by cniethammer** [comment]
Perfect! Yes, the current version in testing (20ccf4de7b15dc3beedf63d12c00d37baf1b8129) works for me.

**Comment by wyphan** [comment]
Please ignore the mention, I meant to reference issue 554 (which is now closed).
