### ISSUE TITLE
`ml show` error when module contains `set-shell_function()`

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#568]
When a Lua module contains `set_shell_function()`, it looks like `ml show` generates an error.

For instance, with that very simple `test/01.lua` modulefile:
```
pushenv("TEST", "test")
set_shell_function("foo", "echo ok")
```
loading works fine and the shell function is correctly defined:
```
$ ml test/01
$ echo $TEST
test
$ typeset -f foo
foo ()
{
    echo ok
}
```
but `ml show` generates the following error:
```
$ ml show test/01
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /share/software/modules/staging/test/01.lua: /share/software/user/open/lmod/lmod/libexec/MC_Show.lua:344: attempt to index local
'cshStr' (a nil value)
     Please check the modulefile and especially if there is a line number specified in the above message
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test/01          /share/software/modules/staging/test/01.lua
```

Commenting the `set_shell_function()` line prevents the error:
```
$ cat 01.lua
pushenv("TEST", "test")
--set_shell_function("foo", "echo ok")
$ ml show test/01
------------------------------------------------------------------------------------------------------------------------------------
   /share/software/modules/staging/test/01.lua:
------------------------------------------------------------------------------------------------------------------------------------
pushenv("TEST","test")
```

This can be reproduced with 8.6.5 and 8.6.12 versions.

**Comment by rtmclay** [comment]
As the docs show, set_shell_function() takes three arguments.  The third argument is the csh alias.  So if you do:

set_shell_function("foo", "echo ok", "") then the current version of Lmod will work fine.  I have updated my copy to have empty third argument.  This will be release as part of Lmod 8.6.13

**Comment by kcgthb** [comment]
Aah, sorry I missed that! Thanks for pointing it out.

**Comment by rtmclay** [comment]
Please test Lmod 8.6.13 to see that your original module file works with "module show"

**Comment by kcgthb** [comment]
Thanks @rtmclay ! Version 8.6.13 indeed shows the module contents, even if the `set_shell_function()` call misses the 3rd argument. It actually displays the corrected version :)
```
$ cat /share/software/modules/staging/test/01.lua
set_shell_function("foo", "echo ok")
$ ml show test
------------------------------------------------------------------------------------------------------
   /share/software/modules/staging/test/01.lua:
------------------------------------------------------------------------------------------------------
set_shell_function("foo","echo ok","")
```

Problem solved, thanks a lot!
