### ISSUE TITLE
8.6.13: error sourcing `init/bash`

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#571]
In 8.6.13, we noticed an error when sourcing `$BASH_ENV`, that didn't happen with 8.6.12.

**8.6.12**:
```
$ source /share/software/user/open/lmod/8.6.12/init/bash
$
```
**8.6.13**:
```
$ source /share/software/user/open/lmod/8.6.13/init/bash
-bash: export: __lmod_file_glob_on: not a function
$
```

The error seems to be happening in https://github.com/TACC/Lmod/blob/f1d670752ca1d760da865a6be78d587df5df1741/init/bash.in#L150 as `__lmod_file_glob_on` doesn't appear to be defined.

**Comment by rtmclay** [comment]
Thanks for pointing this out.  This is fixed in Lmod 8.6.14

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by kcgthb** [comment]
Hi @rtmclay!
Apologies for the delay: I just tested 8.6.14 and the issue is indeed resolved, thank you very much!
Happy to close this.
