### ISSUE TITLE
Documentation for Lua installation assumes `x86_64` architecture

### ISSUE THREAD

**Issue by wyphan** [TACC/Lmod#573]
I'm in the process of installing Lmod on my [NVIDIA Jetson Nano dev kit](https://developer.nvidia.com/embedded/jetson-nano-developer-kit), which is a system with `aarch64` architecture (Arm v8). The default OS installed when you flash the JetPack image to the MicroSD card is Ubuntu 18.04 LTS.

Looks like the documentation for installing Lua at https://lmod.readthedocs.io/en/latest/030_installing.html is hardcoded for the `x86_64` architecture, such as the `amd64` architecture code for Debian/Ubuntu packages and the `luaposix` symlink fix having the `x86_64-linux-gnu` triple. For the Arm64 platform, the `amd64` arch can be replaced with `arm64`, and the correct system triple would be `aarch64-linux-gnu`.

The main reason I'm submitting this issue instead of a PR is to enable brainstorming on the solution. For instance, `ppc64el` (IBM Power9) is another common architecture in current leadership-class systems that isn't `x86_64`.

**Comment by rtmclay** [comment]
I am open to suggestions on how to write the documentation.  I feel that I can not cover every version of Linux on every architecture.  I would hope that knowing how to install it one architecture it would be clear how to install in on the same version of linux with a different architecture.

For example, it was easy to  Lmod and Lua on an IBM power9 running Redhat.

If you have suggestions that provide guidance without having to be specific for every favor of Linux and architecture please let me know.

**Comment by wyphan** [comment]
> it was easy to Lmod and Lua on an IBM power9 running Redhat

That's a good point. What I'm suggesting is simply providing three tabs in the documentation for the most common arches (`x86_64`, `ppc64el`, and `aarch64`) where each tab contains architecture-specific information. Or, if that's too much for readthedocs, maybe simply add a sentence saying something along the line of "customize the following to your system arch and distro".

**Comment by wyphan** [comment]
Btw, I just found out the hard way that sourcing the Lmod init script by creating a symlink (as suggested in the docs) breaks my Unity session :joy:

**Comment by rtmclay** [comment]
Closing this issue.  Feel free to re-open.
