### ISSUE TITLE
Failed to unload both compiler and MPI module

### ISSUE THREAD

**Issue by wjnadia** [TACC/Lmod#574]
I recently installed Lmod 8.6.17 over environment modules 3.2.10-10.
Overall, I am satisfied with it's features.
A problem occurred during unloading of them, after loading compiler and MPI modules with dependencies  such as below;
But, I had success when unloading in the order of MPI and compiler module.  (Also, no problem if I don't use Lmod)
The modules were written in the previous modules's language.
Please help on this issue.

**1148% [test@glogin02 ~]$ ml gcc/4.8.5 mpi/openmpi-3.1.5**

**1157% [test@glogin02 ~]$ ml**

Currently Loaded Modules:
  1) singularity/3.9.7   2) nvtop/1.1.0   3) htop/3.0.5   4) gcc/4.8.5   5) mpi/openmpi-3.1.5

**1149% [test@glogin02 ~]$ ml -gcc/4.8.5 -mpi/openmpi-3.1.5**
        **_mpi/openmpi-3.1.5 Load Error: COMPILER env vars were not properly defined
        mpi/openmpi-3.1.5 is need a compiler_**
        Please set environment using the $ module load {compiler_module} mpi/openmpi-3.1.5
        This module is for use of mpi/openmpi-3.1.5
        use example:
            $ module load intel/18.0.2 mpi/openmpi-3.1.5

**1150% [test@glogin02 ~]$ ml -mpi/openmpi-3.1.5 -gcc/4.8.5** 

**1157% [test@glogin02 ~]$ ml**

Currently Loaded Modules:
  1) singularity/3.9.7   2) nvtop/1.1.0   3) htop/3.0.5 

**[gcc/4.8.5 module file]**
#%Module

proc ModulesHelp { } {
    puts stderr "\tThis module is for use of [module-info name]."
    puts stderr "\tIt needs module(s):"
    puts stderr "\t                  None"
    puts stderr "\tUse example:"
    puts stderr "\t        \$ module load [module-info name]"
    puts stderr "\t"
}

conflict gcc
conflict pgi
conflict intel

set name           gcc
set version        4.8.5
set version2       4.8.5

set prefix         /apps/compiler/$name/$version
set gnu_prefix     /apps/compiler/$name/$version

setenv          COMPILER_PREFIX     $gnu_prefix
setenv          COMPILER            gnu
setenv          COMPILER_VER        $version
setenv          FORTRAN_TYPE        gfortran
setenv          CC                  gcc
setenv          CXX                 g++
setenv          FC                  gfortran
setenv          F90                 gfortran

setenv          PE_ENV              GNU
setenv          GCC_PATH            $gnu_prefix
setenv          GCC_VERSION         $version
setenv          GNU_VERSION         $version

module-whatis   "This module is for use of GNU [module-info name]."

if {![file exists $prefix]} {
    puts stderr "\t[module-info name] Load Error: $prefix does not exist"
    break
    exit 1
}

catch {set cur_manpath $env(MANPATH)}
if {![info exists cur_manpath]} { setenv MANPATH /usr/share/man }

append-path     LD_LIBRARY_PATH      /usr/lib64:/usr/lib64/slurm
append-path     LD_LIBRARY_PATH      /usr/local/lib
append-path     MANPATH              /usr/local/share/man

setenv          KISTI_COMPILER_VER       $version2
setenv          KISTI_COMPILER_HOME      /apps/compiler/$name/$version2
setenv          KISTI_APPLIB1            /apps/compiler/$name/$version2/applib1

**[mpi/openmpi-3.1.5 module file]**

%Module1.0

proc ModulesHelp { } {
    puts stderr "\tThis module is for use of [module-info name]"
    puts stderr "\tuse example:"
    puts stderr "\t    $ module load intel/18.0.2 [module-info name]\n"
}

conflict mpi
conflict cudampi

catch {set COMPILER $env(COMPILER)}
catch {set COMPILER_VER $env(COMPILER_VER)}
if {![info exists COMPILER] || ![info exists COMPILER_VER]} {
    puts stderr "\t[module-info name] Load Error: COMPILER env vars were not properly defined"
    puts stderr "\t[module-info name] is need a compiler"
    puts stderr "\tPlease set environment using the $ module load {compiler_module} [module-info name]\n"
    ModulesHelp
    break
    exit 1
}

catch {set KISTI_CUDA_VER $env(KISTI_CUDA_VER)}
if {[info exists KISTI_CUDA_VER]} {
    puts stderr " "
    puts stderr "\t[module-info name] is not a CUDA version."
    puts stderr "\t[module-info name] does not require the CUDA SDK."
    puts stderr " "
    ModulesHelp
    break
    exit 1
}

set     name            openmpi
set     version         3.1.5
set     version2        3.1.5
set     prefix          $env(KISTI_COMPILER_HOME)/mpi/$name/$version

if {![file exists $prefix]} {
    puts stderr "\t[module-info name] Load Error: $prefix does not exist"
    ModulesHelp
    break
    exit 1
}

module-whatis   "loads the $name environment"

setenv          MPI                 $name
setenv          MPI_VER             $version

setenv          MPICH_HOME          $prefix
setenv          MPIHOME             $prefix
setenv          MPI_HOME            $prefix
setenv          MPI_ROOT            $prefix

prepend-path    PATH                $prefix/bin
prepend-path    LD_LIBRARY_PATH     $prefix/lib
append-path     MANPATH             $prefix/share/man

setenv          KISTI_MPI_VER       $version2
setenv          KISTI_MPI_HOME      $env(KISTI_COMPILER_HOME)/mpi/$name/$version2
setenv          KISTI_APPLIB2       $env(KISTI_COMPILER_HOME)/mpi/$name/$version2/applib2

**Comment by rtmclay** [comment]
This is a feature of Lmod and not a bug.  If you unload the gcc module then the mpi/openmpi-3.1.5 module, the COMPILER and COMPILER_VER have been unset by the gcc module and are therefore undefined when unloading your mpi/openmpi-3.1.5 module.

I would recommend that you change your mpi/openmpi-3.1.5 module to only test the value of $COMPILER and $COMPILER_VERSION when the mode is load:
```
 if [ module-info mode load ] {
        if {![info exists COMPILER] || ![info exists COMPILER_VER]} {
                ...
       }
}

``` 

You need to use KISTI_MPI_HOME to set $prefix on unload.  So if KISTI_MPI_HOME doesn't exist on load then set it otherwise use it to prepend-path and append-path.  You may want to a  unique env. name like KISTI_OPENMPI_HOME for the openmpi modules and say KISTI_MPICH_HOME for mpich etc.

Comments?
