### ISSUE TITLE
suggest warning when unloading a module that is not loaded or auto completion

### ISSUE THREAD

**Issue by sbrozell** [TACC/Lmod#576]
With the proliferation of modules, partly driven perhaps by spack, the silence of module unload is becoming too error prone imho.  It is all too easy for users to do `module unload netcdf` and think it worked when they needed to do `module unload netcdf-c` or worse `module unload netcdf-cxx4-somesillyhash`

Of course, our motto is "don't trust but verify" so we advise ending the module command section with `module list` and experts can use is-loaded in a disciplined script, but humans will be human.

More fancy would be auto completion. Clearly, this creates a new realm of errors.  It could be tailored with command line options ...

thanks for your work,
scott

**Comment by rtmclay** [comment]
I am thinking about this.  It is not an error or a warning to unload a module that is not loaded.  Making lmod produce a non-zero exit status would break too many scripts.

Note that tab completion should be used to unload the correct module so: 
```
module unload netcdf<TAB>
```
But in scripts I can see the problem.  But I'm not sure that how helpful a message would be if the command status won't change.

If I was going to add a message when unloading a module, do you have a recommendation for the wording.  Here is what I'm thinking:

```
% module unload foo                                
Note: the module "foo" was not loaded.
%
```

**Comment by sbrozell** [comment]
I think it would be helpful.  There are typos, cut-n-paste-without-proper-updating errors, global substitution snafus, yada.  Of course, some (many) aren't reading outputs carefully, but we can try to help them discover their errors earlier rather than later.
Your text looks good.  More verbose would be 
`Note: the module "foo" cannot be unloaded because it was not loaded.`
for those readers missing the context.

**Comment by sbrozell** [comment]
It works for me.  Another newline at the tail of the note might be apt.

**Comment by rtmclay** [comment]
I have updated Lmod to have newlines before and after the message.  This is now released as Lmod 8.7.2.  If you get a chance please test Lmod 8.7.2.

**Comment by sbrozell** [comment]
The new message looks good.  Thanks.  Scott

**Comment by rtmclay** [comment]
Thanks for checking this change out and making the recommendation.
