### ISSUE TITLE
module purge causes nested sticky module to be lost

### ISSUE THREAD

**Issue by vanderwb** [TACC/Lmod#579]
We are trying to use the "sticky" capability to preserve both a top-level and a second-level module within the user's module set unless forced out. This works if we only have the top-level, but if there is a sticky module a level below as well, it gets removed during an ordinary `module purge`. See the commands below for the behavior. This outcome seems erroneous to me, but let me know if I am misunderstanding the sticky setting in some manner.

**Potentially relevant details:**
- Lmod Version 8.5.6
- Installed via Spack with default settings
- `ncarenv` module is Lua, `craype` module is Tcl

**Example:**
```
CPE@cheyenne5:Core> module list

Currently Loaded Modules:
  1) ncarenv/22.02 (S)   2) craype/2.7.9 (S)   3) cce/13.0.1   4) ncarcompilers/0.5.2   5) cray-mpich/8.1.13   6) hdf5/1.10.7   7) netcdf/4.8.1   8) cray-libsci/21.08.1.2

  Where:
   S:  Module is Sticky, requires --force to unload or purge



CPE@cheyenne5:Core> module purge
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) ncarenv/22.02

The following sticky modules could not be reloaded:

  1) craype/2.7.9
CPE@cheyenne5:Core> module list

Currently Loaded Modules:
  1) ncarenv/22.02 (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge



CPE@cheyenne5:Core> module load craype
CPE@cheyenne5:Core> module list

Currently Loaded Modules:
  1) ncarenv/22.02 (S)   2) craype/2.7.9 (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge
```

**Comment by vanderwb** [comment]
Sure thing:
```
CPE@cheyenne5:Core> module -T purge
Lmod version: 8.5.6  2021-06-22 08:18 -05:00
running: module -T purge
  (1)(0)Unloading: craype (status: active) (fn: /glade/u/apps/crayenv/22.02/modules/Core/craype/2.7.9)
  (2)(0)Unloading: ncarenv (status: active) (fn: /glade/u/apps/crayenv/22.02/modules/environment/ncarenv/22.02.lua)
    Removing: /glade/u/apps/crayenv/22.02/modules/Core from MODULEPATH
  reloadAll(1)()
  (3)(0)Loading: ncarenv/22.02 (fn: /glade/u/apps/crayenv/22.02/modules/environment/ncarenv/22.02.lua, using Find-Best)
    Appending: /glade/u/apps/crayenv/22.02/modules/Core to MODULEPATH
  reloadAll(1)(ncarenv/22.02)
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) ncarenv/22.02

The following sticky modules could not be reloaded:

  1) craype
```

**Comment by vanderwb** [comment]
Sure thing. It's attached with two simple modules and a run script. To avoid our default module tree, I run it with:
```
env -i ./run.sh
```

[lmod_sticky.tar.gz](https://github.com/TACC/Lmod/files/8816032/lmod_sticky.tar.gz)

**Comment by vanderwb** [comment]
Thanks Robert. Indeed, the 8.7.3 version happily resolves the issue. The new version is not yet checksum'd in Spack and so Spack won't install that version without some extra consent, but that's not an Lmod issue. Please feel free to close!

**Comment by vanderwb** [comment]
The latest version supported in Spack, 8.7.2, also works. Thanks again.

**Comment by rtmclay** [comment]
You are welcome and thanks for the env -i ./script.sh trick.  I'll use that to explain how to create test example when submitting bug reports.
