### ISSUE TITLE
Hyphens in family names

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#580]
Hi @rtmclay!

Not really a big problem, and I'm not sure that's fixable, but it could maybe be worth a note in the docs, or a check when loading a module file?

We just found out that using an hyphen in a family name would cause issues when loading a module.

For instance, with the following `test.lua`:
```Lua
-- -*- lua -*-
family("test-hyphen")
```
`module load` shows this:
```
 $ module load test
-bash: LMOD_FAMILY_TEST-HYPHEN=test: command not found
-bash: export: `LMOD_FAMILY_TEST-HYPHEN': not a valid identifier
-bash: LMOD_FAMILY_TEST-HYPHEN_VERSION=false: command not found
-bash: export: `LMOD_FAMILY_TEST-HYPHEN_VERSION': not a valid identifier
-bash: sherlock_FAMILY_TEST-HYPHEN=test: command not found
-bash: export: `sherlock_FAMILY_TEST-HYPHEN': not a valid identifier
-bash: sherlock_FAMILY_TEST-HYPHEN_VERSION=false: command not found
-bash: export: `sherlock_FAMILY_TEST-HYPHEN_VERSION': not a valid identifier
```

I assume this is not just hyphens, but everything that shells don't allow in variable names, which is pretty much anything that's not a number, letter or underscore.

**Comment by rtmclay** [comment]
I'll modify Lmod to throw an error when the family is not in LETTERS or NUMBERS or underscore. In fact it will have to start with a letter.  Anything else is an error.   Thanks for the info.  I'll let you know when this change has been added.

**Comment by rtmclay** [comment]
I have updated the repo to have this fix.  Names for family(), setenv(), pushenv(), prepend_path(), append_path() now get checked for valid names.  There is a different check for aliases and shell function names as the rules for names are much broader.  As far as I know, only spaces and tabs are illegal there.

If you would like, you can test the latest version of Lmod to see if it works for you.

**Comment by kcgthb** [comment]
Yes, it looks like it's working:
```
$ ml test
Lmod Warning:  unsetenv names must be start with a letter followed letters, numbers and underscores (Not;
"LMOD_FAMILY_TEST-HYPHEN")

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test             /tmp/m/test.lua

Lmod Warning:  unsetenv names must be start with a letter followed letters, numbers and underscores (Not;
"LMOD_FAMILY_TEST-HYPHEN_VERSION")

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test             /tmp/m/test.lua

Lmod Warning:  unsetenv names must be start with a letter followed letters, numbers and underscores (Not;
"sherlock_FAMILY_TEST-HYPHEN")

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test             /tmp/m/test.lua

Lmod Warning:  unsetenv names must be start with a letter followed letters, numbers and underscores (Not;
"sherlock_FAMILY_TEST-HYPHEN_VERSION")

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test             /tmp/m/test.lua

Lmod has detected the following error:  family names must be start with a letter followed letters, numbers and underscores (Not;
"test-hyphen")

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test             /tmp/m/test.lua
```



Maybe just a small suggestion: from a usability standpoint, the last message is the most relevant for users and/or sysadmins:

```
Lmod has detected the following error:  family names must be start with a letter followed letters, numbers and underscores (Not; "test-hyphen")
```

The previous warnings are relative to the internal environment variables that Lmod creates to track module properties, but they're not really actionnable, so I'm wondering if they should be displayed at all, since in that case, they're consequences of the main error that is displayed last.

What do you think?

**Comment by rtmclay** [comment]
What you say is true about having a bad family name.   But that is not the only way that a modulefile could be wrong.  Namely a modulefile might also do:
```
setenv("TEST-FOO","BAR")
```
which is has nothing to do with family names.  I think that it is good to having tests for all environment names not just the ones for family().

**Comment by kcgthb** [comment]
That's a very good point, and those checks are indeed useful for environment variables that would be explicitly defined in a module file with `setenv()` or `pushenv()`.

What I meant was that in the case above, those environment variables (like `LMOD_FAMILY_TEST-HYPHEN`) are not explicitly set in the module file, they're created by Lmod internally. So surfacing a warning about them to the user/sysadmin could just be confusing, because their module file doesn't define nor contain any reference to those environment variables.

But I don't think it's a big deal. And it may not be easy to distinguish between env vars that are explicitly defined in the module and those that are generated internally anyway.

**Comment by rtmclay** [comment]
The problem that you are seeing is that you have loaded the "test" module with the older version of Lmod and then tried to reload it.   The LmodError is treated as an LmodWarning when you unloaded the module and then reloaded it.

Try it again in a fresh shell where you haven't already loaded the "test" module and see if it works better.

**Comment by kcgthb** [comment]
Ah but you're right! Of course, that was it.

A fresh load of the module with the hyphenated family name, with the new version, only display the relevant error:
```
$ ml test
Lmod has detected the following error:  family names must be start with a letter followed letters, numbers and underscores (Not;
"test-hyphen")

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test             /tmp/m/test.lua
```

So all looks good, thanks a lot!

**Comment by rtmclay** [comment]
Great!  I'm glad that this worked out well.  Thanks for reporting this issue and all the feedback.  Closing this issue.
