### ISSUE TITLE
Feature request: Export saved collections

### ISSUE THREAD

**Issue by surak** [TACC/Lmod#582]
Is there a way to easily share module collections (as the ones saved in .lmod.d) among users, other than manually copying the .lmod.d/[COLLECTION] files?

**Comment by rtmclay** [comment]
Not perfectly.  There is the "module describe <collection>" command which will report what modules are loaded with that collection.

There is a danger in copying collection files in the case where user A's personal modules are not readable by user B.

**Comment by surak** [comment]
Okay.
