### ISSUE TITLE
Inconsistency of behaviour between module refresh and requireFullName function

### ISSUE THREAD

**Issue by marcodelapierre** [TACC/Lmod#583]
**Describe the bug**
Using the function `requireFullName()` in a modulefile results in a version warning printed when `module refresh` is used. When `module refresh` is used in shell startup scripts, as a result the warning is produced every time a child shell is spawned, and such a module was previously loaded in the parent shell.
 
**To Reproduce**
```
# Tested with latest Lmod 8.7.4
# Also tested with production Lmod 8.3 on our Supercomputer, by explicitly using the `requireFullName()` implementation in the modulefile

$ cat ziosergio/ver2.lua
setenv('marco_test_var','test_value')

if (mode() == "load") then
  requireFullName()
end

$ module use $(pwd)
$ module load ziosergio/ver2
$ module refresh
Lmod has detected the following error:  Module "ziosergio" must be loaded with the version
specified, e.g. "module load ziosergio/ver2". Use

   $ module spider ziosergio

for available versions.
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    ziosergio/ver2   /home/ubuntu/mod-ver-default/ziosergio/ver2.lua


# Alternative test with function implementation in the modulefile

$ cat ziosergio/ver.lua
setenv('marco_test_var','test_value')

if (mode() == "load") then
  if (myModuleUsrName() ~= myModuleFullName()) then
    LmodError(
        "Default module versions are disabled by your systems administrator.\n\n",
        "\tPlease load this module as <name>/<version>.\n"
    )
  end
end

```

**Expected behavior**
I would expect no error message to be printed when `module refresh` is issued.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: both Ubuntu 18.04 and SLES15
 - XALT Version: n/a

**Comment by rtmclay** [comment]
Thanks very much for the very clear Bug Report and using the template provided.  This was a subtle bug that has been around a while.  I was able to reproduce your bug and fix it for me. Please test Lmod 8.7.6 to see if it works for you.

**Comment by marcodelapierre** [comment]
Hi Robert,
many thanks for the quick response, much appreciated! 
I confirm the fix solves my issue on a test Lmod deployment.
