### ISSUE TITLE
How to stop module unload from unloading something which is a prereq for another

### ISSUE THREAD

**Issue by epsilon-0** [TACC/Lmod#586]
If there are module `a/1.0.0` and `b/1.0.0` and `a` has a `prereq` on `b`, something like 
```
prereq(between("b", "1.0.0", "1.0.0"))
```
and then I do 
```
$ module load b/1.0.0
$ module load a/1.0.0
$ module unload b/1.0.0
```

The above commands work correctly, while the `unload b/1.0.0` should not have worked as now there is a broken dependency for `a/1.0.0`.

Is there any way to stop the unload command from succeeding?

**Comment by rtmclay** [comment]
Nope,  there is no support for that with prereq's.  Please use depends_on() instead.  You can read about depends_on() at lmod.readthedocs.io
