### ISSUE TITLE
Cannot spider/load the module that has been actually installed module

### ISSUE THREAD

**Issue by bowentan** [TACC/Lmod#592]
**Description**
System: Ubuntu 20.04/Centos7
Lmod Version: 8.7/8.4.23

I am currently installing the GCC-11.3.0.eb but after installing the help2man-1.49.2-GCCcore-11.3.0.eb, the "unknown module" error occurred as follows, when EasyBuild was installing flex-2.6.4-GCCcore-11.3.0.eb.
```
Lmod has detected the following error:  The following module(s) are unknown: 

"help2man/1.49.2"
```
And I also couldn't find this module via `module spider` or `module avail` commands, in both systems and both Lmod versions. I checked  and guaranteed that the lua file was indeed located in `MODULEPATH` and the related executables were located in software path.

Could you help about this problem?

**Edit**
I also tried the latest version of Lmod (8.7.7) but nothing was changed. The help2man/1.49.2 could't be found still.

**Comment by ocaisa** [comment]
@bowentan I think the right place for this question is at https://github.com/easybuilders/easybuild/issues , it's unlikely this has anything to do with Lmod.

I suggest you take a look the EasyBuild tutorial at https://easybuilders.github.io/easybuild-tutorial/2022-isc22/ , in particular [configuration ](https://easybuilders.github.io/easybuild-tutorial/2022-isc22/configuration/) and [module naming schemes](https://easybuilders.github.io/easybuild-tutorial/2022-isc22/module_naming_schemes/).

It looks like you are using a hierarchical module naming scheme (from your error message). You need to ensure that you are providing the path to `(prefix)/modules/all/Core` in your `MODULEPATH` (this is explained in the tutorial).

**Comment by bowentan** [comment]
@ocaisa Thanks for your reply and I am sure that the `MODULEPATH` was correctly set and all module files are in `modules/all/core`. Actually, there were no problems for previous module building. 

Anyway, I will send this issue to EasyBuild too. Thanks for your suggestions.
