### ISSUE TITLE
Lmod not loading .modulerc.lua ?

### ISSUE THREAD

**Issue by ghferrari** [TACC/Lmod#593]
We have previously experienced the problem described [here](https://giters.com/TACC/Lmod/issues/484) in which Lmod is unable to parse a `.modulerc` file created by EasyBuild. The solution, which was previously working, was to provide a hand-written `.modulerc.lua` with this content:
```
module_version("Java/11.0.2","11")
module_version("Java/13.0.2","13")
```
This solution has previously been working an relies on Lmod loading `.modulerc.lua` in preference to `.modulerc`.

After recently updating to 8.7.7, this fix is no longer working and Lmod complains that it cannot parse `.modulerc`, despite the file `.modulerc.lua` being available.

```
invalid command name "module-info"
    while executing
"module-info version Java/11"
    invoked from within
"if {"Java/11" eq [module-info version Java/11]} {
    module-version Java/11.0.2 11
}"
    (file "/apps/eb/2020b/skylake/modules/all/Java/.modulerc" line 2)
    invoked from within
"source $mRcFile"
    (procedure "main" line 15)
    invoked from within
"main $fn"
    (file "/usr/share/lmod/lmod/libexec/RC2lua.tcl" line 137)
```

I can imagine two possible diagnoses. Either Lmod is not attempting to read `.modulerc.lua` and so is proceeding to read `.modulerc` instead and hitting the above error. Alternatively, Lmod is attempting to read `.modulerc.lua` but it now expects a different format and refuses to parse this file. Either way, we are unable to remove the error message shown above.

I'd appreciate any help.

**Comment by ghferrari** [comment]
I have temporarily worked around this by downgrading to 8.2.7, which works fine with the above.

**Comment by rtmclay** [comment]
Closing this issue.  Feel free to re-open this issue if there is a problem.
