### ISSUE TITLE
Ignore hidden modulefiles

### ISSUE THREAD

**Issue by simonleary-umass-edu** [TACC/Lmod#596]
I recently added a .modulerc to my modulefiles directory and have hidden some of my modulefiles.
Is there a way to override those hidden modulefiles in `module av`?

**Comment by rtmclay** [comment]
If you are asking is there a way to show hidden module, then yes you can with:
` 
$ module --show_hidden av
`

This was not well documented.  I have updated the documentation: 
https://lmod.readthedocs.io/en/latest/079_hidden_modules.html

**Comment by simonleary-umass-edu** [comment]
thank you!
