### ISSUE TITLE
MODULEPATH directory has too many non-modulefiles - backup module files

### ISSUE THREAD

**Issue by eylenth** [TACC/Lmod#599]
Hi

Since Lmod version 8.7.3, the following warning is generated when an MODULEPATH directory has too many non-modulefiles:
````bash
Lmod Warning:  MODULEPATH directory: "/tools/eb/modules/all" has too many non-modulefiles (132). Please make sure that modulefiles are in their own directory and not mixed in with
`````

Since I'm using Lmod in combination with EasyBuild, it could be possible that some backup module files are generated.
https://docs.easybuild.io/en/latest/Backup_modules.html

Now I'm getting this warning message because I have too many .bak files in my MODULEPATH directory.
What is now the best way to keep forward.
1) should I clean up my backup module files more often?
2) can a fix be implemented to not count those backup module files when detecting too many non-modules ?

**Comment by rtmclay** [comment]
You need to be running Lmod 8.7.4+.  In that version, files that start with a dot are ignored.   Otherwise, please work with the EB community to find a fix for this.

**Comment by boegel** [comment]
Backups of module files currently aren't hidden, so we'll need to work on that in EasyBuild, indeed.
I thought they were, but that's only the case when using Tcl as module syntax, see https://github.com/easybuilders/easybuild-framework/blob/a8c0cad3acc5256735629b7dc94c143731ff650e/easybuild/framework/easyblock.py#L2204-L2208

**Comment by rtmclay** [comment]
@boegel: Note that any file a modulefile directory has to be deal with by Lmod.  If you have renamed a 1.0.lua to 1.0.lua.bak, Lmod treats is as a TCL modulefile, meaning that that it has to open and read the first 10 bytes and determine if "#%Module" string is there.  Now Lmod count 1.0.lua.bak as a non-modulefile.  If you renamed it to be .1.0.lua.bak.  Lmod will still read the first 10 bytes, but it won't count it towards the number of non-modulefiles.

It would be better to have a mirror directory tree of "all", say "all.bak" and move backup modulefiles there.
