### ISSUE TITLE
permission denied on addto on from 8.7.12 to 8.7.13

### ISSUE THREAD

**Issue by surak** [TACC/Lmod#602]
Hey, 

lately (8.7.12 and 13) I've been getting this while making the debian package:

Setting up lmod (8.7.13) ...
/etc/profile.d/lmod.sh: line 28: /usr/lmod/lmod/libexec/addto: Permission denied
/etc/profile.d/lmod.sh: line 29: /usr/lmod/lmod/libexec/addto: Permission denied
/etc/profile.d/lmod.sh: line 53: /usr/lmod/lmod/libexec/addto: Permission denied
/usr/lmod/lmod/init/bash: line 146: /usr/lmod/lmod/libexec/lmod: Permission denied

Seems like the init/ files are doing something different than before? Do I need to push a `sudo` on those lines now?

**Comment by rtmclay** [comment]
This is probably part of the change to support user's umask and resetting the umask to 022 for system users.   Do you need to add --with-mode=755 to your configure step?

**Comment by surak** [comment]
Not sure. I just realized that we have this on the debian patches:

```patch
                                                                                                                  ✔  16:39:38 
This patch makes MODULEPATH to be set with the contents of the file
/etc/lmod/modulespath

Date: 2016-11-10
Author: Ana Guerrero López <ana@debian.org>
--- a/init/profile.in
+++ b/init/profile.in
@@ -23,8 +23,8 @@
     export LMOD_FULL_SETTARG_SUPPORT=@lmod_full_settarg_support@
     export LMOD_COLORIZE=@colorize@
     export LMOD_PREPEND_BLOCK=@prepend_block@
-    export MODULEPATH=$(@PKG@/libexec/addto --append MODULEPATH $MODULEPATH_ROOT/$LMOD_sys $MODULEPATH_ROOT/Core)
-    export MODULEPATH=$(@PKG@/libexec/addto --append MODULEPATH @PKG@/modulefiles/Core)
+	MODULEPATH=`sed -n 's/[   #].*$//; /./H; $ { x; s/^\n//; s/\n/:/g; p; }' /etc/lmod/modulespath`
+    export MODULEPATH
     export MODULESHOME=@PKG@
 
     export BASH_ENV=$MODULESHOME/init/bash
```

**Comment by rtmclay** [comment]
It looks like /usr/lmod/lmod/libexec/addto has the wrong permissions.  Lmod now uses the install program when it can.  It uses a umask of 022 for system users and your umask for regular users.  You  can override this by setting --with-mode=0755.  This change is discussed here: https://lmod.readthedocs.io/en/latest/025_new.html?highlight=Controlling%20intstalled#new-features-in-lmod

I am assuming that /etc/profile.d/lmod.sh is from init/profile.in in the repo.  Correct?

**Comment by surak** [comment]
Fixed. I changed the debian build to account for this (as debs are always installed as root)
