### ISSUE TITLE
load/always_load ignored during a restore

### ISSUE THREAD

**Issue by vanderwb** [TACC/Lmod#605]
**Describe the bug**
The `load` and `always_load` functions are supposed to load a specified module upon load of the module itself. This works fine for standard module loads, but it does not seem to work when restoring a saved module collection that contains the the original module.
 
**To Reproduce**
Simply load a module that contains a `load` or `always_load` command, save it to a module collection, and then purge and restore the collection. For example:
```
$ env -i LMOD_ROOT=$LMOD_ROOT USER=$USER ./bug_report_template.sh
==> Manually loading pkg_a ...
Package A is loading
Package B is loading
==> Manually unloading pkg_a ...
Package B is loading
==> Loading pkg_a using saved collection ...
Restoring modules from user's testset, for system: "bug"
Package A is loading
```

The reproducer for the above is attached ([lmod_always_bugreport.tar.gz](https://github.com/TACC/Lmod/files/9719688/lmod_always_bugreport.tar.gz)). It uses `always_load` but can easily be modified.

**Expected behavior**
We expect the specified module to be loaded upon load of the original module whether the load was performed explicitly or as part of restoring a collection. The resulting environment for the user should be the same.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: SLES
 - Lmod Version: 8.7.2

**Comment by rtmclay** [comment]
Thanks for this report.  However this is not a bug.  This is the way that collections are saved.  They save the state of modules that the user had when "module save testset " was issued.  At this point the collection only had "pkg_A".  The module "pkg_B" was unloaded.  

Imagine the case where a Site has default compilers that are automatically loaded by the "StdEnv".  Then a user would like a different compiler.  The do the following:

```
   $ module load StdEnv    # This loads the intel compiler
   $ module load gcc       # This replaces intel with gcc
   $ module save default # Stdenv and gcc are saved (not intel)
```

Then when the user logs in the next time, they get the gcc compiler instead of the intel compliler. This is what they want.

**Comment by vanderwb** [comment]
Thanks for clarifying for me and I see that you are updating the docs which I think will be very helpful in avoiding confusion.

I know that my use case is an edge case, but I'm having trouble thinking of another good way to support it.

So we have a compiler wrapper that we prepend to the PATH. It also wraps the MPI wrappers like mpicc/mpif90/etc. Our wrapper module is loaded at the compiler-level of the hierarchy, so if an MPI library is loaded the MPI library wrappers hop in front of our wrapper in the PATH. To prevent that problem, I was adding the following to our MPI modules:

```
-- If wrapper is loaded, reload it to keep forward in the PATH
if isloaded("wrapper") then
    always_load("wrapper")
end
```

This worked great, until a user discovered that collections defeat the logic. Do you have an alternative method that could work here?

**Comment by rtmclay** [comment]
Thanks for the update.  Here is new language about collections in 010_user:
```
This creates a file called ``~/.lmod.d/default`` which has the list of
desired modules. Note only the current set of modules is recorded the
in the collection. If module X loads module A and the user deletes
module A before doing ``module save collectionName`` then module A
will NOT be loaded when the collection is restored.  All load(),
always_load(), depends_on() statements are ignored when restoring a
collection. 

Once this is set-up a user can issue::

    $ module restore
```

Hopefully this explains things better.

**Comment by vanderwb** [comment]
Yes - that looks good to me!
