### ISSUE TITLE
Terse output of module spider not machine readable when called with name/version  

### ISSUE THREAD

**Issue by cniethammer** [TACC/Lmod#606]
**Describe the bug**
The `module --terse spider name/version` command will not produce machine readable output as the regular `module spider module`
It will also include the "Help:" section:
e.g.
```
$ module -t spider openmpi/4.1.4

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  openmpi: openmpi/4.1.4
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "openmpi/4.1.4" module is available to load.

      gcc/10.2.0
...
    Help:
      Open MPI ...
```

**Expected behavior**
An easily machine readable output like the one from `module --terse spider module` that does not include the Help.

**Additional context**
I am building some automated module/environment test scripts that require information about modules and their dependencies.
If there would be/is a lmod API with machine readable output (txt, toml or json) this would help a lot.

**Comment by rtmclay** [comment]
Please give an example of what "terse" output you expect in this case.

Also have you looked at lmodule? https://lmodule.readthedocs.io/en/latest/

**Comment by rtmclay** [comment]
I'm closing this issue due to a lack of a response to my question.
