### ISSUE TITLE
UNKNOW_PS meaning

### ISSUE THREAD

**Issue by LukeLabrie** [TACC/Lmod#608]
I'm trying to install lmod using spack, and getting the following error 

```
checking for ps... UNKNOWN_PS

You must have valid ps in your path. Quitting!
```

Can someone quickly tell me what a ps is? Google hasn't been of much help in this case. 

Let me know if I can provide more detail. 

Thanks, 
Luke

**Comment by rtmclay** [comment]
The command ps.  It is usually in /bin or /usr/bin but it might not be installed on your current system.

**Comment by LukeLabrie** [comment]
thanks. what program uses the command ps? I figure that it's some dependency I'm missing, but ps doesn't give me much to work with.

**Comment by rtmclay** [comment]
Lmod needs command ps to install itself.  The ps is command is a standard unix command.  On Centos I found that it is in procps-ng.  On ubuntu it is on procps

**Comment by LukeLabrie** [comment]
thanks, that solved it. was running in a lightweight arch environment so it wasn't pre-installed.
