### ISSUE TITLE
Docs give wrong path for user cache

### ISSUE THREAD

**Issue by sjpb** [TACC/Lmod#610]
**Describe the bug**
https://lmod.readthedocs.io/en/latest/125_personal_spider_cache.html says this cache is at `~/.cache/lmod`. At least on lmod 8.7.7 it is actually in `~/.lmod.d/.cache/`

 
**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: RockyLinux 8.6
 - Lmod Version: 8.7.7
 - `"module --miniConfig`:
```
Modules based on Lua: Version 8.7.7  2022-07-05 10:00 -05:00
    by Robert McLay mclay@tacc.utexas.edu

Changes from Default Configuration
----------------------------------

Name                         Default      Value
----                         -------      -----
LMOD_FAST_TCL_INTERP         no           yes
LMOD_HAVE_LUA_TERM           no           yes
LMOD_PACKAGE_PATH            nil          <empty>
LMOD_PAGER                   less         /usr/bin/more
LMOD_SYSTEM_DEFAULT_MODULES  __unknown__  <empty>
LMOD_TCLSH                   tclsh        /usr/bin/tclsh
MODULEPATH_ROOT                           /usr/share/modulefiles
PATH_TO_LUA                  lua          /usr/bin/lua
```

**Comment by rtmclay** [comment]
The documentation has been updated to say that versions earlier than  Lmod 8.7.12 wrote the cache file to ~/.lmod.d/.cache
