### ISSUE TITLE
Some tests fail when system tools are installed in a PREFIX environment

### ISSUE THREAD

**Issue by trz42** [TACC/Lmod#611]
**Describe the bug**
Installing `v8.7.13` into a PREFIX environment (for EESSI, e.g., `/cvmfs/pilot.eessi-hpc.org/versions/2022.11/compat/linux/x86_64`) lets some tests fail because system tools such as `sed` and `sha1sum` are not found in standard locations. It seems that the regular expressions used in the function `cleanUp` (file `rt/common_funcs.sh`) miss a few entries (all entries for `sed` were missing, one entry for `sha1sum` was missing, order of the one for `sha1sum` before the next two expressions for `sha1sum` is important). See patch added in last section. With that patch all tests pass.
 
**To Reproduce**

Not so easy. Essentially following steps at https://github.com/EESSI/compatibility-layer/tree/main/ansible/playbooks

If necessary, I could attach example output for a failing test and the list of failing tests (see https://github.com/EESSI/gentoo-overlay/pull/84#discussion_r1009702065 for a list of the failing tests). The `configDir` test failed because of the missing expression for `sha1sum`. All the other tests failed because one or more of the four expressions for `PATH_TO_SED` were missing.

**Expected behavior**
All tests should pass. What's missing without the patch is that some paths are just not removed from test output.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: Gentoo
 - Lmod Version: 8.7.13 (will run test with the latest release in the coming days)
 - For Lmod Versions 8.7.7+, please run "module --miniConfig" and
   include the output here.
   - Tricky because the installation is part of a series of `ansible` scripts. Might be doable if it is necessary to understand the issue. As a relatively "trivial" patch exists this might not be needed.

**Additional context**
Using the following patch all tests pass.
```patch
diff --git a/rt/common_funcs.sh b/rt/common_funcs.sh
index 7c0a561f..b011129f 100644
--- a/rt/common_funcs.sh
+++ b/rt/common_funcs.sh
@@ -33,6 +33,7 @@ cleanUp ()
        -e "s|[\\]27|\\\033|g"                             \
        -e "s|='\\\\033|='\\\\\\\\033|g"                   \
        -e "s|\@git\@|$gitV|g"                             \
+       -e "s|$PATH_to_SHA1/sha1sum|PATH_to_HASHSUM|g"     \
        -e "s|/usr/.*/sha1sum|PATH_to_HASHSUM|g"           \
        -e "s|/bin/.*/sha1sum|PATH_to_HASHSUM|g"           \
        -e "s|:$PATH_to_LUA\([:;]\)|\1|g"                  \
@@ -56,6 +57,10 @@ cleanUp ()
        -e "s|;$PATH_to_SHA1:[0-9];|;|g"                   \
        -e "s| $PATH_to_SHA1||g"                           \
        -e "s|\\\;$PATH_to_SHA1:[0-9]\\\;|\\\;|g"          \
+       -e "s|:$PATH_TO_SED\([:;]\)|\1|g"                  \
+       -e "s|;$PATH_TO_SED:[0-9];|;|g"                    \
+       -e "s| $PATH_TO_SED||g"                            \
+       -e "s|\\\;$PATH_TO_SED:[0-9]\\\;|\\\;|g"           \
        -e "s|^ *Lmod version.*||g"                        \
        -e "s|^LMOD_LD_PRELOAD.*||g"                       \
        -e "s|^LuaFileSystem version.*||g"                 \

**Comment by trz42** [comment]
Can confirm that the same tests (see list below) also fail for the latest release `8.7.14` without the patch. The patch resolves the issue.

```
diff     R  3.01   rt/avail/avail/t1
diff     R  2.12   rt/changeMPATH/changeMPATH/t1
diff     R  4.98   rt/columnT/columnT/t1
diff     R  0.392  rt/configDir/configDir/t1
diff     R  1.49   rt/csh_swap/csh_swap/t1
diff     R  0.562  rt/deprecation/deprecation/t1
diff     R  1.47   rt/eb/eb/t1
diff     R  0.68   rt/family/family/t1
diff     R  0.296  rt/fish/fish/t1
diff     R  0.336  rt/hook/hook/t1
diff     R  0.926  rt/hook_avail/hook_avail/t1
diff     R  1.08   rt/inherit/inherit/t1
diff     R  0.646  rt/isloaded/isloaded/t1
diff     R  0.61   rt/junk/junk/t1
diff     R  1.41   rt/lars/lars/t1
diff     R  0.408  rt/lastName/lastName/t1
diff     R  8.69   rt/load/load/t1
diff     R  0.751  rt/mpath/mpath/t1
diff     R  0.643  rt/noTCL/noTCL/t1
diff     R  0.416  rt/personal_mf/personal_mf/t1
diff     R  0.64   rt/petsc/petsc/t1
diff     R  0.77   rt/pkg/pkg/t1
diff     R  0.834  rt/purge/purge/t1
diff     R  1.21   rt/reset/reset/t1
diff     R  0.392  rt/rstats/rstats/t1
diff     R  6.92   rt/saverestore/saverestore/t1
diff     R  1.41   rt/sd_tacc/sd_tacc/t1
diff     R  1.86   rt/sh_to_modulefile/sh_to_modulefile/t1
diff     R  0.331  rt/slash/slash/t1
diff     R  3.28   rt/swap/swap/t1
diff     R  2.6    rt/tabcompl/tabcompl/t1
diff     R  1.94   rt/tacc/tacc/t1
diff     R  0.726  rt/uitSitePkg/uitSitePkg/t1
diff     R  0.661  rt/user_inherit/user_inherit/t1

**Comment by rtmclay** [comment]
Thanks for reporting this issue! This change has been added to the main branch and will become live with the next release of Lmod.

**Comment by trz42** [comment]
Nice!

**Comment by rtmclay** [comment]
Closing this issue
