### ISSUE TITLE
Module switch while maintaing order

### ISSUE THREAD

**Issue by servesh** [TACC/Lmod#616]
When one swaps modules, it would be helpful if there was a way to replace the relevant paths of the particular module is replaced in place maintaining path order.

```
module load foo/0.1
LD_LIBRARY_PATH=/opt/bar/0.1/lib:/opt/foo/0.1/lib:/opt/baz/0.1/lib
```

`module switch foo/0.1 foo/0.2`
does this,
`LD_LIBRARY_PATH=:/opt/foo/0.2/lib:/opt/bar/0.1/lib:/opt/baz/0.1/lib`

instead of
`LD_LIBRARY_PATH=/opt/bar/0.1/lib:/opt/foo/0.2/lib:/opt/baz/0.1/lib`

Any thoughts on how this can be supported?

**Comment by servesh** [comment]
I wasn't aware that swap or switch is nothing but a unload/load in one command. I was assuming, some amount of info is known when swap or switch is used unlike load/unload, i.e. when the prior modulefile's paths which are scanned and removed, the index at which these changes occur can be used as the location to update the new module's paths into.

**Comment by rtmclay** [comment]
The point I was making above was that.  Lmod is not evaluating the modules Lua is.  Lmod is there to handle the setenv(), prepend_path() etc functions.  Lmod has no idea of what the contents of the modulefiles until Lmod functions are called.

I'm closing this issue.
