### ISSUE TITLE
sourcing `init/profile` raises error in bash posix mode

### ISSUE THREAD

**Issue by lgarrison** [TACC/Lmod#619]
**Describe the bug**
When running bash in posix mode (which happens with either `bash --posix` or `sh`), the `Lmod/init/bash` file tries to source the `Lmod/init/lmod_bash_completions` file, which throws an error:

```console
sh-4.4$ . /mnt/sw/lmod/x86_64/rocky8/lmod/lmod/init/profile
sh: /mnt/sw/nix/store/x240zci3c4y5kbr6yw2qcfpfcydda11q-lmod-8.6.5/lmod/lmod/init/lmod_bash_completions: line 95: syntax error near unexpected token `('
sh: /mnt/sw/nix/store/x240zci3c4y5kbr6yw2qcfpfcydda11q-lmod-8.6.5/lmod/lmod/init/lmod_bash_completions: line 95: `  comm -23  <(_module_avail|sort)  <(_module_loaded_modules|sort)'
```

It looks like `init/profile` might try to detect if the shell is `sh`, but it ends up inferring `my_shell=bash`, which is probably the expected behavior.

Both `sh` and `bash --posix` set the `POSIXLY_CORRECT` variable, so one possible solution might be to add this to the list of checks performed before sourcing the bash completions: https://github.com/TACC/Lmod/blob/edb4cf5a65fef719733e6299ce571790b6f0e6ce/init/bash.in#L215

**Expected behavior**
The module command is available in `sh` or `bash --posix` after sourcing `init/profile` (I'm not worried about getting tab completions; just that an error is raised).

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: Rocky 8
 - Lmod Version: 8.6.5. Also tested on 8.7.13.

**Comment by rtmclay** [comment]
Thanks for the bug report!  I went with your suggested fix.  I was able to reproduce this issue on a Rocky 8 and show that this fix works there.   Note that bash version 5+ doesn't report this error only bash 4.

I have updated the testing branch with this fix if you wish to test it out.  Thanks!

**Comment by lgarrison** [comment]
Just tested; works great. Thanks!
