### ISSUE TITLE
Tcl modules - unsetenv

### ISSUE THREAD

**Issue by ddietz89** [TACC/Lmod#62]
I ran into an issue with using one of our Tcl modules with lmod:

---

$ module load hspice
Lmod has detected the following error:  /opt/modules/modulefiles/hspice/2013.03: (hspice/2013.03): invalid command name "unsetenv"

While processing the following module(s):

Module fullname  Module Filename
---------------  ---------------
hspice/2013.03   /opt/modules/modulefiles/hspice/2013.03

---

I tested this with the latest checkout from Github. Poking around in the code, it looks like the tcl2lua translator was just missing a function for unsetenv (even though the definition for it is there). It only took a minute to add the function so that "unsetenv" would work (at least for the single module that needs it). I want to make sure I'm not missing something or if this command just got overlooked. I honestly had no idea "unsetenv" was even a module command until a few hours ago.

**Comment by rtmclay** [comment]
Thanks for the bug report.  I have pushed a new version which supports unsetenv from TCL modulefiles.  It is a rarely used command and nobody caught until now.   This version is 5.9.3.3 and is push to HEAD in the repo's
