### ISSUE TITLE
reportMissingDepModules is not using LmodWarning

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#622]
`reportMissingDepModules` uses `io.stderr:write` instead of `LmodWarning`, see https://github.com/TACC/Lmod/blob/768e9410dae778a89e345e21c3a28046cae0a741/src/MainControl.lua#L933

This prevents customizing the error message via `errWarnMsgHook`.

Is that deliberate for some reason?

**Comment by rtmclay** [comment]
No, it was a mistake.  I have updated Lmod to now use LmodWarning() instead.  Please test Lmod 8.7.19 to see if it works for you.

**Comment by boegel** [comment]
@rtmclay There's no 8.7.19 tag yet?

**Comment by rtmclay** [comment]
It is there now.

**Comment by rtmclay** [comment]
can I close this issue?

**Comment by boegel** [comment]
Yes, thanks!
