### ISSUE TITLE
Any chance to support `module-hide` command?

### ISSUE THREAD

**Issue by shiltian** [TACC/Lmod#623]
**Describe the bug**
`module-hide` is not supported such that Lmod cannot use existing module files.

I have a module file and the contents are very simple:
```
#%Module4.6
# softly hide all qux modules
module-hide --hard testing
```
It is using `module-hide` command. When I execute `module use xxx` where `xxx` contains a directory which contains the module file above, it errors out:
```
invalid command name "module-hide"
    while executing
"module-hide --hard testing"
    (file "/soft/modulefiles/testing/.modulerc" line 3)
    invoked from within
"source $mRcFile"
    (procedure "main" line 15)
    invoked from within
"main $fn"
    (file "/home/ac.shilei.tian/.local/lmod/lmod/libexec/RC2lua.tcl" line 137)
Lmod has detected the following error:  Unable to parse: "/soft/modulefiles/testing/.modulerc". Aborting!
```

Since those module files are out of my control (maintained by system admin), I can't modify them.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: openSUSE Leap 15.3
 - Lmod Version: Modules based on Lua: Version 8.7.19  2023-01-17 10:45 -06:00
 - For Lmod Versions 8.7.7+, please run "module --miniConfig" and
   include the output here.
```
Modules based on Lua: Version 8.7.19  2023-01-17 10:45 -06:00
    by Robert McLay mclay@tacc.utexas.edu

Changes from Default Configuration
----------------------------------

Name                         Where Set  Default      Value
----                         ---------  -------      -----
LFS_VERSION                  D          1.6.3        1.8.0
LMOD_LD_LIBRARY_PATH         E          false        /home/ac.shilei.tian/.local/hwloc/lib:/home/ac.shilei.tian/.local/gdb/lib:/home/ac.shilei.tian/.local/llvm/lib:/home/ac.shilei.tian/.local/lib:
LMOD_PACKAGE_PATH            D          nil          <empty>
LMOD_PAGER                   C          less         /usr/bin/less
LMOD_SYSTEM_DEFAULT_MODULES  D          __unknown__  <empty>
LMOD_TCLSH                   C          tclsh        /usr/bin/tclsh
MODULEPATH_ROOT              C                       /home/ac.shilei.tian/.local/modulefiles
PATH_TO_LUA                  C          lua          /home/ac.shilei.tian/.local/bin/lua


Where Set -> D: default, E: environment, C: configuration
             lmod_cfg: lmod_config.lua SitePkg: SitePackage StdPkg: StandardPackage
             Other: Set somewhere outside of normal locations
```

**Additional Notes**
Is there any way to bypass it such that I can use those modules with `lmod`? Otherwise I guess I can only stick the original module?

**Comment by daRecall** [comment]
I'm absolutely not sure, if that would work, since you have TCL modules, but it could be worth a try. One can "add" own functions to (at least lua) module files, please see
[Implementing functions in SitePackage.lua](https://lmod.readthedocs.io/en/latest/170_hooks.html)
If you just want to bypass `module-hide`, such that you can load the module, it might suffice to create a empty function in `Sitepackage.lua` and do a sandboxregistration for that function.

**Comment by rtmclay** [comment]
Functions written SitePackage.lua can only supply Lua functions not TCL functions.

It would be easy to have module-hide function in TCL do nothing.  Is that useful?

Also I have looked at the documentation in modules.readthedocs.io and it not clear what the module-hide does.  Can you explain what this function does.  That would help.

**Comment by shiltian** [comment]
Hi @rtmclay @daRecall thanks for reply. TBH I don't know what `module-hide` does. I didn't write those module files. I'm using a cluster that is not maintained by me and I cannot modify those module files. I think it's totally okay to just bypass it such that I can take use all those advanced features out of Lmod. For now I have to stick with the existing `module`.

**Comment by xdelaruelle** [comment]
@rtmclay The design notes of this feature may help to understand what it does. It is available at https://modules.readthedocs.io/en/latest/design/hide-or-forbid-modulefile.html

**Comment by rtmclay** [comment]
Lmod 8.7.21 now "supports" module-hide and module-forbid.  These TCL commands that are in .modulerc files are read-in and **IGNORED**.  It is possible that these command could the "right" thing at a later date.

**Comment by shiltian** [comment]
@rtmclay Thanks for the information. I confirm that it "works". I can use Lmod on my cluster now. :-)
