### ISSUE TITLE
README/Documentation/output: HTTP -> HTTPS

### ISSUE THREAD

**Issue by HenrikBengtsson** [TACC/Lmod#626]
Hi,

I noticed that there are a lot of URLs in this repo that uses HTTP while there is a corresponding HTTPS version of those URLs.  Search GitHub for `http://` (<https://github.com/search?q=repo%3ATACC%2FLmod+%22http%3A%2F%2F%22&type=code>) gives instances of:

* `http://lmod.readthedocs.org/...` 
* `http://www.lua.org/...`
* ...

I guess some are for older versions, but it looks like these are also in the latest version, including in the main README and in the 'About' URL on your GitHub repository.

**Comment by rtmclay** [comment]
Thanks for point this out. I have made the request change to the places that it matters.  There are test module files and old presentation that I'm not going to update.  Thanks!

**Comment by HenrikBengtsson** [comment]
Great. Thanks
