### ISSUE TITLE
module hierarchy displayed all at once

### ISSUE THREAD

**Issue by simonleary-umass-edu** [TACC/Lmod#628]
This is the output of my `module avail`:

![image](https://user-images.githubusercontent.com/71396965/217348833-32d25c68-732b-492b-8002-615ab7837402.png)

The openmpi module is configured to prepend the `openmpi-3rgk3nu` directory to `MODULEPATH`, and I want that directory to be hidden up until it's loaded. I could have sworn that I was getting this behavior months ago but now it's different.

Is this an issue with [module naming scheme](https://lmod.readthedocs.io/en/latest/055_module_names.html)? I think I want Lmod to only pay attention to modules of the form `name/version`.

**Comment by rtmclay** [comment]
What is your current $MODULEPATH?   My guess is that you have something like /opt/modulefiles/ with 
directories openjdk and openmpi below /opt/modulefiles.  That won't work.  Please read https://lmod.readthedocs.io/en/latest/080_hierarchy.html about how to set up the software hierarchy.  Please note that
in my examples I set MODULEPATH to be  /opt/apps/modulefiles/Core for modules like ocaml and /opt/app/modulefiles/MPI/.. for software built with a version of some MPI library.

**Comment by simonleary-umass-edu** [comment]
Thanks
