### ISSUE TITLE
prepend_path with space character as delimiter

### ISSUE THREAD

**Issue by krobbins** [TACC/Lmod#63]
Using Lua 5.2.3, Lmod 5.9.3.3, and zsh 5.0.2 on an Ubuntu 14.04 LTS machine, I am trying to use prepend_path in a Lua modulefile to prepend to the Zsh fpath environment variable, which is space delimited and used for finding completion files:

prepend_path("fpath", pathJoin(myModuleRootPath(), "etc"), " ")

Unfortunately, this results in overwriting the existing value of fpath with the result of the pathJoin().

Can you confirm whether this is a bug or a misunderstanding in how to use prepend_path with a delimiter other than ":"?

**Comment by rtmclay** [comment]
You have done everything correctly and there is nothing broken (at least here) with Lmod.  The problem is that fpath is a local variable and is not exported.  I, too, run zsh and when I do:

 % env | grep fpath
 %

There is nothing which means there is nothing for Lmod to prepend to.
