### ISSUE TITLE
disable tab auto-completion?

### ISSUE THREAD

**Issue by simonleary-umass-edu** [TACC/Lmod#631]
On my sytem the tab auto-completion is very slow. I think it's because we have a lot of modules. How can I disable this?

**Comment by simonleary-umass-edu** [comment]
I see that the init script for bash (`/usr/share/lmod/lmod/init/bash`) has this:

```sh
if [ ${BASH_VERSINFO:-0} -ge 3 ] && [ -r  /usr/share/lmod/lmod/init/lmod_bash_completions ] && [ -n "${PS1:-}" ]; then
 . /usr/share/lmod/lmod/init/lmod_bash_completions
fi
```
Rather than symlinking it to /etc/profile.d, I could make a copy and comment out these lines. Right?

**Comment by rtmclay** [comment]
Yes you can.   You should test how long things like "module -t avail" take.  If that is slow then you might consider using the system spider cache.

**Comment by simonleary-umass-edu** [comment]
I am using the system spider cache (I think)
```sh
$ date; module --ignore-cache avail 2> /dev/null; date
Thu Feb 16 02:56:11 UTC 2023
Thu Feb 16 02:56:57 UTC 2023
$ date; module -t avail 2> /dev/null; date
Thu Feb 16 02:57:04 UTC 2023
Thu Feb 16 02:57:05 UTC 2023
$ date; module avail 2> /dev/null; date
Thu Feb 16 02:57:08 UTC 2023
Thu Feb 16 02:57:08 UTC 2023
```

**Comment by rtmclay** [comment]
Yes you are using the spider cache.  So its bash that is slow and not Lmod.  So you can turn off tab completion by doing what you said above.

One question about your number of modules.  What does the following return:
```
$ module -t avail 2>&1 | wc -l
```

**Comment by rtmclay** [comment]
O.K. to close this issue?
