### ISSUE TITLE
Possible to determine/unload dependency tree?

### ISSUE THREAD

**Issue by danfulton** [TACC/Lmod#634]
In the documentation section [Dependent Modules](https://lmod.readthedocs.io/en/latest/098_dependent_modules.html), there are many options to use, including `depends_on()`, `prereq()`,`load()`,`always_load()`, which change the behaviour of how `module A` is loaded and unloaded when a dependent `module X` is loaded and unloaded.  For example, I am using `depends_on()`
```
$ module purge; module load X; module unload X                => unload A
$ module purge; module load A; module load X; module unload X => keep A
```
However, I would like to enforce the behaviour that I can unload the dependency tree.  e.g. The behaviour I would like to see is
```
$ module purge; module load A; module load X; module unload A => unload A and X
```

I can explicitly put in an instruction in the modulefile for `A`.
```
if (mode() == "unload") then
    unload("X")
end
```
however, this does not scale if A has many dependencies.

The use case here is that I would like to create a modulefile `A` for a package and environment manager which is both used as a source for other module installations (say `W`, `X`, `Y`, `Z`) as well as being used directly by users.  If a user loads a dependent module `X`, they may then start using `A` to undo some of what `module load X` did, as well as making user-specific environment changes which should be cleaned up before the package manager is removed from the path.  The dependent modules, `W`, `X`, `Y`, `Z`, have different maintainers, and the list may fluctuate, so it's undesireable to unload the whole list in the modulefile for `A`.

Is there any call similar to `loaded_modules()` that I can filter to find loaded modules that directly `depends_on("A")` and generate a list to unload?  Is there a better way to do this?

**Comment by danfulton** [comment]
I was also wondering if I could scrape some of the module dependencies here with `module spider`, but that seems to be dependent on the filesystem hierarchy rather than the dependencies as they are declared in the modulefiles themselves.

**Comment by danfulton** [comment]
Okay thanks.  I think single level dependencies would actually be preferable in my use case.  I'm not too familiar with using the spider cache, but I'll look into it if I have time.

**Comment by rtmclay** [comment]
closing this issue
