### ISSUE TITLE
Is it possible to force users to specify module version?

### ISSUE THREAD

**Issue by simonleary-umass-edu** [TACC/Lmod#637]
The name says it all. Lmod behaves more consistently as admins make changes to modules if people are used to loading modules with version names. Can we force them to use version names all the time?

**Comment by rtmclay** [comment]
Yes you can.  Read about LMOD_EXACT_MATCH here:

https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html

**Comment by simonleary-umass-edu** [comment]
thanks!
