### ISSUE TITLE
Execute a bash script within the modulesfile lua 8.5 (lmod)

### ISSUE THREAD

**Issue by marseaplage** [TACC/Lmod#641]
Hi

Could you help with the information about how can I modify a modulefile such that a set of environmental variables can be loaded when the user executes: “module load intel-mpicc/openfoam/10.0” since that program requires a set of variables be loaded that is called “bashrc”. I normally run it with: “source …/bashrc” I have installed:

Modules based on Lua: Version 8.5.22 2021-11-01 13:46 -05:00
by Robert McLay [mclay@tacc.utexas.edu](mailto:mclay@tacc.utexas.edu)

My modulefiles is as follows:
proc ModulesHelp { } {

puts stderr " "
puts stderr "This module loads openfoam built with the intel compiler and mpicc"
puts stderr "toolbook openfoam"
puts stderr "\nVersion 10.0\n"

}
module-whatis "Name: openfoam compiled with intel compiler and mpicc"
module-whatis "Version: 10.0"
module-whatis "Category: Toolbox"
module-whatis "Description: openfoam compiled with intel compiler and mpicc"
module-whatis "URL https://openfoam.org/"

set version 10.0

prepend-path PATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/bin
prepend-path MANPATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/doc
prepend-path INCLUDE /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/src
prepend-path LD_LIBRARY_PATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc

setenv OPENFOAM_DIR /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10
setenv OPENFOAM_BIN /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/bin
setenv OPENFOAM_LIB /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc
setenv OPENFOAM_INC /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/src
prepend-path MODULEPATH /opt/ohpc/pub/moduledeps/intel-mpicc

depends-on intel-oneapi
depends-on mpi
depends-on gnu9
depends-on openmpi4
depends-on compiler/2022.2.0

I am not able to update the lmod because it belongs to the ohpc 2.4 version and I do not want to lose compatibility.

Thank you in advance for your help.

**Comment by rtmclay** [comment]
I asked you on the mailing list the same question.  I am not sure what you are asking.  If I had to guess.  I think that you are trying to create a modulefile for openfoam using sh_to_modulefile and you have a problem.  If that is the question then I have this answer.  This answer can be found searching the lmod mailing archive.  See below

The version sh_to_modulefile in Lmod 8.5 is not as good as the version in the latest Lmod.  My recommendation is to install the latest version of Lmod in a personal directory and convert the openfoam bash script into a modulefile. That modulefile will safely be read by Lmod 8.5

If you want to use the source_sh() in a modulefile, you will have to install the latest version of Lmod.

-------------------------------------------------------------------------------------------------------------
Below is the answer to the question on how to fix the openfoam bash script
--------------------------------------------------------------------------------------------------------------
I have found the issue is with the OpenFOAM script. Here is the current
problem:  Currently there are these lines in etc/config.sh/aliases starting
at line 74:

if command -V wmRefresh 2> /dev/null | head -1 | grep -q "function"
then
    unset wmRefresh
else
    unalias wmRefresh 2> /dev/null
fi

When there is no alias for wmRefresh the if test returns a false because
there is nothing written to stdout.  So the script tries to run "unalias
wmRefresh" which fails and sets the error flag.  Because the shell
conversion program does "set -e", means that the shell script conversion
stops at the unalias line. But there is no message, because the error
message is written to /dev/null.

I could remove the "set -e" when evaluating the script but then I won't
know if the conversion fails and I'm unable to report that error.  The fix
here is to change the script to:

if command -V wmRefresh 2> /dev/null | head -1 | grep -q "function"
then
    unset wmRefresh
else
    unalias wmRefresh 2> /dev/null || true
fi

I will also have to explain this issue as part of the error message and
point users to the [lmod.readthedocs.io](http://lmod.readthedocs.io/) pages that explain how to track down
silent errors.

**Comment by marseaplage** [comment]
> I asked you on the mailing list the same question. I am not sure what you are asking. If I had to guess. I think that you are trying to create a modulefile for openfoam using sh_to_modulefile and you have a problem. If that is the question then I have this answer. This answer can be found searching the lmod mailing archive. See below
> 
> The version sh_to_modulefile in Lmod 8.5 is not as good as the version in the latest Lmod. My recommendation is to install the latest version of Lmod in a personal directory and convert the openfoam bash script into a modulefile. That modulefile will safely be read by Lmod 8.5
> 
> If you want to use the source_sh() in a modulefile, you will have to install the latest version of Lmod.
> 
> ## Below is the answer to the question on how to fix the openfoam bash script
> I have found the issue is with the OpenFOAM script. Here is the current problem: Currently there are these lines in etc/config.sh/aliases starting at line 74:
> 
> if command -V wmRefresh 2> /dev/null | head -1 | grep -q "function" then unset wmRefresh else unalias wmRefresh 2> /dev/null fi
> 
> When there is no alias for wmRefresh the if test returns a false because there is nothing written to stdout. So the script tries to run "unalias wmRefresh" which fails and sets the error flag. Because the shell conversion program does "set -e", means that the shell script conversion stops at the unalias line. But there is no message, because the error message is written to /dev/null.
> 
> I could remove the "set -e" when evaluating the script but then I won't know if the conversion fails and I'm unable to report that error. The fix here is to change the script to:
> 
> if command -V wmRefresh 2> /dev/null | head -1 | grep -q "function" then unset wmRefresh else unalias wmRefresh 2> /dev/null || true fi
> 
> I will also have to explain this issue as part of the error message and point users to the [lmod.readthedocs.io](http://lmod.readthedocs.io/) pages that explain how to track down silent errors.

Hi, thank you for your reply. What I am trying to achieve is when the openfoam module is loaded, it also loads a set of environmental variables that are in a script located in .../openfoam/bashrc and I do not know how to do that with lmod 8.5. I presented my openfoam modulefile that I have already working. Could you please give me an idea to achieve that? Normally by command line, I just execute: "source .../openfoam/bashrc". I do no think that script: "modulefile_to_sh" is what I need to do that, but if so, how can I use it? thank you in advance for your reply and help.

**Comment by rtmclay** [comment]
Please read the documentation:

https://lmod.readthedocs.io/en/latest/260_sh_to_modulefile.html?highlight=sh_to_modulefile

**Comment by marseaplage** [comment]
> Please read the documentation:
> 
> https://lmod.readthedocs.io/en/latest/260_sh_to_modulefile.html?highlight=sh_to_modulefile

Hi

I read it but I do not understand how I can apply it to my case, could you please give a me a hint or concrete response?

**Comment by mrcawood** [comment]
@marseaplage Hi, I've followed the thread and can clarify how to resolve your problem. As rtmclay suggests, the sh_to_modulefile utility provided by Lmod will do what you want - convert the etc/bashrc script into a lua module file. However, sh_to_modulefile fails in this case because of an error in the OpenFOAM script, not Lmod, that returns an exit code 1 and halts the evaluation.

1. Fix this error by following rtmclay's earlier instructions (to summarize: add " || true" to line 78 of file etc/config.sh/aliases) to fix the script. 

sh_to_modulefile should now be able to successfully evaluate "source etc/bashrc" and convert this to a modulefile that sets the environment variables that you need:

2. $LMOD_DIR/sh_to_modulefile /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc > openfoam.lua

**Comment by marseaplage** [comment]
> @marseaplage Hi, I've followed the thread and can clarify how to resolve your problem. As rtmclay suggests, the sh_to_modulefile utility provided by Lmod will do what you want - convert the etc/bashrc script into a lua module file. However, sh_to_modulefile fails in this case because of an error in the OpenFOAM script, not Lmod, that returns an exit code 1 and halts the evaluation.
> 
> 1. Fix this error by following rtmclay's earlier instructions (to summarize: add " || true" to line 78 of file etc/config.sh/aliases) to fix the script.
> 
> sh_to_modulefile should now be able to successfully evaluate "source etc/bashrc" and convert this to a modulefile that sets the environment variables that you need:
> 
> 2. $LMOD_DIR/sh_to_modulefile /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc > openfoam.lua

Thank you for your reply.  I found that sript on "/.../lmod/8.5.22/libexec/sh_to_modulefile" but before doing that, I would like you to clarify me: what about the module file that I have already created? How can relate the .lua that is going to generate the "sh_to_module" with that one that I posted earlier for my question in this forum, I mean with this one:

`13:46 -05:00
by Robert McLay [mclay@tacc.utexas.edu](mailto:mclay@tacc.utexas.edu)

My modulefiles is as follows:
proc ModulesHelp { } {

puts stderr " "
puts stderr "This module loads openfoam built with the intel compiler and mpicc"
puts stderr "toolbook openfoam"
puts stderr "\nVersion 10.0\n"

}
module-whatis "Name: openfoam compiled with intel compiler and mpicc"
module-whatis "Version: 10.0"
module-whatis "Category: Toolbox"
module-whatis "Description: openfoam compiled with intel compiler and mpicc"
module-whatis "URL https://openfoam.org/"

set version 10.0

prepend-path PATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/bin
prepend-path MANPATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/doc
prepend-path INCLUDE /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/src
prepend-path LD_LIBRARY_PATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc

setenv OPENFOAM_DIR /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10
setenv OPENFOAM_BIN /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/bin
setenv OPENFOAM_LIB /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc
setenv OPENFOAM_INC /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/src
prepend-path MODULEPATH /opt/ohpc/pub/moduledeps/intel-mpicc

depends-on intel-oneapi
depends-on mpi
depends-on gnu9
depends-on openmpi4
depends-on compiler/2022.2.0`

Thank you in advance for your patience and help

**Comment by ocaisa** [comment]
@marseaplage The output from the `sh_to_modulefile` is just text, you can read it and compare what it does with your original module file. This script only captures changes to the environment, so it is not going to generate `module-whatis` or anything else that doesn't appear as a change in the environment. For example, the output will probably contain the `prepend-path` and `setenv` statements but will not contain the `depends-on` statements (since these are statements that affect Lmod behaviour not the environment).

You will need all of the changes in the `sh_to_modulefile` script and then you can add any content from your original module file  that is not covered by that.

**Comment by marseaplage** [comment]
> @marseaplage The output from the `sh_to_modulefile` is just text, you can read it and compare what it does with your original module file. This script only captures changes to the environment, so it is not going to generate `module-whatis` or anything else that doesn't appear as a change in the environment. For example, the output will probably contain the `prepend-path` and `setenv` statements but will not contain the `depends-on` statements (since these are statements that affect Lmod behaviour not the environment).
> 
> You will need all of the changes in the `sh_to_modulefile` script and then you can add any content from your original module file that is not covered by that.

Hi @ocaisa  

Thank for your reply. I was following your advice but at the moment to run the script I have got these syntax errors from the "sh_to_module" script: 

`<html>
<body>


sh /opt/ohpc/admin/lmod/8.5.22/libexec/sh_to_modulefile /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc


/opt/ohpc/admin/lmod/8.5.22/libexec/sh_to_modulefile: line 2: --: command not found/opt/ohpc/admin/lmod/8.5.22/libexec/sh_to_modulefile: line 4: --------------------------------------------------------------------------: command not found/opt/ohpc/admin/lmod/8.5.22/libexec/sh_to_modulefile: line 5: syntax error near unexpected token `('/opt/ohpc/admin/lmod/8.5.22/libexec/sh_to_modulefile: line 5: `-- This program takes shell scripts (either bash or csh) and converts'​
--


</body>
</html>`

Now I wonder what would be the correct procedure to update my module based on Lua 8.5 to the 8.6 version that includes the "source_sh" function that apparently fulfill straightforward what I requires.

Thank you in advance for any advice or suggestion.

**Comment by marseaplage** [comment]
> Please change the sh to bash:
> 
> ```
> bash /opt/ohpc/admin/lmod/8.5.22/libexec/sh_to_modulefile /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc
> ```
> 
> You would be better off if you upgraded lmod to the latest version. There were some bugs in Lmod 8.6 in source_sh().
> 
> However source_sh() and sh_to_modulefile use the same techniques.

Hi 

I succeded upgrading lmod-ohpc from 8.5.22 to 8.7.6, so I am able to use "source_sh" but I have tried to added to my modulefile as follows and it says that "source_sh" is not found:

`<html>
<body>


​proc ModulesHelp { } {​puts stderr " "puts stderr "This module loads openfoam built with the intel compiler and mpicc"puts stderr "toolbook openfoam"puts stderr "\nVersion 10.0\n"​}module-whatis "Name: openfoam compiled with intel compiler and mpicc"module-whatis "Version: 10.0"module-whatis "Category: Toolbox"module-whatis "Description: openfoam compiled with intel compiler and mpicc"module-whatis "URL https://openfoam.org"​set     version             10.0​prepend-path    PATH                /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/binprepend-path    MANPATH             /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/docprepend-path    INCLUDE             /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/srcprepend-path    LD_LIBRARY_PATH     /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc​setenv          OPENFOAM_DIR        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10setenv          OPENFOAM_BIN        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/binsetenv          OPENFOAM_LIB        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etcsetenv          OPENFOAM_INC        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/srcprepend-path    MODULEPATH          /opt/ohpc/pub/moduledeps/intel-mpiccsource_sh       /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc​depends-on      intel-oneapidepends-on      mpidepends-on      gnu9depends-on      openmpi4​
--



</body>
</html>`

I have also inserted as "source_sh("/opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc",""), it says "invalid comand name". How can  I use the source_sh in my case?

Thank you in advance for your help.

**Comment by marseaplage** [comment]
> @mrcawood comment is correct for Lua modulefiles. However I believe that the current modulefile is written in TCL. In that case:
> 
> ```
> source-sh bash /path/to/bash_shell_script arg1 ... argN
> ```
> 
> This is all clearly written in the documentation:
> 
> https://lmod.readthedocs.io/en/latest/051_tcl_modulefiles.html?highlight=source-sh#tcl-modulefile-functions
> 
> Please consult the documentation before asking questions already answered there. If the documentation isn't clear then ask questions to clarify.

Hi @rtmclay 

I read that, the problem is that it is still not recognise by the lmod 8.7, that's why I am asking for clarification, now I used as follows and I got that error:


`<html>
<body>


#%Module1.0#####################################################################​proc ModulesHelp { } {​puts stderr " "puts stderr "This module loads openfoam built with the intel compiler and mpicc"puts stderr "toolbook openfoam"puts stderr "\nVersion 10.0\n"​}module-whatis "Name: openfoam compiled with intel compiler and mpicc"module-whatis "Version: 10.0"module-whatis "Category: Toolbox"module-whatis "Description: openfoam compiled with intel compiler and mpicc"module-whatis "URL https://openfoam.org"​set     version             10.0​prepend-path    PATH                /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/binprepend-path    MANPATH             /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/docprepend-path    INCLUDE             /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/srcprepend-path    LD_LIBRARY_PATH     /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc​setenv          OPENFOAM_DIR        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10setenv          OPENFOAM_BIN        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/binsetenv          OPENFOAM_LIB        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etcsetenv          OPENFOAM_INC        /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/srcprepend-path    MODULEPATH          /opt/ohpc/pub/moduledeps/intel-mpiccsource-sh       bash                /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc​depends-on      intel-oneapidepends-on      mpidepends-on      gnu9depends-on      openmpi4depends-on      compiler/2022.2.0​​​~~~~~~~~​
--



</body>
</html>`

The error:

<html>
<body>


module load intel-mpicc/openfoam/10.0Lmod has detected the following error: /opt/ohpc/pub/moduledeps/intel-mpicc/openfoam/10.0: (intel-mpicc/openfoam/10.0): invalid commandname "source-sh"While processing the following module(s):    Module fullname            Module Filename    ---------------            ---------------    intel-mpicc/openfoam/10.0  /opt/ohpc/pub/moduledeps/intel-mpicc/openfoam/10.0​
--



</body>
</html>


My script doesn't require arguments, I have also tried with blank arguments between " " and still "source_sh" is not recognised as a valid command...

Thank you in advance for your help

**Comment by marseaplage** [comment]
> > @mrcawood comment is correct for Lua modulefiles. However I believe that the current modulefile is written in TCL. In that case:
> > ```
> > source-sh bash /path/to/bash_shell_script arg1 ... argN
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is all clearly written in the documentation:
> > https://lmod.readthedocs.io/en/latest/051_tcl_modulefiles.html?highlight=source-sh#tcl-modulefile-functions
> > Please consult the documentation before asking questions already answered there. If the documentation isn't clear then ask questions to clarify.
> 
> Hi @rtmclay
> 
> I read that, the problem is that it is still not recognised by the lmod 8.7, that's why I am asking for clarification, now I used as follows and I got that error:
> 
> `#%Module1.0##################################################################### ​ proc ModulesHelp { } { ​ puts stderr " " puts stderr "This module loads openfoam built with the intel compiler and mpicc" puts stderr "toolbook openfoam" puts stderr "\nVersion 10.0\n" ​ } module-whatis "Name: openfoam compiled with intel compiler and mpicc" module-whatis "Version: 10.0" module-whatis "Category: Toolbox" module-whatis "Description: openfoam compiled with intel compiler and mpicc" module-whatis "URL https://openfoam.org" ​ set version 10.0 ​ prepend-path PATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/bin prepend-path MANPATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/doc prepend-path INCLUDE /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/src prepend-path LD_LIBRARY_PATH /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc ​ setenv OPENFOAM_DIR /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10 setenv OPENFOAM_BIN /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/bin setenv OPENFOAM_LIB /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc setenv OPENFOAM_INC /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/src prepend-path MODULEPATH /opt/ohpc/pub/moduledeps/intel-mpicc source-sh bash /opt/ohpc/pub/libs/intel/mpicc/openfoam/10.0/OpenFOAM-10/etc/bashrc ​ depends-on intel-oneapi depends-on mpi depends-on gnu9 depends-on openmpi4 depends-on compiler/2022.2.0`
> 
> The error:
> 
> `module load intel-mpicc/openfoam/10.0Lmod has detected the following error: /opt/ohpc/pub/moduledeps/intel-mpicc/openfoam/10.0: (intel-mpicc/openfoam/10.0): invalid commandname "source-sh"While processing the following module(s):    Module fullname            Module Filename    ---------------            ---------------    intel-mpicc/openfoam/10.0  /opt/ohpc/pub/moduledeps/intel-mpicc/openfoam/10.0​`
> 
> My script doesn't require arguments, I have also tried with blank arguments between " " and still "source_sh" is not recognised as a valid command...
> 
> Thank you in advance for your help

I am in the same case as this one: [lmod-tcl-execute-bash-script-while-loading-module](https://stackoverflow.com/questions/54802681/lmod-tcl-execute-bash-script-while-loading-module)


but the "execute" function is just for Lua modules, and in ohpc the modules are written in tcl and there is no such "execute" function as the documentation shows: [](https://lmod.readthedocs.io/en/latest/051_tcl_modulefiles.html)

**Comment by marseaplage** [comment]
Hey guys, just to make you know, I solved my problem following these conversions: [lmod openfoam issue](https://github.com/TACC/Lmod/issues/598) and the tcl to lua (as 
[@Georgia S](https://openhpc.slack.com/team/U01G0BL9EPJ)
) suggested with this lmod function: https://lmod.readthedocs.io/en/latest/095_tcl2lua.html
