### ISSUE TITLE
environment: line 17: /usr/share/lmod/lmod/libexec/lmod: No such file or directory

### ISSUE THREAD

**Issue by Sububioinfo** [TACC/Lmod#645]
Hi i ahve installed lmod using yum install Lmod
Here is my installed module and its version

module --version

Modules based on Lua: Version 8.7.20  2023-03-16 11:43 -05:00
    by Robert McLay mclay@tacc.utexas.edu

Here is the installed directory

cd /usr/share/lmod/
[root@master lmod]#  tree -L 1
.
├── 8.7.20
└── lmod -> 8.7.20

2 directories, 0 files

module avail

---------------------------------------------------------------- /usr/share/lmod/lmod/modulefiles/Core ----------------------------------------------------------------
   fastqc/0.12.1    lmod    settarg

If the avail list is too long consider trying:

"module --default avail" or "ml -d av" to just list the default modules.
"module overview" or "ml ov" to display the number of modules for each name.

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

When I was loading into Slurm files. I am getting the following error. please help me to rectify this
module load fastqc/0.12.1

environment: line 17: /usr/share/lmod/lmod/libexec/lmod: No such file or directory
/var/spool/slurm/slurmd/job00040/slurm_script: line 14: fastqc: command not found

**Comment by rtmclay** [comment]
With such limited information to go on,  it is hard to tell.  It is helpful to include the modulefile when submitting a bug report.   My best guess is that you are using source-sh script and the script  wasn't found.

If you are trying to use source-sh to convert a script into a module and it doesn't work. You need to run `$LMOD_DIR/sh_to_modulefile`  on the script with the -D option and see what stderr reports.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by GudaLab** [comment]
yes
