### ISSUE TITLE
Python packaging > 21.3 breaks spider -o spider-json $MODULEPATH

### ISSUE THREAD

**Issue by fizwit** [TACC/Lmod#646]
spider -o spider-json and jsonSoftwarePage break with new versions of setuptools and packaging.

Python setuptools >= 66 with packaging > 21.3 will break spider-json and jsonSoftwarePage.

Python packaging tools require semantic versioning.  Many of the software projects deployed with LMOD do not follow semantic versioning.

see:
https://github.com/pypa/setuptools/issues/3772#issuecomment-1384342813
```
MCR
Traceback (most recent call last):
  File "/home/jfdey/git/easybuild-life-sciences/scripts/spider2post.py", line 35, in <module>
    verVal = version.parse(pac[release]['Version'].split('-')[0])
  File "/home/jfdey/.local/lib/python3.8/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/jfdey/.local/lib/python3.8/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'R2020a'
```

**Comment by wpoely86** [comment]
I'm not sure I understand what you're saying. Lmod will simply spit out json with the spider data. It's up to you to use it in any way you like.

This script `spider2post.py` is not something that is part of Lmod.

**Comment by mrcawood** [comment]
For reference, here is the documentation for how Lmod interprets versioning:
https://lmod.readthedocs.io/en/latest/060_locating.html

**Comment by fizwit** [comment]
Yes, `spider -o jsonSoftwarePage $MODULEPATH` does generate perfect JSON. But the documentation shows a pipe to this: command: `python  -mjson.tool` which will no longer work with newer versions of packaging. 
Link to docs:
https://lmod.readthedocs.io/en/latest/136_spider.html?highlight=json#software-page-generation

**Comment by wpoely86** [comment]
What kind of error do you get? `python -mjson.tool` should work as long as it is valid json. It displays it, nothing more.
