### ISSUE TITLE
spider -o jsonSoftwarePage crashes in lua 5.4

### ISSUE THREAD

**Issue by jonaslindemann** [TACC/Lmod#652]
**Describe the bug**
When running $LMOD_DIR/spider lua crashes with the following output:

```
$LMOD_DIR/spider -o jsonSoftwarePage $MODULEPATH
/usr/bin/lua: /usr/share/lua/5.4/json/encode/output.lua:8: variable 'loadstring' is not declared
stack traceback:
        [C]: in function 'error'
        /usr/share/lmod/lmod/libexec/../tools/strict.lua:36: in metamethod 'index'
        /usr/share/lua/5.4/json/encode/output.lua:8: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.4/json/encode.lua:12: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.4/json.lua:6: in main chunk
        [C]: in function 'require'
        /usr/share/lmod/lmod/libexec/spider:369: in local 'func'
        /usr/share/lmod/lmod/libexec/spider:494: in function 'main'
        /usr/share/lmod/lmod/libexec/spider:842: in main chunk
        [C]: in ?
```

**To Reproduce**

Run the command in the previous section.

**Expected behavior**
Json-output of installed modules.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: Rocky 9
 - Lmod Version: 8.7.20

**Comment by rtmclay** [comment]
You have a lua json package for Lua 5.1 installed with lua 5.4 and that won't work.  In Lua 5.1, loadstring() was used, where as in later versions it was changed to load().  Please install the correct version of lua-json for Lua 5.4.

**Comment by jonaslindemann** [comment]
I have lua-5.4 installed from repo with lua-json-1.3.4, which is the latest version. I thought this line should handle the issue:

local loadstring = loadstring or load 

from 1.3.4

**Comment by rtmclay** [comment]
Using ```local loadstring = ...``` only works in the current file.  You would have to modify /usr/share/lua/5.4/json/encode/output.lua to have that line.

This is a bug in the Rocky distribution.  You could either go back to Lua 5.1 or use luarocks to install a later version of luajson or patch your installed version of lua-json-1.3.4

**Comment by rtmclay** [comment]
If you patch your installed of json please use:
```
local load   = (_VERSION == "Lua 5.1") and loadstring or load
```

If you use luarocks then please install the json4lua package.
