### ISSUE TITLE
Feature Request: Print the contents of 'inherited' modules when doing module show.

### ISSUE THREAD

**Issue by Paul-Ferrell** [TACC/Lmod#653]
**Describe the bug**

We've been using the `inherit()` feature to patch in module paths to additional module trees when loading compilers and MPI's. We do this because on Cray Shasta systems we don't have control over the base modulefiles - they come pre-packaged from Cray. This works pretty well - when swapping out compilers/mpi, our modulepaths get changed, which forces reloads of all our provided modules as expected. 

The one big downside is that users only see the actions of the inheriting module (including the `inherit()` line) when they do a `module show`. It would be really nice if instead the actions of the inherited module file were shown too, maybe surrounded with comments about where they were inherited from. 

**To Reproduce**

- Prepend a module path with modules that 'shadow' other modules, and include an `inherit()` directive.
- Run `module show <that_module>`

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: Cray Shasta
 - Lmod Version: 8.3.1

**Comment by rtmclay** [comment]
This will be added to the list of feature requests to be worked on.  Please let me know that your site would be willing to install the latest version of Lmod when this feature exists.

**Comment by Paul-Ferrell** [comment]
Yes, we will install the latest LMOD if it gets this fix.

**Comment by rtmclay** [comment]
Please test Lmod 8.7.29 to see it works for you.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by Paul-Ferrell** [comment]
Yes, this can be closed.


________________________________
From: Robert McLay ***@***.***>
Sent: Sunday, July 23, 2023 1:22 PM
To: TACC/Lmod
Cc: Ferrell, Paul Steven; Author
Subject: [EXTERNAL] Re: [TACC/Lmod] Feature Request: Print the contents of 'inherited' modules when doing module show. (Issue #653)


O.K. to close this issue?
