### ISSUE TITLE
As sysadmin: can I disable defaults and  enforce fullnames (Name/Version) ?

### ISSUE THREAD

**Issue by ruixingw** [TACC/Lmod#658]
Forgive me if this is documented somewhere but I can't find it.

Is it possible to enforce users to use fullnames (Name/Version)? 
For example, they must do `module load FOO/bar`, and `module load FOO` should raise an error.

**Comment by mrcawood** [comment]
Hi, you are looking for [LMOD_EXACT_MATCH](https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html)

**Comment by ruixingw** [comment]
> Hi, you are looking for [LMOD_EXACT_MATCH](https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html)

Thank you. This is useful, but it seems to be globally effective. Is there an option to only enforce fullname for a certain module?
For example, for `FOO`, one must use fullname like `module load FOO/1.0`, and `module load FOO` should raise an error. But for `BAR`, one can just load the default version by `module load BAR`.

**Comment by ruixingw** [comment]
> > Hi, you are looking for [LMOD_EXACT_MATCH](https://lmod.readthedocs.io/en/latest/090_configuring_lmod.html)
> 
> Thank you. This is useful, but it seems to be globally effective. Is there an option to only enforce fullname for a certain module? For example, for `FOO`, one must use fullname like `module load FOO/1.0`, and `module load FOO` should raise an error. But for `BAR`, one can just load the default version by `module load BAR`.

Oh, I guess this can be achieved by creating a module file that simply raises an error (maybe also print a message to tell the users to use fullname), and make a default symlint that points to it.

**Comment by rtmclay** [comment]
That solution you propose will work great.  Other sites have created a 9999999 module to be the default that reports an error.

O.K. to close this issue?

**Comment by ruixingw** [comment]
> That solution you propose will work great. Other sites have created a 9999999 module to be the default that reports an error.
> 
> O.K. to close this issue?

Sure. 
Thanks for the help.
