### ISSUE TITLE
Tab completion on module use

### ISSUE THREAD

**Issue by ddietz89** [TACC/Lmod#66]
Hi, 

I get errors when trying to tab complete "module use" statements:

$ module use /opt/lmo-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found
-bash: _filedir: command not found

"module load" works just fine. I am running version 5.9.3.3.

Dan

**Comment by rtmclay** [comment]
You need the bash-completion package for your system.  _filedir is part of that.

**Comment by ddietz89** [comment]
Ahah. Didn't know that was a separate thing since bash already completes. Seems to have done the trick. Thanks!
