### ISSUE TITLE
Alias is not unset upon unload

### ISSUE THREAD

**Issue by marvinfriede** [TACC/Lmod#661]
I have a modulefile, in which I am setting an alias because the program must always be called with the full path. However, after `unload`ing, the alias is still there and I can call the program. Only after manual `unalias`ing it is gone. Why is this happening, and how can I fix this? Otherwise, everything is working fine.

<details>
  <summary>modulefile</summary>

```lua
-- package info
local name = "orca"
local version = "5.0.4"
local prefix = pathJoin("/opt/software", name, version)

depends_on("openmpi")
prepend_path("PATH", pathJoin(prefix, "bin"))

if (mode() == "load") then
    io.stderr:write(string.format("Module %s (version %s) loaded.\n", name, version))
    
    -- Set an alias to call orca with full path (shell-agnostic)
    set_alias("orca", pathJoin(prefix, "bin",  "orca"))
end

if (mode() == "unload") then
    io.stderr:write(string.format("Module %s (version %s) unloaded.\n", name, version))

    -- FIXME: this does not have an effect
    unset_alias("orca")
end
```

</details> 

<details>
  <summary>Console output</summary>

```console
friede@kopfknoten:~$ module load orca
Module openmpi (version 4.1.5) loaded.
Module orca (version 5.0.4) loaded.

friede@kopfknoten:~$ type -a orca
orca is aliased to `/opt/software/orca/5.0.4/bin/orca'
orca is /opt/software/orca/5.0.4/bin/orca

friede@kopfknoten:~$ module purge
Module openmpi (version 4.1.5) unloaded.
Module orca (version 5.0.4) unloaded.

friede@kopfknoten:~$ type -a orca
orca is aliased to `/opt/software/orca/5.0.4/bin/orca'

friede@kopfknoten:~$ unalias orca

friede@kopfknoten:~$ type -a orca
-bash: type: orca: not found
```

</details>

<details>
  <summary>Further information</summary>

 - lmod version: 8.7
 - shell: bash
 - install path: /opt/software/lmod
 - modulefile path: /opt/modulefiles/orca/5.0.4.lua
 - initialization: `ln -s /opt/software/lmod/lmod/init/profile /etc/profile.d/z00_lmod.sh`

</details>

**Comment by mrcawood** [comment]
Hi, Lmod automatically reverses the set_alias() function when unloading the module (like most other functions), without needing an explicit unset_alias(). Moving the function outside your conditional blocks will produce the expected result.

**Comment by marvinfriede** [comment]
Oh indeed, I thought I already tried this, but apparently I didn't. Thanks.
