### ISSUE TITLE
module command does not work in a SLURM job script

### ISSUE THREAD

**Issue by wadudmiah** [TACC/Lmod#663]
Hi,

I am able to use the `module` command from the Linux shell on a HPC cluster, but when `module` commands are executed in SLURM scripts, the module command does not work and instead shows how to use the `module` command. Below is my simple SLURM job script:
```
#!/bin/sh
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=6:00:00
#SBATCH -p batch

module list
```
When I type `module list` from my Linux shell, it works perfectly fine, but not in a job script. I am using Lmod version 8.2.7. Any help will be greatly appreciated. 

Regards,

**Comment by rtmclay** [comment]
This is more likely a question for the sysadmins at your site than here.  However, I can give you a few things:

1. Change #!/bin/sh to #!/bin/bash
2. Check the value of $BASH_ENV.  It should have a value.  The value should a file name that defines the module and ml commands

Are you running bash or zsh or tcsh as your personal shell?

Also what is output from this command:

$ module --config 2>&1 | grep LMOD_EXPORT_MODULE

**Comment by wadudmiah** [comment]
Hi Robert,

Changing `#!/bin/sh` to `#!/bin/bash` has resolved this issue. Many thanks for the prompt response. I am using BASH. Below is the output of the command:
```
$ module --config 2>&1 | grep LMOD_EXPORT_MODULE
Export the module command (LMOD_EXPORT_MODULE)                yes
```

**Comment by wadudmiah** [comment]
I'll close this ticket since you have resolved it. Thanks again.
