### ISSUE TITLE
No Lmod 8.8 tarball available

### ISSUE THREAD

**Issue by tygoetsch** [TACC/Lmod#664]
The RTDs mention that LMod 8.8+ has Dynamic Spider Cache Support in the form of the HaveDynamicPath() function, however I don't see a tarball on SourceForge for it (highest is 8.7), and I don't see a tag in github (highest is 8.7.30). Is this feature available in lower versions than 8.8, and if not, can I get a tarball for 8.8?

RTD link: https://lmod.readthedocs.io/en/latest/136_spider.html#dynamic-spider-cache-support

**Comment by rtmclay** [comment]
This was a typo in the documentation.  The Feature was added in 8.7.4.  The documentation has been updated.

**Comment by tygoetsch** [comment]
Awesome, thank you!
