### ISSUE TITLE
TCL modulefile missing getenv function

### ISSUE THREAD

**Issue by imciner2** [TACC/Lmod#665]
**Notes**
Please note that we do not provide patches to older versions of Lmod, To speed up fixing your issue please test your bug against the latest version of Lmod.
See: https://lmod.readthedocs.io/en/latest/045_transition.html if you want to install the latest version in your own account.

**Describe the bug**

TCL module files don't recognize the `getenv` function. This can be seen using the Intel Debugger 2023.2.0 module file provided by Intel, since it contains the following snippet:
```
# Documentation                                                         
if { "" eq [getenv MANPATH] || "_UNDEFINED_" eq [getenv MANPATH] } {    
    setenv MANPATH "$gdbroot/documentation/man:"                          
} else {                                                                
    prepend-path MANPATH "$gdbroot/documentation/man"                     
}
```
 
**To Reproduce**

Either:
1) Attempt to use the Intel oneAPI Debugger 2023.2.0 modulefile shipped with the Intel installer (for instance, install from yum/dnf then generate the modulefile).
or
2) Place that above snippet into a TCL module file and try to run it with LMOD

**Expected behavior**

That `getenv` behaves similar to the function provided by Environment Modules and works.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: Fedora 37
 - Lmod Version: 8.7.30
 - For Lmod Versions 8.7.7+, please run "module --miniConfig" and
   include the output here.

```
module --miniConfig

Modules based on Lua: Version 8.7.30  2023-07-21 17:13 -05:00
    by Robert McLay mclay@tacc.utexas.edu

Changes from Default Configuration
----------------------------------

Name                         Where Set  Default                                         Value
----                         ---------  -------                                         -----
LFS_VERSION                  D          1.6.3                                           1.8.0
LMOD_AVAIL_STYLE             E          <system>                                        en_grouped
LMOD_HAVE_LUA_TERM           C          no                                              yes
LMOD_PACKAGE_PATH            D          nil                                             /home/im1716/.local/share/modules
LMOD_PAGER                   E          less                                            none
LMOD_SITEPACKAGE_LOCATION    Other      /usr/share/lmod/8.7.30/libexec/SitePackage.lua  /home/im1716/.local/share/modules/SitePackage.lua
LMOD_SYSTEM_DEFAULT_MODULES  D          __unknown__                                     <empty>
LMOD_TCLSH                   C          tclsh                                           /usr/bin/tclsh
MODULEPATH_ROOT              E                                                          /usr/share/modulefiles
PATH_TO_LUA                  C          lua                                             /usr/bin/lua


Where Set -> D: default, E: environment, C: configuration
             lmod_cfg: lmod_config.lua SitePkg: SitePackage StdPkg: StandardPackage
             Other: Set somewhere outside of normal locations
```

**Additional context**

It appears this TCL function was added by Environment Modules in version 4.0 (documented here https://modules.readthedocs.io/en/latest/modulefile.html). Intel then updated their script to go from
```
prepend-path MANPATH "$gdbroot/documentation/man"
```
to
```
if { "" eq [getenv MANPATH] || "_UNDEFINED_" eq [getenv MANPATH] } {    
    setenv MANPATH "$gdbroot/documentation/man:"                          
} else {                                                                
    prepend-path MANPATH "$gdbroot/documentation/man"                     
}
```
between versions 2023.1.0 and 2023.2.0, so this issue is new when trying to use the 2023.2.0 provided module file.

**Comment by mrcawood** [comment]
Hi, the getenv TCL function has been added, please test with 8.7.31

**Comment by imciner2** [comment]
Thanks. I can confirm that 8.7.31 works with this Intel module file now.
