### ISSUE TITLE
include `modulerc.d/*.lua`???

### ISSUE THREAD

**Issue by simonLeary42** [TACC/Lmod#669]
I would like to separate my modulerc.lua configuration into separate files so that I can update the contents of one of those files with a cron job. Is this doable? Lmod doesn't seem to like `dofile` or `require`.

**Comment by rtmclay** [comment]
Use loadfile instead.

**Comment by simonLeary42** [comment]
```
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
<unknown>
     /modules/lmod/modulerc.lua: [string "loadfile("/modules/lmod/modulerc.d/old.lua"..."]:1: attempt to call global
'loadfile' (a nil value)
     Please check the modulefile and especially if there is a line number specified in the above message
```

I don't know much about lua, do I have to install a special package for this? (I'm on ubuntu 20.04)

**Comment by simonLeary42** [comment]
I also tried this:
```lua
local i18n = require("i18n")
i18n.loadfile("/modules/lmod/modulerc.d/old.lua")
```
but no luck:
```
attempt to call global 'require' (a nil value)
```

**Comment by rtmclay** [comment]
It will be weeks before I'll be able to work on this.  If you are willing to download the latest version of Lmod, you could make loadfile() work by modifying src/mrc_sandbox.lua to have at line 54:
```
local mrc_sandbox_env = {
   loadfile        = loadfile,
```

**Comment by rtmclay** [comment]
Support for this requested feature has been added to the testing branch of Lmod.  You can use either $LMOD_MODULERC or $LMOD_MODULERCFILE to specify a single file, directory or a colon separated list of either.

Please use the testing branch to see if it works for you.

**Comment by simonLeary42** [comment]
Am I doing something wrong?
```
$ ls -l /modules/lmod/test-modulerc.d/test.lua
-rwxrwxr-x+ 1 package-maintainer package-maintainer    29 Jan 15 18:56 test.lua*
$ export LMOD_MODULERC=/modules/lmod/test-modulerc.d
$ module --config 2>&1 | grep "Active RC file" -A 10
Active RC file(s):
------------------
/modules/opt/x86_64/lmod/test/lmod/8.7.34/init/lmodrc.lua
/etc/lmod/lmodrc.lua
```

**Comment by rtmclay** [comment]
There is an overlap of concepts. The RC files are where the  properties for modules  are set and where the spider cache files are.  The LMOD_MODULERC is where the module defaults and aliases are set.  Try this instead:
```
$ export LMOD_MODULERC=/modules/lmod/test-modulerc.d
$ module --config 2>&1 | grep "LMOD_MODULERC"
```

**Comment by simonLeary42** [comment]
It works. But `module --config` says my directory is empty despite applying the defaults/aliases found in that directory.

```
MODULERC (LMOD_MODULERC)                                      /modules/lmod/test-modulerc.d -> <empty>
```

**Comment by simonLeary42** [comment]
LGTM

**Comment by rtmclay** [comment]
Closing this issue then.
