### ISSUE TITLE
prereq for classic module files behaves different for Lmod than env. modules

### ISSUE THREAD

**Issue by bartoldeman** [TACC/Lmod#67]
If I do

prereq gcc/4.8.2 gcc/4.9.1
or
prereq gcc
(with multiple gcc versions available)

then environment modules wants any of these modules loaded (as in prereq_any Lua syntax), but Lmod wants all modules. This causes issues in our upgrade path from environment modules to lmod (unless we rewrite all module files into Lua immediately).

**Comment by bartoldeman** [comment]
A fix is pretty simple. This seems to fix all the local issues (incl. "prereq gcc") but I will check further.

```
--- tcl2lua.tcl.orig	2015-06-17 09:21:06.372786645 -0400
+++ tcl2lua.tcl	2015-06-17 09:20:52.787812000 -0400
@@ -539,7 +539,7 @@
     eval cmdargs $cmdName $args
 }
 proc prereq { args } {
-    eval cmdargs "prereq" $args
+    eval cmdargs "prereq_any" $args
 }
 proc prereq-any { args } {
     eval cmdargs "prereq_any" $args
```

**Comment by rtmclay** [comment]
In reading the man page for prereq, your reading of the TCL/C implementation is correct.  I'll be switching Lmod's version of tcl2lua.tcl to use prereq_any like you have above.

My reading of conflict is that doesn't make a different.

   conflict A B C

or 
   conflict A
   conflict B
   conflict C

Are the same.  Do you agree?

**Comment by rtmclay** [comment]
I have pushed changes to use prereq_any when  the prereq command is used from a TCL modules.   This version is marked 6.0.3

**Comment by bartoldeman** [comment]
Thanks for the quick fix. I agree about conflict (theoretically you could AND conflicts so you would have to have loaded ALL of A B and C to conflict but that is not how it works, and also hard to imagine a practical use case).
