### ISSUE TITLE
lmod incorrectly returns exit code 1 on warning

### ISSUE THREAD

**Issue by haampie** [TACC/Lmod#674]
First bad version is 8.7.19, so it's likely this change:

https://github.com/TACC/Lmod/commit/97e4166d7ed428f6c3e7501af649c07a1adbb3d8

I have a hierarchy:

```
module load gcc # make packages compiled with gcc available
module load openblas # make packages that use openblas for blas available
module load py-scipy # finally use py-scipy that uses openblas and is compiled with gcc
```

This used to work until Lmod version 8.7.19, where the following warning:

```
Lmod Warning: 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: zlib-ng/2.1.4-5xcetrv (required by: gcc/12.3.0), zstd/1.5.5-jkznmrm (required by: gcc/12.3.0)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

is issued which results in an **exit code 1**.

Previously this also warned, but it returned with **exit code 0**.

If it's a warning, then it shouldn't exit with error status.

The reason this warns is that gcc itself depends on `zlib` and `zstd` (I could try to get rid of autoloading these, but technically they are runtime dependencies of the compiler).

**Comment by rtmclay** [comment]
I have updated Lmod's testing branch to NOT set the error return when a warning is produced.  If you get the chance, please try out Lmod's testing branch to see if it works for you.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by haampie** [comment]
Thanks!
