### ISSUE TITLE
module keyword does not work for all capitals

### ISSUE THREAD

**Issue by bartoldeman** [TACC/Lmod#68]
We found that if we did "module keyword FFTW", it did not find any whatis sections mentioning FFTW.
This seems to be connected to the all caps notation.

Example TCL module file:

```
module-whatis "ALLCAPS lowercase"
```

```
module keyword lowercase
```
will find this module

but
```
module keyword ALLCAPS
```

will not.

**Comment by rtmclay** [comment]
Thanks very much for the bug report.  I have updated HEAD to correct this case.  Please test it out and see if it works for you.

**Comment by bartoldeman** [comment]
Thanks for the quick fix! It works now, also for `module keyword FFTW`
