### ISSUE TITLE
module.1 man page is not in the man format

### ISSUE THREAD

**Issue by lahwaacz** [TACC/Lmod#686]
The Makefile installs a `module.1` man page which is not in the man format, but a plain-text file: https://github.com/TACC/Lmod/blob/eb3e9119ef1ec3a17f2feb693c9dba16e1c93503/Makefile.in#L245

This results in suboptimal formatting when viewed with the `man` utility from [man-db](https://gitlab.com/man-db/man-db):

```
Usage: module [options] sub‐command [args ...]

Options:
  ‐h ‐? ‐H ‐‐help                   This help message
  ‐s  availStyle ‐‐style=availStyle  Site controlled avail style:
system
                                    (default: system)
  ‐‐regression_testing              Lmod regression testing
  ‐b ‐‐brief                        brief listing with only  user
specified
                                    modules
  ‐D                                 Program  tracing  written to
stderr
  ‐‐debug=dbglvl                    Program  tracing  written  to
stderr (where
                                    dbglvl is a number 1,2,3)
  ‐‐pin_versions=pinVersions         When  doing  a  restore  use
specified
                                    version, do  not  follow  de‐
faults
  ‐d  ‐‐default                       List  default  modules only
when used with
                                    avail
...
```

[mandoc](https://mandoc.bsd.lv/) can't even parse it and displays unreadable "binary data".

Please write a proper man page in a supported format.

**Comment by rtmclay** [comment]
The branch PR686 now support a man.1 output.  Please test it out to see if works for you.

**Comment by lahwaacz** [comment]
There is no [pull request 686](https://github.com/TACC/Lmod/pulls), the #686 refers to this issue...

**Comment by rtmclay** [comment]
I know that issue #686 is not a pull request.  As I said, a  branch named PR686 has code to generate a manpage for module.1. If you et a chance, please test this branch.

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by rtmclay** [comment]
This is now part of Lmod 8.7.44.  I'm closing this issue.  Feel free to reopen if there are issues.

**Comment by lahwaacz** [comment]
@rtmclay Thanks, it looks fine in 8.7.44.
