### ISSUE TITLE
module is-loaded broken in Lmod version 8.7.34

### ISSUE THREAD

**Issue by lillykayasesa** [TACC/Lmod#687]
**Describe the bug**

From a command line, “$ if module is-loaded pkg ; then echo "pkg is loaded"; fi” always returns that the module is loaded even when it is not. Note: we ran this on several modules to ensure it was not an individual module’s issue.

**To Reproduce**

> module load module_name/1.2.3
> module list
Currently Loaded Modules:
… shows module is listed …
> module is-loaded module_name/1.2.3
> if module is-loaded module_name/1.2.3; then echo "pkg is loaded"; fi
pkg is loaded
> module unload module_name/1.2.3
> module list
Currently Loaded Modules:
… shows module no longer loaded …
> module is-loaded module_name/1.2.3
> if module is-loaded module_name/1.2.3; then echo "pkg is loaded"; fi
pkg is loaded

**Expected behavior**

Functionality is described in the document https://buildmedia.readthedocs.org/media/pdf/lmod/latest/lmod.pdf at the top of page #4.

“
Users may wish to test whether certain modules are already loaded: 

$ module is-loaded packageName1 packageName2 ... 

Lmod will return a true status if all modules are loaded and a false status if one is not. Note that Lmod is setting the status bit, there is nothing printed out. This means that one can do the following: 

$ if module is-loaded pkg ; then echo "pkg is loaded"; fi
“

After installing Lmod 8.7.34 (we were running 8.7.31) we are always receiving the answer “pkg is loaded” even if it isn’t.

**Desktop (please complete the following information):**

- OS: Linux
 - Linux distribution: Sles / Redhat
 - Lmod Version: 8.7.34

**Comment by rtmclay** [comment]
Thanks for the bug report!  This used to work.  Then when warnings stopped setting the non-zero exit status, it broken this and is-avail.  I have updated the testing branch to return is-avail and is-loaded back to work for me.  Please try the "testing" branch to see if it works for you.

**Comment by lillykayasesa** [comment]
testing branch code worked for me. Thank you!

```
suse@sles-sp5> ml --version

Modules based on Lua: Version 8.7.34  2024-01-05 19:34 -07:00
    by Robert McLay mclay@tacc.utexas.edu

suse@sles-sp5> ml

Currently Loaded Modules:
  1) mymod   2) ...

suse@sles-sp5> if module is-loaded mymod ; then echo "pkg is loaded"; fi
pkg is loaded
suse@sles-sp5> ml unload mymod
suse@sles-sp5> if module is-loaded mymod ; then echo "pkg is loaded"; fi
suse@sles-sp5> ml

Currently Loaded Modules:
  ... mymod not here ...

suse@sles-sp5>
```

**Comment by rtmclay** [comment]
Great!  Closing this issue.
