### ISSUE TITLE
hide-modulefile is currently ignored

### ISSUE THREAD

**Issue by riederd** [TACC/Lmod#691]
https://github.com/TACC/Lmod/blob/eb3e9119ef1ec3a17f2feb693c9dba16e1c93503/src/RC2lua.tcl#L65

The `hide-modulefile` function is currently ignored in TCL modules having `.modulerc` files since the function is a noop. 

In my simple minded approach I added basic functionality to it:

```
proc module-hide {args} {
    set mfile [lindex $args end]
    myPuts "\{kind=\"hide_modulefile\", mfile=\"$mfile\"\},"
}
```

This way TCL modules with a `.modulerc` file containing `module-hide [...] <modulefile>` are not shown with `module avail` however they are (as expected) when using `module --show_hidden avail`.

Do I miss something that could cause problems with this simple "fix", or could you think to include this or something more sophisticated in future releases?

**Comment by haampie** [comment]
Similar: #690

**Comment by riederd** [comment]
True, but I'm proposing a "solution" ;-)
However, since I'm new to Lmod, I don't really know if my "solution" is breaking something else.

**Comment by rtmclay** [comment]
I am closing this ticket.  All discussion is being moved to #690.
