### ISSUE TITLE
HEAD detached at

### ISSUE THREAD

**Issue by surak** [TACC/Lmod#699]
At some point, the makefile changed and now I have this message (HEAD Detached at x.x.x) which breaks the debian build. When did this happen?

**Comment by surak** [comment]
I just checked, Makefile.in works just fine from commit 7f8bcd9 from 2 weeks ago. debuild produces this:

```
LUA_PATH="./tools/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua" LUA_CPATH="/usr/local/lib/lua/5.3/?.so;/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;" /usr/bin/lua5.3 ./proj_mgmt/buildVersion_src (HEAD detached at 8.7.36) 8.7.36 8.7.36 "2024-03-15 21:41 +00:00" >  /tmp/git-repo/Lmod/debian/lmod/usr/lmod/8.7.36/libexec/Version.lua 
```

On the broken version. It is not waiting for this `(head detached at xxx)` string

**Comment by rtmclay** [comment]
Lmod will now report the git branch it is on if it can find it  or assume it is "main".  See Makefile.in lines 131-133 where the Makefile.in is asking for the branch.   Please try "make echo" to see what GIT_BRANCH is. I believe that is the problem.

I do not understand the debian build process to be able to test it myself.  Can you recommend a way to rewrite lines 131 - 133 or can you teach me or point me towards some that explains what happens during "debuild"

**Comment by rtmclay** [comment]
Never mind.  I fixed it.  Once I understood that your build script is doing "git checkout X.Y.Z" and got the (HEAD detached at X.Y.Z) message I could fix it.  Please try to build a debian pkg for 8.7.37.  Thanks very much for the bug report.

**Comment by surak** [comment]
Works!!!!

**Comment by surak** [comment]
Here is the debian package file: https://github.com/surak/Lmod/releases/tag/8.7.37
