### ISSUE TITLE
LMOD_TMOD_FIND_FIRST and defaults in rc.lua

### ISSUE THREAD

**Issue by AcerP-py** [TACC/Lmod#729]
Question about `LMOD_TMOD_FIND_FIRST`. Is the expected behavior that it overrides defaults found in the rc.lua file (if the default is in a lower path)? (I can create a reproducer for this but wanted to make sure it was actually a bug before I spent the time.)

**Comment by rtmclay** [comment]
The RC file (or the file or directory pointed to by LMOD_MODULERC) is only for setting defaults or hiding modules, etc. So I don't understand how one could set LMOD_TMOD_FIND_FIRST in an rc file.   Is there someplace in the documentation that implies that one can set LMOD_TMOD_FIND_FIRST in the LMOD_MODULERC files?

One can set LMOD_TMOD_FIND_FIRST as an env. var or configure Lmod or use SitePackage.lua or /etc/lmod/lmod_config.lua.   If this env. var is set then it applies everywhere for all MODULEPATHs.

Or if any directory in the current set of directories is NVV then all are treated as LMOD_TMOD_FIND_FIRST

**Comment by AcerP-py** [comment]
Sorry if my question was a little unclear. I have a version of gcc set as default in my `rc.lua` file. But when I set `LMOD_TMOD_FIND_FIRST` as an environment variable it will ignore that default and pick a version of gcc in a higher path.

**Comment by rtmclay** [comment]
Have you tested the latest version of Lmod?  I believe this has been fixed there.

**Comment by AcerP-py** [comment]
Yes I am using `8.7.53`.

**Comment by rtmclay** [comment]
Actually, the current behavior of Lmod is correct.  Setting LMOD_TMOD_FIND_FIRST means that where the first directory is found is where the default will be determined.  So having a module tree as follows:
```
% tree -a m1 m2        
m1
└── A
    ├── 1.0
    ├── 2.0
    └── 3.0
m2
└── A
    ├── .modulerc
    └── 2.5
```
And `MODULEPATH=/path/to/m1:/path/to/m2`

means that `module load A` will load `A/3.0` even though `m2/A/2.5` is marked as a default.  Now what I remembered is that `module load A/2.5` will load `A/2.5`. Lmod will search all directories in MODULEPATH when finding the exact match. But when this env. var is set only the first directory is search for defaults. 

Obviously, if you want to have `A/2.5` loaded by default then you'll have to have `MODULEPATH=/path/to/m2:/path/to/m1`  or unset `LMOD_TMOD_FIND_FIRST`

**Comment by AcerP-py** [comment]
This is what I wanted to confirm. We are adding some new compilers but wanted to keep the old ones around and the path for the old compilers is above the new ones in our current setup. Since what you explained is the expected behavior then we will have to modify our paths. Thanks!

**Comment by rtmclay** [comment]
You are welcome. Closing this issue.
