### ISSUE TITLE
dbT files allow modules not in...

### ISSUE THREAD

**Issue by ocaisa** [TACC/Lmod#73]
users `MODULEPATH` to be shown in`module spider` output. Gist with reproducible example is [available here](https://gist.github.com/ocaisa/9718c07e0071b6554fa8)

**Comment by rtmclay** [comment]
I am unclear as to what you are asking.  Please be explicit and say something like I got this:

    .....

But I expected this:

   ....

Thanks,

**Comment by ocaisa** [comment]
Ok, no problem, I guess it's a little bit hidden in [the gist](https://gist.github.com/ocaisa/9718c07e0071b6554fa8). Basically, if I use the `update_lmod_system_cache_files` script, it generates `dbT` files in the `cacheDir`.  Now if I do a module spider on the example tree I provided in [the gist](https://gist.github.com/ocaisa/9718c07e0071b6554fa8) I get
```
alanc@alanc-VirtualBox:~/new_test/Example_dbT$ module av

---------------------------------- /home/alanc/new_test/Example_dbT/Tree/UI/Compilers ----------------------------------
   Compiler1/Devel    Compiler2/Devel

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

alanc@alanc-VirtualBox:~/new_test/Example_dbT$ module spider Compiler1/Devel

-------------------------------------------------------------------------------------------------------------------------
  Compiler1: Compiler1/Devel
-------------------------------------------------------------------------------------------------------------------------

    This module can be loaded directly: module load Compiler1/Devel

    Additional variants of this module can also be loaded after the loading the following modules:

      Stages/.Stage1
      Stages/.Stage2
      Stages/Current
      Stages/Devel

```

I consider this wrong because the user has no way to access the Stages module with their current `MODULEPATH`. If I remove the `dbT` files I get what I think is the correct output:

```
alanc@alanc-VirtualBox:~/new_test/Example_dbT$ rm moduleData/cacheDir/dbT.lua*
alanc@alanc-VirtualBox:~/new_test/Example_dbT$ module spider Compiler1/Devel

-------------------------------------------------------------------------------------------------------------------------
  Compiler1: Compiler1/Devel
-------------------------------------------------------------------------------------------------------------------------

    This module can be loaded directly: module load Compiler1/Devel


```

**Comment by rtmclay** [comment]
That is not how **module spider** works.  The command **module avail** tells you what module you can do a **module load**.  In other words if you can't avail it, you can't load it.

**module spider** is is completely different.  It reports modules that are in the whole tree including modules that can not be loaded with the current MODULEPATH.  Here is an edited output from running **ml spider** on stampede:

    $ module spider pmetis/4.0.2
    -------------------------------------------------
     pmetis: pmetis/4.0.2
   -------------------------------------------------
      Parallel graph partitioning and fill-reduction matrix ordering routines

    This module can only be loaded through the following modules:

      gcc/4.9.1  mvapich2/2.1
      intel/13.0.2.146  impi/4.1.0.030
      intel/13.0.2.146  mvapich2/1.9a2
      intel/14.0.1.106  impi/4.1.0.030
      intel/15.0.2  impi/5.0.2
      intel/15.0.2  mvapich2/2.1

    Help:
      The pmetis module defines the following environment variables: 


If I have no compiler or mpi stack module loaded, I'll still get the same output.   It is designed to show what modules in the hierarchy are required to load "pmetis".

You should get the same output independent of whether you have a cached dbT.lua file or not.  The fact that you don't means that the directories searched are different between when the cache was built and when you ran the "module spider Compiler1/Devel".  

To be completely clear,  the second output where you don't have dbT.lua* is the bug.

I can look at it if you email me the following:

a) The log files from doing the following:
      $ module -D -D spider Compiler1/Devel 2> spiderWithdbT.log
      $ rm moduleData/cacheDir/dbT.lua*
      $ module -D -D spider Compiler1/Devel  2> spider.log

b) A tar ball of the module tree. 

c) the generated moduleT.lua and dbT.lua file

**Comment by ocaisa** [comment]
OK, I will privately email the files and tarball (the tarball was already available on [the gist](https://gist.github.com/ocaisa/9718c07e0071b6554fa8)). 

I really don't understand though how you cannot consider what I attach here a bug though. If the user cannot access a module through any available extension of their current module tree then it should not be displayed by `spider`, otherwise `spider` gives that load advice that cannot be executed:
```
~$ module av

------------------ /home/alanc/Example_dbT/Tree/UI/Compilers -------------------
   Compiler1/Devel    Compiler2/Devel

------------------- /home/alanc/Example_dbT/Tree/OtherStages -------------------
   Stages/Current    Stages/Devel

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching
any of the "keys".

~$ module unuse $PWDDIR/Tree/OtherStages
~$ module av

------------------ /home/alanc/Example_dbT/Tree/UI/Compilers -------------------
   Compiler1/Devel    Compiler2/Devel

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching
any of the "keys".

~$ module spider Compiler1/Devel

----------------------------------------------------------------------------
  Compiler1: Compiler1/Devel
----------------------------------------------------------------------------

    This module can be loaded directly: module load Compiler1/Devel

    Additional variants of this module can also be loaded after the loading the 
following modules:

      Stages/.Stage1
      Stages/.Stage2
      Stages/Current
      Stages/Devel
 
    Help:
         EasyBuild is a software build and installation framework
      written in Python that allows you to install software in a structured,
      repeatable and robust way. - Homepage: http://hpcugent.github.com/easybuild/
      
      This module provides the development version of EasyBuild.
      
~$ module load Stages/Current
Lmod has detected the following error:  These module(s) exist but
cannot be loaded as requested: "Stages/Current"

   Try: "module spider Stages/Current" to see how to load the module(s).


~$ module spider Stages/Current

----------------------------------------------------------------------------
  Stages: Stages/Current
----------------------------------------------------------------------------

    This module can be loaded directly: module load Stages/Current

    Help:
         
      This module switches to stage 1.
      
      
      

~$ module load Stages/Current
Lmod has detected the following error:  These module(s) exist but
cannot be loaded as requested: "Stages/Current"

   Try: "module spider Stages/Current" to see how to load the module(s).


```

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by ocaisa** [comment]
Oh, that is lying around a while despite being being fixed...closing
