### ISSUE TITLE
Support for hidden directories

### ISSUE THREAD

**Issue by blappm** [TACC/Lmod#78]
We found that support for hidden directories which should not be displayed was missing. This little patch adds support for it:

```
--- ./5.9.3/libexec/Master.lua.orig     2015-09-29 16:40:39.100433333 +0200
+++ ./5.9.3/libexec/Master.lua  2015-09-29 16:40:50.871209132 +0200
@@ -950,6 +950,13 @@
       return
    end

+   -- ADDED BY martin.blapp@nashire.com, 09292015
+   if (string.match(label, "/(%.[^/]+)$")) then
+      dbg.print{"(1) Skipping hidden directory: ", label,"\n"}
+      dbg.fini("Master.availDir")
+      return
+   end
+
    local cmp = (LMOD_CASE_INDEPENDENT_SORTING:lower():sub(1,1) == "y") and
                case_independent_cmp or nil
```

**Comment by rtmclay** [comment]
I am unable to reproduce the bug.   In the current version 6.0.10, directories with a "." are not printed at all.  I looked at the code for 5.9.3 and the same code is there. Could you please put together a test case that shows the problem and send a tar ball with the module tree that shows this.  Also please do:

       $ module -D -D avail 2> avail.log

and send me avail.log

Thanks.

**Comment by blappm** [comment]
Hi Robert,

The patch I've added was for complete module directories, not for single application folders.

Since we have more than 300 applications and different user groups using them, it makes
sense to hide the main directory with all the apps and only show the class which are important for a certain user group:

mkdir /Easybuild-Apps/modules/.all
cd /Easybuild-Apps/modules/.all
ln -s ../all/* .
module unuse /Easybuild-Apps/modules/all
module use /Easybuild-Apps/modules/.all
module use /Easybuild-Apps/modules/class1
module use /Easybuild-Apps/modules/class2
module use /Easybuild-Apps/modules/class3

Like this, the output of:

module avail

is small, the users see their applications only.

**Comment by rtmclay** [comment]
This has been resolved for sometime.  It currently works with Lmod 7.1+
