### ISSUE TITLE
Feature Request Include Module File Path in Reverse Map

### ISSUE THREAD

**Issue by pforai** [TACC/Lmod#82]
Hi Robert,

Would be nice to have the full absolute path to the module file in the reverse map next module name. Really handy if you feed the reverse map into something like Logstash or Splunk for analysis reasons.

Thanks,
P

**Comment by rtmclay** [comment]
I have added the absolute path of the module file in reverseMapT.  Is that what you need?

**Comment by pforai** [comment]
Hooray! :+1: 

Thanks again Robert, you're amazing!

**Comment by rtmclay** [comment]
You are welcome.
R.
