### ISSUE TITLE
Use (possibly adapted) serpent for string serialization

### ISSUE THREAD

**Issue by ladc** [TACC/Lmod#87]
Some strings are not serialized correctly by `tools/serializeTbl.lua`, for instance, strings containing special characters (e.g. `\`). There is an excellent and compact serialization library called [serpent](https://github.com/pkulchenko/serpent/blob/master/src/serpent.lua) which I would recommend. It's a single Lua file, and it's MIT licensed so freely adaptable if needed.

**Comment by rtmclay** [comment]
Could you please provide an example so I can test this out.

Thanks,
R.

**Comment by ladc** [comment]
Of course. Here's an example (should be run in `tools/`):

```lua
require("serializeTbl")
local nastytab = {"\\","\\\\"}
serializeTbl({name="nasty",value=nastytab, fn="nasty.lua"})
  
local keywordtab={a=0.1}
serializeTbl({name="while",value=keywordtab, fn="keyword.lua"})
```

**Comment by rtmclay** [comment]
Thanks very much for the bug report.  I have updated Lmod to support serializations like what you have shown above.  I have updated Lmod to version 6.0.25.  Please let me know if this fixes the problem for you.  Thanks,

**Comment by ladc** [comment]
Hi, sorry for the delay in checking this, I'll do it next week (and I have another bug to report, still need to prepare a test case...)
