### ISSUE TITLE
Having square brackets in the LoadMessage text block

### ISSUE THREAD

**Issue by DirkdeDraak** [TACC/Lmod#92]
The tcl2lua script converted my TCL module straight into Lua, but upon trying to use it, it failed.

TCL:
```
puts stderr "  load $appname \[$appversion\]"
```
Lua:
```
LmodMessage([[  load Build Environment [DEVELOPMENT]]])
```

It seems that the double square bracket aproach properly handles square brackets inside of it, as long as the closing 2 square brackets are preceded by whitespace.

Lua (this works):
```
LmodMessage([[  load Build Environment [DEVELOPMENT] ]])
```

I'll easily work around it, though just wanted you to be aware of this.

**Comment by rtmclay** [comment]
The 6.1.2 version of Lmod pushed to the repo fixes this problem for me.  Please test this out when you get a chance.

Thanks,
R.

**Comment by DirkdeDraak** [comment]
I can confirm that your fix fixes this issue. Thanx for the swift action.
Thanks,
 Fokko
