### ISSUE TITLE
TCL --delim=C for append/remove/prepend-path not recognized by tcl2lua

### ISSUE THREAD

**Issue by DirkdeDraak** [TACC/Lmod#94]
I had several TCL modulefiles with 
```
append-path --delim=: MYPATHS "/my/apps/bin"
```
through tcl2lua that becomes:
```
append_path("--delim=:","MYPATHS")
```

while it should be
```
append_path("MYPATHS","/my/apps/bin")
```

According to the Tmod specs --delim=: should be allowed:
http://modules.sourceforge.net/man/modulefile.html

**Comment by rtmclay** [comment]
Lmod currently supports -delim :   So if you are in a hurry, you can switch to that syntax or just remove it.  A fix will take a little while as I'm going to have to learn some more TCL.  Thanks for the bug report!

**Comment by rtmclay** [comment]
Version 6.0.29 now supports this syntax: append-path --delim=: A B.  Please test it out when you get a chance.

**Comment by DirkdeDraak** [comment]
I checked it, and it does.
Although you have left a debug statement ("Here 3") in the tcl2lua script in the 6.0.29 release.

**Comment by rtmclay** [comment]
I have updated the repo to remove the debug statement.  Thanks again for the bug reports!
