### ISSUE TITLE
Error reporting on failed swap

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#97]
Currently:
```
$ ml swap cluster/foo
Lmod has detected the following error:  Swap failed.
```
The issue here is that the module `cluster/foo`  does not exist. Could the error be extend to give a bit more information to the user about what is wrong?

**Comment by rtmclay** [comment]
I have changed the error message to be the same as loading a module that doesn't exist:

% ml swap gcc/5.1
Lmod has detected the following error:  The following module(s) are unknown: "gcc/5.1"

Please check the spelling or version number. Also try "module spider ..."

This is now version 6.1.3

**Comment by boegel** [comment]
@rtmclay: is that the only reason why a `swap` can fail?

**Comment by rtmclay** [comment]
At that point in the code, yes.  The module doesn't exist.  If the module has a syntax error it will fail in another place.

**Comment by wpoely86** [comment]
Tested and works perfectly. Thanks!
